force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/factura__c.field-meta.xml
<CustomField>
    <fullName>factura__c</fullName>
    <label>Numero de factura</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Fecha_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_entrega__c</fullName>
    <formula>Oportunidad__r.Fecha_de_entrega__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Imp_Aduanas__c.field-meta.xml
<CustomField>
    <fullName>Imp_Aduanas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Imp. Aduanas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cantidad_de_informes_aprobados__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_informes_aprobados__c</fullName>
    <label>Cantidad de informes aprobados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_entrega__c</fullName>
    <label>Fecha de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/test_Informe_de_Negociacion.cls
@isTest
public class test_Informe_de_Negociacion {
    
    @isTest
    public static void perderAprobacion() {
        Opportunity opp = new Opportunity();
        opp.CloseDate = Date.today() + 7;
        opp.StageName = 'Contacto Exitoso';
        opp.Fecha_de_entrega__c = Date.today() + 1;
        opp.Cantidad_de_informes_aprobados__c = 0;
        insert opp;
        
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        inf.Oportunidad__c = opp.ID;
        inf.Estado__c = 'Esperando aprobacion';
        insert inf;
        
        inf.Estado__c = 'Aprobado';
        update inf;
        
        inf.Imp_Aduanas__c = 10;
        
        Test.startTest();
        Database.SaveResult sr = Database.update(inf, false);
        Test.stopTest();
    }
    
    @isTest
    public static void eliminarInforme() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        inf.Estado__c = 'Aprobado';
        inf.total_negociado__c = 1000;
        
        insert inf;
        
        Test.startTest();
        Database.DeleteResult sr = Database.delete(inf, false);
        Test.stopTest();
    }
    
    @isTest
    public static void mensajeError() {
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        inf.Estado__c = 'Aprobado';
        inf.total_negociado__c = 1000;
        inf.factura__c = '123456';
        
        insert inf;
        
        inf.total_negociado__c = 999;
        
        Test.startTest();
        Database.SaveResult sr = Database.update(inf, false);
        Test.stopTest();
    }
}