force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Reservar__c.field-meta.xml
<CustomField>
    <fullName>Reservar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_VFAsignaChasis.cls
@Istest
public class Test_VFAsignaChasis {
	
    @istest
    public static void testAsignaChasis(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        test.startTest();
        Informe_de_Negociaci_n__c infNeg = new Informe_de_Negociaci_n__c ();
        infNeg.Chasis__c = 'TESTCHASIS_89789798';
        infNeg.Reservar__c = true;
        insert infNeg;
        
        PageReference pageRef = Page.AsignaChasis; // Add your VF page Name here
        pageRef.getParameters().put('Id', infNeg.Id);
        Test.setCurrentPage(pageRef);
        
        
        CtrlAsignaChasis ctrlAC = new CtrlAsignaChasis();
        ctrlAC.recordId = infNeg.Id;
        CtrlAC.goToRecord();
        test.stopTest();
        
	}
    
    @istest
    public static void testAsignaChasis2(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        test.startTest();
        Informe_de_Negociaci_n__c infNeg2 = new Informe_de_Negociaci_n__c ();
        infNeg2.Chasis__c = 'TESTCHASIS_89789798';
        infNeg2.Reservar__c = false;
        insert infNeg2;
        
        PageReference pageRef2 = Page.AsignaChasis; // Add your VF page Name here
        pageRef2.getParameters().put('Id', infNeg2.Id);
        Test.setCurrentPage(pageRef2);
        test.stopTest();
	} 
    
}