force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/OrdenAbierta__c.field-meta.xml
<CustomField>
    <fullName>OrdenAbierta__c</fullName>
    <label>OrdenAbierta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallWSOrdenAbierta.cls
public with sharing class CallWSOrdenAbierta {
    /*Validar si el chasis tiene una orden abierta*/
    @AuraEnabled
    public static String validaChasisOrdenAbierta (Id opportunityId) {
        Integer OrdenesAbiertas=0;
       // System.debug('ENTRO A VALIDAR ORDEN ABIERTA  '+ opportunityId);
       List<Informe_de_Negociaci_n__c> infList= [
           SELECT ID, Chasis__c FROM 
           Informe_de_Negociaci_n__c 
           WHERE Oportunidad__c=: opportunityId
       ];
     
       if (infList.isEmpty())
       {
        return 'Debe existir un informe de negociacion en la oportunidad para verificar si hay orden abierta.';
       }

       for (Informe_de_Negociaci_n__c inf: infList) {
       
            if (String.isBlank(inf.Chasis__c)) {
                return 'Debe existir un chasis en la oportunidad para verificar si hay orden abierta.';
            }

           String resp=tieneOrdenAbierta(inf.Chasis__c);
            if (resp == '1')
            {
                inf.OrdenAbierta__c='1';  
                OrdenesAbiertas= OrdenesAbiertas+1;
            }else {
                inf.OrdenAbierta__c='0';   
            }  
       }
       
       update infList;

       if ( OrdenesAbiertas >0)
       {       
        return 'Existe una orden abierta en JDE';
       
       }else {
           {            
            return 'Ok: No hay orden abierta para los chasis asociados a esta oportunidad';         
           
           }
       }      
   }

   public static string tieneOrdenAbierta(String chasis ){

       ws_Oportunidades.wsOportunidadesPort portObj = new ws_Oportunidades.wsOportunidadesPort(); 
       portObj.timeout_x = 120000;
                 
       String resp = portObj.VerificarChasisTieneOrden(Label.strKey,Label.strApp, Label.strModulo, chasis);
       system.debug(resp);
       return resp;
   }

}