force-app/main/default/objects/NPS_Casa_Pellas__c/NPS_Casa_Pellas__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar notas de NPS en cases</description>
    <label>NPS Casa Pellas</label>
    <nameField>
        <label>NPS Casa Pellas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPS Casa Pellas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPS_Casa_Pellas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NPS Casa Pellas</relationshipLabel>
    <relationshipName>NPS_Casa_Pellas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPS_Casa_Pellas__c/fields/Numero_de_caso__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Para almacenar el llink entre el caso y el objeto</description>
    <label>Numero de Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>NPS Casa Pellas</relationshipLabel>
    <relationshipName>NPS_Casa_Pellas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPS_Casa_Pellas__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>NPS Casa Pellas</relationshipLabel>
    <relationshipName>NPS_Casa_Pellas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NPSHelper.cls
public with sharing class NPSHelper {
    public static void asociarCuentasCase(List<NPS_Casa_Pellas__c> npsList, String objeto) {
        List<ID> listID = new List<ID>();
        Map<ID, ID> cuentaPorID = new Map<ID, ID>();

        for (NPS_Casa_Pellas__c nps : npsList) {
            if (objeto == 'Caso') {
                listID.add(nps.Numero_de_caso__c);
            } else if (objeto == 'Oportunidad') {
                listID.add(nps.Oportunidad__c);
            }
        }

        if (objeto == 'Caso') {
            for (Case c : [SELECT ID, AccountId
                           FROM Case
                           WHERE ID IN :listID]) {
                if (String.isNotBlank(c.AccountID)) {
                    cuentaPorID.put(c.ID, c.AccountID);
                }
            }
        } else if (objeto == 'Oportunidad') {
            for (Opportunity o : [SELECT ID, AccountId
                           FROM Opportunity
                           WHERE ID IN :listID]) {
                if (String.isNotBlank(o.AccountID)) {
                    cuentaPorID.put(o.ID, o.AccountID);
                }
            }
        }

        for (NPS_Casa_Pellas__c nps : npsList) {
            
            if (objeto == 'Caso') {
                if (cuentaPorID.containsKey(nps.Numero_de_caso__c)) {
                    nps.Cuenta__c = cuentaPorID.get(nps.Numero_de_caso__c);
                }
            } else if (objeto == 'Oportunidad') {
                if (cuentaPorID.containsKey(nps.Oportunidad__c)) {
                    nps.Cuenta__c = cuentaPorID.get(nps.Oportunidad__c);
                }
            }
        }
    }
}