force-app/main/default/objects/Aprobador_por_Sucursal__mdt/Aprobador_por_Sucursal__mdt.object-meta.xml
<CustomObject>
    <description>Para definir los aprobadores de informe de negociacion de motos</description>
    <label>Aprobador por Sucursal</label>
    <pluralLabel>Aprobadores por Sucursal</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aprobador_por_Sucursal__mdt/fields/Nombre_del_aprobador__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_aprobador__c</fullName>
    <label>Nombre del aprobador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aprobador_por_Sucursal__mdt/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
                <default>true</default>
                <label>Altamira</label>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aprobador_por_Sucursal__mdt/fields/Tipo_de_vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_vehiculo__c</fullName>
    <label>Tipo de vehiculo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Motocicletas</fullName>
            </value>
            <value>
                <fullName>Motores marinos</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
                <default>true</default>
                <label>Todos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Marca_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Marca_Oportunidad__c</fullName>
    <formula>Oportunidad__r.Marca_UDC__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Monto_total_del_informe__c.field-meta.xml
<CustomField>
    <fullName>Monto_total_del_informe__c</fullName>
    <formula>total_negociado__c - (Total_Accesorios__c + Total_Recibos__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo pendiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Texto_Bandera__c.field-meta.xml
<CustomField>
    <fullName>Texto_Bandera__c</fullName>
    <description>Campo auxiliar para manejar los procesos de aprobacion de motos</description>
    <label>Texto Bandera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ModeloVehiculo__c.field-meta.xml
<CustomField>
    <fullName>ModeloVehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo Vehiculo UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Modelo Vehiculo UDC)</relationshipLabel>
    <relationshipName>UDCMODELO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Motos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Motos</fullName>
    <active>true</active>
    <businessProcess>Principal Motos</businessProcess>
    <label>Principal Motos</label>
</RecordType>

force-app/main/default/objects/User/fields/Aprobador_de_motos__c.field-meta.xml
<CustomField>
    <fullName>Aprobador_de_motos__c</fullName>
    <label>Aprobador de motos</label>
    <relationshipName>Aprobador_de_motos</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnviarInformeParaAprobacion.cls
public class EnviarInformeParaAprobacion { 
    @AuraEnabled
    public static String enviarReporte(ID informeID) {
        List<Approval.ProcessSubmitRequest> aprobacionesList = new List<Approval.ProcessSubmitRequest>();

        Informe_de_Negociaci_n__c inf = 
            [SELECT Monto_total_del_informe__c, Estado__c, Marca_Oportunidad__c, Oportunidad__r.RecordType.DeveloperName,
                    Oportunidad__r.Owner.Sucursal__c, Oportunidad__r.OwnerId, Producto__c, total_negociado__c, Texto_Bandera__c,
                    Oportunidad__r.ModeloVehiculo__r.description1__c
            FROM Informe_de_Negociaci_n__c
            WHERE ID =: informeID
            LIMIT 1
            ];
                
        if (inf.Estado__c == 'Aprobado') {
            return 'Aprobado';
        }
        
        if (inf.Monto_total_del_informe__c != 0) {
            return 'Pendiente';
        }

        List<PricebookEntry> precioMinimo = [
            SELECT Id, UnitPrice
            FROM PricebookEntry
            WHERE Pricebook2.Name = 'Precio mínimo' AND Product2Id =: inf.Producto__c
        ];

        Boolean actualizar = false;

        if (inf.Oportunidad__r.RecordType.DeveloperName == 'Principal_Motos') {
            String tipoVehiculo = '';

            if (inf.Oportunidad__r.ModeloVehiculo__r.description1__c.contains('MOTORES MARINOS')) {
                tipoVehiculo = 'Motores marinos';
            } else {
                tipoVehiculo = 'Motocicletas';
            }

            if (!precioMinimo.isEmpty() && inf.total_negociado__c < precioMinimo[0].UnitPrice) {
                inf.Texto_Bandera__c = 'Aprobacion - Precio invalido';
                update inf;

                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setObjectId(informeID);
                aprobacionesList.add(req);
 
            } else {
                Set<String> aprobadoresName = new Set<String>();
                List<ID> aprobadoresList = new List<ID>();    
                User vendedor = [
                    SELECT ID, Aprobador_de_motos__r.Name, Aprobador_de_motos__c
                    FROM User 
                    WHERE ID =: inf.Oportunidad__r.OwnerId
                ];

                if (String.isNotBlank(vendedor.Aprobador_de_motos__c)) {
                    aprobadoresName.add(vendedor.Aprobador_de_motos__r.Name);
                }

                for (Aprobador_por_Sucursal__mdt apr : [SELECT Nombre_del_aprobador__c
                                                        FROM Aprobador_por_Sucursal__mdt 
                                                        WHERE Sucursal__c =: inf.Oportunidad__r.Owner.Sucursal__c 
                                                        	AND (Tipo_de_vehiculo__c =: tipoVehiculo 
                                                                 	OR Tipo_de_vehiculo__c = 'Todos')
                                                        ]) {
                    aprobadoresName.add(apr.Nombre_del_aprobador__c);
                }

                for (User u : [SELECT ID 
                                FROM User 
                                WHERE Name IN :aprobadoresName
                                ]) {
                    aprobadoresList.add(u.ID);
                }

                for (ID aproID : aprobadoresList) {
                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                    req.setObjectId(informeID);
                    req.setNextApproverIds(new List<ID>{aproID});
                    
                    aprobacionesList.add(req);
                }
            }

        } else {
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(informeID);
            aprobacionesList.add(req);
        }

        if (String.isBlank(inf.Texto_Bandera__c)) {
            inf.Texto_Bandera__c = 'Aprobacion';
            update inf;
        }

        Boolean error = false;
        String errList = 'Error: ';

        if(!aprobacionesList.isEmpty()) {
            try{
                List<Approval.ProcessResult> aprList = Approval.process(aprobacionesList);

                for (Approval.ProcessResult apr : aprList) {
                    if (!apr.isSuccess()) {
                        error = true;
                        errList += apr.getErrors()[0].getMessage();
                    }
                }
            } catch (DmlException e) {
                error = true;
                if (e.getMessage().contains('NO_APPLICABLE_PROCESS')) {
                    errList += 'No hay procesos de aprobación aplicables.';
                } else if (e.getMessage().contains('ALREADY_IN_PROCESS')) {
                    errList +='El registro ya está en un proceso de aprobación.';
                }
            }
        }
        
        if(!error) {
            return 'Ok';
        } else {
            inf.Texto_Bandera__c = '';
            update inf;

            return errList;
        }
    }
}