force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CantidadMinima__c.field-meta.xml
<CustomField>
    <fullName>CantidadMinima__c</fullName>
    <description>Variable original ifeule .</description>
    <label>Cantidad mínima permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodParteEquivalente__c.field-meta.xml
<CustomField>
    <fullName>CodParteEquivalente__c</fullName>
    <description>Variable original inpare .</description>
    <label>Código de la parte equivalente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Compa_a_UDC__c.field-meta.xml
<CustomField>
    <fullName>Compa_a_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accesorios</relationshipLabel>
    <relationshipName>Accesorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/DescripcionAmplia__c.field-meta.xml
<CustomField>
    <fullName>DescripcionAmplia__c</fullName>
    <description>Variable original idesci .</description>
    <label>Descripción amplia del accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Solicitar_Accesorio_Equivalente__c.field-meta.xml
<CustomField>
    <fullName>Solicitar_Accesorio_Equivalente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitar accesorio equivalente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_ProcesoAccesorios.cls
@isTest 
public class Test_ProcesoAccesorios {
    @TestSetup
    public static void crearInforme() {
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Id companiaID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Companias')
                                    .getRecordTypeId();
        
        Catalogo_UDC__c companiasTest = new Catalogo_UDC__c();
        companiasTest.Name = 'KIPESA';
        companiasTest.productcode__c = 'COMP';
        companiasTest.RecordTypeId = companiaID;
        
        insert companiasTest;
        
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        insert inf;
        
        Accesorios__c acc = new Accesorios__c();
        acc.Descripcion__c = 'Test';
        acc.CodigoParte__c = '10BBLD616DYXX';
        acc.CodParteEquivalente__c = '70D1985077010';
        acc.CantidadMinima__c = 1;
        acc.DescripcionAmplia__c = 'Test';
        acc.Compa_a_UDC__c = companiasTest.ID;
        insert acc;
        
        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
        accInf.Estado__c = 'Solicitado';
        accInf.InformeNegociacion__c = inf.ID;
        accInf.Accesorio__c = acc.ID;
        accInf.Solicitar_Accesorio_Equivalente__c = true;
        insert accInf;    
    }

    @isTest
    public static void testGetAccesoriosChasis() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            ];
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        ProcesaGetAccesoriosChasis.getAccesoriosChasis('CHASIS', '' + infList[0].ID);
    }
    
    @isTest
    public static void consultaAccesorios_DisponibilidadAccesorios(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            ];
        
        PageReference pageRef = Page.ConsultaDisponibilidadAccesorios;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', '' + infList[0].ID);
        
        CtrlConsultaDisponibilidadAccesorios cda = new CtrlConsultaDisponibilidadAccesorios ();
        
        Test.startTest();
        cda.validaDisponibilidad();
        CtrlConsultaDisponibilidadAccesorios.solicitaAccesorioInformeAprobado('TEST');
        Test.stopTest();
        
    }
    
    @isTest
    public static void consultaAccesoriosDespachadosTest(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
   		List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            ];
        
        List<Accesorios_del_informe__c> accInfList = 
            [SELECT Id, Estado__c
          	FROM Accesorios_del_informe__c 
          	WHERE InformeNegociacion__c =: infList[0].ID
            ];
        
        for (Accesorios_del_informe__c a : accInfList) {
            a.Estado__c = 'Solicitado';
        }
        
        update accInfList;
        
        PageReference pageRef2 = Page.ConsultaAccesoriosDespachados;
        Test.setCurrentPage(pageRef2);
        ApexPages.currentPage().getParameters().put('Id', '' + infList[0].ID);
        CtrlConsultaAccesoriosDespachados accDesp = new CtrlConsultaAccesoriosDespachados();
        
        Test.startTest();
        accDesp.validaAccesoriosDespachados();
        Test.stopTest();
    }
    
    @isTest
    public static void eliminaSolicitud (){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        
        List<ProcesaWSEliminarSolicitud.WrapperEliminaSolicitud> eliminaSolicitudInfNegList = new List<ProcesaWSEliminarSolicitud.WrapperEliminaSolicitud>();
        
        ProcesaWSEliminarSolicitud.WrapperEliminaSolicitud wInforme = new ProcesaWSEliminarSolicitud.WrapperEliminaSolicitud();
        wInforme.chasis 	= 'TESTCHASIS';
        wInforme.informeNeg	= '000000000000283';
        
        eliminaSolicitudInfNegList.add(wInforme);
        
        test.startTest();
        ProcesaWSEliminarSolicitud.eliminarSolicitud(ProcesaWSEliminarSolicitud.generaXMLRequest(eliminaSolicitudInfNegList));
        test.stopTest();
    }   
}