force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CantidadMinima__c.field-meta.xml
<CustomField>
    <fullName>CantidadMinima__c</fullName>
    <description>Variable original ifeule .</description>
    <label>Cantidad mínima permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/DescripcionAmplia__c.field-meta.xml
<CustomField>
    <fullName>DescripcionAmplia__c</fullName>
    <description>Variable original idesci .</description>
    <label>Descripción amplia del accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Consecutivo_del_Informe__c.field-meta.xml
<CustomField>
    <fullName>Consecutivo_del_Informe__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Consecutivo del Informe</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallWSActualizarAccesoriosTest.cls
@isTest
public class CallWSActualizarAccesoriosTest {
    @TestSetup
    public static void crearInformes(){
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        insert inf;

        Informe_de_Negociaci_n__c inf2 = new Informe_de_Negociaci_n__c();
        insert inf2;

        Accesorios__c acc = new Accesorios__c();
        acc.CodigoParte__c = '70D1985077010';
        acc.CantidadMinima__c = 1;
        acc.DescripcionAmplia__c = 'Test accesorio 1';
        acc.Descripcion__c = 'Test';
        insert acc;
        
        Accesorios__c acc2 = new Accesorios__c();
        acc2.CodigoParte__c = 'UNCODIGOINEXISTENTE';
        acc2.CantidadMinima__c = 1;
        acc2.DescripcionAmplia__c = 'Test accesorio 2';
        acc2.Descripcion__c = 'Test';
        insert acc2;
        
        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c(); 
        accInf.InformeNegociacion__c = inf.ID;
        accInf.Accesorio__c = acc.ID;
        
        insert accInf;
        
        Accesorios_del_informe__c accInf2 = new Accesorios_del_informe__c(); 
        accInf2.InformeNegociacion__c = inf2.ID;
        accInf2.Accesorio__c = acc2.ID;

        insert accInf2;
    }

    @IsTest
    public static void llamadaProgramadaTest(){
        List<Informe_de_Negociaci_n__c> consecutivosList = 
            [SELECT Consecutivo_del_Informe__c 
             FROM Informe_de_Negociaci_n__c
             ORDER BY Consecutivo_del_Informe__c ASC
            ];
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios(
            consecutivosList[0].Consecutivo_del_Informe__c.removeStart('0'), 
            consecutivosList[1].Consecutivo_del_Informe__c.removeStart('0'))
            );

        List<Accesorios_del_informe__c> accList =   
            [SELECT Estado__c, Accesorio__r.CodigoParte__c, InformeNegociacion__r.Consecutivo_del_Informe__c 
            FROM Accesorios_del_informe__c
            ];
        
        for (Accesorios_del_informe__c acc : accList) {
            if(acc.Accesorio__r.CodigoParte__c == '70D1985077010') {
                acc.Estado__c = 'Solicitado';
            } else {
                acc.Estado__c = 'Despachado';
            }
        }

        update accList;

        SchedulableContext sc = null;
        CallWSActualizarAccesorios x = new CallWSActualizarAccesorios();

        Test.startTest();
        x.execute(sc);
        Test.stopTest();

        List<Accesorios_del_informe__c> accListAct =   
            [SELECT Estado__c, Accesorio__r.CodigoParte__c, InformeNegociacion__r.Consecutivo_del_Informe__c 
            FROM Accesorios_del_informe__c
            ];

        for (Accesorios_del_informe__c acc : accListAct) {
            if(acc.Accesorio__r.CodigoParte__c == '70D1985077010') {
                System.assertEquals('Despachado', acc.Estado__c, 'El estado del accesorio ' + acc.Accesorio__r.CodigoParte__c + ' no se ha modificado como debería');
            } else {
                System.assertEquals('Solicitado', acc.Estado__c, 'El estado del accesorio ' + acc.Accesorio__r.CodigoParte__c + ' no se ha modificado como debería');
            }
        }
    }
    
    @isTest
    public static void actualizarAccesorioTest() {
        List<Informe_de_Negociaci_n__c> consecutivosList = 
            [SELECT Consecutivo_del_Informe__c 
             FROM Informe_de_Negociaci_n__c
             ORDER BY Consecutivo_del_Informe__c ASC
            ];
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios(
            consecutivosList[0].Consecutivo_del_Informe__c.removeStart('0'), 
            consecutivosList[1].Consecutivo_del_Informe__c.removeStart('0'))
            );

        List<Accesorios_del_informe__c> accList =   
            [SELECT Estado__c, Accesorio__r.CodigoParte__c 
            FROM Accesorios_del_informe__c
            ];

        for (Accesorios_del_informe__c acc : accList) {
            if(acc.Accesorio__r.CodigoParte__c == '70D1985077010') {
                acc.Estado__c = 'Solicitado';
            } else {
                acc.Estado__c = 'Despachado';
            }
        }

        update accList;
        
        List<Informe_de_Negociaci_n__c> infList =
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            LIMIT 1
            ];

        Test.startTest();
        ActualizarAccesoriosDespachados.ActualizarAccesoriosDespachados(infList[0].ID);
        Test.stopTest();

        List<Accesorios_del_informe__c> accListAct =   
            [SELECT Estado__c, Accesorio__r.CodigoParte__c, InformeNegociacion__c
            FROM Accesorios_del_informe__c
            ];

        for (Accesorios_del_informe__c acc : accListAct) {
            if(acc.InformeNegociacion__c == infList[0].ID) {
                System.assertEquals('Despachado', acc.Estado__c, 'El estado del accesorio ' + acc.Accesorio__r.CodigoParte__c + ' no se ha modificado como debería');
            } else {
                System.assertEquals('Despachado', acc.Estado__c, 'El estado del accesorio ' + acc.Accesorio__r.CodigoParte__c + ' se ha modificado cuando no deberia hacerlo');
            }
        }
    }
}