force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CantidadMinima__c.field-meta.xml
<CustomField>
    <fullName>CantidadMinima__c</fullName>
    <description>Variable original ifeule .</description>
    <label>Cantidad mínima permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/DescripcionAmplia__c.field-meta.xml
<CustomField>
    <fullName>DescripcionAmplia__c</fullName>
    <description>Variable original idesci .</description>
    <label>Descripción amplia del accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Codigo_de_parte__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_parte__c</fullName>
    <formula>Accesorio__r.CodigoParte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de parte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Combo</label>
    <referenceTo>CombosDeInformeDeNegociacion__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Descripci_n_del_accesorio__c.field-meta.xml
<CustomField>
    <fullName>Descripci_n_del_accesorio__c</fullName>
    <formula>Accesorio__r.DescripcionAmplia__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción del accesorio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Combo__c/Combo__c.object-meta.xml
<CustomObject>
    <label>Combo</label>
    <nameField>
        <label>Nombre de Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Combo__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Combo__c/fields/Marca_habilitada__c.field-meta.xml
<CustomField>
    <fullName>Marca_habilitada__c</fullName>
    <label>Marca habilitada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MULTIMARCA</fullName>
            </value>
            <value>
                <fullName>GENESIS</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>YAMAHA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Combo__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo habilitado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Marca_habilitada__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>21AC-A5</fullName>
            </value>
            <value>
                <fullName>22BKT-BL</fullName>
            </value>
            <value>
                <fullName>4RUNNER4x4-LTD</fullName>
            </value>
            <value>
                <fullName>4RUNNER4x4-SR5</fullName>
            </value>
            <value>
                <fullName>AG200F</fullName>
            </value>
            <value>
                <fullName>AGYA A4</fullName>
            </value>
            <value>
                <fullName>AGYA AUT</fullName>
            </value>
            <value>
                <fullName>AGYA C5</fullName>
            </value>
            <value>
                <fullName>AGYA MEC</fullName>
            </value>
            <value>
                <fullName>ALTO DLX 800</fullName>
            </value>
            <value>
                <fullName>APV BUS GL</fullName>
            </value>
            <value>
                <fullName>BALENO GL</fullName>
            </value>
            <value>
                <fullName>BALENO GL AUT</fullName>
            </value>
            <value>
                <fullName>BASE-CVT</fullName>
            </value>
            <value>
                <fullName>BASE-MT</fullName>
            </value>
            <value>
                <fullName>BU150-DECK</fullName>
            </value>
            <value>
                <fullName>CAMRY-25AUT</fullName>
            </value>
            <value>
                <fullName>CAMRY-35AUT</fullName>
            </value>
            <value>
                <fullName>CARNIVAL EX</fullName>
            </value>
            <value>
                <fullName>CELERIO</fullName>
            </value>
            <value>
                <fullName>CELERIO-DLX-AUT</fullName>
            </value>
            <value>
                <fullName>COASTER</fullName>
            </value>
            <value>
                <fullName>COROLLA AUT</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS AD</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS AE</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS AUT BAS</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS AUT FULL</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS AUT INT</fullName>
            </value>
            <value>
                <fullName>COROLLA CROSS CA</fullName>
            </value>
            <value>
                <fullName>DASH125</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Combo_Accesorio__c/Combo_Accesorio__c.object-meta.xml
<CustomObject>
    <label>Accesorio del combo</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Nombre de Accesorio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del combo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Combo_Accesorio__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipName>Combos_Accesorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Combo_Accesorio__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <label>Combo</label>
    <referenceTo>Combo__c</referenceTo>
    <relationshipName>Combos_Accesorios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/CombosDeInformeDeNegociacion__c.object-meta.xml
<CustomObject>
    <label>Combos del informe</label>
    <nameField>
        <label>Nombre de Informe / Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <label>Combo</label>
    <referenceTo>Combo__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigovehiculo__c.field-meta.xml
<CustomField>
    <fullName>Codigovehiculo__c</fullName>
    <description>Codigo visible del vehiculo</description>
    <label>Codigo vehiculo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/classes/AccesoriosNuevosControllerTest.cls
@isTest
public class AccesoriosNuevosControllerTest {
	@TestSetup
    public static void crearAccesorios() {        
        Id modeloUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Modelo')
                                    .getRecordTypeId();
        
        Catalogo_UDC__c modeloTest = new Catalogo_UDC__c();
        modeloTest.Name = 'AGYA A4';
        modeloTest.productcode__c = 'AGYA A4';
        modeloTest.RecordTypeId = modeloUDCID;
        insert modeloTest;
        
        Accesorios__c acc = new Accesorios__c();
        acc.CantidadMinima__c = 1;
        acc.DescripcionAmplia__c = 'Accesorios Test';
        acc.Descripcion__c = 'Accesorios Test';
        acc.CodigoParte__c = '123';
        insert acc;
        
        Combo__c c = new Combo__c();
        c.Marca_habilitada__c = 'MULTIMARCA';
        c.Modelo__c = 'AGYA A4';
        c.Id_Externo__c = '123';
        insert c;
        
        Combo_Accesorio__c cAcc = new Combo_Accesorio__c();
        cAcc.Combo__c = c.ID;
        cAcc.Accesorio__c = acc.ID;
        cAcc.Cantidad__c = 1;
        insert cAcc;
        
        Product2 p = new Product2();
        p.Name = 'test';
        p.Marca_P__c = 'Kia';
        p.ProductCode__c = 'TESTPCode';
        p.Codigovehiculo__c = 'AGYA A4';
        insert p;
        
        Informe_de_negociaci_n__c inf = new Informe_de_negociaci_n__c();
        inf.Producto__c = p.ID;
        insert inf;
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
        accInf.InformeNegociacion__c = inf.ID;
        accInf.Accesorio__c = acc.ID;
        accInf.Cantidad__c = 1;
        insert accInf;
    }
    
    @isTest
    public static void consultarAccesoriosTest() {
        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_negociaci_n__c
            ];
        
        Test.startTest();
        List<Accesorios_del_informe__c> accListRes = AccesoriosNuevosController.consultarAccesorios(infList[0].ID);
        Test.stopTest();

        List<Accesorios_del_informe__c> accList = 
            [SELECT ID, Codigo_de_parte__c, Descripci_n_del_accesorio__c, Cantidad__c, Precio__c, Estado__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: infList[0].ID
            ];

        for (Accesorios_del_informe__c acc : accList) {
            System.assertEquals(true, accListRes.contains(acc), 'El accesorio ' + 
                                        acc.Descripci_n_del_accesorio__c + 
                                        ' no esta en el listado de accesorios del informe.');
        }
    }
    
    @isTest
    public static void obtenerAccesoriosTest() {
        Test.startTest();
        List<Accesorios__c> accListRes = AccesoriosNuevosController.obtenerAccesorios();
        Test.stopTest();

        List<Accesorios__c> accList = [
            SELECT ID, DescripcionAmplia__c, Descripcion__c, CodigoParte__c, Precio__c, CantidadMinima__c
            FROM Accesorios__c
        ];

        for (Accesorios__c acc : accList) {
            System.assertEquals(true, accListRes.contains(acc), 'El accesorio ' + 
                                        acc.Descripcion__c + 
                                        ' no esta en la lista de accesorios.');
        }
    }
        
    @isTest
    public static void obtenerCombosTest() {
        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_negociaci_n__c
            ];
        
        Test.startTest();
        List<Combo__c> comboListRes = AccesoriosNuevosController.obtenerCombos(infList[0].ID);
        Test.stopTest();

        List<Combo__c> comboList = [
            SELECT ID, Name, Id_Externo__c, Modelo__c
            FROM Combo__c
            WHERE Modelo__c = 'AGYA A4'
        ];

        for (Combo__c c : comboList) {
            System.assertEquals(true, comboListRes.contains(c), 'El combo ' + 
                                        c.Name + 
                                        ' no esta en la lista de combos.');
        }
    }
    
    @isTest
    public static void descripcionCombosTest() {
        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_negociaci_n__c
            ];
        
        Test.startTest();
        Map<String, Map<String, String>> detalleCombo = AccesoriosNuevosController.descripcionCombos(infList[0].ID);
        Test.stopTest();

        List<Combo_Accesorio__c> comboAccList = [
            SELECT ID, Combo__r.Id_Externo__c, Accesorio__r.CodigoParte__c, Accesorio__r.Descripcion__c, 
                    Accesorio__r.Precio__c, Combo__r.Name, Cantidad__c
            FROM Combo_Accesorio__c
        ];

        for (Combo_Accesorio__c cAcc : comboAccList) {
            System.assertEquals(true, 
                                detalleCombo.KeySet().contains(cAcc.Combo__r.Id_Externo__c), 
                                'El combo ' + cAcc.Combo__r.Name + ' no esta en la lista de detalles de combos.');

            Map<String, String> detalleAccesorios = detalleCombo.get(cAcc.Combo__r.Id_Externo__c);

            System.assertEquals(true, 
                                detalleAccesorios.KeySet().contains(cAcc.Accesorio__r.CodigoParte__c), 
                                'El accesorio ' + cAcc.Accesorio__r.Descripcion__c + ' no esta en la lista de detalles de combos.');

            String detalle = cAcc.Cantidad__c + '_' + 
                             cAcc.Accesorio__r.Descripcion__c + '_' + 
                             cAcc.Accesorio__r.Precio__c;

            System.assertEquals(true, 
                                detalleAccesorios.Values().contains(detalle), 
                                'Los detalles del accesorio' + cAcc.Accesorio__r.Descripcion__c + ' no esta en la lista de detalles de combos.');
        }
    }
    
    @isTest
    public static void guardarCombosTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        
        List<Object> comboList = new List<Object>();
        comboList.add('123');
        
        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_negociaci_n__c
            ];
        
        Test.startTest();
        String resultado = AccesoriosNuevosController.guardarCombos(infList[0].ID, comboList);
        Test.stopTest();

        List<Accesorios_del_informe__c> accList = 
            [SELECT Cantidad__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: infList[0].ID
            ];

        System.assertEquals('Bien', resultado, 'El proceso ha fallado cuando no deberia.');

        for (Accesorios_del_informe__c accInf : accList) {
            System.assertEquals(2, accInf.Cantidad__c, 'El combo no ha agregado correctamente el accesorio.');
        }
    }
        
    @isTest
    public static void guardarAccesorioTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Object> comboList = new List<Object>();
        comboList.add('123=1');
        
        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_negociaci_n__c
            ];
        
        Test.startTest();
        String resultado = AccesoriosNuevosController.guardarAccesorio(infList[0].ID, comboList);
        Test.stopTest();

        List<Accesorios_del_informe__c> accList = 
            [SELECT Cantidad__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: infList[0].ID
            ];

        System.assertEquals('Bien', resultado, 'El proceso ha fallado cuando no deberia.');

        for (Accesorios_del_informe__c accInf : accList) {
            System.assertEquals(2, accInf.Cantidad__c, 'El accesorio no se ha insertado correctamente.');
        }
    }
    
    @isTest
    public static void eliminarAccesorioTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Accesorios_del_informe__c> accInf = 
            [SELECT ID, InformeNegociacion__c
            FROM Accesorios_del_informe__c
            ];
        
        Test.startTest();
        String resultado = AccesoriosNuevosController.eliminarAccesorio('' + accInf[0].ID);
        Test.stopTest();

        System.assertEquals('Bien', resultado, 'El proceso ha fallado cuando no deberia.');

        List<Accesorios_del_informe__c> accList = 
            [SELECT Cantidad__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: accInf[0].InformeNegociacion__c
                  AND Codigo_de_parte__c = '123'
            ];

        System.assertEquals(true, accList.isEmpty(), 'El accesorio no se ha eliminado correctamente.');
    }
    
    @isTest
    public static void actualizarCantidadesTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Informe_de_negociaci_n__c> infList = 
            [SELECT ID
             FROM Informe_de_negociaci_n__c
            ];
        
         List<Accesorios_del_informe__c> accList = 
            [SELECT Cantidad__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: infList[0].ID
                AND Codigo_de_parte__c ='123'
            ];
        
        Test.startTest();
        AccesoriosNuevosController.actualizarCantidades(infList[0].ID, '123', 6);
        Test.stopTest();
        
        accList = 
            [SELECT Cantidad__c
            FROM Accesorios_del_informe__c
            WHERE InformeNegociacion__c =: infList[0].ID
                AND Codigo_de_parte__c ='123'
            ];

        System.assertEquals(6, accList.get(0).Cantidad__c, 'La nueva cantidad asignada no es la esperada.');
    }
}