force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CantidadMinima__c.field-meta.xml
<CustomField>
    <fullName>CantidadMinima__c</fullName>
    <description>Variable original ifeule .</description>
    <label>Cantidad mínima permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodParteEquivalente__c.field-meta.xml
<CustomField>
    <fullName>CodParteEquivalente__c</fullName>
    <description>Variable original inpare .</description>
    <label>Código de la parte equivalente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Compa_a_UDC__c.field-meta.xml
<CustomField>
    <fullName>Compa_a_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accesorios</relationshipLabel>
    <relationshipName>Accesorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/DescripcionAmplia__c.field-meta.xml
<CustomField>
    <fullName>DescripcionAmplia__c</fullName>
    <description>Variable original idesci .</description>
    <label>Descripción amplia del accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Consecutivo__c.field-meta.xml
<CustomField>
    <fullName>Consecutivo__c</fullName>
    <label>Conscutivo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Solicitar_Accesorio_Equivalente__c.field-meta.xml
<CustomField>
    <fullName>Solicitar_Accesorio_Equivalente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitar accesorio equivalente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Reservar__c.field-meta.xml
<CustomField>
    <fullName>Reservar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccesorioDelInformeTriggerTest.cls
@isTest
public class AccesorioDelInformeTriggerTest {

    @TestSetup
    public static void crearCompania() {
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Id companiaID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Companias')
                                    .getRecordTypeId();
        
        Catalogo_UDC__c companiasTest = new Catalogo_UDC__c();
        companiasTest.Name = 'KIPESA';
        companiasTest.productcode__c = 'COMP';
        companiasTest.RecordTypeId = companiaID;
        
        insert companiasTest;

        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        insert inf;
        
        Accesorios__c acc = new Accesorios__c();
        acc.Descripcion__c = 'Test';
        acc.CodigoParte__c = '10BBLD616DYXX';
        acc.CodParteEquivalente__c = '70D1985077010';
        acc.CantidadMinima__c = 1;
        acc.DescripcionAmplia__c = 'Test';
        acc.Compa_a_UDC__c = companiasTest.ID;
        insert acc;
        
        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
        accInf.InformeNegociacion__c = inf.ID;
        accInf.Accesorio__c = acc.ID;
        accInf.Cantidad__c = 1;
        accInf.Solicitar_Accesorio_Equivalente__c = false;
        insert accInf;
    }
    
    @isTest 
    public static void insertarAccesorioEnInformeReservado() {
        List<Informe_de_Negociaci_n__c> infList = [
            SELECT ID, Reservar__c
            FROM Informe_de_Negociaci_n__c
        ];

        List<Accesorios__c> accList = [
            SELECT ID
            FROM Accesorios__c
        ];

        infList[0].Reservar__c = true;
        update infList;

        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
        accInf.InformeNegociacion__c = infList[0].ID;
        accInf.Accesorio__c = accList[0].ID;
        accInf.Cantidad__c = 1;

        Test.startTest();
        Database.SaveResult sr = Database.insert(accInf, false);
        Test.stopTest();

        System.assertEquals(false, sr.isSuccess(), 'La insercion con un informe reservado funciona cuando no deberia');

        System.assertEquals('El informe se encuentra Reservado, por lo que no es posible agregar los accesorios', 
                            sr.getErrors()[0].getMessage(),
                            'El error mostrado en pantalla no es el esperado');
    }

    @isTest
    public static void setearConsecutivoYEstadoTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = [
            SELECT ID
            FROM Informe_de_Negociaci_n__c
        ];

        List<Accesorios__c> accList = [
            SELECT ID
            FROM Accesorios__c
        ];

        Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
        accInf.InformeNegociacion__c = infList[0].ID;
        accInf.Accesorio__c = accList[0].ID;
        accInf.Cantidad__c = 1;

        Test.startTest();
        Database.SaveResult sr = Database.insert(accInf, false);
        Test.stopTest();

        System.debug([SELECT Consecutivo__c FROM Accesorios_del_informe__c]);

        List<Accesorios_del_informe__c> accInsertado = [
            SELECT Estado__c, Consecutivo__c
            FROM Accesorios_del_informe__c
            WHERE ID =: accInf.ID
        ];

        System.assertEquals(true, sr.isSuccess(), 'La insercion está fallando cuando no deberia');
        System.assertEquals(2, accInsertado[0].Consecutivo__c, 'El consecutivo no se ha seteado correctamente');
        System.assertEquals('No solicitado', accInsertado[0].Estado__c, 'El estado no se ha seteado correctamente');
    }

    @isTest
    public static void actualizarAccesorioDelInformeDespachado() {
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Accesorios_del_informe__c> accInfList = [
            SELECT ID, Estado__c
            FROM Accesorios_del_informe__c
        ];
        
        accInfList[0].Estado__c = 'Despachado';
        
        update accInfList;
        
        accInfList[0].Cantidad__c = 2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Vendedor'];
        
        User u = new User();
        u.Alias = 'TestUser';
        u.Email = 'test@email.com';
        u.EmailEncodingKey = 'UTF-8';
        u.LastName = 'Testing'; 
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US'; 
        u.ProfileId = p.Id;
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.UserName = 'test@email.com.casapellas';
        
        System.runAs(u) {
            Test.startTest();
            List<Database.SaveResult> sr = Database.update(accInfList, false);
            Test.stopTest();

            System.assertEquals(false, sr[0].isSuccess(), 'La actualizacion no falla aunque deberia hacerlo');
            System.assertEquals('No puede modificar un accesorio ya despachado.', 
                                sr[0].getErrors()[0].getMessage(), 
                                'La eliminacion de un informe con accesorios despachado se realizo cuando no deberia.');
        }
    }

    @isTest
    public static void solicitarAccesorioEquivalenteNulo() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Accesorios_del_informe__c> accInfList = [
            SELECT ID, Solicitar_Accesorio_Equivalente__c, Accesorio__c
            FROM Accesorios_del_informe__c
        ];

        List<Accesorios__c> accList = [
            SELECT ID, CodParteEquivalente__c
            FROM Accesorios__c
        ];

        accList[0].CodParteEquivalente__c = '';
        update accList;

        accInfList[0].Solicitar_Accesorio_Equivalente__c = true;

        Test.startTest();
        List<Database.SaveResult> sr = Database.update(accInfList, false);
        Test.stopTest();

        System.assertEquals(false, sr[0].isSuccess(), 'La solicitud de un accesorio equivalente nulo no falla aunque deberia hacerlo');
        System.assertEquals('No puede solicitarse un accesorio equivalente si el accesorio no tiene codigo equivalente.', 
                            sr[0].getErrors()[0].getMessage(), 
                            'El mensaje de la solicitud de accesorio equivalente nulo no es el esperado.');
    }

    @isTest
    public static void eliminarAccesorioDelInformeDespachado() {
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Accesorios_del_informe__c> accInfList = [
            SELECT ID, Estado__c
            FROM Accesorios_del_informe__c
        ];

        accInfList[0].Estado__c = 'Despachado';

        update accInfList;
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Vendedor'];
        
        User u = new User();
        u.Alias = 'TestUser';
        u.Email = 'test@email.com';
        u.EmailEncodingKey = 'UTF-8';
        u.LastName = 'Testing'; 
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US'; 
        u.ProfileId = p.Id;
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.UserName = 'test@email.com.casapellas';
        
        System.runAs(u) {
            Test.startTest();
            List<Database.DeleteResult> dr = Database.delete(accInfList, false);
            Test.stopTest();

            System.assertEquals(false, dr[0].isSuccess(), 'La eliminacion de un accesorio despachado no falla aunque deberia hacerlo');
            System.assertEquals('No puede eliminar un accesorio ya despachado.', 
                                dr[0].getErrors()[0].getMessage(), 
                                'El mensaje de la eliminacion de un accesorio despachado no es el esperado.');
        }
    }

    @isTest
    public static void eliminarAccesorioDeUnInformeReservado() {
    	Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        List<Informe_de_Negociaci_n__c> infList = [
            SELECT ID, Reservar__c
            FROM Informe_de_Negociaci_n__c
        ];

        List<Accesorios_del_informe__c> accInfList = [
            SELECT ID
            FROM Accesorios_del_informe__c
        ];

        infList[0].Reservar__c = true;
        update infList;

        Test.startTest();
        List<Database.DeleteResult> dr = Database.delete(accInfList, false);
        Test.stopTest();

        System.assertEquals(false, dr[0].isSuccess(), 'La eliminacion no falla aunque deberia hacerlo');
        System.assertEquals('El informe se encuentra Reservado, por lo que no es posible eliminar los accesorios', 
                            dr[0].getErrors()[0].getMessage(), 
                            'La eliminacion de un informe con accesorios despachado se realizo cuando no deberia.');
    }
}