force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcesaGetAccesoriosChasis.cls
public class ProcesaGetAccesoriosChasis {

    @future (callout = true)
    public static void getAccesoriosChasis (String chasis, String idInfNeg){
        
        WS_InformeNegociaciones.wsInformeNegociacionPort port = new WS_InformeNegociaciones.wsInformeNegociacionPort();
        port.timeout_x = 120000;
        String resp = port.GetAccesoriosChasis(Label.strKey, Label.strApp, Label.strModulo, chasis);
        
        System.debug('res: ' + resp);
        
        Dom.Document doc = new Dom.Document();  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  
        
        System.debug('rootElement.getChildElements(): ' + rootElement.getChildElements().isEmpty());
        List<wAccesorioChasis> listWAccChasis = new List<wAccesorioChasis>();
        List<Accesorios_del_informe__c> listAccInf = new List<Accesorios_del_informe__c>();
        
        
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
            	wAccesorioChasis acc = new wAccesorioChasis ();             
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){ 
                switch on detailElement.getName() {
                    when 'cantidad'		{ 
                        acc.cantidad	= detailElement.getText().trim() != '' ? Integer.valueOf(detailElement.getText()) : 0; 
                    	system.debug('cantidad:' + detailElement.getText());
                    }
                    when 'codigoArticulo'{ 
                        acc.codigoArticulo		= detailElement.getText() != null ? detailElement.getText() : null; 
                        system.debug('codigoArticulo:' + detailElement.getText());
                    }
                    when 'descripcion'	{ 
                        acc.descripcion	= detailElement.getText() != null ? detailElement.getText() : null; 
                        system.debug('descripcion:' + detailElement.getText());
                    }
                    when 'estado'		{ 
                        acc.estado	= detailElement.getText() != null ? detailElement.getText() : null; 
                        system.debug('estado:' + detailElement.getText());
                    }
                    
                    when else 				{  }
                    
                }
            }
        	
            if(acc.codigoArticulo != null){
                listWAccChasis.add(acc);    
            }
        	
    	}
        
        if(!listWAccChasis.isEmpty()){
            for(wAccesorioChasis wacc : listWAccChasis){
            	Accesorios_del_informe__c accInf 	= new Accesorios_del_informe__c ();
                accInf.Accesorio__r   				= new Accesorios__c(CodigoParte__c=wacc.codigoArticulo);  
                accInf.Cantidad__c	  				= wacc.cantidad;
                accInf.Descripcion__c 				= wacc.descripcion;
                accInf.Estado__c	  				= wacc.estado;
                accInf.Estado__c	  				= wacc.estado;
                if(!test.isRunningTest()){
                	accInf.InformeNegociacion__c		= idInfNeg;    
                }else{
                    accInf.InformeNegociacion__c		= (new Informe_de_Negociaci_n__c()).Id;
                }
                
            	listAccInf.add(accInf);        
            }
            
            
            if(!listAccInf.isEmpty()){
                
                Database.SaveResult[] srList  = Database.insert(listAccInf, false);
                
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()){
                        System.debug(sr.getId());
                    }else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                            System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                        }
                    }
                } 
            }
            
        }

	}
    
    public class wAccesorioChasis {
        public Integer cantidad;
        public String codigoArticulo;
        public String descripcion;
        public String estado;
    }
}