force-app/main/default/objects/Accesorios__c/Accesorios__c.object-meta.xml
<CustomObject>
    <label>Accesorio</label>
    <nameField>
        <label>Nombre de Accesorios Despachados</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accesorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios__c/fields/CantidadMinima__c.field-meta.xml
<CustomField>
    <fullName>CantidadMinima__c</fullName>
    <description>Variable original ifeule .</description>
    <label>Cantidad mínima permitida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/CodigoParte__c.field-meta.xml
<CustomField>
    <fullName>CodigoParte__c</fullName>
    <description>Variable original inopar .</description>
    <externalId>true</externalId>
    <label>Código de la parte</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Compa_a_UDC__c.field-meta.xml
<CustomField>
    <fullName>Compa_a_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accesorios</relationshipLabel>
    <relationshipName>Accesorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Variable original idescr .</description>
    <label>Descripción del Accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/DescripcionAmplia__c.field-meta.xml
<CustomField>
    <fullName>DescripcionAmplia__c</fullName>
    <description>Variable original idesci .</description>
    <label>Descripción amplia del accesorio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Accesorios__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <description>Variable original iprven .</description>
    <label>Precio del accesorio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Combo__c/Combo__c.object-meta.xml
<CustomObject>
    <label>Combo</label>
    <nameField>
        <label>Nombre de Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Combo__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Combo_Accesorio__c/Combo_Accesorio__c.object-meta.xml
<CustomObject>
    <label>Accesorio del combo</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Nombre de Accesorio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del combo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Combo_Accesorio__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipName>Combos_Accesorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Combo_Accesorio__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <label>Combo</label>
    <referenceTo>Combo__c</referenceTo>
    <relationshipName>Combos_Accesorios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Combo_Accesorio__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <formula>Accesorio__r.Precio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ConsumirCombosTest.cls
@isTest
public class ConsumirCombosTest {
    @TestSetup
    public static void crearAccesorios () {
        List<Accesorios__c> accList = new List<Accesorios__c>();
        List<Combo__c> comboList = new List<Combo__c>();

        Id companiaID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Companias')
                                    .getRecordTypeId();
        
        Catalogo_UDC__c companiasTest = new Catalogo_UDC__c();
        companiasTest.Name = 'KIPESA';
        companiasTest.productcode__c = 'COMP';
        companiasTest.RecordTypeId = companiaID;
        
        insert companiasTest;
        
        Accesorios__c acc = new Accesorios__c();
        acc.Name = 'Accesorio de Prueba';
        acc.CodigoParte__c = '70Q42457';
        acc.CurrencyIsoCode = 'USD';
        acc.Precio__c = 10.0;
        acc.CantidadMinima__c = 1;
        acc.DescripcionAmplia__c = 'Test';
        acc.Descripcion__c = 'Test';
        acc.Compa_a_UDC__c = companiasTest.ID;

        accList.add(acc);

        Accesorios__c acc2 = new Accesorios__c();
        acc2.Name = 'Segundo accesorio de Prueba';
        acc2.CodigoParte__c = '70Q40883';
        acc2.CurrencyIsoCode = 'USD';
        acc2.Precio__c = 20.0;
        acc2.CantidadMinima__c = 1;
        acc2.DescripcionAmplia__c = 'Test';
        acc2.Descripcion__c = 'Test';
        acc2.Compa_a_UDC__c = companiasTest.ID;

        accList.add(acc2);

        insert accList;

        Combo__c c = new Combo__c();
        c.Id_Externo__c = '1143';
        c.Name = 'ALFOMBRA DE CARGA GRIS PRADO (2021)';

        comboList.add(c);

        Combo__c c2 = new Combo__c();
        c2.Id_Externo__c = '1147';
        c2.Name = 'ALFOMBRA DE CARGA RAV4 (2021)';

        comboList.add(c2);

        insert comboList;

        Combo_Accesorio__c comboAcc = new Combo_Accesorio__c();
        comboAcc.Combo__c = c2.ID;
        comboAcc.Accesorio__c = acc2.ID;
        comboAcc.Cantidad__c = 1;

        insert comboAcc;
    }

    @IsTest
    public static void consumirCombosTest(){
        List<String> combosNameList = new List<String>();
        combosNameList.add('ALFOMBRA DE CARGA GRIS PRADO (2021)');
        combosNameList.add('ALFOMBRA DE CARGA RAV4 (2021)');

        List<ID> combosIDList = new List<ID>();
        List<ID> accesoriosIDList = new List<ID>();

        Test.startTest();
        ConsumirCombos.consumirCombos();
        Test.stopTest();

        List<Combo__c> combosList = 
            [SELECT ID, Name
            FROM Combo__c 
            ];

        List<Combo_Accesorio__c> combosAccList = 
            [SELECT ID, Combo__c, Accesorio__c, Cantidad__c
            FROM Combo_Accesorio__c
            WHERE Cantidad__c > 1
            ];

        for (Accesorios__c acc : [SELECT ID 
                                  FROM Accesorios__c
                                  ]) {
            accesoriosIDList.add(acc.ID);
        }

        for (Combo__c c : combosList) {
            combosIDList.add(c.ID);
        }

        System.assertEquals(2, 
                            combosList.size(), 
                            'No se estan creando todos los combos');

        for (Combo__c c : combosList) {
            System.assertEquals(true, 
                                combosNameList.contains(c.Name), 
                                'El nombre del combo ' + c.Name + 'no coincide con lo esperado.');
        }

        System.assertEquals(1, 
                            combosAccList.size(), 
                            'Los accesorios no se estan anexando a los combos como corresponde.');
        
        System.assertEquals(true, 
                            combosIDList.contains(combosAccList[0].Combo__c), 
                            'El combo relacionado no es el esperado.');

        System.assertEquals(true, 
                            accesoriosIDList.contains(combosAccList[0].Accesorio__c), 
                            'El accesorio relacionado no es el esperado.');

        System.assertEquals(3, 
                            combosAccList[0].Cantidad__c, 
                            'La cantidad de la relacion no es la esperado.');
    }
}