force-app/main/default/objects/Calificaci_n_del_cliente__c/Calificaci_n_del_cliente__c.object-meta.xml
<CustomObject>
    <label>Calificación del cliente</label>
    <nameField>
        <label>Nombre de Calificación del cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calificaciones del cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Calificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Calificaci_n__c</fullName>
    <label>Calificación</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Criterio__c.field-meta.xml
<CustomField>
    <fullName>Criterio__c</fullName>
    <label>Criterio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tipo Persona</fullName>
            </value>
            <value>
                <fullName>Tipo Cliente</fullName>
            </value>
            <value>
                <fullName>Doc. Identidad</fullName>
            </value>
            <value>
                <fullName>Tipo Relación</fullName>
            </value>
            <value>
                <fullName>Nivel Organizacional</fullName>
            </value>
            <value>
                <fullName>Profesión</fullName>
            </value>
            <value>
                <fullName>Ocupación</fullName>
            </value>
            <value>
                <fullName>Actividad Economica</fullName>
            </value>
            <value>
                <fullName>Canal Contrata</fullName>
            </value>
            <value>
                <fullName>Sucursal</fullName>
            </value>
            <value>
                <fullName>Forma de pago</fullName>
            </value>
            <value>
                <fullName>Tipo de transacción</fullName>
            </value>
            <value>
                <fullName>Responsable del pago</fullName>
            </value>
            <value>
                <fullName>Origen de los fondo</fullName>
            </value>
            <value>
                <fullName>Procedencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calificaciones del cliente</relationshipLabel>
    <relationshipName>Calificaciones_del_cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Descripci_n__c.field-meta.xml
<CustomField>
    <fullName>Descripci_n__c</fullName>
    <label>Descripción</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Calificaciones del cliente</relationshipLabel>
    <relationshipName>Calificaciones_del_cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Ponderaci_n__c.field-meta.xml
<CustomField>
    <fullName>Ponderaci_n__c</fullName>
    <label>Ponderación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Diferencia registros para obtentcion de calificacion cliente y de oportunidad</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calificaci_n_del_cliente__c/fields/Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Juridico</fullName>
            </value>
            <value>
                <fullName>Natural</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Canal_Contrata__c.field-meta.xml
<CustomField>
    <fullName>Canal_Contrata__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribuidor Autorizado</fullName>
            </value>
            <value>
                <fullName>Sucursales Propias - Detalle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_UAF__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_UAF__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Depósitos bancarios</fullName>
            </value>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
            </value>
            <value>
                <fullName>Transferencia bancaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Donaciones (Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Donaciones (No Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Responsable_del_pago__c.field-meta.xml
<CustomField>
    <fullName>Responsable_del_pago__c</fullName>
    <label>Responsable del pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>Tercero Familiar</fullName>
            </value>
            <value>
                <fullName>Tercero Ajeno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_relaci_n_econ_mica__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_relaci_n_econ_mica__c</fullName>
    <label>Tipo de relación económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Credito</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_transacci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_transacci_n__c</fullName>
    <label>Tipo de transacción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anticipo o Prima</fullName>
            </value>
            <value>
                <fullName>Compra de Credito</fullName>
            </value>
            <value>
                <fullName>Compra de Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CMP_ControllerScoringUAF.cls
public class CMP_ControllerScoringUAF {
 
    @AuraEnabled
    public static Calificacion getCalificacionCliente(String recordId) 
    {
       try 
       {
            Calificacion calificacionesLst = new Calificacion();
            Opportunity op = 
                [SELECT Id, AccountId, RecordTypeId, Name, Description, StageName,Tipo_de_relaci_n_econ_mica__c 
                FROM Opportunity 
                where Id=:recordId
                ];
           
            List<Calificaci_n_del_cliente__c> calificacionesClientes = 
                [SELECT Id, Name, Oportunidad__c, Cuenta__c, Tipo_de_Cliente__c, Criterio__c, 
                          Descripci_n__c,Calificaci_n__c, Ponderaci_n__c, Total__c,Tipo__c 
                  FROM Calificaci_n_del_cliente__c 
                  where Oportunidad__c =:op.Id 
                 		AND Cuenta__c=:op.AccountId 
                 		AND Tipo__c='CC'
                ];
           
            system.debug('calificacionesClientes '+calificacionesClientes);
            Calificacion califObj=new Calificacion();
            califObj.Tipocliente=calificacionesClientes[0].Tipo_de_Cliente__c;
            califObj.Nombre=calificacionesClientes[0].Name;
            califObj.Total=calificacionesClientes[0].Total__c;
            califObj.CalificacionFinal=calificacionesClientes[0].Ponderaci_n__c;
            califObj.calificaciones=calificacionesClientes;
            calificacionesLst=califObj;
            
            system.debug('calificacionesLst '+calificacionesLst);
           
        return calificacionesLst;
           
       }
       catch(Exception err)
       {
           throw new AuraHandledException('Error detectado '+err.getMessage()+' Linea '+err.getLineNumber());
       } 

    }
    
    @AuraEnabled
    public static CalificacionOP getCalificacionOportunidad(String recordId) {
        try{
            CalificacionOP calificacionesLst=new CalificacionOP();
            Opportunity op = [
                SELECT Id, AccountId, RecordTypeId, Name, Description, StageName,
                Tipo_de_relaci_n_econ_mica__c,Canal_Contrata__c,
                Sucursal__c,Forma_de_Pago_UAF__c,Tipo_de_transacci_n__c,
                Responsable_del_pago__c,Origen_de_los_fondos__c
                FROM Opportunity 
                where Id=:recordId
            ];
            
            List<Calificaci_n_del_cliente__c> calificacionesClientesOP = [
                SELECT Id, Name, Oportunidad__c, Cuenta__c, Tipo_de_Cliente__c, Criterio__c, 
                Descripci_n__c,Calificaci_n__c, Ponderaci_n__c, Total__c,Tipo__c 
                FROM Calificaci_n_del_cliente__c 
                where Oportunidad__c =:op.Id 
                AND Cuenta__c=:op.AccountId 
                AND Tipo__c='CO'
            ];
            
            system.debug('calificacionesOPs '+calificacionesClientesOP);
            CalificacionOP califObjO=new CalificacionOP();
            
            califObjO.TotalOP=calificacionesClientesOP[0].Total__c;
            califObjO.CalificacionFinalOP=calificacionesClientesOP[0].Ponderaci_n__c;
            califObjO.calificacionesOP=calificacionesClientesOP;
            calificacionesLst=califObjO;
            
            system.debug('calificacionesLst '+calificacionesLst);
            
            return calificacionesLst;
        }
        catch(Exception err){
            throw new AuraHandledException('Error detectado '+err.getMessage()+' Linea '+err.getLineNumber());
        } 
    }
    
    public class Calificacion
    {
        @AuraEnabled
        public Decimal Total{set;get;}
        @AuraEnabled
        public String CalificacionFinal {set;get;}
        @AuraEnabled
        public String Tipocliente {set;get;}
        @AuraEnabled
        public String Nombre {set;get;}
        @AuraEnabled
        public List<Calificaci_n_del_cliente__c> calificaciones{set;get;}
        @AuraEnabled
        public List<Calificaci_n_del_cliente__c> calificacionesOp{set;get;} 
       
    }
    
    public class CalificacionOP
    {
        @AuraEnabled
        public Decimal TotalOP{set;get;}
        @AuraEnabled
        public String CalificacionFinalOP {set;get;}
        @AuraEnabled
        public List<Calificaci_n_del_cliente__c> calificacionesOP{set;get;} 
       
    }
}