force-app/main/default/objects/Exchange_Rate_By_Date__c/Exchange_Rate_By_Date__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate By Date</label>
    <nameField>
        <label>Nombre de Exchange Rate By Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExchangeRateByDate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate_By_Date__c/fields/Tasa__c.field-meta.xml
<CustomField>
    <fullName>Tasa__c</fullName>
    <label>Tasa del cambio del día enviado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcesaWS_ExchangeRateByDate.cls
public class ProcesaWS_ExchangeRateByDate {
    @future (callout=true)
    public static void get_ExchangeRateByDate () {
        DateTime hoy = Datetime.now();
        
        Exchange_Rate_By_Date__c tc = new Exchange_Rate_By_Date__c();
        WS_InformeNegociaciones.wsInformeNegociacionPort port = new WS_InformeNegociaciones.wsInformeNegociacionPort();
        port.timeout_x = 120000;
        Decimal tipoDeCambio = port.GetExchangeRateByDate(Label.strKey, Label.strApp, Label.strModulo, hoy, 'USD');
        if(tipoDeCambio != null) {
            tc.Tasa__c = tipoDeCambio;
            tc.Name = 'USD - ' + Date.today();
            tc.CurrencyIsoCode = 'USD';
            
            System.debug(tc);
            
            insert tc;
        }
    }
}