force-app/main/default/objects/Account/fields/Actividad_economica_UDC__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actividad económica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Actividad económica</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Actividad económica)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nivel_organizacional__c.field-meta.xml
<CustomField>
    <fullName>Nivel_organizacional__c</fullName>
    <label>Tipo de contribuyente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asalariado</fullName>
            </value>
            <value>
                <fullName>Cuota Fija</fullName>
            </value>
            <value>
                <fullName>Gran Contribuyente</fullName>
            </value>
            <value>
                <fullName>Mediano Contribuyente</fullName>
            </value>
            <value>
                <fullName>No trabaja</fullName>
            </value>
            <value>
                <fullName>Trabajo Cuenta Propia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ocupacion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ocupacion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ocupación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ocupación</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Ocupación)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pa_s__c.field-meta.xml
<CustomField>
    <fullName>Pa_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pais</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profesion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Profesion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesión</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesión</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Profesión)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Ocasional</fullName>
            </value>
            <value>
                <fullName>Habitual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cliente__c</fullName>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Natural</fullName>
            </value>
            <value>
                <fullName>Jurídico</fullName>
                <label>Sujeto Obligado Jurídico</label>
            </value>
            <value>
                <fullName>PEP</fullName>
                <label>PEP Natural</label>
            </value>
            <value>
                <fullName>Empresa Estatal</fullName>
            </value>
            <value>
                <fullName>Empresa Privada</fullName>
            </value>
            <value>
                <fullName>Organizaciones sin fines de lucro</fullName>
                <label>OSFL</label>
            </value>
            <value>
                <fullName>Sujeto Obligado</fullName>
                <label>Sujeto Obligado Natural</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Actividad_Economica.recordType-meta.xml
<RecordType>
    <fullName>Actividad_Economica</fullName>
    <active>true</active>
    <label>Actividad económica</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Ocupacion.recordType-meta.xml
<RecordType>
    <fullName>Ocupacion</fullName>
    <active>true</active>
    <label>Ocupación</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Pais.recordType-meta.xml
<RecordType>
    <fullName>Pais</fullName>
    <active>true</active>
    <label>Pais</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Profesion.recordType-meta.xml
<RecordType>
    <fullName>Profesion</fullName>
    <active>true</active>
    <label>Profesión</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Canal_Contrata__c.field-meta.xml
<CustomField>
    <fullName>Canal_Contrata__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribuidor Autorizado</fullName>
            </value>
            <value>
                <fullName>Sucursales Propias - Detalle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_UAF__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_UAF__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Depósitos bancarios</fullName>
            </value>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
            </value>
            <value>
                <fullName>Transferencia bancaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Responsable_del_pago__c.field-meta.xml
<CustomField>
    <fullName>Responsable_del_pago__c</fullName>
    <label>Responsable del pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>Tercero Familiar</fullName>
            </value>
            <value>
                <fullName>Tercero Ajeno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_relaci_n_econ_mica__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_relaci_n_econ_mica__c</fullName>
    <label>Tipo de relación económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Credito</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_transacci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_transacci_n__c</fullName>
    <label>Tipo de transacción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anticipo o Prima</fullName>
            </value>
            <value>
                <fullName>Compra de Credito</fullName>
            </value>
            <value>
                <fullName>Compra de Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerScoringUAFTest.cls
@isTest
public class ControllerScoringUAFTest {
	@TestSetup
    public static void crearCuentasYOpp() {
        Id paisUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Pais')
                                    .getRecordTypeId();

        Id actEconomicaUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Actividad_Economica')
                                    .getRecordTypeId();

        Id profesionUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Profesion')
                                    .getRecordTypeId();

        Id ocupacionUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Ocupacion')
                                    .getRecordTypeId();

        Catalogo_UDC__c paisTest = new Catalogo_UDC__c();
        paisTest.Name = 'Argentina';
        paisTest.productcode__c = 'P';
        paisTest.RecordTypeId = paisUDCID;

        Catalogo_UDC__c actEconomicaTest = new Catalogo_UDC__c();
        actEconomicaTest.Name = 'Comercio';
        actEconomicaTest.productcode__c = 'A';
        actEconomicaTest.RecordTypeId = actEconomicaUDCID;

        Catalogo_UDC__c profesionTest = new Catalogo_UDC__c();
        profesionTest.Name = 'Comunicador';
        profesionTest.productcode__c = 'P';
        profesionTest.RecordTypeId = profesionUDCID;

        Catalogo_UDC__c ocupacionTest = new Catalogo_UDC__c();
        ocupacionTest.Name = 'Contador';
        ocupacionTest.productcode__c = 'O';
        ocupacionTest.RecordTypeId = ocupacionUDCID;

        List<Catalogo_UDC__c> catList = new List<Catalogo_UDC__c> {paisTest,
                                                                  actEconomicaTest,
                                                                  profesionTest,
                                                                  ocupacionTest} ;

        insert catList;
        
        Id personAccountID = Schema.SObjectType.Account
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('PersonAccount')
                                    .getRecordTypeId();

        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        Account acc = new Account();

       	acc.Name = 'Test J Account';
        acc.Nivel_organizacional__c = 'No trabaja';
        acc.Ocupacion_UDC__c = ocupacionTest.ID;
        acc.Actividad_economica_UDC__c = actEconomicaTest.ID;
        acc.Profesion_UDC__c = profesionTest.ID;
        acc.Pa_s__c = paisTest.ID;
        acc.Cedula__c = '123juridica';
        acc.Tipo_Cliente__c = 'Nuevo';
        acc.Tipo_de_Indentificaci_n__c = 'Otros';
        acc.Tipo_de_cliente__c = 'Organizaciones sin fines de lucro';
        acc.Email__c = 'email@email.com';
        
        insert acc;
        
        Account pAcc = new Account();

       	pAcc.LastName = 'Account';
        pAcc.FirstName = 'Test N';
        pAcc.Nivel_organizacional__c = 'No trabaja';
        pAcc.Ocupacion_UDC__c = ocupacionTest.ID;
        pAcc.Actividad_economica_UDC__c = actEconomicaTest.ID;
        pAcc.Profesion_UDC__c = profesionTest.ID;
        pAcc.Cedula__c = '123natural';
        pAcc.Pa_s__c = paisTest.ID;
        pAcc.Tipo_Cliente__c = 'Nuevo';
        pAcc.Tipo_de_Indentificaci_n__c = 'Otros';
        pAcc.Tipo_de_cliente__c = 'Natural';
        pAcc.Email__c = 'email@email.com';
        
        insert pAcc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.Sucursal__c = 'Estelí';
        opp.Tipo_de_relaci_n_econ_mica__c = 'Contado';
        opp.AccountId = acc.ID;
        opp.Canal_Contrata__c = 'Distribuidor Autorizado';
        opp.Forma_de_Pago_UAF__c = 'Efectivo';
        opp.Tipo_de_transacci_n__c = 'Compra de Contado';
        opp.Responsable_del_pago__c = 'Facturado';
        opp.Origen_de_los_fondos__c = 'Otros';
        opp.StageName = 'Contacto Exitoso';
        opp.CloseDate = Date.today() + 7;
        
        insert opp;
        
        Opportunity nOpp = new Opportunity();
        nOpp.Name = 'Test';
        nOpp.Sucursal__c = 'Estelí';
        nOpp.Tipo_de_relaci_n_econ_mica__c = 'Contado';
        nOpp.AccountId = pAcc.ID;
        nOpp.Canal_Contrata__c = 'Distribuidor Autorizado';
        nOpp.Forma_de_Pago_UAF__c = 'Efectivo';
        nOpp.Tipo_de_transacci_n__c = 'Compra de Contado';
        nOpp.Responsable_del_pago__c = 'Facturado';
        nOpp.Origen_de_los_fondos__c = 'Otros';
        nOpp.StageName = 'Contacto Exitoso';
        nOpp.CloseDate = Date.today() + 7;
        
        insert nOpp;
    }
    
    @isTest
    public static void getCalificacionOportunidadTest() {
        List<Opportunity> oppList = 
            [SELECT ID
            FROM Opportunity
            ];
        
        /*Test.startTest();
        ProcesarScoringUAF.generarCalificacion(new List<ID> {oppList[0].ID});
        CMP_ControllerScoringUAF.getCalificacionOportunidad(oppList[0].ID);
        Test.stopTest();*/
    }
    
    @isTest
    public static void getCalificacionClienteTest() {
        List<Opportunity> oppList = [
            SELECT ID
            FROM Opportunity
        ];
        
        /*Test.startTest();
        ProcesarScoringUAF.generarCalificacion(new List<ID> {oppList[0].ID});
        CMP_ControllerScoringUAF.getCalificacionCliente(oppList[0].ID);
        Test.stopTest();*/
    }
}