force-app/main/default/objects/Account/fields/Actividad_economica_UDC__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actividad económica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Actividad económica</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Actividad económica)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Algun_familiar_es_PEP__c.field-meta.xml
<CustomField>
    <fullName>Algun_familiar_es_PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Algún familiar es PEP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cargo_PEP__c.field-meta.xml
<CustomField>
    <fullName>Cargo_PEP__c</fullName>
    <label>Cargo que ocupa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cargo_PEP_del_familiar__c.field-meta.xml
<CustomField>
    <fullName>Cargo_PEP_del_familiar__c</fullName>
    <label>Cargo PEP del familiar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Municipio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Representante_Legal__c.field-meta.xml
<CustomField>
    <fullName>Representante_Legal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante Legal</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cuentas (Representante Legal)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <description>Numero de identificación único de cada contacto</description>
    <label>Número de documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comentario_del_PIC__c.field-meta.xml
<CustomField>
    <fullName>Comentario_del_PIC__c</fullName>
    <label>Comentario del PIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compa_a__c.field-meta.xml
<CustomField>
    <fullName>Compa_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Compañía)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comprador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Comprador)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Donaciones (Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Donaciones (No Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Procedencia_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Procedencia_de_los_fondos__c</fullName>
    <label>Procedencia de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Microfinancieras</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PC_PJuridica_PDF_Controller.cls
public class PC_PJuridica_PDF_Controller {
    public string strFechaHoraMex {get;set;}				//Fecha-Hora 
    public Account cuentaPJ {get;set;} 						// Variable para Visualforce de la cuenta Persona Jurídica
    public Opportunity opp {get;set;}
    public String oppID {get;set;}
    public Account representanteLegal {get; set;}

    public PC_PJuridica_PDF_Controller(ApexPages.StandardController stdController) {
        String pageLink = ApexPages.currentpage().getUrl();
        String cuentaId;
        if (pageLink.contains('null')) {
            cuentaId = ApexPages.currentpage().getparameters().get('id');
            oppID = null;
        } else {
            cuentaId = stdController.getId();
            oppID = ApexPages.currentpage().getparameters().get('idOpp');
        }

        cuentaPJ = 
            [SELECT Name, Cedula__c, Email__c, Phone, Direccion__c,
                    Departamento__r.Name, Municipio__r.Name, Actividad_economica_UDC__r.Name,
                    Representante_Legal__r.Name, Representante_Legal__r.Numero_de_documento__c,
                    Representante_Legal__r.Phone, Representante_Legal__c, Representante_Legal__r.AccountId
            FROM Account 
            WHERE ID =: cuentaId
            LIMIT 1 
            ];
        
        if (String.isNotBlank(cuentaPJ.Representante_Legal__c)) {     
            representanteLegal = [
                SELECT PEP__c, Cargo_PEP__c, Algun_familiar_es_PEP__c, Cargo_PEP_del_familiar__c
                FROM Account
                WHERE ID =: cuentaPJ.Representante_Legal__r.AccountId
                LIMIT 1
            ];
        }
        
        if (oppID != null) {
            opp = 
                [SELECT Name, Compa_a__r.Name, Origen_de_los_fondos__c, Procedencia_de_los_fondos__c, Comprador__c, Comprador__r.Name, 
                        Comprador__r.Numero_de_documento__c, Comentario_del_PIC__c
                FROM Opportunity
                WHERE ID =: oppID
                LIMIT 1
                ];
        }
        
        //Obtenemos fecha actual
        Datetime datFechaActual = Datetime.now();
        //Formateamos la fecha
        strFechaHoraMex = datFechaActual.format('hh:mm:ss aa','America/Mexico_City');
        
        String cuenta = cuentaPJ.Name.replaceAll(' ','_').replaceAll(',','_');
        
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=PIC_'+ cuenta + '.pdf');
    }
    
}