force-app/main/default/objects/Account/fields/Actividad_economica_UDC__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actividad económica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Actividad económica</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Actividad económica)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nivel_organizacional__c.field-meta.xml
<CustomField>
    <fullName>Nivel_organizacional__c</fullName>
    <label>Tipo de contribuyente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asalariado</fullName>
            </value>
            <value>
                <fullName>Cuota Fija</fullName>
            </value>
            <value>
                <fullName>Gran Contribuyente</fullName>
            </value>
            <value>
                <fullName>Mediano Contribuyente</fullName>
            </value>
            <value>
                <fullName>No trabaja</fullName>
            </value>
            <value>
                <fullName>Trabajo Cuenta Propia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ocupacion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ocupacion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ocupación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ocupación</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Ocupación)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pa_s__c.field-meta.xml
<CustomField>
    <fullName>Pa_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pais</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profesion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Profesion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesión</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesión</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Profesión)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Ocasional</fullName>
            </value>
            <value>
                <fullName>Habitual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cliente__c</fullName>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Natural</fullName>
            </value>
            <value>
                <fullName>Jurídico</fullName>
                <label>Sujeto Obligado Jurídico</label>
            </value>
            <value>
                <fullName>PEP</fullName>
                <label>PEP Natural</label>
            </value>
            <value>
                <fullName>Empresa Estatal</fullName>
            </value>
            <value>
                <fullName>Empresa Privada</fullName>
            </value>
            <value>
                <fullName>Organizaciones sin fines de lucro</fullName>
                <label>OSFL</label>
            </value>
            <value>
                <fullName>Sujeto Obligado</fullName>
                <label>Sujeto Obligado Natural</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Actividad_Economica.recordType-meta.xml
<RecordType>
    <fullName>Actividad_Economica</fullName>
    <active>true</active>
    <label>Actividad económica</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Ocupacion.recordType-meta.xml
<RecordType>
    <fullName>Ocupacion</fullName>
    <active>true</active>
    <label>Ocupación</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Pais.recordType-meta.xml
<RecordType>
    <fullName>Pais</fullName>
    <active>true</active>
    <label>Pais</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Profesion.recordType-meta.xml
<RecordType>
    <fullName>Profesion</fullName>
    <active>true</active>
    <label>Profesión</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Sucursales.recordType-meta.xml
<RecordType>
    <fullName>Sucursales</fullName>
    <active>true</active>
    <label>Sucursales</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Canal_Contrata__c.field-meta.xml
<CustomField>
    <fullName>Canal_Contrata__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribuidor Autorizado</fullName>
            </value>
            <value>
                <fullName>Sucursales Propias - Detalle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Responsable_del_pago__c.field-meta.xml
<CustomField>
    <fullName>Responsable_del_pago__c</fullName>
    <label>Responsable del pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>Tercero Familiar</fullName>
            </value>
            <value>
                <fullName>Tercero Ajeno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_relaci_n_econ_mica__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_relaci_n_econ_mica__c</fullName>
    <label>Tipo de relación económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Credito</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_transacci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_transacci_n__c</fullName>
    <label>Tipo de transacción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anticipo o Prima</fullName>
            </value>
            <value>
                <fullName>Compra de Credito</fullName>
            </value>
            <value>
                <fullName>Compra de Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcesarScoringUAFTest.cls
@isTest
public class ProcesarScoringUAFTest {
    @TestSetup
    public static void crearCuentasYOpp() {
        Id paisUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Pais')
                                    .getRecordTypeId();

        Id actEconomicaUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Actividad_Economica')
                                    .getRecordTypeId();

        Id profesionUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Profesion')
                                    .getRecordTypeId();

        Id ocupacionUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Ocupacion')
                                    .getRecordTypeId();

        Catalogo_UDC__c argentina = new Catalogo_UDC__c();
        argentina.Name = 'Argentina';
        argentina.productcode__c = 'ARG';
        argentina.RecordTypeId = paisUDCID;

        Catalogo_UDC__c nicaragua = new Catalogo_UDC__c();
        nicaragua.Name = 'Nicaragua';
        nicaragua.productcode__c = 'NIC';
        nicaragua.RecordTypeId = paisUDCID;

        Catalogo_UDC__c comercio = new Catalogo_UDC__c();
        comercio.Name = 'Comercio';
        comercio.productcode__c = 'CMR';
        comercio.RecordTypeId = actEconomicaUDCID;

        Catalogo_UDC__c renta = new Catalogo_UDC__c();
        renta.Name = 'Renta de Vehículos';
        renta.productcode__c = 'REN';
        renta.RecordTypeId = actEconomicaUDCID;

        Catalogo_UDC__c ingeniero = new Catalogo_UDC__c();
        ingeniero.Name = 'Ingeniero en Sistemas';
        ingeniero.productcode__c = 'ING';
        ingeniero.RecordTypeId = profesionUDCID;

        Catalogo_UDC__c tecnico = new Catalogo_UDC__c();
        tecnico.Name = 'Técnico en Computación';
        tecnico.productcode__c = 'TEC';
        tecnico.RecordTypeId = ocupacionUDCID;

        List<Catalogo_UDC__c> catList = new List<Catalogo_UDC__c> {argentina,
                                                                  nicaragua,
                                                                  comercio,
                                                                  renta,
                                                                  ingeniero,
                                                                  tecnico
                                                                } ;

        insert catList;
        
        Id personAccountID = Schema.SObjectType.Account
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('PersonAccount')
                                    .getRecordTypeId();

        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));


        Account acc = new Account();

       	acc.Name = 'Test J Account';
        acc.Nivel_organizacional__c = 'No trabaja';
        acc.Actividad_economica_UDC__c = renta.ID;
        acc.Pa_s__c = argentina.ID;
        acc.Cedula__c = '123juridica';
        acc.Tipo_Cliente__c = 'Habitual';
        acc.Tipo_de_Indentificaci_n__c = 'Otros';
        acc.Tipo_de_cliente__c = 'Organizaciones sin fines de lucro';
        acc.Email__c = 'email@email.com';
        
        insert acc;
        
        Account pAcc = new Account();

       	pAcc.LastName = 'Account';
        pAcc.FirstName = 'Test N';
        pAcc.Nivel_organizacional__c = 'Asalariado';
        pAcc.Ocupacion_UDC__c = tecnico.ID;
        pAcc.Actividad_economica_UDC__c = comercio.ID;
        pAcc.Profesion_UDC__c = ingeniero.ID;
        pAcc.Cedula__c = '123natural';
        pAcc.Pa_s__c = nicaragua.ID;
        pAcc.Tipo_Cliente__c = 'Nuevo';
        pAcc.Tipo_de_Indentificaci_n__c = 'Otros';
        pAcc.Tipo_de_cliente__c = 'Sujeto Obligado';
        pAcc.Email__c = 'email@email.com';
        pAcc.RecordTypeId = personAccountID;
        
        insert pAcc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.Sucursal__c = 'Estelí';
        opp.Tipo_de_relaci_n_econ_mica__c = 'Contado';
        opp.AccountId = acc.ID;
        opp.Canal_Contrata__c = 'Distribuidor Autorizado';
        opp.Tipo_de_transacci_n__c = 'Compra de Contado';
        opp.Responsable_del_pago__c = 'Facturado';
        opp.Origen_de_los_fondos__c = 'Otros';
        opp.StageName = 'Contacto Exitoso';
        opp.Tipo_de_relaci_n_econ_mica__c = 'Contado';
        opp.CloseDate = Date.today() + 7;
        
        insert opp;
        
        Opportunity nOpp = new Opportunity();
        nOpp.Name = 'Test';
        nOpp.Sucursal__c = 'Kia El Retiro';
        nOpp.Tipo_de_relaci_n_econ_mica__c = 'Contado';
        nOpp.AccountId = pAcc.ID;
        nOpp.Canal_Contrata__c = 'Sucursales Propias - Detalle';
        nOpp.Forma_de_Pago_UAF__c = 'Efectivo';
        nOpp.Tipo_de_transacci_n__c = 'Anticipo o Prima';
        nOpp.Responsable_del_pago__c = 'Tercero Familiar';
        nOpp.Origen_de_los_fondos__c = 'Donaciones (Giro Negocio)';
        nOpp.StageName = 'Contacto Exitoso';
        nOpp.Tipo_de_relaci_n_econ_mica__c = 'Licitaciones';
        nOpp.CloseDate = Date.today() + 7;
        
        insert nOpp;

        Informe_de_Negociaci_n__c inf1 = new Informe_de_Negociaci_n__c();
        inf1.Oportunidad__c = opp.ID;
        inf1.total_negociado__c  = 2;
        
        insert inf1;
        
        Informe_de_Negociaci_n__c inf2 = new Informe_de_Negociaci_n__c();
        inf2.Oportunidad__c = nOpp.ID;
        inf2.total_negociado__c  = 2;

        insert inf2;

        List<AllRecibidos__c> recibosList = new List<AllRecibidos__c>();
        List<Recibos_de_la_negociaci_n__c> recibosNegList = new List<Recibos_de_la_negociaci_n__c>();

        for (Integer i = 0; i < 2; i++) {
            AllRecibidos__c rec = new AllRecibidos__c();
            if (i == 0) {
                rec.Instrumento_de_pago__c = 'Efectivo';
                rec.Cuenta__c = pAcc.ID;
            } else {
                rec.Instrumento_de_pago__c = 'Transferencia';
                rec.Cuenta__c = acc.ID;
            }

            rec.Saldo__c = 2;

            recibosList.add(rec);
        }

        insert recibosList;

        for (Integer i = 0; i < 4; i++) {
            Recibos_de_la_negociaci_n__c recNeg = new Recibos_de_la_negociaci_n__c();
            if (Math.mod(i, 4) == 0) {
                recNeg.Recibos__c = recibosList[0].ID;
                recNeg.Informe_de_Negociaci_n__c = inf1.ID;
            } else if (Math.mod(i, 4) == 1) {
                recNeg.Recibos__c = recibosList[0].ID;
                recNeg.Informe_de_Negociaci_n__c = inf2.ID;
            } else if (Math.mod(i, 4) == 2) {
                recNeg.Recibos__c = recibosList[1].ID;
                recNeg.Informe_de_Negociaci_n__c = inf1.ID;
            } else {
                recNeg.Recibos__c = recibosList[1].ID;
                recNeg.Informe_de_Negociaci_n__c = inf2.ID;
            }

            recNeg.Monto_aplicado_a_la_negociaci_n__c = 1;

            recibosNegList.add(recNeg);
        }

        insert recibosNegList;

    }
    
    @isTest
    public static void generarCalificacionTestJuridica() {        
        List<Opportunity> oppList = [
            SELECT ID, AccountID, Tipo_de_relaci_n_econ_mica__c,
                    Canal_Contrata__c, Sucursal__c, Tipo_de_transacci_n__c,
                    Responsable_del_pago__c, Origen_de_los_fondos__c
            FROM Opportunity
            WHERE Name LIKE '%Test J Account%'
            ];

        Test.startTest();
        Map<ID, String> calificacion = ProcesarScoringUAF.generarCalificacion(oppList);
        Test.stopTest();

        System.assertEquals('3.20_3.200', calificacion.get(oppList[0].ID), 'La calificación no coincide con lo esperado en cuentas juridicas.');
    }
    
    @isTest
    public static void generarCalificacionTestPersonal() {
        List<Opportunity> oppList = [
            SELECT ID, AccountID, Tipo_de_relaci_n_econ_mica__c,
                    Canal_Contrata__c, Sucursal__c, Tipo_de_transacci_n__c,
                    Responsable_del_pago__c, Origen_de_los_fondos__c
            FROM Opportunity
            WHERE Name LIKE '%Test N Account%'
            ];
        
        Test.startTest();
        Map<ID, String> calificacion = ProcesarScoringUAF.generarCalificacion(oppList);
        Test.stopTest();

        System.assertEquals('3.00_2.350', calificacion.get(oppList[0].ID), 'La calificación no coincide con lo esperado en cuentas personales.');
    }
}