force-app/main/default/objects/Account/fields/Actividad_economica_UDC__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actividad económica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Actividad económica</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Actividad económica)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Algun_familiar_es_PEP__c.field-meta.xml
<CustomField>
    <fullName>Algun_familiar_es_PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Algún familiar es PEP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cargo_PEP__c.field-meta.xml
<CustomField>
    <fullName>Cargo_PEP__c</fullName>
    <label>Cargo que ocupa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cargo_PEP_del_familiar__c.field-meta.xml
<CustomField>
    <fullName>Cargo_PEP_del_familiar__c</fullName>
    <label>Cargo PEP del familiar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Municipio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad_UDC__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Nacionalidad</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Nacionalidad)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ocupacion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ocupacion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ocupación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ocupación</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Ocupación)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Profesion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Profesion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesión</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesión</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Profesión)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Genero.recordType-meta.xml
<RecordType>
    <fullName>Genero</fullName>
    <active>true</active>
    <label>Género</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Comentario_del_PIC__c.field-meta.xml
<CustomField>
    <fullName>Comentario_del_PIC__c</fullName>
    <label>Comentario del PIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compa_a__c.field-meta.xml
<CustomField>
    <fullName>Compa_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Compañía)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Donaciones (Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Donaciones (No Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Procedencia_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Procedencia_de_los_fondos__c</fullName>
    <label>Procedencia de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Microfinancieras</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Perfil_del_Cliente_PDF_Controller.cls
public class Perfil_del_Cliente_PDF_Controller {
    public Id cuentaId {get; set;}                  //Id de la cuenta
    public string strFechaHoraMex {get; set;}       //Fecha-Hora
    public Account cuentaPN {get; set;}             // Variable para Visualforce de la cuenta Persona Natural
    public String genero {get; set;} 
    public Opportunity opp {get; set;}
    public List<String> apellidos {get; set;}
    
    public Perfil_del_Cliente_PDF_Controller(ApexPages.StandardController stdController) { 
		String pageLink = ApexPages.currentpage().getUrl();
        ID oppID;
        if (pageLink.contains('null')) {
            cuentaId = ApexPages.currentpage().getparameters().get('id');
            oppID = null;
        } else {
            cuentaId = stdController.getId();
            oppID = ApexPages.currentpage().getparameters().get('idOpp');
        }

        cuentaPN = 
            [SELECT ID, FirstName, MiddleName, LastName, Genero_UDC__pc,
                    Nacionalidad_UDC__r.Name, Tipo_de_Indentificaci_n__c, Cedula__c,
                    Direccion__c, Departamento__r.Name, Municipio__r.Name,
                    Email__c, Phone, Actividad_economica_UDC__r.Name, Profesion_UDC__r.Name,
                    Ocupacion_UDC__r.Name, PEP__c, Cargo_PEP__c, Algun_familiar_es_PEP__c, 
                    Cargo_PEP_del_familiar__c
            FROM Account 
            WHERE Id =: cuentaId
            LIMIT 1
            ];

        List<String> splitApellidos = cuentaPN.LastName.split(' ');
        apellidos = new List<String>();
        apellidos.add(splitApellidos[0]);

        System.debug(splitApellidos);

        if (splitApellidos.size() > 1) {
            String segundoApellido = '';
            for (Integer i = 1; i < splitApellidos.size(); i++) {
                segundoApellido += ' ' + splitApellidos[i];
            }
            apellidos.add(segundoApellido);
        } else {
            apellidos.add('-- --');
        }

        System.debug(apellidos);
        
        if (oppID != null) {
            opp = 
                [SELECT Origen_de_los_fondos__c, Procedencia_de_los_fondos__c, Compa_a__r.Name, Comentario_del_PIC__c
                FROM Opportunity 
                WHERE ID =: oppID 
                LIMIT 1
                ];   
        }
        
        try {
            Catalogo_UDC__c generoUDC = 
                [SELECT Id, Name 
                 FROM Catalogo_UDC__c 
                 WHERE Id =: cuentaPN.Genero_UDC__pc 
                 LIMIT 1
                ];   // Se busca en Catálogos UDC
            switch on generoUDC.Name {
                when  'Male' {
                    genero = 'Masculino';
                } when 'Female' {
                    genero = 'Femenino';
                } when else {
                    genero = generoUDC.Name;
                }
            }

        } catch(Exception e) {
            System.debug('Ha ocurrido la siguiente excepción: ' + e.getMessage());
            System.debug('Causa: ' + e.getCause());
            System.debug('Número de Línea: ' + e.getLineNumber());
            genero = '';
         }

        //Obtenemos fecha actual
        Datetime datFechaActual = Datetime.now();        
        //Formateamos la fecha
        strFechaHoraMex = datFechaActual.format('hh:mm:ss aa','America/Mexico_City');
        
        String cuenta = cuentaPn.FirstName.replaceAll(' ','_').replaceAll(',','_') + '_' + cuentaPn.LastName.replaceAll(' ','_').replaceAll(',','_');
        
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=PIC_'+ cuenta + '.pdf');
    }
}