force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Juridicos.recordType-meta.xml
<RecordType>
    <fullName>Juridicos</fullName>
    <active>true</active>
    <description>Utilizando para cuentas Jurídicas o de compañías</description>
    <label>Jurídicos</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Motos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Motos</fullName>
    <active>true</active>
    <businessProcess>Principal Motos</businessProcess>
    <label>Principal Motos</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <formula>UnitPrice -  Subtotal__c -  Imp_Aduanas__c -  IVA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <formula>IF( X15_I_V_A__c,  UnitPrice * 0.15 ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigovehiculo__c.field-meta.xml
<CustomField>
    <fullName>Codigovehiculo__c</fullName>
    <description>Codigo visible del vehiculo</description>
    <label>Codigo vehiculo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaci_n_1__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_1__c</fullName>
    <label>Especificación 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaci_n_2__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_2__c</fullName>
    <label>Especificación 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaci_n_3__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_3__c</fullName>
    <label>Especificación 3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaci_n_4__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_4__c</fullName>
    <label>Especificación 4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Genesis.recordType-meta.xml
<RecordType>
    <fullName>Genesis</fullName>
    <active>true</active>
    <label>Genesis</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Especificaci_n_1__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_1__c</fullName>
    <label>Especificación 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Especificaci_n_2__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_2__c</fullName>
    <label>Especificación 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Especificaci_n_3__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_3__c</fullName>
    <label>Especificación 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Especificaci_n_4__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_4__c</fullName>
    <label>Especificación 4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <label>IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Precio_de_lista_unitario__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_lista_unitario__c</fullName>
    <label>Precio de lista unitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Total_precio_especial__c.field-meta.xml
<CustomField>
    <fullName>Total_precio_especial__c</fullName>
    <label>Total precio especial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_PDFCotizacion.cls
@isTest
public class Test_PDFCotizacion {

    @TestSetup
    public static void makeData(){
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        Date closeDt = Date.Today();
        Id pricebookId = Test.getStandardPricebookId();
        
        ID juridicaAccountID = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName()
            .get('Juridicos')
            .getRecordTypeId();
        
        ID motosID = Schema.SObjectType.Opportunity
            .getRecordTypeInfosByDeveloperName()
            .get('Principal_Motos')
            .getRecordTypeId();
        
        Id marcasUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Marcas')
            .getRecordTypeId();
        
        List<Catalogo_UDC__c> catList = new List<Catalogo_UDC__c>();
        
        Catalogo_UDC__c kia = new Catalogo_UDC__c();
        kia.Name = 'KIA';
        kia.productcode__c = 'KIA';
        kia.RecordTypeId = marcasUDCID;
        
        Catalogo_UDC__c genesis = new Catalogo_UDC__c();
        genesis.Name = 'GENESIS';
        genesis.productcode__c = 'GENESIS';
        genesis.RecordTypeId = marcasUDCID;
        
        catList.add(kia);
        catList.add(genesis);
        
        insert catList;
        
        List<Account> accList = new List<Account>();
        
        Account a2 = new Account(Name = 'Cuenta Motos',
                                 CurrencyIsoCode = 'USD',
                                 Secuencia_contactos__c = 2,
                                 Email__c = 'correo@test.com',
                                 Cedula__c = '321321',
                                 Phone = '+50558888888');
        
        a2.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
            'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        a2.RecordTypeID = juridicaAccountID;
        a2.CodigoCliente__c = '321321';
        accList.add(a2);
        
        Account a = new Account(Name = 'Cuenta Autos',
                                 CurrencyIsoCode = 'USD',
                                 Secuencia_contactos__c = 2,
                                 Email__c = 'correo@test.com',
                                 Cedula__c = '123456',
                                 Phone = '+50558888888');
        
        a.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
            'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        a.RecordTypeID = juridicaAccountID;
        a.CodigoCliente__c = '123456';
        accList.add(a);
        
        insert accList;
        
        List<Opportunity> oppList = new List<Opportunity>();
        
        Opportunity opp = new opportunity(
            Name = 'testing DIE 4/6/2015',  
            AccountId = a2.Id,
            StageName = 'Contacto Exitoso', 
            CloseDate = closeDt, 
            Pricebook2Id = pricebookId, 
            Sucursal__c = 'Altamira',
            Marca_UDC__c = kia.Id
        );
        
        oppList.add(opp);
        
        Opportunity oppMotos = new opportunity(
            Name = 'testing DIE 4/6/2015',  
            AccountId = a.Id,
            StageName = 'Contacto Exitoso', 
            CloseDate = closeDt, 
            Pricebook2Id = pricebookId,
            RecordTypeId = motosID,
            Sucursal__c = 'Altamira',
            Marca_UDC__c = genesis.Id
        );
        
        oppList.add(oppMotos);
        
        insert oppList;
        
        //Create your product
        Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            Codigovehiculo__c = 'Pro-X',
            Marca_P__c = 'Kia',
            ProductCode__c = 'sku_producto',
            Especificaci_n_1__c = 'Especificacion 1',
            Especificaci_n_2__c = 'Especificacion 2',
            Especificaci_n_3__c = 'Especificacion 3',
            Especificaci_n_4__c = 'Especificacion 4',
            isActive = true,
            CurrencyIsoCode = 'USD'
        );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 1,
            PricebookEntryId = pbEntry.Id,
            TotalPrice = 1 * pbEntry.UnitPrice           
        );
        insert oli;
    }   
    
    @IsTest
    public static void cotizacionAutosTest(){
        List<Opportunity> oppList = 
            [SELECT Id
            FROM Opportunity 
            WHERE Name LIKE '%AUTOS%'
            ];

        List<Product2> prodList = 
            [SELECT Id
            FROM Product2 
            LIMIT 1
            ];

        List<PricebookEntry> pbEntry = 
            [SELECT Id
            FROM PricebookEntry
            WHERE Product2Id =: prodList[0].Id 
            ];

        Quote q = new Quote();
        q.OpportunityId = oppList[0].Id;
        q.Name = 'AUTOS QUOTE';
        q.ExpirationDate = Date.today();
        insert q;

        QuoteLineItem qli = new QuoteLineItem();
        qli.Product2Id = prodList[0].Id;
        qli.Quantity = 1;
        qli.QuoteId = q.Id;
        qli.PricebookEntryId = pbEntry[0].Id;
        qli.UnitPrice = 12339;
        qli.Descuento__c = 0;
        qli.IVA__c = 0;
        qli.Total_precio_especial__c = 200000;
        qli.Precio_de_lista_unitario__c = 10000;
        insert qli;

        Test.startTest();
        PageReference pageRef = Page.PDF_Cotizacion;
        pageRef.getParameters().put('id', '' + q.Id);
        Test.setCurrentPage(pageRef); 

        CtrlPDF_Cotizacion pdf = new CtrlPDF_Cotizacion();
        Test.stopTest();
    }
    
    @IsTest
    public static void cotizacionMotosTest(){
        List<Opportunity> oppList = 
            [SELECT Id
            FROM Opportunity 
            WHERE Name LIKE '%MOTOS%'
            ];

        List<Product2> prodList = 
            [SELECT Id
            FROM Product2 
            LIMIT 1
            ];

        List<PricebookEntry> pbEntry = 
            [SELECT Id
            FROM PricebookEntry
            WHERE Product2Id =: prodList[0].Id 
            ];

        Quote qMotos = new Quote();
        qMotos.OpportunityId = oppList[0].Id;
        qMotos.Name = 'MOTOS QUOTE';
        qMotos.ExpirationDate = Date.today();
        insert qMotos;
                
        QuoteLineItem qliMotos = new QuoteLineItem();
        qliMotos.Product2Id = prodList[0].Id;
        qliMotos.Quantity = 1;
        qliMotos.QuoteId = qMotos.Id;
        qliMotos.PricebookEntryId = pbEntry[0].Id;
        qliMotos.UnitPrice = 2000;
        qliMotos.Descuento__c = 0;
        qliMotos.IVA__c = 0;
        qliMotos.Total_precio_especial__c = 200000;
        qliMotos.Precio_de_lista_unitario__c = 10000;
        insert qliMotos;
        
        Test.startTest();
        PageReference pageRef = Page.PDF_Cotizacion;
        pageRef.getParameters().put('id', '' + qMotos.Id);
        Test.setCurrentPage(pageRef); 
        
        CtrlPDF_Cotizacion pdf = new CtrlPDF_Cotizacion();
        Test.stopTest();
    }
    
    @IsTest
    public static void agregarComaTest(){
        List<Opportunity> oppList = 
            [SELECT Id
            FROM Opportunity 
            WHERE Name LIKE '%MOTOS%'
            ];

        List<Product2> prodList = 
            [SELECT Id
            FROM Product2 
            LIMIT 1
            ];

        List<PricebookEntry> pbEntry = 
            [SELECT Id
            FROM PricebookEntry
            WHERE Product2Id =: prodList[0].Id 
            ];

        Quote qMotos = new Quote();
        qMotos.OpportunityId = oppList[0].Id;
        qMotos.Name = 'MOTOS QUOTE';
        qMotos.ExpirationDate = Date.today();
        insert qMotos;
                
        QuoteLineItem qliMotos = new QuoteLineItem();
        qliMotos.Product2Id = prodList[0].Id;
        qliMotos.Quantity = 1;
        qliMotos.QuoteId = qMotos.Id;
        qliMotos.PricebookEntryId = pbEntry[0].Id;
        qliMotos.UnitPrice = 2000;
        qliMotos.Descuento__c = 0;
        qliMotos.IVA__c = 0;
        qliMotos.Total_precio_especial__c = 200000;
        qliMotos.Precio_de_lista_unitario__c = 10000;
        insert qliMotos;

        Test.startTest();
        PageReference pageRef = Page.PDF_Cotizacion;
        pageRef.getParameters().put('id', '' + qMotos.Id);

        Test.setCurrentPage(pageRef); 
        CtrlPDF_Cotizacion pdf = new CtrlPDF_Cotizacion();
        String valor = pdf.agregarComa('123456.20');
        Test.stopTest();
        
        System.assertEquals('123,456.20', valor);
    }
}