force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Instrumento_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Instrumento_de_pago__c</fullName>
    <label>Instrumento de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Tarjeta de credito</fullName>
            </value>
            <value>
                <fullName>Deposito bancario</fullName>
            </value>
            <value>
                <fullName>Transferencia</fullName>
            </value>
            <value>
                <fullName>Carta banco</fullName>
            </value>
            <value>
                <fullName>Credito/Orden de compra</fullName>
            </value>
            <value>
                <fullName>Intercambio Autolote</fullName>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
            <value>
                <fullName>Financiamiento FIDEM</fullName>
            </value>
            <value>
                <fullName>Nota de debito</fullName>
                <label>Nota de débito</label>
            </value>
            <value>
                <fullName>Nota de credito</fullName>
                <label>Nota de crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_aplicado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_aplicado__c</fullName>
    <label>Saldo total aplicado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>IF(ISPICKVAL(C_digo_moneda_recibida__c , &quot;COR&quot;),
   Saldo__c /  Tasa__c - Suma_de_montos_aplicados__c, 
   Saldo__c -  Suma_de_montos_aplicados__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Recibos</relationshipLabel>
    <relationshipName>Recibos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/recordTypes/Intercambio.recordType-meta.xml
<RecordType>
    <fullName>Intercambio</fullName>
    <active>true</active>
    <description>Recibo para la entrega de dinero al cliente</description>
    <label>Depósito al cliente</label>
</RecordType>

force-app/main/default/objects/AllRecibidos__c/recordTypes/Principal.recordType-meta.xml
<RecordType>
    <fullName>Principal</fullName>
    <active>true</active>
    <description>Recibo que viene de caja/Acreditar al código</description>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Avaluo.recordType-meta.xml
<RecordType>
    <fullName>Avaluo</fullName>
    <active>true</active>
    <businessProcess>Avaluo</businessProcess>
    <label>Avalúo</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Intercambio.recordType-meta.xml
<RecordType>
    <fullName>Intercambio</fullName>
    <active>true</active>
    <businessProcess>Intercambio</businessProcess>
    <label>Intercambio</label>
</RecordType>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/Recibos_de_la_negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Recibo de la negociación</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Nombre de Recibos de la negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos de la negociación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Monto_aplicado_a_la_negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Monto_aplicado_a_la_negociaci_n__c</fullName>
    <label>Monto aplicado a la negociación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Recibos__c.field-meta.xml
<CustomField>
    <fullName>Recibos__c</fullName>
    <label>Recibos</label>
    <referenceTo>AllRecibidos__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>Recibos__r.Saldo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>Recibos__r.Saldo_disponible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Precio_de_compra_aprobado_S_Autolote__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_compra_aprobado_S_Autolote__c</fullName>
    <description>Precio definitivo para oferta de compra de auto, lo llena el supervisor de compra</description>
    <label>Precio de compra aprobado S. Autolote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReciboDeNegociacionTriggerTest.cls
@isTest
public with sharing class ReciboDeNegociacionTriggerTest {
    @TestSetup
    static void crearRecibo() {
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 2,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';
        insert acc;

        AllRecibidos__c recibo = new AllRecibidos__c();
        recibo.Cuenta__c = acc.ID;
        recibo.Saldo__c = 10000;
        recibo.Instrumento_de_pago__c = 'Efectivo';
        insert recibo;

        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        inf.total_negociado__C = 50000; 
        insert inf;
    }

    @IsTest
    public static void updatearMontoErroneo(){
        List<Informe_de_Negociaci_n__c> inf = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            ];

        List<AllRecibidos__c> rec = 
            [SELECT ID, Saldo_aplicado__c, Saldo_disponible__c
            FROM AllRecibidos__c
            ];

        Recibos_de_la_negociaci_n__c recNeg = new Recibos_de_la_negociaci_n__c();
        recNeg.Recibos__c = rec[0].ID;
        recNeg.Informe_de_Negociaci_n__c = inf[0].ID;
        recNeg.Monto_aplicado_a_la_negociaci_n__c = 0;
        insert recNeg;

        recNeg.Monto_aplicado_a_la_negociaci_n__c = 50000;

        Test.startTest();
        Database.SaveResult sr = Database.update(recNeg, false);
        Test.stopTest();

        Decimal montoEx = recNeg.Monto_aplicado_a_la_negociaci_n__c - rec[0].Saldo_disponible__c;
        
        List<AllRecibidos__c> recibo = 
            [SELECT ID, Saldo_aplicado__c, Saldo_disponible__c
            FROM AllRecibidos__c
            ];
    }

    @isTest
    public static void asociarReciboDeVehiculoSinCerrar() {
        ID principalId = Schema.SObjectType.AllRecibidos__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Principal')
                                    .getRecordTypeId();

        Id avaluoOpp = Schema.SObjectType.Opportunity
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Avaluo')
                                    .getRecordTypeId();

        Account acc = [
            SELECT Id 
            FROM Account 
            LIMIT 1
        ];

        Informe_de_Negociaci_n__c infNeg = [
            SELECT Id 
            FROM Informe_de_Negociaci_n__c
            LIMIT 1
        ];

        Opportunity oppAvaluo = new Opportunity();
        oppAvaluo.RecordTypeId = avaluoOpp;
        oppAvaluo.CloseDate = Date.today().addDays(7);
        oppAvaluo.AccountId = acc.Id;
        oppAvaluo.StageName = 'Cliente en espera de avaluo';
        oppAvaluo.Name = 'AVALUO/CUENTA TEST';
        insert oppAvaluo;

        Vehiculo__c veh = new Vehiculo__c();
        veh.Placa__c = '123456';
        veh.Kilometraje__c = '1000';
        veh.Precio_de_compra_aprobado_S_Autolote__c = 1500;
        veh.Chasis__c = 'CHASIS21345678912';
        insert veh;

        Vehiculo_de_la_Oportunidad__c vehOpp = new Vehiculo_de_la_Oportunidad__c();
        vehOpp.Oportunidad__c = oppAvaluo.Id;
        vehOpp.Vehiculo__c = veh.Id;
        insert vehOpp;

        AllRecibidos__c rec = new AllRecibidos__c();
        rec.RecordTypeId = principalId;
        rec.Saldo__c = 1500;
        rec.Cuenta__c = acc.Id;
        rec.Vehiculo__c = veh.Id;
        rec.Instrumento_de_pago__c = 'Intercambio Autolote';
        insert rec;

        Recibos_de_la_negociaci_n__c recNeg = new Recibos_de_la_negociaci_n__c();
        recNeg.Recibos__c = rec.Id;
        recNeg.Informe_de_Negociaci_n__c = infNeg.Id;
        recNeg.Monto_aplicado_a_la_negociaci_n__c = 1500;

        Test.startTest();
        Database.SaveResult sr = Database.insert(recNeg, false);
        Test.stopTest();

        System.assertEquals(false, sr.isSuccess(), 'La insercion de un recibo para un vehiculo sin finalizar no esta fallando cuando deberia');
        System.assertEquals('No puede asociarse el recibo de un vehiculo que aun no está liberado', sr.getErrors()[0].getMessage(), 'La insercion de un recibo para un vehiculo sin finalizar no esta fallando cuando deberia');
    }
}