force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ciudad_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Ciudad)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creado_desde_Sitio_Externo__c.field-meta.xml
<CustomField>
    <fullName>Creado_desde_Sitio_Externo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Creado desde Sitio Externo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Municipio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad_UDC__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Nacionalidad</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Nacionalidad)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pa_s__c.field-meta.xml
<CustomField>
    <fullName>Pa_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pais</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmentaci_n_por_linea__c.field-meta.xml
<CustomField>
    <fullName>Segmentaci_n_por_linea__c</fullName>
    <description>Almacenara el campo padre para que se deriven los cmapos de segmentacion según tableau</description>
    <label>Segmentación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agroforestal</fullName>
            </value>
            <value>
                <fullName>Aseguradora</fullName>
            </value>
            <value>
                <fullName>Autolote</fullName>
            </value>
            <value>
                <fullName>Automotriz</fullName>
            </value>
            <value>
                <fullName>Avicola</fullName>
            </value>
            <value>
                <fullName>Banco</fullName>
            </value>
            <value>
                <fullName>Bebidas y Licores</fullName>
            </value>
            <value>
                <fullName>Café</fullName>
            </value>
            <value>
                <fullName>Camaronera</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Corredor de Seguros</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Distribución de Consumo masivo</fullName>
            </value>
            <value>
                <fullName>Embutidos y carnes frias</fullName>
            </value>
            <value>
                <fullName>Energía</fullName>
            </value>
            <value>
                <fullName>Equipos electricos</fullName>
            </value>
            <value>
                <fullName>Exploración Petrolera</fullName>
            </value>
            <value>
                <fullName>Financiera</fullName>
            </value>
            <value>
                <fullName>Funeraria</fullName>
            </value>
            <value>
                <fullName>Ganaderia</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
            <value>
                <fullName>Hidrocarburos y derivados</fullName>
            </value>
            <value>
                <fullName>Ingenios</fullName>
            </value>
            <value>
                <fullName>Lacteos</fullName>
            </value>
            <value>
                <fullName>LOGISTICA</fullName>
            </value>
            <value>
                <fullName>Maquinaria industrial</fullName>
            </value>
            <value>
                <fullName>Matadero</fullName>
            </value>
            <value>
                <fullName>Metalurgia</fullName>
            </value>
            <value>
                <fullName>Mineria</fullName>
            </value>
            <value>
                <fullName>Muebles y electrodomesticos</fullName>
            </value>
            <value>
                <fullName>Pesca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_email__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sugerencias: Email address, internal address, internet address</inlineHelpText>
    <label>Tipo de email</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tipos de eMail</value>
        </filterItems>
        <infoMessage>Sugerencias: Email address, internal address, internet address</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Tipo de email)</relationshipLabel>
    <relationshipName>Cuentas9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_t_lefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_t_lefono__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sugerencia de opciones, Home, Work, Car o Mobile, FAX, Home - Emergency Contact, Other, Work - Emergency Contact</inlineHelpText>
    <label>Tipo de télefono</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tipo de Telefono</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Tipo de télefono)</relationshipLabel>
    <relationshipName>Cuentas5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Juridicos.recordType-meta.xml
<RecordType>
    <fullName>Juridicos</fullName>
    <active>true</active>
    <description>Utilizando para cuentas Jurídicas o de compañías</description>
    <label>Jurídicos</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Departamento.recordType-meta.xml
<RecordType>
    <fullName>Departamento</fullName>
    <active>true</active>
    <label>Departamento</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Genero.recordType-meta.xml
<RecordType>
    <fullName>Genero</fullName>
    <active>true</active>
    <label>Género</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Municipio.recordType-meta.xml
<RecordType>
    <fullName>Municipio</fullName>
    <active>true</active>
    <label>Municipio</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Nacionalidad.recordType-meta.xml
<RecordType>
    <fullName>Nacionalidad</fullName>
    <active>true</active>
    <label>Nacionalidad</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Pais.recordType-meta.xml
<RecordType>
    <fullName>Pais</fullName>
    <active>true</active>
    <label>Pais</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Tipo_de_Telefono.recordType-meta.xml
<RecordType>
    <fullName>Tipo_de_Telefono</fullName>
    <active>true</active>
    <label>Tipo de Telefono</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Tipos_de_eMail.recordType-meta.xml
<RecordType>
    <fullName>Tipos_de_eMail</fullName>
    <active>true</active>
    <label>Tipos de eMail</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cuenta personal</label>
</RecordType>

force-app/main/default/classes/AccountManagementTest.cls
@isTest
public class AccountManagementTest {
	@TestSetup
    public static void createAccountAndUDC() {
    	Id paisUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Pais')
                                    .getRecordTypeId();
        
        Id generoUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Genero')
                                    .getRecordTypeId();

        Id departamentoUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Departamento')
                                    .getRecordTypeId();

        Id municipioUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Municipio')
                                    .getRecordTypeId();

        Id nacionalidadUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Nacionalidad')
                                    .getRecordTypeId();
        
        Id tipoTelUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Tipo_de_Telefono')
                                    .getRecordTypeId();
        
        Id tipoEmailUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Tipos_de_eMail')
                                    .getRecordTypeId();

        Catalogo_UDC__c paisTest = new Catalogo_UDC__c();
        paisTest.Name = 'Pais';
        paisTest.productcode__c = 'P';
        paisTest.RecordTypeId = paisUDCID;

        Catalogo_UDC__c municipioTest = new Catalogo_UDC__c();
        municipioTest.Name = 'Municipio';
        municipioTest.productcode__c = 'M';
        municipioTest.RecordTypeId = municipioUDCID;

        Catalogo_UDC__c departamentoTest = new Catalogo_UDC__c();
        departamentoTest.Name = 'Departamento';
        departamentoTest.productcode__c = 'D';
        departamentoTest.RecordTypeId = departamentoUDCID;

        Catalogo_UDC__c tipoTelefonoTest = new Catalogo_UDC__c();
        tipoTelefonoTest.Name = 'Telefono';
        tipoTelefonoTest.productcode__c = 'T';
        tipoTelefonoTest.RecordTypeId = tipoTelUDCID;
        
        Catalogo_UDC__c tipoEmailTest = new Catalogo_UDC__c();
        tipoEmailTest.Name = 'Email';
        tipoEmailTest.productcode__c = 'E';
        tipoEmailTest.RecordTypeId = tipoEmailUDCID;
        
        Catalogo_UDC__c generoTest = new Catalogo_UDC__c();
        generoTest.Name = 'Genero';
        generoTest.productcode__c = 'G';
        generoTest.RecordTypeId = generoUDCID;
        
        Catalogo_UDC__c nacionalidadTest = new Catalogo_UDC__c();
        nacionalidadTest.Name = 'Nacionalidad';
        nacionalidadTest.productcode__c = 'N';
        nacionalidadTest.RecordTypeId = nacionalidadUDCID;

        List<Catalogo_UDC__c> catList = new List<Catalogo_UDC__c> {
            paisTest, municipioTest, departamentoTest, tipoTelefonoTest, tipoEmailTest, generoTest, nacionalidadTest
		};

        insert catList;

        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());

        ID juridicaAccountID = Schema.SObjectType.Account
                .getRecordTypeInfosByDeveloperName()
                .get('Juridicos')
                .getRecordTypeId();
        
        ID personAccountID = Schema.SObjectType.Account
                .getRecordTypeInfosByDeveloperName()
                .get('PersonAccount')
                .getRecordTypeId();

        Account accJ = new Account();
		accJ.Name = 'Cuenta Juridica Test';
        accJ.CodigoCliente__c = '123456';
        accJ.Cedula__c = '1001';
        accJ.Creado_desde_Sitio_Externo__c = true;
        insert accJ;
        
        Account accP = new Account();
        accP.FirstName = 'Cuenta Personal';
        accP.LastName = 'Test';
        accP.CodigoCliente__c = '654321';
        accP.Cedula__c = '1000';
        accP.Creado_desde_Sitio_Externo__c = true;
        insert accP;
    }
    
    @isTest
    public static void modificarCuentaPersonal() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        String r = AccountManagement.editRecord(
            						'654321', 'Genero', 'Nueva direccion', 'Municipio', 'Departamento', 
                                    'Departamento','Pais', '88888888', 'Telefono', 'nuevo@email.com', 'Email', 'Nacionalidad', '');
        Test.stopTest();
        
        List<Account> accJ =
            [SELECT ID, Name, Genero_UDC__pr.Name, Direccion__c, Municipio__r.Name, Ciudad_UDC__r.Name, 
                    Departamento__r.Name, Pa_s__r.Name, Tipo_de_t_lefono__r.Name, Phone, 
                    Tipo_de_Indentificaci_n__c, Cedula__c, Email__c, Tipo_de_email__r.Name, Nacionalidad_UDC__r.Name
            FROM Account
            WHERE CodigoCliente__c = '654321'
            ];
        
        System.assertEquals('La modificacion de la cuenta 654321 ha sido un éxito!', r, 'La respuesta no es la que corresponde');
        System.assertEquals('Genero', accJ[0].Genero_UDC__pr.Name, 'El genero seteado no es el que corresponde');
        System.assertEquals('Nueva direccion', accJ[0].Direccion__c, 'La direccion seteada no es la que corresponde');
        System.assertEquals('Municipio', accJ[0].Municipio__r.Name, 'El municipio seteado no es el que corresponde');
        System.assertEquals('Departamento', accJ[0].Ciudad_UDC__r.Name, 'La ciudad seteada no es la que corresponde');
        System.assertEquals('Departamento', accJ[0].Departamento__r.Name, 'El departamento seteado no es el que corresponde');
        System.assertEquals('Pais', accJ[0].Pa_s__r.Name, 'El pais seteado no es el que corresponde');
        System.assertEquals('88888888', accJ[0].Phone, 'El telefono seteado no es el que corresponde');
        System.assertEquals('Telefono', accJ[0].Tipo_de_t_lefono__r.Name, 'El tipo de telefono seteado no es el que corresponde');
        System.assertEquals('nuevo@email.com', accJ[0].Email__c, 'El mail seteado no es el que corresponde');
        System.assertEquals('Email', accJ[0].Tipo_de_email__r.Name, 'El tipo de email seteado no es el que corresponde');
        System.assertEquals('Nacionalidad', accJ[0].Nacionalidad_UDC__r.Name, 'La nacionalidad seteada no es la que corresponde');
    }
    
    @isTest
    public static void modificarCuentaJuridica() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        String r = AccountManagement.editRecord(
            						'123456', 'Genero', 'Nueva direccion', 'Municipio', 'Departamento', 
                                    'Departamento','Pais', '88888888', 'Telefono', 'nuevo@email.com', 'Email', 'Nacionalidad', 'Pesca');
        Test.stopTest();
        
        List<Account> accJ =
            [SELECT ID, Direccion__c, Municipio__r.Name, Ciudad_UDC__r.Name, 
                    Departamento__r.Name, Pa_s__r.Name, Tipo_de_t_lefono__r.Name, Phone, 
                    Segmentaci_n_por_linea__c, Email__c, Tipo_de_email__r.Name
            FROM Account
            WHERE CodigoCliente__c = '123456'
            ];
        
        System.assertEquals('La modificacion de la cuenta 123456 ha sido un éxito!', r, 'La respuesta no es la que corresponde');
        System.assertEquals('Nueva direccion', accJ[0].Direccion__c, 'La direccion seteada no es la que corresponde');
        System.assertEquals('Municipio', accJ[0].Municipio__r.Name, 'El municipio seteado no es el que corresponde');
        System.assertEquals('Departamento', accJ[0].Ciudad_UDC__r.Name, 'La ciudad seteada no es la que corresponde');
        System.assertEquals('Departamento', accJ[0].Departamento__r.Name, 'El departamento seteado no es el que corresponde');
        System.assertEquals('Pais', accJ[0].Pa_s__r.Name, 'El pais seteado no es el que corresponde');
        System.assertEquals('88888888', accJ[0].Phone, 'El telefono seteado no es el que corresponde');
        System.assertEquals('Telefono', accJ[0].Tipo_de_t_lefono__r.Name, 'El tipo de telefono seteado no es el que corresponde');
        System.assertEquals('nuevo@email.com', accJ[0].Email__c, 'El mail seteado no es el que corresponde');
        System.assertEquals('Email', accJ[0].Tipo_de_email__r.Name, 'El tipo de email seteado no es el que corresponde');	    
        System.assertEquals('Pesca', accJ[0].Segmentaci_n_por_linea__c, 'La segmentacion seteada no es la que corresponde');	    
    }
    
    @isTest
    public static void modificarCuentaInexistente() {
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://gcpcrm--dev3.my.salesforce.com/services/apexrest/AccountManagement/';
        request.httpMethod = 'PATCH';
        request.addHeader('Content-Type', 'application/json');
        
        String json = '{"codigoCliente": "0"}';
        
        request.requestBody = Blob.valueOf(json);
        RestContext.request = request;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        String r = AccountManagement.editRecord(
            						'0', '', '', '', '', 
                                    '','', '', '', '', '', '', '');
        Test.stopTest();
        
        System.assertEquals('La cuenta con código de cliente 0 no existe.', r, 'El codigo de error seteado no es el correcto');
    }
    
    @isTest
    public static void modificarCuentaConDatosErroneos() {
    	RestRequest request = new RestRequest();
        request.requestUri =
            'https://gcpcrm--dev3.my.salesforce.com/services/apexrest/AccountManagement/';
        request.httpMethod = 'PATCH';
        request.addHeader('Content-Type', 'application/json');
        
        String json = '{"codigoCliente": "123456", "nombre":"Nuevo nombre", "direccion":"Nueva direccion",'+
            ' "municipio":"M", "ciudad":"Departamento", "departamento":"D", "pais":"P", "tipoDeIdentificacion":"Otros",'+
            ' "identificacion":"99999", "telefono":"99999", "tipoDeTelefono":"T", "email":"nuevo@email.com", "tipoDeEmail":"E"}';
        
        request.requestBody = Blob.valueOf(json);
        RestContext.request = request;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        String r = AccountManagement.editRecord(
            						'123456', '', '', '', '', 
                                    '','', '', '', 'unEmailErroneo', '', '', '');
        Test.stopTest();
        
        List<Account> accJ =
            [SELECT ID, Name, Direccion__c, Municipio__r.Name, Ciudad_UDC__r.Name, 
                    Departamento__r.Name, Pa_s__r.Name, Tipo_de_t_lefono__r.Name, Phone, 
                    Tipo_de_Indentificaci_n__c, Cedula__c, Email__c, Tipo_de_email__r.Name
            FROM Account
            WHERE CodigoCliente__c = '123456'
            ];
        
        System.assertEquals('El email no tiene un formato valido en Salesforce.', r, 'El codigo de error seteado no es el correcto');	        
    }
    
    @isTest
    public static void creacionCuentaJuridica() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        String r = AccountManagement.createNewRecords(
            						'Juridico', '', '', '', 'Nuevo nombre', '', 'Nueva direccion',
                                    'Municipio', 'Departamento', 'Departamento' ,'Pais', 'Otros', '99999', '88888888', 'Pesca', 'Telefono',
                                    'nuevo@email.com', 'Email', '');
        Test.stopTest();
        
        System.debug(r);

        String codigoCliente = r.split(':')[1].trim();
        
        List<Account> accJ =
            [SELECT ID, Name, Genero_UDC__pr.Name, Direccion__c, Municipio__r.Name, Ciudad_UDC__r.Name, 
                    Departamento__r.Name, Pa_s__r.Name, Tipo_de_t_lefono__r.Name, Phone, 
                    Tipo_de_Indentificaci_n__c, Cedula__c, Email__c, Tipo_de_email__r.Name, Nacionalidad_UDC__r.Name,
             		RecordType.DeveloperName
            FROM Account
            WHERE CodigoCliente__c =: codigoCliente
            ];
        
        System.assertEquals(false, accJ.isEmpty(), 'La lista está vacia cuando no deberia estarlo.');
        
        System.assertEquals('Juridicos', accJ[0].RecordType.DeveloperName, 'El tipo de cuenta no se ha seteado correctamente.');
        System.assertEquals('NUEVO NOMBRE', accJ[0].Name, 'El nombre seteado no es el que corresponde');
        System.assertEquals('Nueva direccion', accJ[0].Direccion__c, 'La direccion seteada no es la que corresponde');
        System.assertEquals('Municipio', accJ[0].Municipio__r.Name, 'El municipio seteado no es el que corresponde');
        System.assertEquals('Departamento', accJ[0].Ciudad_UDC__r.Name, 'La ciudad seteada no es la que corresponde');
        System.assertEquals('Departamento', accJ[0].Departamento__r.Name, 'El departamento seteado no es el que corresponde');
        System.assertEquals('Pais', accJ[0].Pa_s__r.Name, 'El pais seteado no es el que corresponde');
        System.assertEquals('Otros', accJ[0].Tipo_de_Indentificaci_n__c, 'El tipo de id seteado no es el que corresponde');
        System.assertEquals('99999', accJ[0].Cedula__c, 'La cedula seteada no es la que corresponde');
        System.assertEquals('88888888', accJ[0].Phone, 'El telefono seteado no es el que corresponde');
        System.assertEquals('Telefono', accJ[0].Tipo_de_t_lefono__r.Name, 'El tipo de telefono seteado no es el que corresponde');
        System.assertEquals('nuevo@email.com', accJ[0].Email__c, 'El mail seteado no es el que corresponde');
        System.assertEquals('Email', accJ[0].Tipo_de_email__r.Name, 'El tipo de email seteado no es el que corresponde');	    
        
    }
    
    @isTest
    public static void creacionCuentaPersonal() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        String r = AccountManagement.createNewRecords(
            						'Natural', 'Otro', 'Nombre', 'Distinto', '', 'Genero', 'Nueva direccion',
                                    'Municipio', 'Departamento', 'Departamento', 'Pais', 'Otros', '99999', '88888888', '', 'Telefono',
                                    'nuevo@email.com', 'Email', 'Nacionalidad');
        Test.stopTest();
        
        String codigoCliente = r.split(':')[1].trim();
        
        List<Account> accJ =
            [SELECT ID, Name, Genero_UDC__pr.Name, Direccion__c, Municipio__r.Name, Ciudad_UDC__r.Name, 
                    Departamento__r.Name, Pa_s__r.Name, Tipo_de_t_lefono__r.Name, Phone, 
                    Tipo_de_Indentificaci_n__c, Cedula__c, Email__c, Tipo_de_email__r.Name, Nacionalidad_UDC__r.Name,
             		RecordType.DeveloperName
            FROM Account
            WHERE CodigoCliente__c =: codigoCliente
            ];
        
        System.assertEquals(false, accJ.isEmpty(), 'La lista está vacia cuando no deberia estarlo.');
        
        System.assertEquals('PersonAccount', accJ[0].RecordType.DeveloperName, 'El tipo de cuenta no se ha seteado correctamente.');
        System.assertEquals('OTRO NOMBRE DISTINTO', accJ[0].Name, 'El nombre seteado no es el que corresponde');
        System.assertEquals('Genero', accJ[0].Genero_UDC__pr.Name, 'El genero seteado no es el que corresponde');
        System.assertEquals('Nueva direccion', accJ[0].Direccion__c, 'La direccion seteada no es la que corresponde');
        System.assertEquals('Municipio', accJ[0].Municipio__r.Name, 'El municipio seteado no es el que corresponde');
        System.assertEquals('Departamento', accJ[0].Ciudad_UDC__r.Name, 'La ciudad seteada no es la que corresponde');
        System.assertEquals('Departamento', accJ[0].Departamento__r.Name, 'El departamento seteado no es el que corresponde');
        System.assertEquals('Pais', accJ[0].Pa_s__r.Name, 'El pais seteado no es el que corresponde');
        System.assertEquals('Otros', accJ[0].Tipo_de_Indentificaci_n__c, 'El tipo de id seteado no es el que corresponde');
        System.assertEquals('99999', accJ[0].Cedula__c, 'La cedula seteada no es la que corresponde');
        System.assertEquals('88888888', accJ[0].Phone, 'El telefono seteado no es el que corresponde');
        System.assertEquals('Telefono', accJ[0].Tipo_de_t_lefono__r.Name, 'El tipo de telefono seteado no es el que corresponde');
        System.assertEquals('nuevo@email.com', accJ[0].Email__c, 'El mail seteado no es el que corresponde');
        System.assertEquals('Email', accJ[0].Tipo_de_email__r.Name, 'El tipo de email seteado no es el que corresponde');
        System.assertEquals('Nacionalidad', accJ[0].Nacionalidad_UDC__r.Name, 'La nacionalidad seteada no es la que corresponde');    
    }
    
    @isTest
    public static void creacionCuentaConPersonalConError() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        
        String r = AccountManagement.createNewRecords(
            						'Natural', '', 'Nombre', '', '', 'Genero', 'Nueva direccion',
                                    'Municipio', 'Departamento', 'Departamento' ,'Pais', 'Otros', '1000', '88888', '', 'Telefono',
                                    'unEmailConFormatoIncorrecto', 'Eemail', 'Nacionalidad');
        Test.stopTest();
        
        System.assertEquals(true, r.contains('Ya existe una cuenta personal con esa identificación.'), 'El error por duplicidad no se ha seteado correctamente');
    }
    
    @isTest
    public static void creacionCuentaConJuridicaConError() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        String r = AccountManagement.createNewRecords(
            						'Juridico', '', '', '', 'Cuenta Juridica Test', '', 'Nueva direccion',
                                    'Municipio', 'Departamento', 'Departamento' ,'Pais', 'Otros', '1001', '88888', 'Pesca', 'Telefono',
                                    'unEmailConFormatoIncorrecto', 'Email', '');
        Test.stopTest();
        
        System.assertEquals(true, r.contains('Esta cuenta jurídica ya existe en Salesforce.'), 'El error por duplicidad no se ha seteado correctamente');
    }
    
    @isTest
    public static void creacionCuentaConJuridicaConNombreIncorrecto() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        String r = AccountManagement.createNewRecords(
            						'Juridico', '', '', '', '', '', 'Nueva direccion',
                                    'M', 'Departamento', 'D' ,'P', 'Otros', '1001', '88888', '', 'T',
                                    'mail@mail.com', 'E', 'N');
        Test.stopTest();
        
        System.assertEquals(false, r.contains('Esa cuenta jurídica ya existe en Salesforce.'), 'El error por duplicidad no se ha seteado correctamente');
        System.assertEquals(true, r.contains('El campo nombre es obligatorio.'), 'El error nombre no se ha seteado correctamente');
    }
    
    @isTest
    public static void creacionCuentaConTipoInvalido() {
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        String r = AccountManagement.createNewRecords(
            						'', '', '', '', 'Cuenta Juridica Test', '', 'Nueva direccion',
                                    'M', 'Departamento', 'D' ,'P', 'Otros', '1001', '88888', '', 'T',
                                    'unEmailConFormatoIncorrecto', 'E', 'N');
        Test.stopTest();
        
        System.assertEquals(true, r.contains('El tipo de cuenta seleccionado no existe.'), 'El error de cuenta invalida no se ha seteado correctamente');
    }
}