force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ciudad_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Ciudad)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Municipio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pa_s__c.field-meta.xml
<CustomField>
    <fullName>Pa_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pais</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais_de_origen__c.field-meta.xml
<CustomField>
    <fullName>Pais_de_origen__c</fullName>
    <label>País de origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afganistán</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Alemania</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua y Barbuda</fullName>
            </value>
            <value>
                <fullName>Arabia Saudita</fullName>
            </value>
            <value>
                <fullName>Argelia</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaiyán</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bangladés</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Baréin</fullName>
            </value>
            <value>
                <fullName>Bélgica</fullName>
            </value>
            <value>
                <fullName>Belice</fullName>
            </value>
            <value>
                <fullName>Benín</fullName>
            </value>
            <value>
                <fullName>Bielorrusia</fullName>
            </value>
            <value>
                <fullName>Birmania</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia y Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botsuana</fullName>
            </value>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Brunéi</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_email__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sugerencias: Email address, internal address, internet address</inlineHelpText>
    <label>Tipo de email</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tipos de eMail</value>
        </filterItems>
        <infoMessage>Sugerencias: Email address, internal address, internet address</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Tipo de email)</relationshipLabel>
    <relationshipName>Cuentas9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_t_lefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_t_lefono__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sugerencia de opciones, Home, Work, Car o Mobile, FAX, Home - Emergency Contact, Other, Work - Emergency Contact</inlineHelpText>
    <label>Tipo de télefono</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tipo de Telefono</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (Tipo de télefono)</relationshipLabel>
    <relationshipName>Cuentas5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Juridicos.recordType-meta.xml
<RecordType>
    <fullName>Juridicos</fullName>
    <active>true</active>
    <description>Utilizando para cuentas Jurídicas o de compañías</description>
    <label>Jurídicos</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Departamento.recordType-meta.xml
<RecordType>
    <fullName>Departamento</fullName>
    <active>true</active>
    <label>Departamento</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Municipio.recordType-meta.xml
<RecordType>
    <fullName>Municipio</fullName>
    <active>true</active>
    <label>Municipio</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Nacionalidad.recordType-meta.xml
<RecordType>
    <fullName>Nacionalidad</fullName>
    <active>true</active>
    <label>Nacionalidad</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Pais.recordType-meta.xml
<RecordType>
    <fullName>Pais</fullName>
    <active>true</active>
    <label>Pais</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Tipo_de_Telefono.recordType-meta.xml
<RecordType>
    <fullName>Tipo_de_Telefono</fullName>
    <active>true</active>
    <label>Tipo de Telefono</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Tipos_de_eMail.recordType-meta.xml
<RecordType>
    <fullName>Tipos_de_eMail</fullName>
    <active>true</active>
    <label>Tipos de eMail</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CODIGOCLIENTE__c.field-meta.xml
<CustomField>
    <fullName>CODIGOCLIENTE__c</fullName>
    <externalId>true</externalId>
    <label>Codigo del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Ciudad_UDC__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Departamento</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Leads (Ciudad)</relationshipLabel>
    <relationshipName>Leads3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_a_cotizar_autolote__c.field-meta.xml
<CustomField>
    <fullName>Marca_a_cotizar_autolote__c</fullName>
    <label>Marca a cotizar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para realizar por medio de trigger el matcheo con el campo picklist, util para hacer la conversion a oportunidad</description>
    <label>Marca UDC</label>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Leads (Marca UDC)</relationshipLabel>
    <relationshipName>Leads5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Modelo_a_cotizar_autolote__c.field-meta.xml
<CustomField>
    <fullName>Modelo_a_cotizar_autolote__c</fullName>
    <label>Modelo a cotizar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pais_de_origen__c.field-meta.xml
<CustomField>
    <fullName>Pais_de_origen__c</fullName>
    <label>Pais de origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nicaragua</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>España</fullName>
            </value>
            <value>
                <fullName>Estados Unidos</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Managua</fullName>
                <isActive>false</isActive>
                <label>Managua</label>
            </value>
            <value>
                <fullName>NICARGUA</fullName>
                <isActive>false</isActive>
                <label>NICARGUA</label>
            </value>
            <value>
                <fullName>Nicaragu</fullName>
                <isActive>false</isActive>
                <label>Nicaragu</label>
            </value>
            <value>
                <fullName>Nicaragüense</fullName>
                <isActive>false</isActive>
                <label>Nicaragüense</label>
            </value>
            <value>
                <fullName>Nixaragua</fullName>
                <isActive>false</isActive>
                <label>Nixaragua</label>
            </value>
            <value>
                <fullName>Panama</fullName>
                <isActive>false</isActive>
                <label>Panama</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Anfitrion.recordType-meta.xml
<RecordType>
    <fullName>Anfitrion</fullName>
    <active>true</active>
    <businessProcess>Proceso de leads para Anfitrión</businessProcess>
    <label>Anfitrión</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Autolote.recordType-meta.xml
<RecordType>
    <fullName>Autolote</fullName>
    <active>true</active>
    <businessProcess>Toyota</businessProcess>
    <label>Autolote</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Ventas.recordType-meta.xml
<RecordType>
    <fullName>Ventas</fullName>
    <active>true</active>
    <businessProcess>Toyota</businessProcess>
    <label>Ventas</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Intercambio.recordType-meta.xml
<RecordType>
    <fullName>Intercambio</fullName>
    <active>true</active>
    <businessProcess>Intercambio</businessProcess>
    <label>Intercambio</label>
</RecordType>

force-app/main/default/classes/LeadTriggerTest.cls
@isTest
public class LeadTriggerTest {
    @TestSetup
    public static void makeUDCs(){
        ID paisUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Pais')
            .getRecordTypeId();
        
        ID modeloUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Modelo')
            .getRecordTypeId();
        
        ID marcasUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Marcas')
            .getRecordTypeId();
        
        ID telefonoUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Tipo_de_Telefono')
            .getRecordTypeId();
        
        ID emailUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Tipos_de_eMail')
            .getRecordTypeId();
        
        ID nacionalidadUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Nacionalidad')
            .getRecordTypeId();
        
        ID municipioUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Municipio')
            .getRecordTypeId();
        
        ID departamentoUDCID = Schema.SObjectType.Catalogo_UDC__c
            .getRecordTypeInfosByDeveloperName()
            .get('Departamento')
            .getRecordTypeId();
        
        Catalogo_UDC__c nicaragua = new Catalogo_UDC__c (
            Name = 'Nicaragua',
            productcode__c = 'NIC',
            description1__c = 'Nicaragua',
            ExternalId__c = 'TEST_NIC',
            RecordTypeId = paisUDCID
        );
        
        Catalogo_UDC__c guatemala = new Catalogo_UDC__c (
            Name = 'Guatemala',
            productcode__c = 'GUA',
            description1__c = 'Guatemala',
            ExternalId__c = 'TEST_GUA',
            RecordTypeId = paisUDCID
        );
        
        Catalogo_UDC__c kia = new Catalogo_UDC__c (
            Name = 'Kia',
            productcode__c = 'KIA',
            description1__c = 'Kia',
            ExternalId__c = 'TEST_KIA',
            RecordTypeId = marcasUDCID
        );
        
        Catalogo_UDC__c suzuki = new Catalogo_UDC__c (
            Name = 'SUZUKI',
            productcode__c = 'SUZ',
            description1__c = 'Suzuki',
            ExternalId__c = 'TEST_SUZ',
            RecordTypeId = marcasUDCID
        );
        
        Catalogo_UDC__c picanto = new Catalogo_UDC__c (
            Name = 'Picanto',
            productcode__c = 'PIC',
            description1__c = 'Picanto',
            ExternalId__c = 'TEST_PIC',
            RecordTypeId = modeloUDCID
        );
        
        Catalogo_UDC__c alto = new Catalogo_UDC__c (
            Name = 'Alto',
            productcode__c = 'ALT',
            description1__c = 'Alto',
            ExternalId__c = 'TEST_ALT',
            RecordTypeId = modeloUDCID
        );
        
        Catalogo_UDC__c telefono = new Catalogo_UDC__c (
            Name = 'Telefono',
            productcode__c = 'T',
            description1__c = 'Telefono',
            RecordTypeId = telefonoUDCID
        );
        
        Catalogo_UDC__c email = new Catalogo_UDC__c (
            Name = 'Email',
            productcode__c = 'E',
            description1__c = 'Email',
            RecordTypeId = emailUDCID
        );
        
        Catalogo_UDC__c nacionalidad = new Catalogo_UDC__c (
            Name = 'Nacionalidad',
            productcode__c = 'N',
            description1__c = 'Nacionalidad',
            RecordTypeId = nacionalidadUDCID
        );
        
        Catalogo_UDC__c capitalFederal = new Catalogo_UDC__c (
            Name = 'Capital Federal',
            productcode__c = 'CP',
            description1__c = 'Capital Federal',
            RecordTypeId = departamentoUDCID
        );
        
        Catalogo_UDC__c buenosAires = new Catalogo_UDC__c (
            Name = 'Buenos Aires',
            productcode__c = 'BSAS',
            description1__c = 'Buenos Aires',
            RecordTypeId = municipioUDCID
        );
        
        List<Catalogo_UDC__c> catList = new List<Catalogo_UDC__c>{
            nicaragua,
                guatemala,
                kia,
                suzuki,
                picanto,
                alto,
                telefono,
                email,
                nacionalidad,
                capitalFederal,
                buenosAires
                };
                    
                    insert catList;
        
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        ID juridicaAccountID = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName()
            .get('Juridicos')
            .getRecordTypeId();
        
        Account acc = new Account(Name = 'Test Empresa',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 0,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '999999abc',
                                  Phone = '+505588888888');
        
        acc.Direccion__c = 'Direccion';
        acc.RecordTypeID = juridicaAccountID;
        acc.CodigoCliente__c = '321321';
        acc.Pa_s__c = nicaragua.ID;
        acc.Municipio__c = buenosAires.ID;
        acc.Ciudad_UDC__c = capitalFederal.ID;
        acc.Departamento__c = capitalFederal.ID;
        acc.Tipo_de_t_lefono__c = telefono.ID; 
        acc.Tipo_de_email__c = email.ID;
        insert acc;
        
        Test.setCreatedDate(acc.Id, Date.today().addDays(-7));  
    }
    
    @IsTest
    public static void insertLeadsAutolote() {
        ID autoloteID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Autolote')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'TestLead';
        ld.RecordTypeId = autoloteID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        
        Test.startTest();
        Database.SaveResult sr = Database.insert(ld, false);
        Test.stopTest();
        
        System.debug(sr);
        
        Lead lead = 
            [SELECT Marca_UDC__r.Name, Modelo_UDC__r.Name, Pais_UDC__r.Name 
             FROM Lead 
             WHERE LastName = 'TestLead'
            ];
        
        System.assertEquals(true, sr.isSuccess(), 'Algo ha salido mal en la insercion');
        System.assertEquals('Kia', lead.Marca_UDC__r.Name, 'La marca no coincide con lo esperado');
        System.assertEquals('Picanto', lead.Modelo_UDC__r.Name, 'El modelo no coincide con lo esperado');
        System.assertEquals('Nicaragua', lead.Pais_UDC__r.Name, 'El pais no coincide con lo esperado');
    }
    
    @IsTest
    public static void insertLeadsVentas() {
        ID ventasID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Ventas')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'TestLead';
        ld.RecordTypeId = ventasID;
        ld.Modelo_a_cotizar__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar__c = 'Kia';
        
        Test.startTest();
        Database.SaveResult sr = Database.insert(ld, false);
          
        Test.stopTest();
        
        Lead lead = 
            [SELECT Marca_UDC__r.Name, Modelo_UDC__r.Name, Pais_UDC__r.Name 
             FROM Lead 
             WHERE LastName = 'TestLead'
            ];
        
        System.assertEquals(true, sr.isSuccess(), 'Algo ha salido mal en la insercion');
        System.assertEquals('Kia', lead.Marca_UDC__r.Name, 'La marca no coincide con lo esperado');
        System.assertEquals('Picanto', lead.Modelo_UDC__r.Name, 'El modelo no coincide con lo esperado');
        System.assertEquals('Nicaragua', lead.Pais_UDC__r.Name, 'El pais no coincide con lo esperado');
    }
    
    @IsTest
    public static void updateLeadsAutolote() {
        ID autoloteID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Autolote')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'TestLead';
        ld.RecordTypeId = autoloteID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        insert ld;
        
        
        ld.Modelo_a_cotizar_autolote__c = 'Alto';
        ld.Pais_de_origen__c = 'Guatemala';
        ld.Marca_a_cotizar_autolote__c = 'Suzuki';
        
        Test.startTest();
        Database.SaveResult sr = Database.update(ld, false);
        Test.stopTest();
        
        
        Lead lead = 
            [SELECT Marca_UDC__r.Name, Modelo_UDC__r.Name, Pais_UDC__r.Name 
             FROM Lead 
             WHERE LastName = 'TestLead'
            ];
        
        System.assertEquals(true, sr.isSuccess(), 'Algo ha salido mal en la insercion');
        System.assertEquals('SUZUKI', lead.Marca_UDC__r.Name, 'La marca no coincide con lo esperado');
        System.assertEquals('Alto', lead.Modelo_UDC__r.Name, 'El modelo no coincide con lo esperado');
        System.assertEquals('Guatemala', lead.Pais_UDC__r.Name, 'El pais no coincide con lo esperado');
    }
    
    @IsTest
    public static void updateLeadsVentas() {
        ID ventasID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Ventas')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'TestLead';
        ld.RecordTypeId = ventasID;
        ld.Modelo_a_cotizar__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar__c = 'Kia';
        insert ld;
        
        ld.Modelo_a_cotizar__c = 'Alto';
        ld.Pais_de_origen__c = 'Guatemala';
        ld.Marca_a_cotizar__c = 'Suzuki';
        
        Test.startTest();
        Database.SaveResult sr = Database.update(ld, false);
        Test.stopTest();
        
        Lead lead = 
            [SELECT Marca_UDC__r.Name, Modelo_UDC__r.Name, Pais_UDC__r.Name 
             FROM Lead 
             WHERE LastName = 'TestLead'
            ];
        
        System.assertEquals(true, sr.isSuccess(), 'Algo ha salido mal en la insercion');
        System.assertEquals('SUZUKI', lead.Marca_UDC__r.Name, 'La marca no coincide con lo esperado');
        System.assertEquals('Alto', lead.Modelo_UDC__r.Name, 'El modelo no coincide con lo esperado');
        System.assertEquals('Guatemala', lead.Pais_UDC__r.Name, 'El pais no coincide con lo esperado');
    }
    
    @IsTest
    public static void eliminarContactoLuegoDeConvertir() {
        List<Catalogo_UDC__c> tipoTelefono =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipo_de_Telefono'
            ];
        
        List<Catalogo_UDC__c> tipoEmail =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipos_de_eMail'
            ];
        
        List<Catalogo_UDC__c> tipoNacionalidad =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Nacionalidad'
            ];
        
        ID autoloteID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Autolote')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'Lead';
        ld.FirstName = 'Test';
        ld.Direccion__c = 'Test direccion';
        ld.Company = 'TestCompany';
        ld.Tipo_de_email_UDC__c = tipoEmail[0].ID;
        ld.Tipo_de_telefono_UDC__c = tipoTelefono[0].ID;
        ld.Tipo_de_documento__c = 'Otros';
        ld.Phone = '12345678';
        ld.Email = 'email@email.com';
        ld.Nacionalidad__c = tipoNacionalidad[0].ID;
        ld.RecordTypeId = autoloteID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        ld.Cedula_Nro__c = '123456';
        ld.Title = 'Cargo de prueba';
        ld.OwnerId = UserInfo.getUserId();
        
        insert ld;
        
        test.StartTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Database.LeadConvert lc = new database.LeadConvert();  
        lc.setLeadId(ld.ID);  
        lc.setDoNotCreateOpportunity(true);  
        lc.setConvertedStatus('Convertido');  
        lc.setOwnerId(ld.OwnerId);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
        test.stopTest();
        
        System.debug(lcr);
        
        System.assertEquals(true, lcr.isSuccess(), 'La conversion está fallando');
        
        List<Account> accList = 
            [SELECT ID, Envio_correcto_a_WS__c, Name
             FROM Account
             WHERE Name = 'TESTCOMPANY'
            ];
        
        List<Contact> contList = 
            [SELECT ID
             FROM Contact
             WHERE Name = 'TEST LEAD' OR Creado_desde_un_Lead__c = true
            ];
        
        System.assertEquals(true, !accList.isEmpty(), 'La lista de cuentas convertidas esta vacia cuando no deberia');
        
        for (Account acc : accList) {
            System.assertEquals(true, acc.Envio_correcto_a_WS__c, 'La cuenta ' + acc.Name + ' se ingresó correctamente');
        }
        
        System.assertEquals(true, contList.isEmpty(), 'La lista de contactos convertidos no esta vacia cuando deberia');
    }
    
    @IsTest
    public static void convertirCorrectamenteCuentasPersonales() {
        List<Catalogo_UDC__c> tipoTelefono =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipo_de_Telefono'
            ];
        
        List<Catalogo_UDC__c> tipoEmail =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipos_de_eMail'
            ];
        
        List<Catalogo_UDC__c> tipoNacionalidad =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Nacionalidad'
            ];
        
        ID autoloteID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Autolote')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'Lead';
        ld.FirstName = 'Test';
        ld.Direccion__c = 'Test direccion';
        ld.Tipo_de_email_UDC__c = tipoEmail[0].ID;
        ld.Tipo_de_telefono_UDC__c = tipoTelefono[0].ID;
        ld.Tipo_de_documento__c = 'Otros';
        ld.Phone = '12345678';
        ld.Email = 'email@email.com';
        ld.Nacionalidad__c = tipoNacionalidad[0].ID;
        ld.RecordTypeId = autoloteID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        ld.Cedula_Nro__c = '123456';
        ld.OwnerId = UserInfo.getUserId();
        
        insert ld;
        
        test.StartTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Database.LeadConvert lc = new database.LeadConvert();  
        lc.setLeadId(ld.ID);  
        lc.setDoNotCreateOpportunity(true);  
        lc.setConvertedStatus('Convertido');  
        lc.setOwnerId(ld.OwnerId);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
        test.stopTest();
        
        System.assertEquals(true, lcr.isSuccess(), 'La conversion está fallando');
        
        List<Lead> ldList = [
            SELECT ConvertedAccountId
            FROM Lead
            WHERE ID =: ld.Id
        ];
        
        List<Account> accList = 
            [SELECT ID, Envio_correcto_a_WS__c, Name, Email__c
             FROM Account
             WHERE ID =: ldList[0].ConvertedAccountId
            ];
        
        System.assertEquals(true, !accList.isEmpty(), 'La lista de cuentas convertidas esta vacia cuando no deberia');
        
        for (Account acc : accList) {
            System.assertEquals('email@email.com', acc.Email__c, 'El email no se setea correctamente en la cuenta ' + acc.Name);
        }
    } 
    
    @IsTest
    public static void convertirOportunidades() {
        List<Catalogo_UDC__c> tipoTelefono =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipo_de_Telefono'
            ];
        
        List<Catalogo_UDC__c> tipoEmail =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Tipos_de_eMail'
            ];
        
        List<Catalogo_UDC__c> tipoNacionalidad =
            [SELECT ID
             FROM Catalogo_UDC__c
             WHERE RecordType.DeveloperName = 'Nacionalidad'
            ];
        
        ID ventasID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Ventas')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'Lead';
        ld.FirstName = 'Test';
        ld.Direccion__c = 'Test direccion';
        ld.Tipo_de_email_UDC__c = tipoEmail[0].ID;
        ld.Tipo_de_telefono_UDC__c = tipoTelefono[0].ID;
        ld.Tipo_de_documento__c = 'Otros';
        ld.Phone = '12345678';
        ld.Email = 'email@email.com';
        ld.Nacionalidad__c = tipoNacionalidad[0].ID;
        ld.RecordTypeId = ventasID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        ld.Cedula_Nro__c = '123456';
        ld.Como_desea_realizar_su_compra__c = 'Contado';
        ld.Desea_realizar_intercambios__c = true;
        ld.OwnerId = UserInfo.getUserId();
        
        insert ld;
        
        test.StartTest();
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Database.LeadConvert lc = new database.LeadConvert();  
        lc.setLeadId(ld.ID);  
        lc.setDoNotCreateOpportunity(false);  
        lc.setConvertedStatus('Convertido');  
        lc.setOwnerId(ld.OwnerId);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
        test.stopTest();
        
        System.debug(lcr.getErrors());
        System.assertEquals(true, lcr.isSuccess(), 'La conversion está fallando');
        
        List<Lead> ldList = 
            [SELECT ConvertedOpportunityId 
             FROM Lead
             WHERE ID =: ld.ID
            ];
        
        List<Opportunity> oppList = 
            [SELECT ID, Forma_de_Pago_Multiple__c, Desea_realizar_intercambio__c
             FROM Opportunity
             WHERE ID =: ldList[0].ConvertedOpportunityId
            ];
        
        System.assertEquals(true, !oppList.isEmpty(), 'La lista de oportunidades convertidas esta vacia cuando no deberia');
        
        System.assertEquals('Contado', oppList[0].Forma_de_Pago_Multiple__c, 'La forma de adquisicion no se ha seteado correctamente');
        System.assertEquals('SI', oppList[0].Desea_realizar_intercambio__c, 'Desea realizar intercambio no se ha seteado correctamente');
    } 
    
    @IsTest
    public static void convertirConError() {
        ID autoloteID = Schema.SObjectType.Lead
            .getRecordTypeInfosByDeveloperName()
            .get('Autolote')
            .getRecordTypeId();
        
        Lead ld = new Lead();
        ld.LastName = 'Lead';
        ld.FirstName = 'Test';
        ld.Company = 'TestCompany';
        ld.RecordTypeId = autoloteID;
        ld.Modelo_a_cotizar_autolote__c = 'Picanto';
        ld.Pais_de_origen__c = 'Nicaragua';
        ld.Marca_a_cotizar_autolote__c = 'Kia';
        ld.OwnerId = UserInfo.getUserId();
        
        insert ld;
        
        test.StartTest();
        Test.setMock(HttpCalloutMock.class, new HTTPErrorMock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Database.LeadConvert lc = new database.LeadConvert();  
        lc.setLeadId(ld.ID);  
        lc.setDoNotCreateOpportunity(false);  
        lc.setConvertedStatus('Convertido');  
        lc.setOwnerId(ld.OwnerId);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
        test.stopTest();
        
        List<Debug_log__c> debugList =
            [SELECT ID
             FROM Debug_log__c
            ];
        
        System.assertEquals(false, lcr.isSuccess(), 'La conversión no está fallando cuando deberia hacerlo');
        System.assertEquals(true, debugList.isEmpty(), 'No se estan creando debugs cuando hay un error');
    } 
    
    /*@IsTest
public static void convertirLeadAUnaCuentaExistente(){
ID anfitrionId = Schema.SObjectType.Lead
.getRecordTypeInfosByDeveloperName()
.get('Anfitrion')
.getRecordTypeId();

Account acc = [
SELECT Id 
FROM Account
];

Lead ld = new Lead();
ld.LastName = 'Lead';
ld.FirstName = 'Test';
ld.RecordTypeId = anfitrionId;
ld.Company = 'Test Empresa';
ld.OwnerId = UserInfo.getUserId();

insert ld;
Test.setCreatedDate(ld.Id, System.now().addDays(-1));


Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

Test.startTest();
Database.LeadConvert lc = new database.LeadConvert();  
lc.setLeadId(ld.Id);  
lc.setAccountId(acc.Id);  
lc.setDoNotCreateOpportunity(true);  
lc.setConvertedStatus('Convertido');  
lc.setOwnerId(ld.OwnerId);
Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
Test.stopTest();

System.debug(lcr.getErrors()[0].getMessage());

System.assertEquals(false, lcr.isSuccess(), 'La conversión no está fallando cuando deberia hacerlo');
System.assertEquals(true, 
lcr.getErrors()[0].getMessage().contains(
'La cuenta que ha seleccionado tiene los siguientes campos requeridos vacios:' + 
' Tipo de identificación. Por favor rellenelos en el lead para convertir.'
), 
'El mensaje de error al convertir para una cuenta existente no es el esperado'
);
}*/
    
    /*@IsTest
public static void convertirLeadAUnaCuentaNueva(){
ID anfitrionId = Schema.SObjectType.Lead
.getRecordTypeInfosByDeveloperName()
.get('Anfitrion')
.getRecordTypeId();

Account acc = [
SELECT Id 
FROM Account
];

Lead ld = new Lead();
ld.LastName = 'Lead';
ld.FirstName = 'Test';
ld.RecordTypeId = anfitrionId;
ld.Cedula_Nro__c = '123456';
ld.Tipo_de_documento__c = 'Otros';
ld.Company = 'Test Empresa';
ld.OwnerId = UserInfo.getUserId();

insert ld;

Test.startTest();
Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

Database.LeadConvert lc = new database.LeadConvert();  
lc.setLeadId(ld.Id);  
lc.setDoNotCreateOpportunity(true);  
lc.setConvertedStatus('Convertido');  
lc.setOwnerId(ld.OwnerId);
Database.LeadConvertResult lcr = Database.convertLead(lc, false);  
Test.stopTest();

System.assertEquals(false, lcr.isSuccess(), 'La conversión no está fallando cuando deberia hacerlo');
System.assertEquals(true, 
lcr.getErrors()[0].getMessage().contains('Para convertir debe completar los campos: Dirección,' + 
' País, Tipo de teléfono, Email, Nacionalidad, Teléfono, Tipo de email'
), 
'El mensaje de error al convertir para una cuenta nueva no es el esperado'
);
}*/
}