force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Instrumento_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Instrumento_de_pago__c</fullName>
    <label>Instrumento de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Tarjeta de credito</fullName>
            </value>
            <value>
                <fullName>Deposito bancario</fullName>
            </value>
            <value>
                <fullName>Transferencia</fullName>
            </value>
            <value>
                <fullName>Carta banco</fullName>
            </value>
            <value>
                <fullName>Credito/Orden de compra</fullName>
            </value>
            <value>
                <fullName>Intercambio Autolote</fullName>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
            <value>
                <fullName>Financiamiento FIDEM</fullName>
            </value>
            <value>
                <fullName>Nota de debito</fullName>
                <label>Nota de débito</label>
            </value>
            <value>
                <fullName>Nota de credito</fullName>
                <label>Nota de crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/actualizarRecibosTest.cls
@isTest
public class actualizarRecibosTest {
    @TestSetup
    public static void crearRecibos() {
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 2,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';

        insert acc;

        AllRecibidos__c rec = new AllRecibidos__c();
        rec.Id_Externo__c = '48_3150_PR_2012-08-08_E03     _00080_!_null_100002_85_SISTEMAS CONTROLES E INGENIERIA SA_1094846';
        rec.Cuenta__c = acc.ID;
        rec.Instrumento_de_pago__c = 'Efectivo';

        insert rec;
    }

    @IsTest
    static void actualizarRecibosTest(){
        Test.startTest();
        actualizarRecibos.actualizarRecibos();
        Test.stopTest();
    }
}