force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Juridicos.recordType-meta.xml
<RecordType>
    <fullName>Juridicos</fullName>
    <active>true</active>
    <description>Utilizando para cuentas Jurídicas o de compañías</description>
    <label>Jurídicos</label>
</RecordType>

force-app/main/default/classes/ActivosDelClienteControllerTest.cls
@isTest
public class ActivosDelClienteControllerTest {
    @TestSetup
    public static void crearCuenta(){
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        ID juridicaAccountID = Schema.SObjectType.Account
                                .getRecordTypeInfosByDeveloperName()
                                .get('Juridicos')
                                .getRecordTypeId();

        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 2,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.RecordTypeID = juridicaAccountID;
        acc.CodigoCliente__c = '321321';
        insert acc;
    }

    @IsTest
    public static void obtenerActivosTest(){
        List<Account> accList = [
            SELECT ID, CodigoCliente__c
            FROM Account
        ];
        
        accList[0].CodigoCliente__c = '123456';

        update accList; 
        
        Test.setMock(WebServiceMock.class, new ActivosDelClienteMock());

        Test.startTest();
        List<ActivosDelClienteController.ActivosCliente> activosList = ActivosDelClienteController.obtenerActivos('' + accList[0].Id);
        Test.stopTest();
        
        System.assertEquals(false, activosList.isEmpty(), 'El listado de activos esta vacio cuando no deberia.');

        for (ActivosDelClienteController.ActivosCliente act : activosList) {
            System.assertEquals('123456', act.chassis, 'El chasis no es el esperado');
            System.assertEquals('TEST', act.descripcionMarca, 'La descripcion DE Marca no es el esperado');
            System.assertEquals('TEST', act.descripcionModeloGenerico, 'La descripcion de Modelo Generico no es el esperado');
            System.assertEquals('123', act.kilometraje, 'El kilometraje no es el esperado');
            System.assertEquals('TEST', act.motor, 'El motor no es el esperado');
            System.assertEquals('123', act.numFactura, 'El numero de Factura no es el esperado');
            System.assertEquals('TEST', act.estado, 'El estado no es el esperado');
            System.assertEquals('true', act.MPP, 'El MPP no es el esperado');
            System.assertEquals('2021', act.anno, 'El año no es el esperado');
            System.assertEquals('123', act.placa, 'La placa no es la esperado');
            System.assertEquals('19-02-2015', act.fechaVenta, 'La fecha de venta no es la esperado');
        }
    }
}