force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IdInformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>IdInformeNegociacion__c</fullName>
    <label>IdInformeNegociacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Producto_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Producto_Referencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto Referencia</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerTest.cls
@isTest
public class OpportunityLineItemTriggerTest {
	@TestSetup
    public static void crearOportunidades(){
		Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 0,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';
        insert acc;

        Product2 p = new Product2();
        p.Name = 'Test';
        p.Marca_P__c = 'Kia';
        p.ProductCode__c = 'TESTPCode';
        insert p;
        
        Id pricebookId = Test.getStandardPricebookId();

        Opportunity opp = new Opportunity();
        opp.Name = 'TEST';
        opp.AccountId = acc.ID;
        opp.StageName = 'Contacto Exitoso';
        opp.CloseDate = date.today();
        opp.C_digo_de_Oportunidad_Numerico__c = 12345566;
        opp.Marca__c = 'Kia';
        opp.Sucursal__c = 'Kia El Retiro'; 
        opp.Pricebook2Id = pricebookId;
        insert opp;
        
        PricebookEntry pbEntry = new PricebookEntry();
        pbEntry.Pricebook2Id = pricebookId;
        pbEntry.Product2Id = p.Id;
        pbEntry.UnitPrice = 100.00;
        pbEntry.IsActive = true;
        insert pbEntry;
    }
    
    @isTest
    public static void generaCotizacionesTest(){
        List<Product2> pList = 
            [SELECT ID
            FROM Product2
            WHERE Name = 'Test'
            ];
        
        List<Opportunity> oppList =
            [SELECT ID, Name
			FROM Opportunity
            ];
        
        List<PricebookEntry> pbList =
            [SELECT ID, UnitPrice
            FROM PricebookEntry
           	WHERE Product2Id =: pList[0].ID
            ];
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppList[0].ID;
        oli.Product2Id = pList[0].ID;
        oli.UnitPrice = 1.0;
        oli.Quantity = 1;
        
        Test.startTest();
        insert oli;
        Test.stopTest();
        
        List<Quote> qList = 
            [SELECT OpportunityId, Name, ExpirationDate, Producto_Referencia__c, ID
             FROM Quote
            ];
        
        List<QuoteLineItem> qliList = 
            [SELECT Product2Id, Quantity, QuoteId, PricebookEntryId, 
             		UnitPrice
            FROM QuoteLineItem
            WHERE QuoteId =: qList[0].ID
            ];
        
        System.assertEquals(oppList[0].ID, qList[0].OpportunityId, 'La oportunidad de la cotizacion no se genera correctamente');
        System.assertEquals(oppList[0].Name, qList[0].Name, 'El nombre de la cotizacion no se genera correctamente');
        System.assertEquals(Date.today().addDays(7), qList[0].ExpirationDate, 'La fecha de expiracion de la cotizacion no se genera correctamente');
        System.assertEquals(pList[0].ID, qList[0].Producto_Referencia__c, 'El producto de la cotizacion no se genera correctamente');
        
        System.assertEquals(pList[0].ID, qliList[0].Product2Id, 'El producto del producto de cotizacion no se genera correctamente');
        System.assertEquals(1, qliList[0].Quantity, 'La cantidad del producto de cotizacion no se genera correctamente');
        System.assertEquals(qList[0].ID, qliList[0].QuoteId, 'La cotizacion del producto de cotizacion no se genera correctamente');
        System.assertEquals(pbList[0].ID, qliList[0].PricebookEntryId, 'El precio de lista del producto de cotizacion no se genera correctamente');
    }
    
    @isTest
    public static void actualizarPrecioUnitarioTest(){
        List<Product2> pList = 
            [SELECT ID
            FROM Product2
            WHERE Name = 'Test'
            ];
        
        List<Opportunity> oppList =
            [SELECT ID, Name
			FROM Opportunity
            ];

        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppList[0].ID;
        oli.Product2Id = pList[0].ID;
        oli.UnitPrice = 1.0;
        oli.Quantity = 1;
        
        insert oli;
        
        oli.UnitPrice = 250.10;
        
        Test.startTest();
		update oli;
        Test.stopTest();
	}
    
    @isTest
    public static void eliminarCotizacionesTest() {
    	List<Product2> pList = 
            [SELECT ID
            FROM Product2
            WHERE Name = 'Test'
            ];
        
        List<Opportunity> oppList =
            [SELECT ID, Name
			FROM Opportunity
            ];
        
        List<PricebookEntry> pbList =
            [SELECT ID, UnitPrice
            FROM PricebookEntry
           	WHERE Product2Id =: pList[0].ID
            ];
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppList[0].ID;
        oli.Product2Id = pList[0].ID;
        oli.UnitPrice = 1.0;
        oli.Quantity = 1;
        insert oli;
        
        List<Quote> qList = 
            [SELECT ID
            FROM Quote
            ];
        
        Test.startTest();
        delete oli;
        Test.stopTest();    
        
        System.assertEquals(1, qList.size(), 'Las cotizaciones no se crearon bien de ppio.');
        System.assertEquals(0, [SELECT ID FROM Quote].size(), 'Las cotizaciones no se eliminaron como debian hacerlo.');
    }

    @isTest
    public static void eliminarOportunidadConInforme() {
        List<Product2> pList = 
            [SELECT ID
            FROM Product2
            WHERE Name = 'Test'
            ];
        
        List<Opportunity> oppList =
            [SELECT ID, Name
			FROM Opportunity
            ];
        
        List<PricebookEntry> pbList =
            [SELECT ID, UnitPrice
            FROM PricebookEntry
           	WHERE Product2Id =: pList[0].ID
            ];
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppList[0].ID;
        oli.Product2Id = pList[0].ID;
        oli.UnitPrice = 1.0;
        oli.Quantity = 1;
        insert oli;

        Informe_de_negociaci_n__c inf = new Informe_de_negociaci_n__c();
        insert inf;

        oli.IdInformeNegociacion__c = inf.ID;
        update oli;

        Test.startTest();
        Database.delete(oli, false);
        Test.stopTest();  
    }

    @isTest
    public static void actualizarChasisTest() {
        List<Product2> pList = 
            [SELECT ID
            FROM Product2
            WHERE Name = 'Test'
            ];
        
        List<Opportunity> oppList =
            [SELECT ID, Name
			FROM Opportunity
            ];
        
        List<PricebookEntry> pbList =
            [SELECT ID, UnitPrice
            FROM PricebookEntry
           	WHERE Product2Id =: pList[0].ID
            ];
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = oppList[0].ID;
        oli.Product2Id = pList[0].ID;
        oli.UnitPrice = 1.0;
        oli.Quantity = 1;
        insert oli;

        oli.Chasis__c = 'ChasisTest';

        Test.startTest();
        Database.SaveResult sr = Database.update(oli, false);
        Test.stopTest();

        System.assertEquals(true, sr.isSuccess());
    }
}