force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/Permitido_para_autolote__c.field-meta.xml
<CustomField>
    <fullName>Permitido_para_autolote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permitido para autolote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/UDC_Padre__c.field-meta.xml
<CustomField>
    <fullName>UDC_Padre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UDC Padre</label>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Catalogos UDC</relationshipLabel>
    <relationshipName>Catalogos_UDC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Submodelo.recordType-meta.xml
<RecordType>
    <fullName>Submodelo</fullName>
    <active>true</active>
    <label>Submodelo</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Oportunidad_original__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad_original__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad original</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Avaluo.recordType-meta.xml
<RecordType>
    <fullName>Avaluo</fullName>
    <active>true</active>
    <businessProcess>Avaluo</businessProcess>
    <label>Avalúo</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Autos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autos</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Orden_de_etapas_por_recordType__mdt/Orden_de_etapas_por_recordType__mdt.object-meta.xml
<CustomObject>
    <label>Orden de etapas por recordType</label>
    <pluralLabel>Ordenes de etapas por recordType</pluralLabel>
</CustomObject>

force-app/main/default/objects/Orden_de_etapas_por_recordType__mdt/fields/Codigo_de_color__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_color__c</fullName>
    <label>Codigo de color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Anio_opcion__c.field-meta.xml
<CustomField>
    <fullName>Anio_opcion__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>1984</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/mostrarOportunidadHijoTest.cls
@isTest
public without sharing class mostrarOportunidadHijoTest {
    @TestSetup
    public static void crearOportunidad(){
        Id principalAutos = Schema.SObjectType.Opportunity
                            .getRecordTypeInfosByDeveloperName()
                            .get('Principal_Autos')
                            .getRecordTypeId();

        Id marcaId = Schema.SObjectType.Catalogo_UDC__c
                            .getRecordTypeInfosByDeveloperName()
                            .get('Marcas')
                            .getRecordTypeId();

        Id modeloId = Schema.SObjectType.Catalogo_UDC__c
                            .getRecordTypeInfosByDeveloperName()
                            .get('Modelo')
                            .getRecordTypeId();

        Id submodeloId = Schema.SObjectType.Catalogo_UDC__c
                            .getRecordTypeInfosByDeveloperName()
                            .get('Submodelo')
                            .getRecordTypeId();

        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        Catalogo_UDC__c marca = new Catalogo_UDC__c();
        marca.Name = 'KIA';
        marca.productcode__c = 'KIA';
        marca.RecordTypeId = marcaId;
        marca.Permitido_para_autolote__c = true;
        insert marca;

        Catalogo_UDC__c modelo = new Catalogo_UDC__c();
        modelo.Name = 'PICANTO';
        modelo.productcode__c = 'PICANTO';
        modelo.RecordTypeId = modeloId;
        modelo.Permitido_para_autolote__c = true;
        modelo.udc_padre__c = marca.Id;
        insert modelo;

        Catalogo_UDC__c submodelo = new Catalogo_UDC__c();
        submodelo.Name = 'PICANTO MECANICO';
        submodelo.productcode__c = 'PICANTO MECANICO';
        submodelo.RecordTypeId = submodeloId;
        submodelo.Permitido_para_autolote__c = true;
        submodelo.udc_padre__c = modelo.Id;
        insert submodelo;

        Account acc = new Account();
        acc.Name = 'Cuenta empresa';
        acc.CurrencyIsoCode = 'USD';
        acc.Email__c = 'correo@test.com';
        acc.Cedula__c = '321321';
        acc.Phone = '88888888';
        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';
        acc.Tipo_de_Indentificaci_n__c = 'Otros';
        insert acc;

        Opportunity opp = new Opportunity();
        opp.StageName = 'Contacto Exitoso';
        opp.CloseDate = Date.today();
        opp.Name = 'Oportunidad Autos';
        opp.RecordTypeId = principalAutos;
        opp.AccountId = acc.Id;
        insert opp;
    }

    @isTest
    public static void obtenerAniosTest(){
        List<String> anios = new List<String>();

        Schema.DescribeFieldResult f = Vehiculo__c.Anio_opcion__c.getDescribe();
		List<Schema.PicklistEntry> pickL = f.getPicklistValues();
        
		for (Schema.PicklistEntry pickV : pickL) {
            anios.add(pickV.getLabel());
		}     

        Test.startTest();
        List<String> respuesta = mostrarOportunidadHijo.obtenerListaAnios();
        Test.stopTest();

        for (String anio : anios) {
            System.assertEquals(true, 
                                respuesta.contains(anio),
                                'El anio ' + anio + ' no esta en el resultado cuando deberia');
        }
    }

    @isTest
    public static void obtenerMapaUdcTest(){
        Test.startTest();
        List<Map<String, List<String>>> listadoMapaUdc = mostrarOportunidadHijo.obtenerUdcs();
        Test.stopTest();

        System.assertEquals(2, 
                            listadoMapaUdc.size(), 
                            'El mapa de udc no trae uno por modelo y otro por submodelo como deberia');

        Map<String, List<String>> mapaModeloPorMarca = listadoMapaUdc[0];
        Map<String, List<String>> mapaSubmodeloPorMarca = listadoMapaUdc[1];

        System.assertEquals(true, 
                            mapaModeloPorMarca.containsKey('KIA'),
                            'La marca KIA no aparece en el mapa cuando deberia');
        System.assertEquals(true, 
                            mapaModeloPorMarca.get('KIA').contains('PICANTO'),
                            'El modelo PICANTO no aparece en el mapa relacionado a KIA cuando deberia');

        System.assertEquals(true, 
                            mapaSubmodeloPorMarca.containsKey('PICANTO'),
                            'La modelo PICANTO no aparece en el mapa cuando deberia');
        System.assertEquals(true, 
                            mapaSubmodeloPorMarca.get('PICANTO').contains('PICANTO MECANICO'),
                            'El modelo PICANTO MECANICO no aparece en el mapa relacionado a PICANTO cuando deberia');
    }

    @isTest
    public static void obtenerMapaEtapasTest(){
        Test.startTest();
        Map<String, String> colorPorEtapa = mostrarOportunidadHijo.obtenerMapaEtapas();
        Test.stopTest();

        List<Orden_de_etapas_por_recordType__mdt> ordenList = [
            SELECT Label, Codigo_de_color__c 
            FROM Orden_de_etapas_por_recordType__mdt
            WHERE RecordType__c = 'Avaluo'
        ];

        for (Orden_de_etapas_por_recordType__mdt orden : ordenList) {
            System.assertEquals(true, 
                                colorPorEtapa.containsKey(orden.Label), 
                                'La etapa ' + orden.Label + ' no esta siendo incluida en el mapa de etapas');
            System.assertEquals(orden.Codigo_de_color__c, 
                                colorPorEtapa.get(orden.Label),
                                'El color de la etapa ' + orden.Label + ' no esta coincide con lo esperado');
        }
    }

    @isTest
    public static void obtenerAvaluoTest() {
        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            LIMIT 1
        ];

        mostrarOportunidadHijo.crearAvaluo(
            opp.Id,
            'PLACA123',
            'KIA',
            'PICANTO',
            'PICANTO MECANICO',
            '2021',
            '12000'
        );

        Test.startTest();
        List<Vehiculo_de_la_Oportunidad__c> vehList = mostrarOportunidadHijo.obtenerHijoAvaluo(opp.Id);
        Test.stopTest();

        Opportunity avaluo = [
            SELECT Id 
            FROM Opportunity
            WHERE RecordType.DeveloperName = 'Avaluo'
                AND Oportunidad_original__c =: opp.Id
        ];

        Vehiculo_de_la_Oportunidad__c vehOpp = [
            SELECT Id 
            FROM Vehiculo_de_la_Oportunidad__c
            WHERE Oportunidad__c =: avaluo.Id 
        ];

        System.assertEquals(false, vehList.isEmpty(), 'No se esta retornando ningun vehiculo cuando deberia');
        System.assertEquals(vehOpp.Id, vehList[0].Id, 'El vehiculo que se esta retornando no es el correcto');
    }

    @isTest
    public static void asociarVehiculoInexistenteTest(){
        Vehiculo__c veh = new Vehiculo__c();
        veh.Placa__c = '123456';
        veh.Kilometraje__c = '200';
        veh.Estado__c = 'Pendiente';
        insert veh;

        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            LIMIT 1
        ];

        Test.startTest();
        String respuesta = mostrarOportunidadHijo.asociarVehiculoExistente(opp.Id, 'placaInexistente');
        Test.stopTest();

        System.assertEquals('No existe vehiculo disponible con la placa indicada', respuesta, 'La respuesta de error no coincide con lo esperado');
    }

    @isTest
    public static void asociarVehiculoNoDisponibleTest(){
        Vehiculo__c veh = new Vehiculo__c();
        veh.Placa__c = '123456';
        veh.Kilometraje__c = '200';
        veh.Estado__c = 'Libre';
        insert veh;

        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            LIMIT 1
        ];

        Test.startTest();
        String respuesta = mostrarOportunidadHijo.asociarVehiculoExistente(opp.Id, '123456');
        Test.stopTest();

        System.assertEquals('No existe vehiculo disponible con la placa indicada', respuesta, 'La respuesta de error no coincide con lo esperado');
    }

    @isTest
    public static void asociarVehiculoExistenteTest(){
        Vehiculo__c veh = new Vehiculo__c();
        veh.Placa__c = '123456';
        veh.Kilometraje__c = '200';
        veh.Estado__c = 'Pendiente';
        insert veh;

        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            LIMIT 1
        ];

        Test.startTest();
        String respuesta = mostrarOportunidadHijo.asociarVehiculoExistente(opp.Id, '123456');
        Test.stopTest();

        List<Opportunity> oppPreAvaluo = [
            SELECT Id 
            FROM Opportunity
            WHERE Oportunidad_original__c =: opp.Id
        ];

        List<Vehiculo_de_la_Oportunidad__c> vehOpp = [
            SELECT Id
            FROM Vehiculo_de_la_Oportunidad__c
            WHERE Vehiculo__c =: veh.Id AND Oportunidad__r.Oportunidad_original__c =: opp.Id
        ];

        System.assertEquals('Ok', respuesta, 'La respuesta no coincide con lo esperado');
        System.assertEquals(false, oppPreAvaluo.isEmpty(), 'No se esta creando correctamente el pre avaluo asociado al vehiculo.');
        System.assertEquals(false, vehOpp.isEmpty(), 'No se esta asociando correctamente el vehiculo a la oportunidad.');
    }

    @isTest
    public static void asociarVehiculoQueTodaviaEstaEnAvaluo(){
        ID avaluoId = Schema.SObjectType.Opportunity
                    .getRecordTypeInfosByDeveloperName()
                    .get('Avaluo')
                    .getRecordTypeId();

        Account acc = [
            SELECT Id
            FROM Account
            LIMIT 1
        ];
        
        Opportunity oppPrincipal = [
            SELECT Id
            FROM Opportunity
            LIMIT 1
        ];

        Opportunity opp = new Opportunity();
        opp.StageName = 'Avaluo Realizado';
        opp.CloseDate = Date.today();
        opp.Name = 'Oportunidad Autos';
        opp.RecordTypeId = avaluoId;
        opp.AccountId = acc.Id;
        insert opp;

        Vehiculo__c veh = new Vehiculo__c();
        veh.Placa__c = '123456';
        veh.Kilometraje__c = '200';
        veh.Estado__c = 'Pendiente';
        insert veh;

        Vehiculo_de_la_Oportunidad__c vehOpp = new Vehiculo_de_la_Oportunidad__c();
        vehOpp.Oportunidad__c = opp.Id;
        vehOpp.Vehiculo__c = veh.Id;    
        insert vehOpp;


        Test.startTest();
        String respuesta = mostrarOportunidadHijo.asociarVehiculoExistente(oppPrincipal.Id, '123456');
        Test.stopTest();

        System.assertEquals(true, respuesta.contains('Este vehiculo es parte de un proceso llevado por'));
        System.assertEquals(true, respuesta.contains(', con lo cual no puede ser asociado.'));
    }
}