force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Juridicos.recordType-meta.xml
<RecordType>
    <fullName>Juridicos</fullName>
    <active>true</active>
    <description>Utilizando para cuentas Jurídicas o de compañías</description>
    <label>Jurídicos</label>
</RecordType>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/C_digo_tipo_de_recibo__c.field-meta.xml
<CustomField>
    <fullName>C_digo_tipo_de_recibo__c</fullName>
    <defaultValue>&quot;PR&quot;</defaultValue>
    <label>Código tipo de recibo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto del recibo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Instrumento_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Instrumento_de_pago__c</fullName>
    <label>Instrumento de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Tarjeta de credito</fullName>
            </value>
            <value>
                <fullName>Deposito bancario</fullName>
            </value>
            <value>
                <fullName>Transferencia</fullName>
            </value>
            <value>
                <fullName>Carta banco</fullName>
            </value>
            <value>
                <fullName>Credito/Orden de compra</fullName>
            </value>
            <value>
                <fullName>Intercambio Autolote</fullName>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
            <value>
                <fullName>Financiamiento FIDEM</fullName>
            </value>
            <value>
                <fullName>Nota de debito</fullName>
                <label>Nota de débito</label>
            </value>
            <value>
                <fullName>Nota de credito</fullName>
                <label>Nota de crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/MontoAplicado__c.field-meta.xml
<CustomField>
    <fullName>MontoAplicado__c</fullName>
    <label>Monto aplicado en el recibo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/NumeroRecibido__c.field-meta.xml
<CustomField>
    <fullName>NumeroRecibido__c</fullName>
    <label>Número de recibo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_aplicado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_aplicado__c</fullName>
    <label>Saldo total aplicado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate_By_Date__c/Exchange_Rate_By_Date__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate By Date</label>
    <nameField>
        <label>Nombre de Exchange Rate By Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExchangeRateByDate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate_By_Date__c/fields/Tasa__c.field-meta.xml
<CustomField>
    <fullName>Tasa__c</fullName>
    <label>Tasa del cambio del día enviado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Color_Externo__c.field-meta.xml
<CustomField>
    <fullName>Color_Externo__c</fullName>
    <label>Color Externo</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Exchange_Rate_By_Date__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate_By_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchange Rate By Date</label>
    <referenceTo>Exchange_Rate_By_Date__c</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Facturar_a_nombre_de__c.field-meta.xml
<CustomField>
    <fullName>Facturar_a_nombre_de__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturar a nombre de</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Precio_de_Lista_sin_IMP__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Lista_sin_IMP__c</fullName>
    <label>Precio de Lista sin IMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Precio_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta__c</fullName>
    <label>Precio de Venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Reservar__c.field-meta.xml
<CustomField>
    <fullName>Reservar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bueno</fullName>
            </value>
            <value>
                <fullName>Malo</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/Recibos_de_la_negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Recibo de la negociación</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Nombre de Recibos de la negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos de la negociación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Monto_aplicado_a_la_negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Monto_aplicado_a_la_negociaci_n__c</fullName>
    <label>Monto aplicado a la negociación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Recibos__c.field-meta.xml
<CustomField>
    <fullName>Recibos__c</fullName>
    <label>Recibos</label>
    <referenceTo>AllRecibidos__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>Recibos__r.Saldo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_RecibosCte.cls
@isTest()
public class Test_RecibosCte {
    @TestSetup
    public static void crearCuenta(){
        ID juridicaAccountID = Schema.SObjectType.Account
                                .getRecordTypeInfosByDeveloperName()
                                .get('Juridicos')
                                .getRecordTypeId();

        Account a = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 2,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '32132188');

        a.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        a.RecordTypeID = juridicaAccountID;
        a.CodigoCliente__c = '321321';
        insert a;
    }
    
    @isTest()
    public static void testRecibos (){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Exchange_Rate_By_Date__c tasa_cambio = new Exchange_Rate_By_Date__c () ;
        tasa_cambio.Name = 'USD';
        tasa_cambio.Tasa__c = 34.5;
        insert tasa_cambio;
        
        Date closeDt = Date.Today();
        Id pricebookId = Test.getStandardPricebookId();
        
        Account a = [
            SELECT Id
            FROM Account
            LIMIT 1
        ];

		opportunity opp = new opportunity(
            Name ='testing DIE 4/6/2015',  
            AccountId = a.Id,
            StageName = 'Contacto Exitoso', 
            CloseDate = closeDt, 
            Pricebook2Id = pricebookId, 
            Sucursal__c='Altamira'
        );
		insert opp;
        
        // ***** Crea Informe de Negociación **** ///
        Informe_de_Negociaci_n__c informe01 = new Informe_de_Negociaci_n__c();
        
        informe01.Facturar_a_nombre_de__c = a.Id; 					//Factura a nombre de Cuenta
        informe01.Exchange_Rate_By_Date__c = tasa_cambio.Id;		//Exhange Rate By Date
        informe01.Cuenta__c = a.Id;									//Cuenta 
        informe01.Oportunidad__c = opp.Id; 							//Oportunidad
        informe01.Reservar__c = false; 								//Reservar
        informe01.Chasis__c = '298388';								//Chasis
        informe01.Motor__c = '298388';								//Motor
        informe01.Color_Externo__c = 'Blanco Perla';
        informe01.Precio_de_Lista_sin_IMP__c = 38000;				//Precio de Lista sin IMP
        informe01.Precio_de_Venta__c = 43000;						//Precio de Venta
        informe01.total_negociado__C = informe01.Precio_de_Venta__c; 
        
        insert informe01;
        
        // **** Crea Recibos **** //
        AllRecibidos__c recibo1 				= new AllRecibidos__c () ;
        recibo1.Concepto__c  					= 'Reservación';
        recibo1.MontoAplicado__c 				= 50000;
        recibo1.Saldo__c						= 50000;
        recibo1.Saldo_aplicado__c				= 0;
        recibo1.Cuenta__c 						= a.Id;
        recibo1.NumeroRecibido__c				= 12345;
        recibo1.C_digo_tipo_de_recibo__c		= 'PR';
        recibo1.Instrumento_de_pago__c = 'Efectivo';
        insert recibo1;
        
        Recibos_de_la_negociaci_n__c rNeg 		= new Recibos_de_la_negociaci_n__c ();
        rNeg.Informe_de_Negociaci_n__c 			= informe01.Id;
        rNeg.Recibos__c 						= recibo1.Id;
        rNeg.Monto_aplicado_a_la_negociaci_n__c = 10;
        insert rNeg;
        
        test.startTest();
        PageReference pageRef = Page.RecibosCte;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', informe01.Id);
        
        Ctrl_Recibos pcc = new Ctrl_Recibos();
        pcc.validaSeleccionados();
        pcc.limpiaBusqueda();
        Test.setCurrentPage(pageRef);
        
        rNeg.Monto_aplicado_a_la_negociaci_n__c = 0;
        update rNeg;
        rNeg.Monto_aplicado_a_la_negociaci_n__c = 100;
        update rNeg;
        
        delete [SELECT ID FROM Recibos_de_la_negociaci_n__c];
        
        delete informe01;
        test.stopTest();
    }
}