force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Catalogo_Sucursales__c/Catalogo_Sucursales__c.object-meta.xml
<CustomObject>
    <label>Catalogo Sucursal</label>
    <nameField>
        <label>Nombre de Catalogo Sucursales</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos de Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_Sucursales__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Lineas_de_negocio.recordType-meta.xml
<RecordType>
    <fullName>Lineas_de_negocio</fullName>
    <active>true</active>
    <label>Lineas de negocio</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Sucursales.recordType-meta.xml
<RecordType>
    <fullName>Sucursales</fullName>
    <active>true</active>
    <label>Sucursales</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Color_Externo__c.field-meta.xml
<CustomField>
    <fullName>Color_Externo__c</fullName>
    <label>Color Externo</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ModeloVehiculo__c.field-meta.xml
<CustomField>
    <fullName>ModeloVehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo Vehiculo UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Modelo Vehiculo UDC)</relationshipLabel>
    <relationshipName>UDCMODELO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bueno</fullName>
            </value>
            <value>
                <fullName>Malo</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IdInformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>IdInformeNegociacion__c</fullName>
    <label>IdInformeNegociacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cuenta personal</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Suzuki.recordType-meta.xml
<RecordType>
    <fullName>Suzuki</fullName>
    <active>true</active>
    <label>Suzuki</label>
</RecordType>

force-app/main/default/classes/OpportunityProduct_Edit_Controller_Test.cls
@isTest
public class OpportunityProduct_Edit_Controller_Test {   
    @TestSetup
    static void createOppProdAndOppItem(){
        ID personAccountID = Schema.SObjectType.Account
                                .getRecordTypeInfosByDeveloperName()
                                .get('PersonAccount')
                                .getRecordTypeId();
        
        ID marcas = Schema.SObjectType.Catalogo_UDC__c
                                .getRecordTypeInfosByDeveloperName()
                                .get('Marcas')
                                .getRecordTypeId();
        
        ID modelos = Schema.SObjectType.Catalogo_UDC__c
                                .getRecordTypeInfosByDeveloperName()
                                .get('Modelo')
                                .getRecordTypeId();

        Id sucursalID = Schema.SObjectType.Catalogo_UDC__c
                                .getRecordTypeInfosByDeveloperName()
                                .get('Sucursales')
                                .getRecordTypeId();

        Id linNegocioID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Lineas_de_negocio')
                                    .getRecordTypeId();
                                            
        List<Catalogo_UDC__c> listCatalogoToInsert = new List<Catalogo_UDC__c>();

        Catalogo_UDC__c lineaNegocioTest = new Catalogo_UDC__c();
        lineaNegocioTest.Name = 'Autos Nuevos';
        lineaNegocioTest.productcode__c = 'LDN';
        lineaNegocioTest.RecordTypeId = linNegocioID;

        listCatalogoToInsert.add(lineaNegocioTest);
        
        Catalogo_UDC__c marca = new Catalogo_UDC__c();
        marca.RecordTypeId = marcas;
        marca.Name = 'SUZUKI';
        
        listCatalogoToInsert.add(marca);
        
        Catalogo_UDC__c modelo = new Catalogo_UDC__c();
        modelo.RecordTypeId = modelos;
        modelo.Name = 'TestModelo';
        
        listCatalogoToInsert.add(modelo);
        
        insert listCatalogoToInsert;
        
        Catalogo_Sucursales__c sucursalElRetiro = new Catalogo_Sucursales__c();
        sucursalElRetiro.Name = 'Kia El Retiro';
        sucursalElRetiro.Codigo_de_la_sucursal__c = '123';

        insert sucursalElRetiro;
       
        Product2 prod = new Product2 (Name = 'Test product',
                                    IsActive = true,
                                    Marca_P__c = 'Kia',
                                    CurrencyIsoCode = 'USD',
                                    ProductCode__c = '316220');
        
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));

        Account acc = new Account(FirstName = 'Cuenta',
                                  LastName = 'Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 2,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.RecordTypeID = personAccountID;
        acc.CodigoCliente__c = '321321';
        insert acc;  
        insert prod;
        
        Pricebook2 pricebook = new Pricebook2(Name = 'Test pricebook for Test Product',
                                              IsActive = true);
        
        insert pricebook;
        
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;

        PricebookEntry entry = new PricebookEntry(
            Product2Id = prod.ID,
            Pricebook2Id = pricebook.ID,
            UnitPrice = 123.45,
            IsActive = true
        );

        insert entry;
        
        Opportunity opp = new Opportunity (Name = 'Test opportunity',
                                           StageName = 'Contacto Exitoso',
                                           CloseDate = Date.today().addDays(1),
                                           Marca_UDC__c = marca.Id,
                                           ModeloVehiculo__c = modelo.Id,
                                           C_digo_de_Oportunidad_Numerico__c = 987654,
                                           AccountID = acc.ID,
                                           Sucursal__c = 'Kia El Retiro',
                                           Pricebook2Id = pricebook.id);

        insert opp;

        List<OpportunityLineItem> oppItemLista = new List<OpportunityLineItem>();
        
        for(Integer i = 0; i < 10; i++) {
            OpportunityLineItem oppItem = new  OpportunityLineItem (OpportunityId = opp.ID,
                                                                    Product2Id = prod.ID,
                                                                    PricebookEntryId = entry.Id,
                                                                    UnitPrice = 123.45,
                                                                    Quantity = 996.13,
                                                                    Motor__c = 'Test Motor ' + i,
                                                                    Chasis__c = 'Test Chasis ' + i);
            oppItemLista.add(oppItem);
        }
        
        oppItemLista[0].Motor__c = null;
        oppItemLista[1].Motor__c = 'Test Motor 2';
        oppItemLista[1].Chasis__c = 'Test Chasis 2';

        insert oppItemLista;
    }

    @isTest 
    public static void getProductosTest() {
        Opportunity opp = [SELECT ID 
                           FROM Opportunity 
                           WHERE Name = 'CUENTA TEST/SUZUKI/TestModelo'
                           ];
       
        List<OpportunityLineItem> oppProd = [SELECT ID, Name
                                            FROM OpportunityLineItem 
                                            WHERE OpportunityId = :opp.ID
                                            ];
        
        Test.startTest();
        List<OpportunityLineItem> oppItemLista = OpportunityProduct_Edit_Controller.getProductos(opp.ID);
        Test.stopTest();

        Set<ID> oppIDs = new Set<ID>();
        
        for(OpportunityLineItem oppIt : oppItemLista) {
            oppIDs.add(oppIt.ID);
        }
        
        System.assertEquals(oppProd.size(),
                            oppItemLista.size(),
                            'El getProductos esta trayendo Opportunity Product incorrectos');

        for(OpportunityLineItem oppIt : oppProd) {
            System.assertEquals(true,
                                oppIDs.contains(oppIt.ID),
                                'El opportunity product ' + oppIt.Name + ' no esta siendo traido por el getProductos');
        }
    }

    @IsTest
    public static void asignarMotorChasisTest(){
       Opportunity opp = [SELECT ID, Pricebook2Id 
                           FROM Opportunity 
                           WHERE Name = 'CUENTA TEST/SUZUKI/TestModelo'
                           LIMIT 1
                           ];

        Product2 prod = [SELECT ID
                         FROM Product2
                         WHERE Name = 'Test product'
                         LIMIT 1
                         ];

        PricebookEntry entry = [SELECT ID
                                FROM PricebookEntry
                                WHERE Pricebook2Id =: opp.Pricebook2Id
                                LIMIT 1
                               ];


        OpportunityLineItem oppItem = new  OpportunityLineItem(OpportunityId = opp.ID,
                         Product2Id = prod.ID,
                         PricebookEntryId = entry.Id,
                         UnitPrice = 123.45,
                         Quantity = 1);

        insert oppItem;

        Test.startTest();
        String estado = OpportunityProduct_Edit_Controller.AsignarMotorChasis(oppItem.Id, 'Motor', 'Chasis1', 'Color');
        Test.stopTest();

        OpportunityLineItem oppIt = [SELECT Motor__c, Chasis__c, Color__c
                                       FROM OpportunityLineItem
                                       WHERE ID = :oppItem.ID
                                       LIMIT 1];

        System.assertEquals('ok',
                             estado,
                             'AsignarMotorChasis esta fallando cuando no deberia hacerlo');

        System.assertEquals('Motor', 
                            oppIt.Motor__c,
                            'El motor se ha asignado incorrectamente');

        System.assertEquals('Chasis1', 
                             oppIt.Chasis__c,
                             'El chasis se ha asignado incorrectamente');

        System.assertEquals('Color',
                             oppIt.Color__c,
                             'El color se ha asignado incorrectamente');
    }

    @IsTest
    static void deasignarTest(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Opportunity opp = [
          	SELECT ID, Pricebook2Id 
           	FROM Opportunity 
           	WHERE Name = 'CUENTA TEST/SUZUKI/TestModelo'
           	];

        Product2 prod = [
            SELECT ID
          	FROM Product2
         	WHERE Name = 'Test product'
         	LIMIT 1
        ];

        PricebookEntry entry = [
            SELECT ID
            FROM PricebookEntry
            WHERE Pricebook2Id =: opp.Pricebook2Id
            LIMIT 1
        ];


        OpportunityLineItem oppItem = new OpportunityLineItem(
            OpportunityId = opp.ID,
         	Product2Id = prod.ID,
         	PricebookEntryId = entry.Id,
         	UnitPrice = 123.45,
         	Quantity = 1,
            Motor__c = 'Motor',
            Chasis__c = 'Chasis'
        );

        insert oppItem;
        
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        insert inf;
                
        oppItem.IdInformeNegociacion__c = inf.Id;
        update oppItem;

        Test.startTest();
        delete inf;
        String estado = OpportunityProduct_Edit_Controller.Desasignar(oppItem.Id, '', 'Deasignacion');
        Test.stopTest();

        OpportunityLineItem oppItemDeasignado = [
            SELECT ID, Motor__c, Chasis__c, IdInformeNegociacion__c, Color__c
            FROM OpportunityLineItem
            WHERE ID =: oppItem.ID
            LIMIT 1
		];
        

        System.assertEquals('ok', 
                            estado,
                            'Deasignar esta fallando cuando no deberia hacerlo');

        System.assertEquals(null,
                            oppItemDeasignado.Motor__c,
                            'El motor no fue correctamente reasignado');
        System.assertEquals(null,
                            oppItemDeasignado.Chasis__c,
                            'El chasis no fue correctamente reasignado');
        System.assertEquals(null,
                            oppItemDeasignado.Color__c,
                            'El color no fue correctamente reasignado');

        System.assertEquals(null,
                            oppItemDeasignado.IdInformeNegociacion__c,
                            'El informe no fue correctamente deasignado');
    }

    @IsTest
    static void crearInformeTest(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        OpportunityLineItem oppItem = [SELECT ID
                                      FROM OpportunityLineItem
                                      WHERE Chasis__c = 'Test Chasis 3'
                                      LIMIT 1
                                      ];

        Test.startTest();
        String estado = OpportunityProduct_Edit_Controller.CrearInformeNegociacion(oppItem.Id);
        Test.stopTest();

        oppItem = [SELECT ID, Product2Id, OpportunityId, Motor__c, 
                          Chasis__c, Color__c, IdInformeNegociacion__c
                  FROM OpportunityLineItem
                  WHERE Chasis__c = 'Test Chasis 3'
                  ];

        Informe_de_Negociaci_n__c infNeg = [SELECT Producto__c, Oportunidad__c, Motor__c, 
                                                   Chasis__c, Color_Externo__c
                                            FROM Informe_de_Negociaci_n__c
                                            WHERE ID = :oppItem.IdInformeNegociacion__c
                                            ];
        
        System.assertEquals('ok', 
                            estado,
                            'CrearInformeNegociacion no esta funcionando pero deberia hacerlo');

        System.assertEquals(infNeg.ID, 
                            oppItem.IdInformeNegociacion__c, 
                            'El informe no esta bien asociado al opportunity item');

        System.assertEquals(oppItem.Product2Id, 
                            infNeg.Producto__c, 
                            'El producto no coincide entre el opportuniny item y el informe');

        System.assertEquals(oppItem.OpportunityId, 
                            infNeg.Oportunidad__c, 
                            'La oportunidad no coincide entre el opportuniny item y el informe');

        System.assertEquals(oppItem.Motor__c, 
                            infNeg.Motor__c, 
                            'El motor no coincide entre el opportuniny item y el informe');

        System.assertEquals(oppItem.Chasis__c, 
                            infNeg.Chasis__c, 
                            'El chasis no coincide entre el opportuniny item y el informe');

        System.assertEquals(oppItem.Color__c, 
                            infNeg.Color_Externo__c, 
                            'El color no coincide entre el opportuniny item y el informe');

    }

    @IsTest
    static void crearInformeErrorInformeTest(){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Opportunity opp = [SELECT ID, Pricebook2Id 
                           FROM Opportunity 
                           WHERE Name = 'CUENTA TEST/SUZUKI/TestModelo'
                           LIMIT 1
                           ];
        
        Product2 prod = [SELECT ID
                         FROM Product2
                         WHERE Name = 'Test product'
                         LIMIT 1
                         ];


        PricebookEntry entry = [SELECT ID
                                FROM PricebookEntry
                                WHERE Pricebook2Id =: opp.Pricebook2Id
                                LIMIT 1
                                ];

        OpportunityLineItem oppItem = new  OpportunityLineItem (OpportunityId = opp.ID,
                         Product2Id = prod.ID,
                         PricebookEntryId = entry.Id,
                         UnitPrice = 123.45,
                         Quantity = 1);

        insert oppItem;
        
        Informe_de_negociaci_n__c inf = new Informe_de_negociaci_n__c();
        insert inf;
        
        oppItem.IdInformeNegociacion__c = inf.Id;
        update oppItem;
        
        Test.startTest();
        String estado = OpportunityProduct_Edit_Controller.CrearInformeNegociacion(oppItem.Id);
        Test.stopTest();
     
        System.assertEquals('InformeYaCreado', estado);
    }

    @IsTest
    static void crearInformeErrorChasisTest(){
        Opportunity opp = [SELECT ID 
                           FROM Opportunity 
                           WHERE Name = 'CUENTA TEST/SUZUKI/TestModelo'
                           ];

        OpportunityLineItem oppItem = [SELECT ID, IdInformeNegociacion__c
                                      FROM OpportunityLineItem
                                      WHERE OpportunityId = :opp.ID
                                       		AND IdInformeNegociacion__c = null
                                            AND Motor__c = null
                                      LIMIT 1];

        Test.startTest();
        String estado = OpportunityProduct_Edit_Controller.CrearInformeNegociacion(oppItem.ID);
        Test.stopTest();
        
        System.assertEquals('MotorChasisNoAsignado', 
                            estado,
                            'El motor no fue asignado pero aun asi CrearInformeNegociacion no falla');
    }
    
    @isTest
    public static void obtenerTipoOportunidadTest() {
		List<Opportunity> oppList = 
            [SELECT ID, RecordType.DeveloperName
            FROM Opportunity
            ];
        
        Test.startTest();
        String estado = OpportunityProduct_Edit_Controller.obtenerRecordTypeOpp('' + oppList[0].ID);
        Test.stopTest();
        
        System.assertEquals(oppList[0].RecordType.DeveloperName, 
                            estado,
                            'El tipo de oportunidad no se obtiene correctamente.');
    }
}