force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/C_digo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Cliente__c</fullName>
    <formula>Oportunidad__r.Account.CodigoCliente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Consecutivo_del_Informe__c.field-meta.xml
<CustomField>
    <fullName>Consecutivo_del_Informe__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Consecutivo del Informe</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Error_sincronizacion_WS__c.field-meta.xml
<CustomField>
    <fullName>Error_sincronizacion_WS__c</fullName>
    <label>Error sincronización WS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Facturar_a_nombre_de__c.field-meta.xml
<CustomField>
    <fullName>Facturar_a_nombre_de__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturar a nombre de</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sincronizacion_WS__c.field-meta.xml
<CustomField>
    <fullName>Sincronizacion_WS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronización WS (Factura)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestWS_InsertaFacturasAutomaticas.cls
@isTest
public class TestWS_InsertaFacturasAutomaticas {
    @TestSetup
    public static void crearCuentaYOpp() {
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        
        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 0,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';
        insert acc;
        
        Id pricebookId = Test.getStandardPricebookId();

        Opportunity opp = new Opportunity();
        opp.Name = 'TEST OPP CTE1';
        opp.AccountId = acc.ID;
        opp.StageName = 'Contacto Exitoso';
        opp.CloseDate = date.today();
        opp.C_digo_de_Oportunidad_Numerico__c = 123456;
        opp.Marca__c = 'Kia';
        opp.Sucursal__c = 'Kia El Retiro'; 
        opp.Pricebook2Id = pricebookId;
        insert opp;
        
        Informe_de_Negociaci_n__c infNeg = new Informe_de_Negociaci_n__c ();
        infNeg.Chasis__c = 'TESTCHASIS';
		infNeg.Cuenta__c = acc.ID;
        infNeg.Oportunidad__c = opp.ID;
        infNeg.Facturar_a_nombre_de__c = acc.ID;
        insert infNeg;
    }
    
    @isTest
    public static void generarXML() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Informe_de_Negociaci_n__c infNeg = 
            [SELECT ID, C_digo_de_Cliente__c, Chasis__c, Oportunidad__r.C_digo_de_Oportunidad_Numerico__c, 
                	   Name, Error_sincronizacion_WS__c, Sincronizacion_WS__c, Consecutivo_del_Informe__c, Facturar_a_nombre_de__r.CodigoCliente__c 
            FROM Informe_de_Negociaci_n__c
            ];
        
        Test.startTest();
        String xml = CallWSInsertaFacturaAutomatica.crearXML(infNeg);
        Test.stopTest();
        
        System.assertEquals(true, xml.contains(infNeg.C_digo_de_Cliente__c), 'El codigo de cliente del inf no se setea correctamente.');
        System.assertEquals(true, xml.contains(infNeg.Chasis__c), 'El chasis del inf no se setea correctamente.');
        System.assertEquals(true, xml.contains('' + infNeg.Oportunidad__r.C_digo_de_Oportunidad_Numerico__c), 
                            'El codigo numerico de la oportunidad del inf no se setea correctamente.');
        System.assertEquals(true, xml.contains(infNeg.Consecutivo_del_Informe__c), 'El consecutivo del inf no se setea correctamente.');
    }
    
    @isTest
    public static void getFacturasAutomaticas(){
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Informe_de_Negociaci_n__c infNeg = 
            [SELECT ID, C_digo_de_Cliente__c, Chasis__c, Oportunidad__r.C_digo_de_Oportunidad_Numerico__c, 
                    Name, Error_sincronizacion_WS__c, Sincronizacion_WS__c, Consecutivo_del_Informe__c,
             		Facturar_a_nombre_de__r.CodigoCliente__c
            FROM Informe_de_Negociaci_n__c
            ];
        
        String xml = CallWSInsertaFacturaAutomatica.crearXML(infNeg);
        ws_Oportunidades.wsOportunidadesPort wsOpp = new ws_Oportunidades.wsOportunidadesPort();
        
        Test.startTest();
        String resp = wsOpp.InsertarFacturacionAutomatica(Label.strKey, Label.strApp, Label.strModulo, xml);
        Test.stopTest();
        
        System.assertEquals('Bien', resp, 'La respuesta recibida del WS es incorrecta');
    }
}