force-app/main/default/objects/Account/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Identificación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CODIGOCLIENTE__c.field-meta.xml
<CustomField>
    <fullName>CODIGOCLIENTE__c</fullName>
    <externalId>true</externalId>
    <label>Codigo del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_Multiple__c</fullName>
    <label>Forma de Adquisición</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Financiamiento Bancario</fullName>
            </value>
            <value>
                <fullName>Ciclo Casa Pellas</fullName>
            </value>
            <value>
                <fullName>Go Leasing</fullName>
            </value>
            <value>
                <fullName>Financiamiento</fullName>
            </value>
            <value>
                <fullName>Tasa 0</fullName>
            </value>
            <value>
                <fullName>Aun no desea realizar su compra</fullName>
                <label>Aún no desea realizar su compra</label>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ModeloVehiculo__c.field-meta.xml
<CustomField>
    <fullName>ModeloVehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo Vehiculo UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Modelo Vehiculo UDC)</relationshipLabel>
    <relationshipName>UDCMODELO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Autos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autos</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Toyota.recordType-meta.xml
<RecordType>
    <fullName>Toyota</fullName>
    <active>true</active>
    <label>Toyota</label>
</RecordType>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/Recibos_de_la_negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Recibo de la negociación</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Nombre de Recibos de la negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos de la negociación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RVA_PDF.cls
@isTest
public class Test_RVA_PDF {
    @TestSetup
    public static void crearInforme() {
        ID modeloUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Modelo')
                                    .getRecordTypeId();

        ID marcasUDCID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Marcas')
                                    .getRecordTypeId();
        
        ID RTIdAcc = Schema.SObjectType.Account
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('PersonAccount')
                                    .getRecordTypeId();

        Catalogo_UDC__c Toyota = new Catalogo_UDC__c (
                                            Name = 'KIA',
                                            productcode__c = 'TOY',
                                            description1__c = 'Toyota',
                                            ExternalId__c = 'TEST_TOY',
                                            RecordTypeId = marcasUDCID
        								);
        
        Catalogo_UDC__c prius = new Catalogo_UDC__c (
                                            Name = 'Prius',
                                            productcode__c = 'PRI',
                                            description1__c = 'Prius',
                                            ExternalId__c = 'TEST_PRI',
                                            RecordTypeId = modeloUDCID
                                        );
        
        insert prius;
        insert Toyota;
        
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());

        Account acc = new Account(Name = 'Cuenta Test',
                                  CurrencyIsoCode = 'USD',
                                  Secuencia_contactos__c = 0,
                                  Email__c = 'correo@test.com',
                                  Cedula__c = '321321',
                                  Phone = '88888888');

        acc.Direccion__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ornare, ' +
                        'magna eget ultricies ultrices, massa lorem pretium sapien, et blandit tellus quam sit';
        acc.CodigoCliente__c = '321321';
        insert acc;

        Account acc2 = new Account ();
        acc2.RecordTypeId = RTIdAcc;											
        acc2.FirstName = 'jkrva12';
        acc2.LastName = 'Contact';
        acc2.Cedula__c = '123abc2';
        acc2.Email__c = 'prueba@industrias.com';
        acc2.Phone = '88888888';
        acc2.Direccion__c = 'calle 1';

        insert acc2;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        product2 p = new Product2();
        p.Name = 'test';
        p.Marca_P__c = 'Kia';
        p.ProductCode__c = 'TESTPCode';
        insert p;
        
        PricebookEntry pbEntry = new PricebookEntry();
        pbEntry.Pricebook2Id = pricebookId;
        pbEntry.Product2Id = p.Id;
        pbEntry.UnitPrice = 100.00;
        pbEntry.IsActive = true;
        insert pbEntry;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TEST OPP CTE1';
        opp.AccountId = acc.ID;
        opp.StageName = 'Contacto Exitoso';
        opp.CloseDate = date.today();
        opp.C_digo_de_Oportunidad_Numerico__c = 12345566;
        opp.Marca__c = 'Kia';
        opp.Marca_UDC__c = Toyota.ID;
        opp.ModeloVehiculo__c = prius.ID;
        opp.Sucursal__c = 'Kia El Retiro'; 
        opp.Pricebook2Id = pricebookId;
        opp.Forma_de_Pago_Multiple__c = 'Contado';
        insert opp;
        
        Informe_de_Negociaci_n__c infNeg = new Informe_de_Negociaci_n__c ();
        infNeg.total_negociado__c = 5800;
        infNeg.Oportunidad__c = opp.ID;
        infNeg.Cuenta__c = acc.ID;
        insert infNeg;
    }
    
    @isTest
    public static void testPDF (){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Exchange_Rate_By_Date__c tasa_cambio2 = new Exchange_Rate_By_Date__c () ;
        tasa_cambio2.Name = 'USD';
        tasa_cambio2.Tasa__c = 34.5;
        insert tasa_cambio2;

        Account accPersonal = [
            SELECT Id 
            FROM Account
            WHERE RecordType.DeveloperName = 'PersonAccount'
        ];
        
        List<Opportunity> opp_casapellas =
            [SELECT ID
            FROM Opportunity 
            ];
        
        Informe_de_Negociaci_n__c informetest2 = new Informe_de_Negociaci_n__c();
        informetest2.Facturar_a_nombre_de__c = accPersonal.Id; 					//Factura a nombre de Cuenta
        informetest2.Exchange_Rate_By_Date__c = tasa_cambio2.Id;			//Exhange Rate By Date
        informetest2.Cuenta__c = accPersonal.Id;									//Cuenta 
        informetest2.Oportunidad__c = opp_casapellas[0].Id; 					//Oportunidad
        informetest2.Reservar__c = true; 									//Reservar
        informetest2.Chasis__c = '298328';									//Chasis
        informetest2.Motor__c = '298383';									//Motor
        informetest2.Color_Externo__c = 'Blanco Perla';
        informetest2.Precio_de_Lista_sin_IMP__c = 380020;					//Precio de Lista sin IMP
        informetest2.Precio_de_Venta__c = 430030;							//Precio de Venta
        informetest2.total_negociado__c = 430030;							//Precio de Venta
        informetest2.fechafactura__c = Date.valueOf('2020-11-24');
        
        insert informetest2;
            
        test.startTest();
        PageReference pageRef = Page.Reporte_Ventas_Automotores;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('fechaInicial','2020-11-20');
        pageRef.getParameters().put('fechaFinal','2020-11-30');
        pageRef.getParameters().put('compania','');
        pageRef.getParameters().put('lineasDeNegocio','');
        pageRef.getParameters().put('montoMaximo','');
        pageRef.getParameters().put('tiposDePago','Todos');
        Ctrl_Reporte_Ventas_Automotores pdf = new Ctrl_Reporte_Ventas_Automotores();
    
        test.stopTest();
       
    }
    
     @isTest
    public static void testPDF2 (){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Exchange_Rate_By_Date__c tasa_cambio = new Exchange_Rate_By_Date__c () ;
        
        tasa_cambio.Name = 'USD';
        tasa_cambio.Tasa__c = 34.5;
        
        insert tasa_cambio;
        
		Account accPersonal = [
            SELECT Id 
            FROM Account
            WHERE RecordType.DeveloperName = 'PersonAccount'
        ];
        
        List<Opportunity> opp_casapellas =
            [SELECT ID
            FROM Opportunity 
            ];
        
        Informe_de_Negociaci_n__c informetest = new Informe_de_Negociaci_n__c();
        
        informetest.Facturar_a_nombre_de__c = accPersonal.Id; 					//Factura a nombre de Cuenta
        informetest.Exchange_Rate_By_Date__c = tasa_cambio.Id;			//Exhange Rate By Date
        informetest.Cuenta__c = accPersonal.Id;									//Cuenta 
        informetest.Oportunidad__c = opp_casapellas[0].Id; 					//Oportunidad
        informetest.Reservar__c = true; 									//Reservar
        informetest.Chasis__c = '298328';									//Chasis
        informetest.Motor__c = '298383';									//Motor
        informetest.Color_Externo__c = 'Blanco Perla';
        informetest.Precio_de_Lista_sin_IMP__c = 380020;					//Precio de Lista sin IMP
        informetest.Precio_de_Venta__c = 430030;							//Precio de Venta
        informetest.total_negociado__c = 430030;							//Precio de Venta
        informetest.fechafactura__c = Date.valueOf('2020-11-24');
        insert informetest;
        
        test.startTest();        
        
        PageReference pageRef = Page.Reporte_Ventas_Automotores;
        Test.setCurrentPage(pageRef);

        pageRef.getParameters().put('fechaInicial','2020-11-20');
        pageRef.getParameters().put('fechaFinal','2020-11-30');
        pageRef.getParameters().put('compania','');
        pageRef.getParameters().put('lineasDeNegocio','');
        pageRef.getParameters().put('montoMaximo','');
        pageRef.getParameters().put('tiposDePago','Todos');
        Ctrl_Reporte_Ventas_Automotores pdf = new Ctrl_Reporte_Ventas_Automotores();
    
        test.stopTest();
       
    }
    
      @isTest
    public static void testPDF3 (){
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        Exchange_Rate_By_Date__c tasa_cambio = new Exchange_Rate_By_Date__c () ;
        tasa_cambio.Name = 'USD';
        tasa_cambio.Tasa__c = 34.5;
        
        insert tasa_cambio;

        Account accPersonal = [
            SELECT Id 
            FROM Account
            WHERE RecordType.DeveloperName = 'PersonAccount'
        ];
        
        Id RTIdUDC= Schema.SObjectType.Catalogo_UDC__c.getRecordTypeInfosByName().get('Companias').getRecordTypeId();

        Catalogo_UDC__c compania = new Catalogo_UDC__c();
        compania.Name='CASA PELLAS S.A';
        compania.ExternalId__c='0001';
        compania.RecordTypeId = RTIdUDC;
        insert compania;

        Id RTIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Principal_Autos').getRecordTypeId();
        
        Opportunity opp_casapellas = new Opportunity();
        opp_casapellas.RecordTypeId = RTIdOpp;
        opp_casapellas.Compa_a__c = compania.Id;
        opp_casapellas.AccountID = accPersonal.Id;
        opp_casapellas.Name = 'Name';
        opp_casapellas.StageName = 'Contacto Exitoso';
        opp_casapellas.CloseDate = Date.today() + 1;
        opp_casapellas.Sucursal__c = 'Altamira';
        insert opp_casapellas;
        
        Informe_de_Negociaci_n__c informetest = new Informe_de_Negociaci_n__c();
        informetest.Facturar_a_nombre_de__c = accPersonal.Id; 					//Factura a nombre de Cuenta
        informetest.Exchange_Rate_By_Date__c = tasa_cambio.Id;			//Exhange Rate By Date
        informetest.Cuenta__c = accPersonal.Id;							//Cuenta 
        informetest.Oportunidad__c = opp_casapellas.ID; 					//Oportunidad
        informetest.Reservar__c = true; 									//Reservar
        informetest.Chasis__c = '298328';									//Chasis
        informetest.Motor__c = '298383';									//Motor
        informetest.Color_Externo__c = 'Blanco Perla';
        informetest.Precio_de_Lista_sin_IMP__c = 380020;					//Precio de Lista sin IMP
        informetest.Precio_de_Venta__c = 430030;
        informetest.total_negociado__c = 430030;
        informetest.fechafactura__c = Date.valueOf('2020-11-24');
        //Precio de Venta
        
        insert informetest;
        
        test.startTest();
        
        PageReference pageRef = Page.Reporte_Ventas_Automotores;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('fechaInicial','2020-11-20');
        pageRef.getParameters().put('fechaFinal','2020-11-30');
        pageRef.getParameters().put('compania', compania.Name);
        pageRef.getParameters().put('lineasDeNegocio', '');
        pageRef.getParameters().put('montoMaximo','');
        pageRef.getParameters().put('tiposDePago','Todos');
        Ctrl_Reporte_Ventas_Automotores pdf = new Ctrl_Reporte_Ventas_Automotores();
    
        test.stopTest();
       
    }
    
    @isTest
	public static void filtradoTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID, fechafactura__c
            FROM Informe_de_Negociaci_n__c
            ];
        
        List<Account> accList =
            [SELECT ID
            FROM Account 
            ];

        List<AllRecibidos__c> recibosContado = new List<AllRecibidos__c>();
        List<Recibos_de_la_negociaci_n__c> recNegList = new List<Recibos_de_la_negociaci_n__c>();

        for (Integer i = 0; i < 4; i++) {
            AllRecibidos__c rec = new AllRecibidos__c();
            rec.Saldo__c = 1450;
            rec.CodigoInstrumentoPago__c = '.';
            rec.Cuenta__c = accList[0].ID;

            recibosContado.add(rec);
        }

        insert recibosContado;

        for (Integer i = 0; i < 4; i++) {
            Recibos_de_la_negociaci_n__c recNeg = new Recibos_de_la_negociaci_n__c();
            recNeg.Recibos__c = recibosContado[i].ID;
            recNeg.Informe_de_Negociaci_n__c = infList[0].ID;
            recNeg.Monto_aplicado_a_la_negociaci_n__c = 1450;

            recNegList.add(recNeg);
        }

        insert recNegList;

        for (Informe_de_Negociaci_n__c inf : infList) {
            inf.fechafactura__c = Date.valueOf('2020-11-24');
        }

        update infList;

        Test.startTest();
        PageReference pageRef = Page.Reporte_Ventas_Automotores;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('fechaInicial','2020-11-20');
        pageRef.getParameters().put('fechaFinal','2020-11-30');
        pageRef.getParameters().put('compania', '');
        pageRef.getParameters().put('lineasDeNegocio', '');
        pageRef.getParameters().put('montoMaximo','');
        pageRef.getParameters().put('tiposDePago','Efectivo');
        Ctrl_Reporte_Ventas_Automotores pdf = new Ctrl_Reporte_Ventas_Automotores();
        Test.stopTest();
    }

}