force-app/main/default/objects/Account/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Nombre de la ciudad</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha de la última actualización</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LineaNegocio__c.field-meta.xml
<CustomField>
    <fullName>LineaNegocio__c</fullName>
    <label>Linea de negocio</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/FacturasMaestro__c.object-meta.xml
<CustomObject>
    <label>Facturas Maestro</label>
    <nameField>
        <displayFormat>FACT-{000000000}</displayFormat>
        <label>Nombre de Facturas Maestro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas Maestro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FacturasMaestro__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad del cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/CodigoSucursal__c.field-meta.xml
<CustomField>
    <fullName>CodigoSucursal__c</fullName>
    <description>Código de la sucursal donde se registró la factura.</description>
    <inlineHelpText>Código de la sucursal donde se registró la factura.</inlineHelpText>
    <label>Código de la sucursal</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Nombre del contacto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/CP__c.field-meta.xml
<CustomField>
    <fullName>CP__c</fullName>
    <label>Código del país</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas Maestro</relationshipLabel>
    <relationshipName>Facturas_Maestro1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Direccion_1__c.field-meta.xml
<CustomField>
    <fullName>Direccion_1__c</fullName>
    <label>Dirección del cliente - Linea 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Direccion_2__c.field-meta.xml
<CustomField>
    <fullName>Direccion_2__c</fullName>
    <label>Direccion del cliente - Linea 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha de la factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/FechaVence__c.field-meta.xml
<CustomField>
    <fullName>FechaVence__c</fullName>
    <label>Fecha de vencimiento de la factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/LineaNegocio__c.field-meta.xml
<CustomField>
    <fullName>LineaNegocio__c</fullName>
    <label>Código de la linea de negocio</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/MontoRecibido__c.field-meta.xml
<CustomField>
    <fullName>MontoRecibido__c</fullName>
    <label>Monto recibido del cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/NombreCliente__c.field-meta.xml
<CustomField>
    <fullName>NombreCliente__c</fullName>
    <label>Nombre del cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/NombreVendedor__c.field-meta.xml
<CustomField>
    <fullName>NombreVendedor__c</fullName>
    <label>Nombre del vendedor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/NumeroFactura__c.field-meta.xml
<CustomField>
    <fullName>NumeroFactura__c</fullName>
    <externalId>true</externalId>
    <label>Número de la factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País del cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/SaldoFactura__c.field-meta.xml
<CustomField>
    <fullName>SaldoFactura__c</fullName>
    <label>Saldo de la factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/StatusFactura__c.field-meta.xml
<CustomField>
    <fullName>StatusFactura__c</fullName>
    <label>Estado de la factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/TipoFactura__c.field-meta.xml
<CustomField>
    <fullName>TipoFactura__c</fullName>
    <label>Tipo de factura</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/TotalFactura__c.field-meta.xml
<CustomField>
    <fullName>TotalFactura__c</fullName>
    <label>Total de la factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/TotalImpuesto__c.field-meta.xml
<CustomField>
    <fullName>TotalImpuesto__c</fullName>
    <label>Impuesto de la factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProcesaWSFacturas.cls
public class ProcesaWSFacturas {
    
    public static void procesaMaestroFactura (String resp){
        System.debug(resp);
        String errors = 'Errores: \n\n';
        List<String> errorsList = new List<String>();
        
        Dom.Document doc = new Dom.Document();  
        //doc.load( new ws_Clientes.wsClientesPort().GetFacturasMaestro(Label.strKey, Label.strApp, Label.strModulo,'2016','2') );  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  
        
        System.debug('rootElement.getChildElements(): ' + rootElement.getChildElements().size());
        List<FacturasMaestro__c> listFacturas = new List<FacturasMaestro__c>();
        
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
        //for ( Integer i=0; i <rootElement.getChildElements().size(); i++ ) {  
            	FacturasMaestro__c facturaMaestro = new FacturasMaestro__c ();             
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){ 
                switch on detailElement.getName() {
                    when 'CP'				{ 
                        facturaMaestro.CP__c 				= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('CP:' + detailElement.getText());
                    }
                    when 'ciudad' 			{ 
                        facturaMaestro.Ciudad__c			= detailElement.getText() != null ? detailElement.getText() : null; 
                        system.debug('ciudad:' + detailElement.getText());
                    }
                    when 'codSucursal' 		{ 
                        facturaMaestro.CodigoSucursal__c 	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('codSucursal:' + detailElement.getText());
                    }
                    when 'codigoCliente'	{ 
                        facturaMaestro.CodigoCliente__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('codigoCliente:' + detailElement.getText());
                    }
                    when 'contacto'		 	{ 
                        facturaMaestro.Contacto__c		= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('contacto:' + detailElement.getText());
                    }
                    when 'direccion1'		{ 
                        facturaMaestro.Direccion_1__c		= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('direccion1:' + detailElement.getText());
                    }
                    when 'direccion2'		{ 
                        facturaMaestro.Direccion_2__c		= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('direccion2:' + detailElement.getText());
                    }
                    when 'fecha'	 		{ 
                        facturaMaestro.Fecha__c	 		= detailElement.getText() .trim() != '' ? Date.valueOf(detailElement.getText().substring(0,10)) : null; 
                    	system.debug('fecha:' + detailElement.getText());
                    } 
                    when 'fechaVence'	 	{ 
                        facturaMaestro.FechaVence__c 		= detailElement.getText() .trim() != '' ? Date.valueOf(detailElement.getText().substring(0,10)) : null; 
                    	system.debug('fechaVence:' + detailElement.getText());
                    } 
                    when 'lineaNegocio'		{ 
                        facturaMaestro.LineaNegocio__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('lineaNegocio:' + detailElement.getText());
                    }
                    when 'montoRecibido'	{ 
                        facturaMaestro.MontoRecibido__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('montoRecibido:' + detailElement.getText());
                    }
                    when 'nombreCliente'	{ 
                        facturaMaestro.NombreCliente__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('nombreCliente:' + detailElement.getText());
                    }
                    when 'nombreVendedor'	{ 
                        facturaMaestro.NombreVendedor__c 	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('nombreVendedor:' + detailElement.getText());
                    }
                    when 'numeroFactura'	{ 
                        facturaMaestro.NumeroFactura__c	= detailElement.getText().trim() != '' ? Integer.valueOf(detailElement.getText()) : 0; 
                    	system.debug('numeroFactura:' + detailElement.getText());
                    }
                    when 'pais'		 		{ 
                        facturaMaestro.Pais__c			= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('pais:' + detailElement.getText());
                    }
                    when 'saldo'			{ 
                        facturaMaestro.SaldoFactura__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('saldo:' + detailElement.getText());
                    }
                    when 'status'	 		{ 
                        facturaMaestro.StatusFactura__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('status:' + detailElement.getText());
                    }
                    when 'tipo'		 		{ 
                        facturaMaestro.TipoFactura__c		= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('tipo:' + detailElement.getText());
                    }
                    when 'totalFactura'		{ 
                        facturaMaestro.TotalFactura__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('totalFactura:' + detailElement.getText());
                    }
                    when 'totalImpuesto'	{ 
                        facturaMaestro.TotalImpuesto__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('totalImpuesto:' + detailElement.getText());
                    }
                    when else 				{  }
                }
            }
        	
            if(facturaMaestro.CodigoCliente__c != ''){
                facturaMaestro.Cuenta__r = new Account(CodigoCliente__c=facturaMaestro.CodigoCliente__c);  
                //facturaMaestro.Cuenta__r = new Account(CodigoCliente__c='110612');  
            	listFacturas.add(facturaMaestro);    
            }
        	
    	}
        
        if(listFacturas.size()>0){
            //NumeroFactura__c
            Schema.SObjectField c = FacturasMaestro__c.Fields.NumeroFactura__c;
			Database.UpsertResult [] srList = Database.upsert(listFacturas, c, false);
            //Database.SaveResult[] srList  = Database.insert(listFacturas, false);
                
                for (Database.UpsertResult sr : srList) {
                    if (sr.isSuccess()){
                        
                    }else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                            System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                            
                            errorsList.add('Ha ocurrido un error en la FacturaMaestro:' + err.getStatusCode() + ': ' + err.getMessage() + '\n' + 'Los campos que interfieren en el error son: ' + err.getFields()+ '\n\n');
                            
                        }
                    }
               } 
            	
        }

	}
}