force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha de la última actualización</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/C_digo_de_caja__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_caja__c</fullName>
    <label>Código de caja</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/C_digo_moneda_recibida__c.field-meta.xml
<CustomField>
    <fullName>C_digo_moneda_recibida__c</fullName>
    <label>Código moneda recibida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>COR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/C_digo_tipo_de_recibo__c.field-meta.xml
<CustomField>
    <fullName>C_digo_tipo_de_recibo__c</fullName>
    <defaultValue>&quot;PR&quot;</defaultValue>
    <label>Código tipo de recibo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Codigocompania__c.field-meta.xml
<CustomField>
    <fullName>Codigocompania__c</fullName>
    <label>Código de compañía</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/CodigoInstrumentoPago__c.field-meta.xml
<CustomField>
    <fullName>CodigoInstrumentoPago__c</fullName>
    <label>Código de instrumento de pago</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/CodigoLinea__c.field-meta.xml
<CustomField>
    <fullName>CodigoLinea__c</fullName>
    <label>Código de Línea</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/CodigoSucursal__c.field-meta.xml
<CustomField>
    <fullName>CodigoSucursal__c</fullName>
    <label>Código de Sucursal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/CodigoUnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>CodigoUnidadNegocio__c</fullName>
    <label>Código de unidad de negocio</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto del recibo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha del registro del recibo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Monto_recibido__c.field-meta.xml
<CustomField>
    <fullName>Monto_recibido__c</fullName>
    <label>Monto recibido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/MontoAplicado__c.field-meta.xml
<CustomField>
    <fullName>MontoAplicado__c</fullName>
    <label>Monto aplicado en el recibo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/NumeroRecibido__c.field-meta.xml
<CustomField>
    <fullName>NumeroRecibido__c</fullName>
    <label>Número de recibo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Refer1__c.field-meta.xml
<CustomField>
    <fullName>Refer1__c</fullName>
    <label>Refer1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Refer2__c.field-meta.xml
<CustomField>
    <fullName>Refer2__c</fullName>
    <label>Refer2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Refer3__c.field-meta.xml
<CustomField>
    <fullName>Refer3__c</fullName>
    <label>Refer3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Refer4__c.field-meta.xml
<CustomField>
    <fullName>Refer4__c</fullName>
    <label>Refer4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_aplicado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_aplicado__c</fullName>
    <label>Saldo total aplicado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/recordTypes/Principal.recordType-meta.xml
<RecordType>
    <fullName>Principal</fullName>
    <active>true</active>
    <description>Recibo que viene de caja/Acreditar al código</description>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Ejecucion_Personalizada_WS__mdt/Ejecucion_Personalizada_WS__mdt.object-meta.xml
<CustomObject>
    <description>Ejecuta de forma personalizada indicando la fecha de la cual solicita datos, actualmente solo disponible para Recibos</description>
    <label>Ejecución Personalizada WS</label>
    <pluralLabel>Ejecuciones Personalizadas WS</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ejecucion_Personalizada_WS__mdt/fields/Fecha_de_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_ejecucion__c</fullName>
    <label>Fecha de ejecucion</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProcesaRecibosDia.cls
public class ProcesaRecibosDia {
	@future(callout = true)
    public static void procesaRecibos (){
    	procesaRecibosNow();    
    }
    
    public static void procesaRecibosNow (){
        WS_InformeNegociaciones.wsInformeNegociacionPort port = new WS_InformeNegociaciones.wsInformeNegociacionPort();
        port.timeout_x = 120000;
        
        String anio;
        String mes;
        String dia;
        
        Ejecucion_Personalizada_WS__mdt [] ejecucion = 
            [SELECT MasterLabel, Activo__c, Fecha_de_ejecucion__c 
             FROM Ejecucion_Personalizada_WS__mdt 
             WHERE MasterLabel = 'RECIBOS' 
             		AND Activo__c = true 
             		AND Fecha_de_ejecucion__c != null 
             LIMIT 1
            ];
        
        if (ejecucion.size() == 1) {
            anio	= '' + ejecucion[0].Fecha_de_ejecucion__c.Year();		
            mes		= '' + ejecucion[0].Fecha_de_ejecucion__c.Month();		
            dia		= '' + ejecucion[0].Fecha_de_ejecucion__c.Day();
        } else {
            anio	= '' + Date.today().Year();
            mes 	= '' + Date.today().Month();
            dia 	= '' + Date.today().Day();
        }    
       
        String resp = port.GetAllRecibosDia(Label.strKey, Label.strApp, Label.strModulo, anio, mes, dia);
        
        Id rtId_Recibo = 
            [SELECT id 
             FROM RecordType 
             WHERE sObjectType='AllRecibidos__c' 
             		AND DeveloperName ='Principal'].Id;
        
        Dom.Document doc = new Dom.Document();  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  
        
        System.debug('cantidad de recibos: ' + rootElement.getChildElements().size());
        List<AllRecibidos__c> listRecibos = new List<AllRecibidos__c>();
        
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
			AllRecibidos__c recibo = new AllRecibidos__c ();
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){
                switch on detailElement.getName() {
                    when 'codigoCaja'				{ 
                        recibo.C_digo_de_caja__c	= detailElement.getText() != null ? detailElement.getText().trim() : null; 
                    }
                    when 'codigoCliente' 			{ 
                        recibo.CodigoCliente__c		= detailElement.getText() != null ? detailElement.getText().trim() : null; 
                    }
                    when 'codigoCompania'				{ 
                        recibo.Codigocompania__c  = detailElement.getText() != null ? detailElement.getText().trim() : null;
                    }
                    when 'codigoInstrumentoPago'				{ 
                        recibo.CodigoInstrumentoPago__c = detailElement.getText() != null ? detailElement.getText().trim() : null;
                    }
                    when 'codigoLinea'				{ 
                        recibo.CodigoLinea__c  = detailElement.getText() != null ? detailElement.getText().trim() : null;
                    }
                    when 'codigoMonedaAplicada'				{ 
                        recibo.CurrencyIsoCode  = detailElement.getText() == 'USD' ? 'USD' : 'NIO'; 
                    }
                    when 'codigoMonedaRecibida'	{ 
                        recibo.C_digo_moneda_recibida__c = detailElement.getText() == 'USD' ? 'USD' : 'COR';
                        System.debug(recibo.C_digo_moneda_recibida__c);                        
                    }
                    when 'codigoSucursal'				{ 
                        recibo.CodigoSucursal__c  = detailElement.getText() != null ? detailElement.getText().trim() : null;
                    }
                    when 'codigoTipoRecibo'				{ 
                        recibo.C_digo_tipo_de_recibo__c  = detailElement.getText() != null ? detailElement.getText().trim() : null; 
                    }
                    when 'codigoUnidadNegocio'				{ 
                        recibo.CodigoUnidadNegocio__c  = detailElement.getText() != null ? detailElement.getText().trim() : null;
                    }
                    when 'concepto' 		{ 
                        recibo.Concepto__c 	= detailElement.getText() != null ? detailElement.getText().trim() : null; 
                    }
                    when 'fecha' 		{ 
                         recibo.Fecha__c 	= detailElement.getText() != null ? Date.valueOf(detailElement.getText().substring(0,10)) : null;
                    }
                    when 'montoMonedaAplicada'	{ 
                        recibo.MontoAplicado__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    }
                    when 'montoRecibido'	{ 
                        recibo.Monto_recibido__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0;
                        recibo.Saldo__c	 = recibo.Monto_recibido__c;
                    }
                    when 'numeroRecibo'		 	{ 
                        recibo.NumeroRecibido__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                        System.debug(recibo.NumeroRecibido__c);
                    }
                    when 'tasa' 		{ 
                        recibo.Tasa__c 	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : null; 
                    }
                    when 'refer1' 		{ 
                        recibo.refer1__c 	= detailElement.getText().trim() != '' ? detailElement.getText().trim() : null; 
                    }
                    when 'refer2' 		{ 
                        recibo.refer2__c 	= detailElement.getText().trim() != '' ? detailElement.getText().trim() : null; 
                    }
                    when 'refer3' 		{ 
                        recibo.refer3__c 	= detailElement.getText().trim() != '' ? detailElement.getText().trim() : null; 
                    }
                    when 'refer4' 		{ 
                        recibo.refer4__c 	= detailElement.getText().trim() != '' ? detailElement.getText().trim() : null; 
                    }
                    when else 				{  }
                    
                }
            }
        	
            if(recibo.CodigoCliente__c != null){
                recibo.cuenta__r 	= new Account(CodigoCliente__c = recibo.CodigoCliente__c);
                recibo.RecordTypeId = rtId_Recibo;
                recibo.Saldo_aplicado__c = 0;
                Date fechha = recibo.Fecha__c;
                String myDtString = fechha.format();
                List<String> values=  myDtString.split('/');

                for (Integer i = 0; i < values.size(); i++) {
                    if (values[i].length() == 1) {
                        values[i] = '0' + values[i]; 
                    }
                }

                String val = values[2] + '-' + values[1] + '-' + values[0];
               
                recibo.Id_Externo__c =  recibo.C_digo_de_caja__c + '_' + 
                    				    recibo.NumeroRecibido__c + '_' + 
                     				    recibo.C_digo_tipo_de_recibo__c + '_' + 
                    				    val + '_' + 
                    				    recibo.Codigocompania__c + '_' + 
                    					recibo.CodigoSucursal__c + '_' +
                                     	recibo.CodigoInstrumentoPago__c + '_' + 
                    					recibo.C_digo_moneda_recibida__c + '_' +
                    					recibo.refer1__c + '_' +
                    					recibo.refer2__c + '_' +
                                        recibo.refer3__c + '_' +
                    					recibo.refer4__c;
                                        
            	listRecibos.add(recibo);
                System.debug(recibo.Id_Externo__c);
            }
    	}
        
        if (!listRecibos.isEmpty()) {   
            Database.UpsertResult[] srList  = Database.upsert(listRecibos,AllRecibidos__c.Id_Externo__c,false);
            for (Database.UpsertResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                        System.debug('Los campos que interfieren en el error son: ' + err.getFields());                        
                    }
                }
           	} 
        }
	}
}