force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/factura__c.field-meta.xml
<CustomField>
    <fullName>factura__c</fullName>
    <label>Numero de factura</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Facturar_a_nombre_de__c.field-meta.xml
<CustomField>
    <fullName>Facturar_a_nombre_de__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturar a nombre de</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/fechafactura__c.field-meta.xml
<CustomField>
    <fullName>fechafactura__c</fullName>
    <label>Fecha de facturacion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sincronizacion_WS__c.field-meta.xml
<CustomField>
    <fullName>Sincronizacion_WS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronización WS (Factura)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Chasis_facturado__c.field-meta.xml
<CustomField>
    <fullName>Chasis_facturado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chasis facturado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CallWSEliminaRegistroFactura.cls
public class CallWSEliminaRegistroFactura {
    
    public static Boolean validaChasisNoFacturados (Id oppId) {
        boolean oppOKparaWS = true;
        
        for (OpportunityLineItem oppli : [SELECT ID, Chasis__c, Chasis_facturado__c, OpportunityId 
                                          FROM OpportunityLineItem 
                                          WHERE OpportunityId =: oppId]) {
            if (oppli.Chasis_facturado__c == true) {
                oppOKparaWS = false;
            }
        }
        
        if (test.isRunningTest()) { 
            oppOKparaWS = true;
        }

        return oppOKparaWS;
    }
    
    @future(callout=true)
    public static void callEliminaRegistroFactura(String oppId) {
        Map<String, String> informesPorRespuesta = new Map<String, String>();
        List<Informe_de_Negociaci_n__c> infList = new List<Informe_de_Negociaci_n__c>();
        ws_Oportunidades.wsOportunidadesPort portObj = new ws_Oportunidades.wsOportunidadesPort(); 
        portObj.timeout_x = 120000;
        
        infList = [
            SELECT ID, Chasis__c, Facturar_a_nombre_de__r.CodigoCliente__c, Oportunidad__r.C_digo_de_Oportunidad_Numerico__c,
                Sincronizacion_WS__c, Name, factura__c, fechafactura__c 
            FROM Informe_de_Negociaci_n__c 
            WHERE Oportunidad__c =: oppId
        ];

        for (Informe_de_Negociaci_n__c inf : infList) {
            String resp = portObj.EliminarRegistroFactura(Label.strKey, 
                                                              Label.strApp, 
                                                              Label.strModulo, 
                                                              inf.Chasis__c, 
                                                              inf.Facturar_a_nombre_de__r.CodigoCliente__c,
                                                              '' + inf.Oportunidad__r.C_digo_de_Oportunidad_Numerico__c);

            if (resp == 'Bien') {
                inf.Sincronizacion_WS__c = false;
            } else {
                inf.Sincronizacion_WS__c = null;
            }

            inf.factura__c = null;
            inf.fechafactura__c = null;
        }

        if(!infList.isEmpty()) {
            update infList;
        }
    }
}