force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/FacturaDetalle__c.object-meta.xml
<CustomObject>
    <label>Factura Detalle</label>
    <nameField>
        <label>Nombre de Factura Detalle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas Detalle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FacturaDetalle__c/fields/Codigo_de_la_sucursal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_la_sucursal__c</fullName>
    <label>Código de la sucursal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/CodigoDeLaUnidadDeNegocio__c.field-meta.xml
<CustomField>
    <fullName>CodigoDeLaUnidadDeNegocio__c</fullName>
    <label>Código de la unidad de negocio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/CodigoItem__c.field-meta.xml
<CustomField>
    <fullName>CodigoItem__c</fullName>
    <label>Código del producto facturado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas Detalle</relationshipLabel>
    <relationshipName>Facturas_Detalle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción del producto facturado</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Facturas_Maestro__c.field-meta.xml
<CustomField>
    <fullName>Facturas_Maestro__c</fullName>
    <label>Factura</label>
    <referenceTo>FacturasMaestro__c</referenceTo>
    <relationshipLabel>Facturas Detalle</relationshipLabel>
    <relationshipName>Facturas_Detalle</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/NumeroFactura__c.field-meta.xml
<CustomField>
    <fullName>NumeroFactura__c</fullName>
    <label>Número de la factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/TotalLinea__c.field-meta.xml
<CustomField>
    <fullName>TotalLinea__c</fullName>
    <label>Total de la linea facturada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/FacturasMaestro__c.object-meta.xml
<CustomObject>
    <label>Facturas Maestro</label>
    <nameField>
        <displayFormat>FACT-{000000000}</displayFormat>
        <label>Nombre de Facturas Maestro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas Maestro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FacturasMaestro__c/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas Maestro</relationshipLabel>
    <relationshipName>Facturas_Maestro1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Id_Externo_Factura__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo_Factura__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo Factura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/NumeroFactura__c.field-meta.xml
<CustomField>
    <fullName>NumeroFactura__c</fullName>
    <externalId>true</externalId>
    <label>Número de la factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcesaWSGetFacturasDetalleDiaList.cls
public class ProcesaWSGetFacturasDetalleDiaList {
    
    public static void getFacturasDetalleDiaList (String linea){
        
        System.debug('ProcesaWSGetFacturasDetalleDiaList.getFacturasDetalleDiaList()');
        
        String anio = ''+Date.today().Year();
        String mes = ''+Date.today().Month();
        String dia = ''+(Date.today().Day());
        
        System.debug('anio: ' + anio);
        System.debug('mes: ' + mes);
        System.debug('dia: ' + dia);
        System.debug('linea: ' + linea);
        
        List<String> errorsList = new List<String>();
        List<ObjRespGetFacturasDetalleDiaList> detalleFactList = new List<ObjRespGetFacturasDetalleDiaList>();
        List<FacturaDetalle__c> detallesFactToUpsert = new List<FacturaDetalle__c>();
        
        HttpResponse response;
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        //QA
        //http://ap1.casapellas.com.ni:9089/GCPSFWSREST/gcpwsrest/FacturasRest/getFacturasDetalleDiaList
        request.setEndpoint(Label.URL_WS_GetFacturasDetalleDiaList);   
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('key', Label.strKey);
        request.setHeader('app', Label.strApp);
        request.setHeader('mod', Label.strModulo);
        request.setHeader('anio', anio );
        request.setHeader('mes', mes);
        request.setHeader('dia', dia);
        request.setHeader('linea', linea);
        request.setTimeout(120000);
        
        
        try{
        	response = http.send(request);
            System.debug('RESPONSE: ' + response);
            
            if (response.getStatusCode() != 201) {
                System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
            } else {
               	System.debug('RESPUESTA: ' + response.getBody());
                detalleFactList = ObjRespGetFacturasDetalleDiaList.parse(response.getBody());
                System.debug('REGISTROS DE LA RESPUESTA getFacturasMaestroDia: ' + detalleFactList.size());
                if(detalleFactList.size()>0){
                	for(ObjRespGetFacturasDetalleDiaList f: detalleFactList){
                        FacturaDetalle__c fact				= new FacturaDetalle__c();
                        fact.Cuenta__r						= new Account(CodigoCliente__c = ''+f.codigocliente); 	//Cuenta__c
                        fact.Codigo_de_la_sucursal__c		= f.codigoSucursal;										//Chasis__c
                        fact.CodigoDeLaUnidadDeNegocio__c	= f.codigoUnidadNegocio;								//NumFactura__c
                        fact.NumeroFactura__c				= f.numeroFactura;										//Descripci_n_Linea_de_neogco__c
                        fact.Cantidad__c					= f.cantidad;											//Motor__c
                        fact.Precio__c						= f.precio;												//Descripcion__c
                        fact.TotalLinea__c					= f.totalLinea;		 									//SE LLAMA DESCRIPCION PERO TIENE ETIQUETA CODIGO DEL VEHICULO DescCodigoVehiculo__c
                        fact.CodigoItem__c					= f.codigoItem;											//Descripcion_codigo_del_vehiculo
                        fact.Descripcion__c					= f.descripcion;										//Codigo_del_modelo_generico__c
                        fact.Facturas_Maestro__r			= new FacturasMaestro__c(Id_Externo_Factura__c = f.numeroFactura+'_'+f.codigocliente+'_'+f.codigoSucursal+'_'+f.codigoUnidadNegocio);
                        
                        System.debug('================DETALLE FACTURA===============');
                        System.debug('Código de Cliente: '	 		+ f.codigocliente);
                        System.debug('Código de Sucursal: ' 		+ f.codigoSucursal);
                        System.debug('Código Unidad de Negocio: ' 	+ f.codigoUnidadNegocio);
                        System.debug('Número de Factura: ' 			+ f.numeroFactura);
                        System.debug('Cantidad: ' 					+ f.cantidad);
                        System.debug('Precio: ' 					+ f.precio);
                        System.debug('Total Linea: ' 				+ f.totalLinea);
                        System.debug('Código Item: ' 				+ f.codigoItem);
                        System.debug('Descripción: ' 				+ f.descripcion);
                        System.debug('Llave factura: ' 				+ f.numeroFactura+'_'+f.codigocliente+'_'+f.codigoSucursal+'_'+f.codigoUnidadNegocio);
                        
                        detallesFactToUpsert.add(fact);
                        
                   	}
                    
                    if(detallesFactToUpsert.size()>0){
                        Database.SaveResult[] srList = Database.insert(detallesFactToUpsert, false);
                
                        for (Database.SaveResult sr : srList) {
                            if (sr.isSuccess()){
                                
                            }else {
                                for(Database.Error err : sr.getErrors()) {
                                    System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                                    System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                                    errorsList.add('Ha ocurrido un error en la UDC:' + err.getStatusCode() + ': ' + err.getMessage() + '\n' + 'Los campos que interfieren en el error son: ' + err.getFields()+ '\n\n');
                                }
                            }
                       } 
                    
                        if(errorsList.size()>0){
                            //ProcesaWSClientes.notificaLlamadoWS(errorsList);
                        }
                    }
                }
                
            }
            
            
            
        }catch (CallOutException ex){/*generaSolicitudEmail('Hubo una excepcion: ' + ex.getMessage() +', '+ ex.getStackTraceString());*/
        	System.debug('Excepción: ' + ex.getMessage());
        }
    	
	}

}