force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/AU__c.field-meta.xml
<CustomField>
    <fullName>AU__c</fullName>
    <label>AU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Nombre del cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto del recibo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Recibos</relationshipLabel>
    <relationshipName>Recibos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Anio_opcion__c.field-meta.xml
<CustomField>
    <fullName>Anio_opcion__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>1984</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/AU__c.field-meta.xml
<CustomField>
    <fullName>AU__c</fullName>
    <label>AU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Capacidad__c.field-meta.xml
<CustomField>
    <fullName>Capacidad__c</fullName>
    <label>Capacidad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Carta_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Carta_de_venta__c</fullName>
    <label>Carta de venta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Cilindros__c.field-meta.xml
<CustomField>
    <fullName>Cilindros__c</fullName>
    <label>Cilindros</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Circulacion__c.field-meta.xml
<CustomField>
    <fullName>Circulacion__c</fullName>
    <label>Circulación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Veh_culos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Combustible__c.field-meta.xml
<CustomField>
    <fullName>Combustible__c</fullName>
    <label>Combustible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gasolina</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Equipado_con__c.field-meta.xml
<CustomField>
    <fullName>Equipado_con__c</fullName>
    <description>Detalle de los accesorios a los que viene el vehiculo</description>
    <label>Equipado con</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Evaluador__c.field-meta.xml
<CustomField>
    <fullName>Evaluador__c</fullName>
    <label>Evaluador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Vehiculos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos (Modelo)</relationshipLabel>
    <relationshipName>Vehiculos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Precio_de_compra_aprobado_S_Autolote__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_compra_aprobado_S_Autolote__c</fullName>
    <description>Precio definitivo para oferta de compra de auto, lo llena el supervisor de compra</description>
    <label>Precio de compra aprobado S. Autolote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>ST Wagon</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>PickUp</fullName>
            </value>
            <value>
                <fullName>Pasajeros</fullName>
            </value>
            <value>
                <fullName>Panel</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Ambulancia</fullName>
            </value>
            <value>
                <fullName>Camion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <description>Nombre de la persona que llevo a cabo el pre-avalúo del vehículo</description>
    <label>Vendedor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ctrl_ComprobanteAU.cls
public class Ctrl_ComprobanteAU {
    public String porcentajeImpuesto {get;set;}
    public String nombreCliente {get;set;}
    public String codigoCliente {get;set;}
    public Vehiculo__c vehiculo {get;set;}
    public Decimal impuesto {get;set;}
    public List<String> listaAbogados {get;set;}
    public List<String> listaContables {get;set;}
    public List<AllRecibidos__c> recibos {get;set;}

    public Ctrl_ComprobanteAU() {
        Id idVehiculo = ApexPages.currentPage().getParameters().get('Id');

        vehiculo = [
            SELECT Id, Placa__c, Tipo__c, Marca__c, Marca__r.Name, Cliente__c, Circulacion__c,
                Modelo__c, Modelo__r.Name, Anio_opcion__c, Color__c, Cilindros__c,
                Motor__c, Chasis__c, Kilometraje__c, Equipado_con__c, Carta_de_venta__c,
                Precio_de_compra_aprobado_S_Autolote__c, Vendedor__c, Evaluador__c, AU__c,
                Capacidad__c, Combustible__c, VIN__c, Cliente__r.Name, Cliente__r.CodigoCliente__c
            FROM Vehiculo__c
            WHERE Id =: idVehiculo
        ];

        recibos = [
            SELECT Concepto__c, Saldo__c
            FROM AllRecibidos__c
            WHERE Vehiculo__c =: vehiculo.Id
        ];

        if (String.isNotBlank(vehiculo.Cliente__c)) {
            nombreCliente = vehiculo.Cliente__r.Name;
            codigoCliente = vehiculo.Cliente__r.CodigoCliente__c;
        }

        if (vehiculo.Precio_de_compra_aprobado_S_Autolote__c != null) {
            impuesto = vehiculo.Precio_de_compra_aprobado_S_Autolote__c> 50000? 0.015 : 0.01;
            porcentajeImpuesto = vehiculo.Precio_de_compra_aprobado_S_Autolote__c> 50000? '1.5%' : '1%';
        }

        listaContables = Label.AU_Contadores.split(',');
    }
}