force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Cedula_Nro__c.field-meta.xml
<CustomField>
    <fullName>Cedula_Nro__c</fullName>
    <label>Cedula Nro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_a_cotizar__c.field-meta.xml
<CustomField>
    <fullName>Marca_a_cotizar__c</fullName>
    <label>Marca a cotizar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Autolote</fullName>
            </value>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BYD</fullName>
            </value>
            <value>
                <fullName>Mercedes Benz</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para realizar por medio de trigger el matcheo con el campo picklist, util para hacer la conversion a oportunidad</description>
    <label>Marca UDC</label>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Leads (Marca UDC)</relationshipLabel>
    <relationshipName>Leads5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Modelo_a_cotizar__c.field-meta.xml
<CustomField>
    <fullName>Modelo_a_cotizar__c</fullName>
    <label>Modelo a cotizar</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Marca_a_cotizar__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agya</fullName>
            </value>
            <value>
                <fullName>Yaris</fullName>
            </value>
            <value>
                <fullName>Yaris Hatchback</fullName>
            </value>
            <value>
                <fullName>Corolla</fullName>
            </value>
            <value>
                <fullName>Prius</fullName>
            </value>
            <value>
                <fullName>Camry</fullName>
            </value>
            <value>
                <fullName>Rush</fullName>
            </value>
            <value>
                <fullName>Fortuner</fullName>
            </value>
            <value>
                <fullName>Rav4</fullName>
            </value>
            <value>
                <fullName>Prado</fullName>
            </value>
            <value>
                <fullName>Landcruiser SW</fullName>
            </value>
            <value>
                <fullName>Hilux 2.4 4x2</fullName>
            </value>
            <value>
                <fullName>Hilux 2.4 4x4</fullName>
            </value>
            <value>
                <fullName>Hilux 2.8 4x4</fullName>
            </value>
            <value>
                <fullName>Tacoma</fullName>
            </value>
            <value>
                <fullName>Tundra</fullName>
            </value>
            <value>
                <fullName>Land Cruiser Pickup cabina sencilla</fullName>
            </value>
            <value>
                <fullName>Land Cruiser Pickup cabina doble</fullName>
            </value>
            <value>
                <fullName>Hiace bus</fullName>
            </value>
            <value>
                <fullName>Hiace</fullName>
            </value>
            <value>
                <fullName>Coaster</fullName>
            </value>
            <value>
                <fullName>Dyna</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Celerio</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Dzire</fullName>
            </value>
            <value>
                <fullName>S-presso</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Vitara</fullName>
            </value>
            <value>
                <fullName>XL7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Anfitrion.recordType-meta.xml
<RecordType>
    <fullName>Anfitrion</fullName>
    <active>true</active>
    <businessProcess>Proceso de leads para Anfitrión</businessProcess>
    <label>Anfitrión</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Autos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autos</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/User/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlujoAnfitrionController.cls
public without sharing class FlujoAnfitrionController {
    @AuraEnabled
    public static List<Opportunity> getOpportunities (String searchKey) {
        try {
            searchKey = '%' + searchKey.replace(' ', '%') + '%';

            List<Opportunity> oppList = [
                SELECT Id, Name, Account.CodigoCliente__c,
                    Owner.Name, CreatedDate, Marca_UDC__c, Marca_UDC__r.Name
                FROM Opportunity
                WHERE (Name LIKE :searchKey OR Account.Name LIKE :searchKey 
                    OR Account.CodigoCliente__c LIKE :searchKey)
                    AND RecordType.DeveloperName = 'Principal_Autos'
                    AND StageName != 'Cerrada ganada'  
                    AND StageName != 'Cerrada perdida'
            ];

            return oppList;

        } catch (Exception e) {
            throw new AuraHandledException('No se ha encontrado ninguna oportunidad...');
        }
    }

    @AuraEnabled
    public static Map<String, List<String>> getModelosByMarca() {
        Map<String, List<String>> modelosByMarca = OportunidadCerradaController.getDependentPicklistValues(Lead.Modelo_a_cotizar__c);

        return modelosByMarca;
    }

    @AuraEnabled
    public static Map<String, List<User>> getUserBySucursal() {
        Map<String, List<User>> userBySucursal = new Map<String, List<User>>();

        for (User u : [SELECT Id, Name, Sucursal__c
                        FROM User
                        WHERE Sucursal__c != null
                            AND Profile.Name LIKE 'Vendedor%'
                            AND IsActive = true]) {

            List<User> uList = new List<User>();

            if (userBySucursal.containsKey(u.Sucursal__c)) {
                uList = userBySucursal.get(u.Sucursal__c);
            }

            uList.add(u);

            userBySucursal.put(u.Sucursal__c, uList);
        }

        return userBySucursal;
    }

    @AuraEnabled
    public static String crearTareaDeAnfitrion(Id userId, Id oppId) {
        Task tk = new Task();
        tk.Status = 'Completada';
        tk.Subject = 'Visita';
        tk.ActivityDate = Date.today();
        tk.OwnerId = userId;
        tk.WhatId = oppId;

        Database.SaveResult sr = Database.insert(tk, false);

        if (!sr.isSuccess()) {
            for (Database.Error err : sr.getErrors()) {
                return err.getMessage();
            }
        }

        return 'Ok';
    }

    @AuraEnabled
    public static String createLeadAnfitrion(String firstName,
                                             String middleName,
                                             String lastName,
                                             String email,
                                             String phone,
                                             String identification,
                                             String marca,
                                             String modelo,
                                             String owner
                                             ){
        try {
            ID anfitrionId = Schema.SObjectType.Lead
                    .getRecordTypeInfosByDeveloperName()
                    .get('Anfitrion')
                    .getRecordTypeId();

            List<User> userList = new List<User>();

            if (String.isNotBlank(owner)) {
                userList = [
                    SELECT Id 
                    FROM User 
                    WHERE Name =: owner
                        AND IsActive = true
                ];
            }

            Lead ld = new Lead();
                ld.FirstName = firstName;
                ld.MiddleName = middleName;
                ld.LastName = lastName;
                ld.Email = email;
                ld.Phone = phone;
                ld.Cedula_Nro__c = identification;
                ld.LeadSource = 'Presencial';
                ld.Status = 'Contacto exitoso';
                ld.Marca_a_cotizar__c = marca;
                ld.Modelo_a_cotizar__c = modelo;
                ld.RecordTypeId = anfitrionId;
                ld.OwnerId = !userList.isEmpty()? userList[0].Id : null;

            insert ld;

            return ld.Id; 

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}