force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Envio_correcto_a_WS__c.field-meta.xml
<CustomField>
    <fullName>Envio_correcto_a_WS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para verificar que el contacto exista en el JD E1</description>
    <label>Envío correcto a WS (Account)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CODIGOCLIENTE__c.field-meta.xml
<CustomField>
    <fullName>CODIGOCLIENTE__c</fullName>
    <externalId>true</externalId>
    <label>Codigo del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Envio_correcto_a_WS__c.field-meta.xml
<CustomField>
    <fullName>Envio_correcto_a_WS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para verificar que el contacto exista en el JD E1</description>
    <label>Envío correcto a WS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/Debug_log__c.object-meta.xml
<CustomObject>
    <label>Debug log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Debug log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debugs logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error ocurrido</description>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/fields/ID_Objeto__c.field-meta.xml
<CustomField>
    <fullName>ID_Objeto__c</fullName>
    <description>ID del objeto sobre el que ocurrió el error</description>
    <label>ID Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>Almacena errores en creacion/actualizacion de registros</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/ButtonRecallController.cls
public with sharing class ButtonRecallController {
    @AuraEnabled
	public static void recall(ID identificacion, String tipoCuenta) { 
        if(tipoCuenta == 'Account') {
            Account acc = 
                [SELECT ID, CodigoCliente__c, Envio_correcto_a_WS__c
                FROM Account
                WHERE ID =: identificacion
                ];
            if(!acc.Envio_correcto_a_WS__c) {
                System.debug('Se envia a InsertarCliente');
                Database.executeBatch(new BatchWSClientes('1', new List<ID>{acc.ID}, null), 1);
            }
        } else {
            Contact cont =
                [SELECT Envio_correcto_a_WS__c
                FROM Contact
                WHERE ID =: identificacion
                ];

            if(!cont.Envio_correcto_a_WS__c) {
                System.debug('Entra en la condicion de contactos');
                Database.executeBatch(new BatchWSContactos('1', new List<String>{'Parent', 'All relation'}, new List<ID>{cont.ID}, null), 1);
            }
        }
    }

    @AuraEnabled
    public static Boolean yaHaSidoEnviado(ID identificacion, String tipoCuenta){
        List<Debug_log__c> debugLista = 
            [SELECT ID
             FROM Debug_log__c
             WHERE ID_Objeto__c =: '' + identificacion
             ];

        Boolean envioCorrecto;

        if(tipoCuenta == 'Account') {
            Account acc = 
                [SELECT Envio_correcto_a_WS__c
                FROM Account
                WHERE ID =: identificacion
                ];
            envioCorrecto = acc.Envio_correcto_a_WS__c;
        } else {
            Contact cont =
                [SELECT Envio_correcto_a_WS__c
                FROM Contact
                WHERE ID =: identificacion
                ];
            envioCorrecto = cont.Envio_correcto_a_WS__c;
        }

        System.debug(debugLista.size());
        System.debug(envioCorrecto);
        
        if (debugLista.isEmpty() && !envioCorrecto) {
            return false;
        } else {
            return true;
        }
    }

    @AuraEnabled
    public static String erroresNotificados(ID identificacion){
        
        List<Debug_log__c> debugLista = 
            [SELECT ID, Error__c
             FROM Debug_log__c
             WHERE ID_Objeto__c =: '' + identificacion
             ];

        if (!debugLista.isEmpty()) {
            if (debugLista[0].Error__c.contains('500')) {
                return 'Error en la comunicacion con el WS';
            } else {
                return debugLista[0].Error__c;
            }
        } else {
            return null;
        }
    }
}