force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/FacturaDetalle__c.object-meta.xml
<CustomObject>
    <label>Factura Detalle</label>
    <nameField>
        <label>Nombre de Factura Detalle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas Detalle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FacturaDetalle__c/fields/CodigoItem__c.field-meta.xml
<CustomField>
    <fullName>CodigoItem__c</fullName>
    <label>Código del producto facturado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas Detalle</relationshipLabel>
    <relationshipName>Facturas_Detalle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción del producto facturado</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/DescuentoDeLinea__c.field-meta.xml
<CustomField>
    <fullName>DescuentoDeLinea__c</fullName>
    <label>Descuento de linea</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Facturas_Maestro__c.field-meta.xml
<CustomField>
    <fullName>Facturas_Maestro__c</fullName>
    <label>Factura</label>
    <referenceTo>FacturasMaestro__c</referenceTo>
    <relationshipLabel>Facturas Detalle</relationshipLabel>
    <relationshipName>Facturas_Detalle</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/IdExt_Detalle_Factura__c.field-meta.xml
<CustomField>
    <fullName>IdExt_Detalle_Factura__c</fullName>
    <externalId>true</externalId>
    <label>IdExt Detalle Factura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/NumeroFactura__c.field-meta.xml
<CustomField>
    <fullName>NumeroFactura__c</fullName>
    <label>Número de la factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/TotalLinea__c.field-meta.xml
<CustomField>
    <fullName>TotalLinea__c</fullName>
    <label>Total de la linea facturada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/UnidadOrdenada__c.field-meta.xml
<CustomField>
    <fullName>UnidadOrdenada__c</fullName>
    <label>Cantidad ordenada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FacturaDetalle__c/fields/UnidadSurtida__c.field-meta.xml
<CustomField>
    <fullName>UnidadSurtida__c</fullName>
    <label>Cantidad surtida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/FacturasMaestro__c.object-meta.xml
<CustomObject>
    <label>Facturas Maestro</label>
    <nameField>
        <displayFormat>FACT-{000000000}</displayFormat>
        <label>Nombre de Facturas Maestro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas Maestro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FacturasMaestro__c/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas Maestro</relationshipLabel>
    <relationshipName>Facturas_Maestro1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FacturasMaestro__c/fields/NumeroFactura__c.field-meta.xml
<CustomField>
    <fullName>NumeroFactura__c</fullName>
    <externalId>true</externalId>
    <label>Número de la factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcesaDetalleFacturas.cls
public class ProcesaDetalleFacturas {
    
    public static void procesaDetalleFact (String resp){
        
        String errors = 'Errores: \n\n';
        List<String> errorsList = new List<String>();
        
        Dom.Document doc = new Dom.Document();  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  
        
        System.debug('rootElement.getChildElements(): ' + rootElement.getChildElements().size());
        List<FacturaDetalle__c> listFacturas = new List<FacturaDetalle__c>();
        
        //for ( Integer i=0; i <rootElement.getChildElements().size(); i++ ) {  
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
            	FacturaDetalle__c facturaDetalle = new FacturaDetalle__c ();             
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){ 
                switch on detailElement.getName() {
                    when 'codigoItem'				{ 
                        facturaDetalle.CodigoItem__c 				= detailElement.getText() != null ? detailElement.getText() : null; 
                    	system.debug('codigoItem:' + detailElement.getText());
                    }
                    when 'descripcion' 			{ 
                        facturaDetalle.Descripcion__c				= detailElement.getText() != null ? detailElement.getText() : null; 
                        system.debug('descripcion:' + detailElement.getText());
                    }
                    when 'descuentoDeLinea' 		{ 
                        facturaDetalle.DescuentoDeLinea__c 	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('descuentoDeLinea:' + detailElement.getText());
                    }
                    when 'numeroFactura'	{ 
                        facturaDetalle.NumeroFactura__c	= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('numeroFactura:' + detailElement.getText());
                    }
                    when 'precio'		 	{ 
                        facturaDetalle.Precio__c		= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('precio:' + detailElement.getText());
                    }
                    when 'totalLinea'		{ 
                        facturaDetalle.TotalLinea__c		= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0; 
                    	system.debug('totalLinea:' + detailElement.getText());
                    }
                    when 'unidadOrdenada'		{ 
                        facturaDetalle.UnidadOrdenada__c		= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0;  
                    	system.debug('unidadOrdenada:' + detailElement.getText());
                    }
                    when 'unidadSurtida'	 		{ 
                        facturaDetalle.UnidadSurtida__c	 		= detailElement.getText().trim() != '' ? Decimal.valueOf(detailElement.getText()) : 0;  
                    	system.debug('unidadSurtida:' + detailElement.getText());
                    } 
                    
                    when else 				{  }
                    
                }
            }
        	
            if(facturaDetalle.NumeroFactura__c != null){
                /*facturaMaestro.Cuenta__r = new Account(CodigoCliente__c=facturaMaestro.CodigoCliente__c);  */
                facturaDetalle.Facturas_Maestro__r = new FacturasMaestro__c(NumeroFactura__c=facturaDetalle.NumeroFactura__c);
                facturaDetalle.IdExt_Detalle_Factura__c = facturaDetalle.CodigoItem__c+'_'+facturaDetalle.NumeroFactura__c;
            	listFacturas.add(facturaDetalle);    
            }
        	
    	}
        
        if(listFacturas.size()>0){
            Schema.SObjectField c = FacturaDetalle__c.Fields.IdExt_Detalle_Factura__c;
			Database.UpsertResult [] srList = Database.upsert(listFacturas, c, false);
            //Database.SaveResult[] srList  = Database.insert(listFacturas, false);
                
                for (Database.UpsertResult sr : srList) {
                    if (sr.isSuccess()){
                        
                    }else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                            System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                            
                            errorsList.add('Ha ocurrido un error en la FacturaMaestro:' + err.getStatusCode() + ': ' + err.getMessage() + '\n' + 'Los campos que interfieren en el error son: ' + err.getFields()+ '\n\n');
                            
                        }
                    }
               }             	
        }

	}
}