force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Veh_culos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Precio_de_compra_aprobado_S_Autolote__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_compra_aprobado_S_Autolote__c</fullName>
    <description>Precio definitivo para oferta de compra de auto, lo llena el supervisor de compra</description>
    <label>Precio de compra aprobado S. Autolote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_ComprobanteAU.cls
@isTest
public class Test_ComprobanteAU {
    @isTest
    public static void testGenerarComprobanteAu(){
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_Mock());
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        
        Account account = TestFactory.createPersonAccount();
		insert account;        
        
        Vehiculo__c vehiculo = TestFactory.createVehiculo();
        vehiculo.Cliente__c = account.Id;
        vehiculo.Precio_de_compra_aprobado_S_Autolote__c = 10000;
        insert vehiculo;
        
       	Test.startTest();
        PageReference pageRef = Page.comprobanteAU;
        Test.setCurrentPage(pageRef);
        Test.stopTest(); 
        
        Account insertedAccount = [
            SELECT Name, CodigoCliente__c
            FROM Account
            WHERE Id =: account.Id
            LIMIT 1
        ];
        
		pageRef.getParameters().put('Id', vehiculo.Id); 
        
        Ctrl_ComprobanteAU comprobanteController = new Ctrl_ComprobanteAU();
        
        System.assertEquals(vehiculo.Id, comprobanteController.vehiculo.Id, 'El vehiculo no es el esperado');
        System.assertEquals('1%', comprobanteController.porcentajeImpuesto, 'El porcentaje de impuestos no coincide con lo esperado');
        System.assertEquals(0.01, comprobanteController.impuesto, 'El valor del impuesto no coincide con lo esperado');
        System.assertEquals(insertedAccount.Name, comprobanteController.nombreCliente, 'El nombre de cliente no coincide con lo esperado');
        System.assertEquals(insertedAccount.CodigoCliente__c, comprobanteController.codigoCliente, 'El codigo de cliente no coincide con lo esperado');
    }
}