force-app/main/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <externalId>true</externalId>
    <label>Código del cliente</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha de la última actualización</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/AU__c.field-meta.xml
<CustomField>
    <fullName>AU__c</fullName>
    <label>AU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Codigo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Cliente__c</fullName>
    <formula>Cuenta__r.CodigoCliente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Codigo de Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto del recibo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Esquela__c.field-meta.xml
<CustomField>
    <fullName>Esquela__c</fullName>
    <label>Esquela</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha del registro del recibo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>All_Recibidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/MontoAplicado__c.field-meta.xml
<CustomField>
    <fullName>MontoAplicado__c</fullName>
    <label>Monto aplicado en el recibo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_cliente__c</fullName>
    <formula>IF( Cuenta__r.IsPersonAccount , 
    Cuenta__r.FirstName &amp; &quot; &quot; &amp; Cuenta__r.MiddleName &amp; &quot; &quot; &amp; Cuenta__r.LastName, 
    Cuenta__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/NumeroRecibido__c.field-meta.xml
<CustomField>
    <fullName>NumeroRecibido__c</fullName>
    <label>Número de recibo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_aplicado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_aplicado__c</fullName>
    <label>Saldo total aplicado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>IF(ISPICKVAL(C_digo_moneda_recibida__c , &quot;COR&quot;),
   Saldo__c /  Tasa__c - Suma_de_montos_aplicados__c, 
   Saldo__c -  Suma_de_montos_aplicados__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Recibos</relationshipLabel>
    <relationshipName>Recibos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/recordTypes/Principal.recordType-meta.xml
<RecordType>
    <fullName>Principal</fullName>
    <active>true</active>
    <description>Recibo que viene de caja/Acreditar al código</description>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_cliente__c</fullName>
    <formula>IF(Facturar_a_nombre_de__r.IsPersonAccount,Facturar_a_nombre_de__r.FirstName &amp; &quot; &quot; &amp; Facturar_a_nombre_de__r.LastName, Facturar_a_nombre_de__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comprador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Esquela__c.field-meta.xml
<CustomField>
    <fullName>Esquela__c</fullName>
    <label>Esquela</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_cliente__c</fullName>
    <formula>IF(Account.IsPersonAccount,  Account.FirstName &amp; &quot; &quot; &amp; Account.LastName, Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/Recibos_de_la_negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Recibo de la negociación</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Nombre de Recibos de la negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos de la negociación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Monto_aplicado_a_la_negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Monto_aplicado_a_la_negociaci_n__c</fullName>
    <label>Monto aplicado a la negociación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Recibos__c.field-meta.xml
<CustomField>
    <fullName>Recibos__c</fullName>
    <label>Recibos</label>
    <referenceTo>AllRecibidos__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>Recibos__r.Saldo_disponible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/AU__c.field-meta.xml
<CustomField>
    <fullName>AU__c</fullName>
    <label>AU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ctrl_Recibos.cls
public without sharing class Ctrl_Recibos{

	public list<Wrapper> ListWrap			{get;set;}
	public list<AllRecibidos__c> listcon	{get;set;}
    //public String esquela				    {get;set;}
    public String paramBusqueda				{get;set;}
    public String tipoDeBusqueda			{get;set;}
    public String msjBusqueda				{get;set;}
    public Id idInfNeg;
    public Id rtId_ReciboPrincipal;

	//=====================class Constructor

	public Ctrl_Recibos(){
        tipoDeBusqueda = 'código del cliente';
        idInfNeg = ApexPages.currentPage().getParameters().get('id');
        
        if (idInfNeg != null) {
            List<Informe_de_Negociaci_n__c> infList = [
                SELECT Id, Cuenta__c, Cuenta__r.CodigoCliente__c, Oportunidad__r.Esquela__c
                FROM Informe_de_Negociaci_n__c 
                WHERE id =: idInfNeg
            ];
         
            if (!infList.isEmpty()) {
                if (String.isNotBlank(infList[0].Cuenta__c)) {
                    paramBusqueda = infList[0].Cuenta__r.CodigoCliente__c;
                    //esquela = infList[0].Oportunidad__r.Esquela__c;
                    consultaRecibos();
                }
            }   
        }
	}
	
    public void consultaRecibos() {
       	System.debug('TIPO DE BUSQUEDA: ' + tipoDeBusqueda );
        System.debug('VALOR BUSQUEDA: ' + paramBusqueda );

        list<AllRecibidos__c> listR = new List<AllRecibidos__c>();

        if (tipoDeBusqueda == 'nombre del cliente') {
        	listR = [
                SELECT Id, AU__c, Name, NumeroRecibido__c, Codigo_de_Cliente__c, Nombre_del_cliente__c, Fecha__c, Vehiculo__r.AU__c,
                     		Concepto__c, MontoAplicado__c, Cuenta__c, CurrencyIsoCode, Saldo_disponible__c, Saldo_aplicado__c  
                FROM AllRecibidos__c 
                WHERE Nombre_del_cliente__c =: paramBusqueda 
                    AND RecordType.DeveloperName = 'Principal'
                ORDER BY Fecha__c, NumeroRecibido__c DESC 
                NULLS LAST
            ]; 
            
            System.debug('ENTRA nombre del cliente');
            System.debug('listR: ' + listR.size());
        }
        
        if (tipoDeBusqueda == 'código del cliente') {
        	listR = [
                SELECT Id, AU__c, Name, NumeroRecibido__c, Codigo_de_Cliente__c, Nombre_del_cliente__c, Fecha__c, Vehiculo__r.AU__c,
                     		Concepto__c, MontoAplicado__c, Cuenta__c, CurrencyIsoCode, Saldo_disponible__c, Saldo_aplicado__c  
                FROM AllRecibidos__c 
                WHERE Codigo_de_Cliente__c =: paramBusqueda
                    AND RecordType.DeveloperName = 'Principal'
                ORDER BY Fecha__c, NumeroRecibido__c DESC 
                NULLS LAST
            ]; 
            
            System.debug('ENTRA código del cliente');
            System.debug('listR: ' + listR.size());
        }
        
        if (tipoDeBusqueda == 'número del recibo') {
            if (paramBusqueda.isNumeric()) {
            	listR = [
                    SELECT Id, AU__c, Name, NumeroRecibido__c, Codigo_de_Cliente__c, Nombre_del_cliente__c, Fecha__c, Vehiculo__r.AU__c,
                         		Concepto__c, MontoAplicado__c, Cuenta__c, CurrencyIsoCode, Saldo_disponible__c, Saldo_aplicado__c  
                    FROM AllRecibidos__c 
                    WHERE NumeroRecibido__c =: Decimal.valueOf(paramBusqueda) 
                        AND RecordType.DeveloperName = 'Principal'
                    ORDER BY Fecha__c, NumeroRecibido__c DESC 
                    NULLS LAST
                ]; 
            } else {
                msjBusqueda = 'El valor de busqueda con número de recibo debe ser númerico';
            }
            
            System.debug('ENTRA número del recibo');
            System.debug('listR: ' + listR.size());
        }

        if (tipoDeBusqueda == 'au' || test.isRunningTest()) {
            listR = [
                SELECT Id, Name, NumeroRecibido__c, Codigo_de_Cliente__c, Nombre_del_cliente__c, Fecha__c, Vehiculo__r.AU__c,
                            Concepto__c, MontoAplicado__c, Cuenta__c, CurrencyIsoCode, Saldo_disponible__c, Saldo_aplicado__c  
                FROM AllRecibidos__c 
                WHERE Vehiculo__r.AU__c =: paramBusqueda 
                   AND RecordType.DeveloperName = 'Principal'
                ORDER BY Fecha__c, NumeroRecibido__c DESC 
                NULLS LAST
            ]; 
            
            System.debug('ENTRA au');
            System.debug('listR: ' + listR.size());
            
        }

        /*if (tipoDeBusqueda == 'esquela' || test.isRunningTest()) {
            listR = [
                SELECT Id, AU__c, Name, NumeroRecibido__c, Codigo_de_Cliente__c, Nombre_del_cliente__c, Fecha__c,
                            Concepto__c, MontoAplicado__c, Cuenta__c, CurrencyIsoCode, Saldo_disponible__c, Saldo_aplicado__c  
                FROM AllRecibidos__c 
                WHERE Esquela__c =: paramBusqueda
                    AND RecordType.DeveloperName = 'Principal'
                ORDER BY Fecha__c, NumeroRecibido__c DESC 
                NULLS LAST
            ]; 
            
            System.debug('ENTRA esquela');
            System.debug('listR: ' + listR.size());
            
        }*/
        
        if (!listR.isEmpty()) {
            msjBusqueda = 'Se encontraron '+ listR.size() + ' registros';
        } else {
            msjBusqueda = 'No se encontraron registros para esta búsqueda, valide que la información sea correcta';
        }        

		ListWrap = new List<wrapper>(); //---------- wrapper class object
        
		for (AllRecibidos__c r : listR) {
            Boolean Nodisponible = r.Saldo_disponible__c == 0;
            Decimal saldoAplicado = r.Saldo_aplicado__c != null? r.Saldo_aplicado__c : 0;

            System.debug('NO DISPONIBLE: ' + noDisponible);
            System.debug('r.Saldo_aplicado__c: ' + r.Saldo_aplicado__c);
            System.debug('r.Saldo_disponible__c: ' + r.Saldo_disponible__c);
            System.debug('r.Id: ' + r.Id);
            
			ListWrap.add(new wrapper(r, 
                                     r.Vehiculo__r.AU__c, 
                                     ''+r.NumeroRecibido__c, 
                                     ''+r.Codigo_de_Cliente__c, 
                                     ''+r.Nombre_del_cliente__c, 
                                     (''+r.Fecha__c).mid(0, 10), r.Concepto__c, 
                                     r.CurrencyIsoCode + ' $'+String.valueOf(saldoAplicado),
                                     r.CurrencyIsoCode + ' $'+String.valueOf(r.Saldo_disponible__c.format()),
                                     Nodisponible));
		}
    }

	public PageReference validaSeleccionados() {
		List<Recibos_de_la_negociaci_n__c> recibosNeg = new List<Recibos_de_la_negociaci_n__c>();
        
		for (wrapper c : ListWrap) {
			if(c.checkbox == true) {
				System.debug('RECIBO SELECCIONADO: ' + c.numRecibo);
                recibosNeg.add(
                    new Recibos_de_la_negociaci_n__c (
                        Informe_de_Negociaci_n__c = idInfNeg, 
                        Recibos__c = c.recibo.Id, 
                        CurrencyIsoCode = c.recibo.CurrencyIsoCode, 
                        Monto_aplicado_a_la_negociaci_n__c = 0
                    )
                );
            }
        }
        
        if (!recibosNeg.isEmpty()) {
            insert recibosNeg;
        }
        
        PageReference  p = new PageReference ('/'+idInfNeg);
        p.setRedirect(true);	
		return p;
	}
    
    public void limpiaBusqueda() {
        ListWrap = new List<wrapper>();
        msjBusqueda = '';
        paramBusqueda = '';
        /*if (tipoDeBusqueda == 'esquela') {
            paramBusqueda = esquela;
        }*/
    }

    public void setParamBusqueda(){
    }
    
    public void refrescarRecibos() {
        try {
            System.debug('entra en refrescar recibos');

            ProcesaRecibosDia.procesaRecibosNow();
            
            String parametroBusqueda = paramBusqueda;
            
            PageReference tempPage = ApexPages.currentPage();            
        	tempPage.setRedirect(true);
            paramBusqueda = parametroBusqueda;
            consultaRecibos();
        } catch (Exception e) {
            System.debug('Algo ha salido mal. ' + e);
        }
    }

    /*public void refrescarRecibosEsquela() {
        try {
            System.debug('entra en refrescar esquelas');

            String esquela = paramBusqueda;

            System.debug(esquela);
            System.debug(String.isBlank(esquela));

            if (String.isBlank(esquela)) {
                msjBusqueda = 'Debe ingresar una esquela para hacer el actualización';
            } else {
                String mensaje = CallWSEsquelas.obtenerRecibosPorEsquela(esquela);
                
                if (mensaje == 'Ok') {
                    PageReference tempPage = ApexPages.currentPage();            
                    tempPage.setRedirect(true);
                    paramBusqueda = esquela;
        
                    consultaRecibos();
                } else {
                    msjBusqueda = mensaje;
                }
            }
            
        } catch (Exception e) {
            System.debug('Algo ha salido mal. ' + e);
        }
    }*/

	//========== wrapper class ====================

	public class wrapper{

		public AllRecibidos__c recibo 	{get;set;}
		public String au    			{get;set;}
		public String numRecibo			{get;set;}
        public String codCliente		{get;set;}
        public String cliente			{get;set;}
        public String fecha				{get;set;}
        public String concepto			{get;set;}
        public String saldoAplicado		{get;set;}
        public String saldoDisponible	{get;set;}
		public boolean checkbox			{get;set;}
        public boolean noVisible		{get;set;}
        
		public Wrapper(AllRecibidos__c rec, String au, String numRec, String codCte, String cte, String f, String concep, String saldoApli, String saldoDisp, Boolean noVisible) {
		 	this.recibo = rec;
			this.au = au;
			this.numRecibo = numRec;
			this.codCliente = codCte;
			this.cliente = cte;
			this.fecha = f;
			this.concepto = concep;		
			this.saldoAplicado = saldoApli;
            this.saldoDisponible = saldoDisp;
            this.saldoDisponible = saldoDisp;
            this.checkbox = test.isRunningTest();	
            this.noVisible = noVisible;
		}
	}
}