force-app/main/default/objects/Account/fields/Creado_desde_un_Lead__c.field-meta.xml
<CustomField>
    <fullName>Creado_desde_un_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check bandera para corroborar si el contacto fue creado a partir de un lead y asi poder enviarlo al WS por separado</description>
    <label>Creado desde un Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <label>IdExterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secuencia_contactos__c.field-meta.xml
<CustomField>
    <fullName>Secuencia_contactos__c</fullName>
    <label>Secuencia contactos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <label>IdExterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/contactid__c.field-meta.xml
<CustomField>
    <fullName>contactid__c</fullName>
    <label>Consecutivo del contacto</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Creado_desde_un_Lead__c.field-meta.xml
<CustomField>
    <fullName>Creado_desde_un_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check bandera para corroborar si el contacto fue creado a partir de un lead y asi poder eliminarlo</description>
    <label>Creado desde un Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <description>Numero de identificación único de cada contacto</description>
    <label>Número de documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactHelper.cls
public with sharing class ContactHelper {
    public static void actualizarContactID(List<Contact> contactosLista) {
        Map<ID, Decimal> cuentasIDPorSecuenciaContactos = obtenerMapaCuentasPorSecuenciaContacto(contactosLista);

        for (Contact contact : contactosLista) {
            Decimal conteo = cuentasIDPorSecuenciaContactos.get(contact.AccountID); 

            if (String.isBlank(contact.contactid__c)) {
                Decimal valor = conteo == null ? 1 : conteo + 1;

                contact.contactid__c = '' + valor;

                cuentasIDPorSecuenciaContactos.put(contact.AccountID, valor);
            }
        }
    }

    public static void checkContactCreation(List<Contact> contactosList) {
        Profile perfil = [
            SELECT Name
            FROM Profile
            WHERE Id =: UserInfo.getProfileId() 
            LIMIT 1
        ];

        Boolean isAdmin = perfil.Name.toUpperCase().contains('ADMIN');

        for (Contact contact : contactosList) {
            if (!isAdmin && !contact.Creado_desde_un_Lead__c) {
                contact.addError('No es posible crear contactos. Consulte con un administrador.');
            }
        }
    }

    public static void upperCaseName(List<Contact> contactoList) {
        for (Contact con : contactoList) {
            con.FirstName = String.isNotBlank(con.FirstName)? con.FirstName.toUpperCase() : '';
            con.MiddleName = String.isNotBlank(con.MiddleName)? con.MiddleName.toUpperCase() : '';
            con.LastName = String.isNotBlank(con.LastName)? con.LastName.toUpperCase() : '';
            con.Numero_de_documento__c = String.isNotBlank(con.Numero_de_documento__c)? con.Numero_de_documento__c.toUpperCase() : '';
        }
    }

    public static void modificarContactosEnServicio(List<Contact> contactosLista,
                                                    Map<ID, Contact> oldTriggerMap,
                                                    String actionTypeContact
    ) {
        if(!contactosLista.isEmpty()){
            List<ID> idList = new List<ID>();
            List<String> criterios = new List<String>{ 'Parent' };
                
            if (actionTypeContact == '2') {
                criterios.add('All relation');
            }
            
            for (Contact con : contactosLista) {
                idList.add(con.ID);
            }

            Integer size = 10;
            
            if(idList.size() < 10 || Test.isRunningTest()) {
                size = idList.size();
            }
            
            System.debug(size);
            System.debug(idList);
            System.debug(criterios);

            System.debug('SE ENVIAN ' + idList.size() + ' CONTACTOS AL BATCH CON ACTION ' + actionTypeContact);
            Database.executeBatch(new BatchWSContactos(actionTypeContact, criterios, idList, oldTriggerMap), size); 
        }
    }
    
    public static void eliminarRelaciones (Map<ID, Contact> contMap) {
        List<AccountContactRelation> acrList =
            [SELECT ContactID, IdExterno__c
            FROM AccountContactRelation 
            WHERE ContactID IN :contMap.keySet()
            ];
        
        System.debug('La cuenta tiene ' + acrList.size() + ' relaciones y se van a eliminar');
        
        if (!acrList.isEmpty()) {
            Database.DeleteResult[] dr = Database.delete(acrList, false);
        }
    }


    private static Map<ID, Decimal> obtenerMapaCuentasPorSecuenciaContacto (List<Contact> contactosLista) {
        Set<ID> cuentasID = new Set<ID>();
        
        for (Contact contact : contactosLista) {
            cuentasID.add(contact.AccountID);
        }

        Map<ID, Decimal> cuentasIDPorSecuenciaContactos = new Map<ID, Decimal>();

        for(Account acc : [SELECT ID, Secuencia_contactos__c
                            FROM Account 
                            WHERE ID IN :cuentasID
                            ]) {
            cuentasIDPorSecuenciaContactos.put(acc.ID, acc.Secuencia_contactos__c);
        }
        
        return cuentasIDPorSecuenciaContactos;
    }
}