force-app/main/default/objects/Account/fields/Nivel_organizacional__c.field-meta.xml
<CustomField>
    <fullName>Nivel_organizacional__c</fullName>
    <label>Tipo de contribuyente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asalariado</fullName>
            </value>
            <value>
                <fullName>Cuota Fija</fullName>
            </value>
            <value>
                <fullName>Gran Contribuyente</fullName>
            </value>
            <value>
                <fullName>Mediano Contribuyente</fullName>
            </value>
            <value>
                <fullName>No trabaja</fullName>
            </value>
            <value>
                <fullName>Trabajo Cuenta Propia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pa_s__c.field-meta.xml
<CustomField>
    <fullName>Pa_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pais</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profesion_UDC__c.field-meta.xml
<CustomField>
    <fullName>Profesion_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesión</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesión</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Accounts (Profesión)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Ocasional</fullName>
            </value>
            <value>
                <fullName>Habitual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_cliente__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cliente__c</fullName>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Natural</fullName>
            </value>
            <value>
                <fullName>Jurídico</fullName>
                <label>Sujeto Obligado Jurídico</label>
            </value>
            <value>
                <fullName>PEP</fullName>
                <label>PEP Natural</label>
            </value>
            <value>
                <fullName>Empresa Estatal</fullName>
            </value>
            <value>
                <fullName>Empresa Privada</fullName>
            </value>
            <value>
                <fullName>Organizaciones sin fines de lucro</fullName>
                <label>OSFL</label>
            </value>
            <value>
                <fullName>Sujeto Obligado</fullName>
                <label>Sujeto Obligado Natural</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Indentificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Indentificaci_n__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cedula de Identidad</fullName>
            </value>
            <value>
                <fullName>Cedula de Residente</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>DUI</fullName>
            </value>
            <value>
                <fullName>RUC</fullName>
            </value>
            <value>
                <fullName>RUC Extranjero</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Cédula</fullName>
                <isActive>false</isActive>
                <label>Cédula</label>
            </value>
            <value>
                <fullName>Cédula de identidad</fullName>
                <isActive>false</isActive>
                <label>Cédula de identidad</label>
            </value>
            <value>
                <fullName>Cédula de residente</fullName>
                <isActive>false</isActive>
                <label>Cédula de residente</label>
            </value>
            <value>
                <fullName>Dimex</fullName>
                <isActive>false</isActive>
                <label>Dimex</label>
            </value>
            <value>
                <fullName>Otro</fullName>
                <isActive>false</isActive>
                <label>Otro</label>
            </value>
            <value>
                <fullName>RUC_Extranjero</fullName>
                <isActive>false</isActive>
                <label>RUC_Extranjero</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Canal_Contrata__c.field-meta.xml
<CustomField>
    <fullName>Canal_Contrata__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribuidor Autorizado</fullName>
            </value>
            <value>
                <fullName>Sucursales Propias - Detalle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Donaciones (Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Donaciones (No Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Responsable_del_pago__c.field-meta.xml
<CustomField>
    <fullName>Responsable_del_pago__c</fullName>
    <label>Responsable del pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>Tercero Familiar</fullName>
            </value>
            <value>
                <fullName>Tercero Ajeno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_relaci_n_econ_mica__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_relaci_n_econ_mica__c</fullName>
    <label>Tipo de relación económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Credito</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_transacci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_transacci_n__c</fullName>
    <label>Tipo de transacción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anticipo o Prima</fullName>
            </value>
            <value>
                <fullName>Compra de Credito</fullName>
            </value>
            <value>
                <fullName>Compra de Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcesarScoringUAF.cls
public without sharing class ProcesarScoringUAF{
	public static Map<ID, String> generarCalificacion(List<Opportunity> oppList) {
        ID personAccountID = Schema.SObjectType.Account
                .getRecordTypeInfosByDeveloperName()
                .get('PersonAccount')
                .getRecordTypeId();

        List<String> opcionesList = new List<String>();
        List<ID> accIDList = new List<ID>();
        List<ID> oppIDList = new List<ID>();

        for (Opportunity opp : oppList) {
            accIDList.add(opp.AccountID);
            oppIDList.add(opp.ID);

            opcionesList.add(opp.Canal_Contrata__c);
            opcionesList.add(opp.Sucursal__c);
            opcionesList.add(opp.Tipo_de_transacci_n__c);
            opcionesList.add(opp.Responsable_del_pago__c);
            opcionesList.add(opp.Origen_de_los_fondos__c);
            opcionesList.add(opp.Tipo_de_relaci_n_econ_mica__c);
        }

        Map<ID, Account> accMapPorId = new Map<ID, Account>([
            SELECT Pa_s__c, Pa_s__r.Name, Tipo_de_cliente__c, Tipo_Cliente__c, Tipo_de_Indentificaci_n__c,
                   Nivel_organizacional__c, Profesion_UDC__c, Profesion_UDC__r.Name, Ocupacion_UDC__c, Ocupacion_UDC__r.Name,
                   Actividad_economica_UDC__c, Actividad_economica_UDC__r.Name, PEP__c, RecordTypeId
            FROM Account
            WHERE ID IN :accIDList
        ]);

        for (Opportunity opp : oppList) {
            Account acc = accMapPorId.get(opp.AccountID);

            opcionesList.add(acc.Pa_s__r.Name);
            opcionesList.add(acc.Tipo_de_cliente__c);
            opcionesList.add(acc.Tipo_Cliente__c);
            opcionesList.add(acc.Tipo_de_Indentificaci_n__c);
            opcionesList.add(acc.Nivel_organizacional__c);

            if (acc.RecordTypeId == personAccountID) {
                opcionesList.add(acc.Profesion_UDC__r.Name);
                opcionesList.add(acc.Ocupacion_UDC__r.Name);
            } else {
                opcionesList.add(acc.Actividad_economica_UDC__r.Name);
            }
        }

        Map<ID, List<String>>  recibosPorOportunidadID = new Map<ID, List<String>>();
        Map<ID, Integer> calificacionRecibosPorOportunidadID = new Map<ID, Integer>();

        for (Recibos_de_la_negociaci_n__c recNeg : [SELECT Recibos__r.Instrumento_de_pago__c, Informe_de_Negociaci_n__r.Oportunidad__c
                                                    FROM Recibos_de_la_negociaci_n__c
                                                    WHERE Informe_de_Negociaci_n__r.Oportunidad__c IN: oppIDList
                                                    ]) {

            List<String> recibosList;
            if (!recibosPorOportunidadID.containsKey(recNeg.Informe_de_Negociaci_n__r.Oportunidad__c)) {
                recibosList = new List<String>();
            } else {
                recibosList = recibosPorOportunidadID.get(recNeg.Informe_de_Negociaci_n__r.Oportunidad__c);
            }

            recibosList.add(recNeg.Recibos__r.Instrumento_de_pago__c);

            recibosPorOportunidadID.put(recNeg.Informe_de_Negociaci_n__r.Oportunidad__c, 
                                        recibosList);

            if (!opcionesList.contains(recNeg.Recibos__r.Instrumento_de_pago__c)) {
                opcionesList.add(recNeg.Recibos__r.Instrumento_de_pago__c);
            }
        }

        Map<String, Decimal> calificacionPorName = new Map<String, Decimal>();

        for (CriterioCalificacionCliente__mdt c : [SELECT MasterLabel, Valor__c 
                                                   FROM CriterioCalificacionCliente__mdt
                                                   WHERE MasterLabel IN :opcionesList]) {
            calificacionPorName.put(c.MasterLabel, c.Valor__c);
        }

        Map<ID, Decimal> puntajeRecibosPorOppID = new Map<ID, Decimal>();
        Map<ID, String> scoringPorOppID = new Map<ID, String>();

        for (Opportunity opp : oppList) {
            Decimal puntajeRecibos = 0;
            List<String> listadoRecibos = recibosPorOportunidadID.get(opp.ID);

            for (String tipoRecibo : listadoRecibos) {
                puntajeRecibos += calificacionPorName.get(tipoRecibo);
            }

            puntajeRecibosPorOppID.put(opp.ID, puntajeRecibos / listadoRecibos.size());
        }

        for (Opportunity opp : oppList) {
            Account acc = accMapPorId.get(opp.AccountID);

            Decimal detalleCuenta = 0;
            Decimal detalleOportunidad = 0;

            if (acc.PEP__c || (acc.Tipo_de_cliente__c.contains('PEP'))) {
                scoringPorOppID.put(opp.ID, '4_4');
            } else {
                detalleCuenta += calificacionPorName.get(acc.Tipo_de_cliente__c) * 0.2;
                detalleCuenta += calificacionPorName.get(acc.Tipo_Cliente__c) * 0.2;
                detalleCuenta += calificacionPorName.get(acc.Tipo_de_Indentificaci_n__c) * 0.2;
                detalleCuenta += calificacionPorName.get(opp.Tipo_de_relaci_n_econ_mica__c) * 0.1;
                detalleCuenta += calificacionPorName.get(acc.Nivel_organizacional__c) * 0.1;
                
                if (acc.RecordTypeId == personAccountID) {
                    detalleCuenta += calificacionPorName.get(acc.Profesion_UDC__r.Name) * 0.1;
                    detalleCuenta += calificacionPorName.get(acc.Ocupacion_UDC__r.Name) * 0.1;
                } else {
                    detalleCuenta += calificacionPorName.get(acc.Actividad_economica_UDC__r.Name) * 0.2;
                }

                detalleOportunidad += calificacionPorName.get(opp.Canal_Contrata__c) * 0.05;
                detalleOportunidad += calificacionPorName.get(opp.Sucursal__c) * 0.05;
                detalleOportunidad += puntajeRecibosPorOppID.get(opp.ID) * 0.2;
                detalleOportunidad += calificacionPorName.get(opp.Tipo_de_transacci_n__c) * 0.25;
                detalleOportunidad += calificacionPorName.get(opp.Responsable_del_pago__c) * 0.1;
                detalleOportunidad += calificacionPorName.get(opp.Origen_de_los_fondos__c) * 0.15;
                detalleOportunidad += calificacionPorName.get(acc.Pa_s__r.Name) * 0.2;

                scoringPorOppID.put(opp.ID, detalleCuenta + '_' + detalleOportunidad);
            }
        }

        return scoringPorOppID;
    }
}