force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/NumeroRecibido__c.field-meta.xml
<CustomField>
    <fullName>NumeroRecibido__c</fullName>
    <label>Número de recibo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_aplicado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_aplicado__c</fullName>
    <label>Saldo total aplicado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>IF(ISPICKVAL(C_digo_moneda_recibida__c , &quot;COR&quot;),
   Saldo__c /  Tasa__c - Suma_de_montos_aplicados__c, 
   Saldo__c -  Suma_de_montos_aplicados__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Recibos</relationshipLabel>
    <relationshipName>Recibos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Avaluo.recordType-meta.xml
<RecordType>
    <fullName>Avaluo</fullName>
    <active>true</active>
    <businessProcess>Avaluo</businessProcess>
    <label>Avalúo</label>
</RecordType>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/Recibos_de_la_negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Recibo de la negociación</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Nombre de Recibos de la negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos de la negociación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Monto_aplicado_a_la_negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Monto_aplicado_a_la_negociaci_n__c</fullName>
    <label>Monto aplicado a la negociación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Recibos__c.field-meta.xml
<CustomField>
    <fullName>Recibos__c</fullName>
    <label>Recibos</label>
    <referenceTo>AllRecibidos__c</referenceTo>
    <relationshipLabel>Recibos de la negociación</relationshipLabel>
    <relationshipName>Recibos_de_la_negociaci_n</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recibos_de_la_negociaci_n__c/fields/Saldo_disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_disponible__c</fullName>
    <formula>Recibos__r.Saldo_disponible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecibosDeNegociacionHelper.cls
public class RecibosDeNegociacionHelper {
    public static void validarMaximo(List<Recibos_de_la_negociaci_n__c> recibosNegList,
                                     Map<ID, Recibos_de_la_negociaci_n__c> recNegOldMap) {
        List<ID> recibosID = new List<ID>();
        for (Recibos_de_la_negociaci_n__c rn : recibosNegList) {
            recibosID.add(rn.Recibos__c);
        }

        Map<ID, AllRecibidos__c> recibosMap = new Map<ID, AllRecibidos__c>(
            [SELECT ID, Saldo_disponible__c, Saldo_aplicado__c, NumeroRecibido__c, CurrencyIsoCode 
            FROM AllRecibidos__c
            WHERE ID IN :recibosID
            ]);
        
        for (Recibos_de_la_negociaci_n__c rn : recibosNegList) {
            AllRecibidos__c r = recibosMap.get(rn.Recibos__c);
            Decimal montoViejo;

            if (recNegOldMap != null) {
                montoViejo = recNegOldMap.get(rn.ID).Monto_aplicado_a_la_negociaci_n__c;
            } else {
                montoViejo = 0;
            }

            Decimal diferencia =  r.Saldo_disponible__c - (rn.Monto_aplicado_a_la_negociaci_n__c - montoViejo); 
            if (diferencia < 0) {
                rn.addError('El monto aplicado al recibo ' + r.NumeroRecibido__c + ' es mayor al saldo disponible,'+
                                ' excede por la cantidad de: ' + r.CurrencyIsoCode + '$ ' + (-1) * diferencia +
                                ', favor de validar la información');
            }
        }
    }

    public static void validarVehiculoCerrado(List<Recibos_de_la_negociaci_n__c> recibosNegList) {
        List<Id> reciboId = new List<Id>();
        List<Id> vehiculosSinCerrar = new List<Id>();
        Map<Id, Id> vehiculoByRecId = new Map<Id, Id>();

        for (Recibos_de_la_negociaci_n__c recNeg : recibosNegList) {
            reciboId.add(recNeg.Recibos__c);
        }

        for (AllRecibidos__c rec : [SELECT Id, Vehiculo__c 
                                    FROM AllRecibidos__c 
                                    WHERE Id IN :reciboId]) {
            vehiculoByRecId.put(rec.Id, rec.Vehiculo__c);
        }

        for (Vehiculo_de_la_Oportunidad__c vehOpp : [SELECT Id, Vehiculo__c
                                                    FROM Vehiculo_de_la_Oportunidad__c
                                                    WHERE Vehiculo__c IN :vehiculoByRecId.values()
                                                        AND Oportunidad__r.RecordType.DeveloperName = 'Avaluo'
                                                        AND Oportunidad__r.StageName != 'Cerrada ganada'
                                                        AND Oportunidad__r.StageName != 'Cerrada perdida']) {
            vehiculosSinCerrar.add(vehOpp.Vehiculo__c);
        }

        for (Recibos_de_la_negociaci_n__c recNeg : recibosNegList) {
            Id vehiculoId = vehiculoByRecId.containsKey(recNeg.Recibos__c)? vehiculoByRecId.get(recNeg.Recibos__c) : '';

            if (String.isNotBlank(vehiculoId) && vehiculosSinCerrar.contains(vehiculoId)) {
                recNeg.addError('No puede asociarse el recibo de un vehiculo que aun no está liberado');
            }
        }
    }
}