force-app/main/default/objects/AllRecibidos__c/AllRecibidos__c.object-meta.xml
<CustomObject>
    <label>Recibos</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Nombre de All Recibidos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recibos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AllRecibidos__c/fields/CodigoInstrumentoPago__c.field-meta.xml
<CustomField>
    <fullName>CodigoInstrumentoPago__c</fullName>
    <label>Código de instrumento de pago</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Instrumento_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Instrumento_de_pago__c</fullName>
    <label>Instrumento de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Tarjeta de credito</fullName>
            </value>
            <value>
                <fullName>Deposito bancario</fullName>
            </value>
            <value>
                <fullName>Transferencia</fullName>
            </value>
            <value>
                <fullName>Carta banco</fullName>
            </value>
            <value>
                <fullName>Credito/Orden de compra</fullName>
            </value>
            <value>
                <fullName>Intercambio Autolote</fullName>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
            <value>
                <fullName>Financiamiento FIDEM</fullName>
            </value>
            <value>
                <fullName>Nota de debito</fullName>
                <label>Nota de débito</label>
            </value>
            <value>
                <fullName>Nota de credito</fullName>
                <label>Nota de crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/NumeroRecibido__c.field-meta.xml
<CustomField>
    <fullName>NumeroRecibido__c</fullName>
    <label>Número de recibo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Recibos</relationshipLabel>
    <relationshipName>Recibos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllRecibidos__c/recordTypes/Gravamen.recordType-meta.xml
<RecordType>
    <fullName>Gravamen</fullName>
    <active>true</active>
    <description>Recibo para la deuda de un vehículo a ser comprado</description>
    <label>Gravamen</label>
</RecordType>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Precio_de_compra_aprobado_S_Autolote__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_compra_aprobado_S_Autolote__c</fullName>
    <description>Precio definitivo para oferta de compra de auto, lo llena el supervisor de compra</description>
    <label>Precio de compra aprobado S. Autolote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RecibosHelper.cls
public class RecibosHelper {
    public static void actualizarInstrumentoPagoCodigo(List<AllRecibidos__c> recList) {
        for(AllRecibidos__c rec : recList) {
            String codigo;

            switch on rec.Instrumento_de_pago__c {
                when 'Efectivo' {
                    codigo = '.';
                }	
                when 'Cheque' {
                    codigo = '!';
                }
                when 'Tarjeta de credito' {
                    codigo = '?';
                }
                when 'Deposito bancario' {
                    codigo = 'N';
                }
                when 'Transferencia' {		  
                    codigo = 'T';
                }
                when 'Carta banco' {
                    codigo = null;
                }
            }

            if (String.isNotBlank(codigo)) {
                rec.CodigoInstrumentoPago__c = codigo;
            } else {
                rec.CodigoInstrumentoPago__c = null;
            }
        }
    }

    public static void actualizarInstrumentoPagoPick(List<AllRecibidos__c> recList) {
        for(AllRecibidos__c rec : recList) {
            String codigo;
        
            if (rec.CodigoInstrumentoPago__c == '.') {
                codigo = 'Efectivo';
            } else if (rec.CodigoInstrumentoPago__c == '!') {
                codigo = 'Cheque';
            } else if (rec.CodigoInstrumentoPago__c == '?') {
                codigo = 'Tarjeta de credito';
            } else if (rec.CodigoInstrumentoPago__c == 'N') {
                codigo = 'Deposito bancario';
            } else if (rec.CodigoInstrumentoPago__c == 'T') {
                codigo = 'Transferencia';
            }
            
            if (String.isNotBlank(codigo)) {
                rec.Instrumento_de_pago__c = codigo;
            } else {
                rec.Instrumento_de_pago__c = null;
            }
        }
    }

    public static void validarSaldoGravamen(List<AllRecibidos__c> recList) {
        List<Id> vehiculoIdList = new List<Id>();

        for (AllRecibidos__c rec : recList) {
            vehiculoIdList.add(rec.Vehiculo__c);
        }

        Map<Id, Vehiculo__c> vehMapById = new Map<Id, Vehiculo__c>([
            SELECT Precio_de_compra_aprobado_S_Autolote__c
            FROM Vehiculo__c
            WHERE Id IN :vehiculoIdList
        ]);

        for (AllRecibidos__c rec : recList) {
            if (rec.Saldo__c > vehMapById.get(rec.Vehiculo__c).Precio_de_compra_aprobado_S_Autolote__c) {
                rec.addError('El gravamen no puede ser mayor que el precio de compra aprobado.');
            }
        }
    }

    public static void validarSaldoARecibosDeVehiculos(List<AllRecibidos__c> recList) {
        List<Id> vehiculoIdList = new List<Id>();
        List<Id> reciboIdList = new List<Id>();
        Map<Id, Decimal> gravamenSumByVehId = new Map<Id, Decimal>();
        Map<Id, Decimal> recibosSumByVehId = new Map<Id, Decimal>();

        for (AllRecibidos__c rec : recList) {
            vehiculoIdList.add(rec.Vehiculo__c);
            reciboIdList.add(rec.Id);
        }

        Map<Id, Vehiculo__c> vehMapById = new Map<Id, Vehiculo__c>([
            SELECT Precio_de_compra_aprobado_S_Autolote__c
            FROM Vehiculo__c
            WHERE Id IN :vehiculoIdList
        ]);

        for (AllRecibidos__c rec : [SELECT Vehiculo__c, Saldo__c 
                                    FROM AllRecibidos__c
                                    WHERE Vehiculo__c IN :vehiculoIdList
                                        AND RecordType.DeveloperName = 'Gravamen']) {
            Decimal gravamen;

            if (gravamenSumByVehId.containsKey(rec.Vehiculo__c)) {
                gravamen = gravamenSumByVehId.get(rec.Vehiculo__c);
            } else {
                gravamen = 0;
            }

            gravamen += rec.Saldo__c;

            gravamenSumByVehId.put(rec.Vehiculo__c, gravamen);
        }

        for (AllRecibidos__c rec : [SELECT Vehiculo__c, Saldo__c 
                                    FROM AllRecibidos__c
                                    WHERE Vehiculo__c IN :vehiculoIdList
                                        AND RecordType.DeveloperName != 'Gravamen'
                                        AND Id NOT IN :reciboIdList]) {
            Decimal suma;

            if (recibosSumByVehId.containsKey(rec.Vehiculo__c)) {
                suma = recibosSumByVehId.get(rec.Vehiculo__c);
            } else {
                suma = 0;
            }

            suma += rec.Saldo__c;

            recibosSumByVehId.put(rec.Vehiculo__c, suma);
        }

        for (AllRecibidos__c rec : recList) {
            Decimal suma = recibosSumByVehId.containsKey(rec.Vehiculo__c)? recibosSumByVehId.get(rec.Vehiculo__c) : 0;
            Decimal gravamen = gravamenSumByVehId.containsKey(rec.Vehiculo__c)? gravamenSumByVehId.get(rec.Vehiculo__c) : 0;
            Decimal precioAprobado = vehMapById.get(rec.Vehiculo__c).Precio_de_compra_aprobado_S_Autolote__c - gravamen - suma;

            if (rec.Saldo__c > precioAprobado) {
                rec.addError('El saldo se excede ' + (rec.Saldo__c - precioAprobado) + ' del precio del vehiculo.');
            }
        }
    }
    // Metodo actualizar numero cuando es manual
    public static void actualizarNum(List<AllRecibidos__c> objReci) {
        List<AllRecibidos__c> lstRecUltimonum = [
            SELECT NumeroRecibido__c 
            FROM AllRecibidos__c
            WHERE NumeroRecibido__c >= 5000000
            AND CreatedDate >= THIS_WEEK 
            ORDER 
            BY NumeroRecibido__c DESC 
            LIMIT 1  
        ];
        Decimal Maximo = 5000000;
        if(!lstRecUltimonum.isEmpty() && lstRecUltimonum.get(0).NumeroRecibido__c>=Maximo){
            Maximo = lstRecUltimonum.get(0).NumeroRecibido__c;
        }
        
        for(AllRecibidos__c recibo : objReci){
            Maximo += 1;
            recibo.NumeroRecibido__c = Maximo;
        }
        /*	System.debug('*******'+ lstRecUltimonum);
Integer intNumrecibo = Integer.valueOf(lstRecUltimonum[0].NumeroRecibido__c);
objReci.NumeroRecibido__c = intNumrecibo+1;
System.debug('*******'+ objReci.NumeroRecibido__c);*/
        
    }
}