force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Consecutivo__c.field-meta.xml
<CustomField>
    <fullName>Consecutivo__c</fullName>
    <label>Conscutivo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cantidad_de_Accesorios__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Accesorios__c</fullName>
    <label>Cantidad de Accesorios</label>
    <summarizedField>Accesorios_del_informe__c.Cantidad__c</summarizedField>
    <summaryForeignKey>Accesorios_del_informe__c.InformeNegociacion__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/InformeSincronizado__c.field-meta.xml
<CustomField>
    <fullName>InformeSincronizado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Informe sincronizado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Reservar__c.field-meta.xml
<CustomField>
    <fullName>Reservar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Omitir_validaci_n_despachado__mdt/Omitir_validaci_n_despachado__mdt.object-meta.xml
<CustomObject>
    <label>Omitir validación despachado</label>
    <pluralLabel>Omitir validaciones despachados</pluralLabel>
</CustomObject>

force-app/main/default/objects/Omitir_validaci_n_despachado__mdt/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccesoriosDelInformeHelper.cls
public without sharing class AccesoriosDelInformeHelper {
    public static void validarInformeReservado(List<Accesorios_del_informe__c> accInfList, String accion) {
        Map<ID, Informe_de_Negociaci_n__c> infNegMap = obtenerInformes(accInfList);

        for (Accesorios_del_informe__c accInf : accInfList) {
            if (infNegMap.get(accInf.InformeNegociacion__c).Reservar__c) {
                accInf.addError('El informe se encuentra Reservado, por lo que no es posible ' + accion + ' los accesorios');
            }
        }
    }

    public static void setearConsecutivoYEstado(List<Accesorios_del_informe__c> accInfList) {
        Map<ID, Decimal> conteoPorInfID = new Map<ID, Decimal>();
        Map<ID, Informe_de_Negociaci_n__c> infNegMap = obtenerInformes(accInfList);

        for (Informe_de_Negociaci_n__c inf : infNegMap.values()) {
            Decimal conteo = inf.Cantidad_de_Accesorios__c == null? 0 : inf.Cantidad_de_Accesorios__c;
            conteoPorInfID.put(inf.ID, conteo);
        }

        for (Accesorios_del_informe__c accInf : accInfList) {
            if (!infNegMap.get(accInf.InformeNegociacion__c).Reservar__c && accInf.Estado__c  != 'Despachado') {
                accInf.Estado__c = 'No solicitado';
            }

            Decimal conteo = conteoPorInfID.get(accInf.InformeNegociacion__c) + 1;
            accInf.Consecutivo__c = conteo;

            conteoPorInfID.put(accInf.InformeNegociacion__c, conteo);
        }
    }

    public static void validarAccesorioDespachado(List<Accesorios_del_informe__c> accInfList, String accion) {
        Boolean omitirValidacion = obtenerValidacion();

        if (!omitirValidacion) {
            for (Accesorios_del_informe__c accInf : accInfList) {
                accInf.addError('No puede ' + accion + ' un accesorio ya despachado.');
            }
        }
    }

    public static void validarAccesorioEquivalente(List<Accesorios_del_informe__c> accInfList) {
        for (Accesorios_del_informe__c accInf : accInfList) {
            accInf.addError('No puede solicitarse un accesorio equivalente si el accesorio no tiene codigo equivalente.');
        }
    }

    public static void solicitarAccesorioInformeAprobado(List<Accesorios_del_informe__c> accInfList, String accion) {
        Map<ID, Informe_de_Negociaci_n__c> infMapByID = new Map<ID, Informe_de_Negociaci_n__c>();

        if (accion != 'Eliminacion') {
            infMapByID = obtenerInformes(accInfList);
        }

        for (Accesorios_del_informe__c accInf : accInfList) {
            Boolean validacion = false;

            if (!infMapByID.KeySet().isEmpty()) {
                Informe_de_Negociaci_n__c inf = infMapByID.get(accInf.InformeNegociacion__c);

                if (accion == 'Insercion' && inf.InformeSincronizado__c && !inf.Reservar__c) {
                    validacion = true;
                }

                if (accion == 'Actualizacion' && inf.InformeSincronizado__c) {
                    validacion = true;
                }
            } else {
                validacion = true;
            }

            if (validacion) {
                CtrlConsultaDisponibilidadAccesorios.solicitaAccesorioInformeAprobado(accInf.InformeNegociacion__c);
            }
        }
    }

    public static void consultarDisponibilidad(List<Accesorios_del_informe__c> accInfList) {
        for (Accesorios_del_informe__c accInf : accInfList) {
            CtrlConsultaDisponibilidadAccesorios.validaDisponibilidadFROMAccesoriosDelComboParaInforme(accInf.InformeNegociacion__c);
        }
    }

    private static Map<ID, Informe_de_Negociaci_n__c> obtenerInformes(List<Accesorios_del_informe__c> accInfList) {
        List<ID> infNegIDList = new List<ID>();

        for (Accesorios_del_informe__c accInf : accInfList) {
            if (String.isNotBlank(accInf.InformeNegociacion__c)) {
                if (!infNegIDList.contains(accInf.InformeNegociacion__c)) {
                    infNegIDList.add(accInf.InformeNegociacion__c);
                }
            }
        }

        Map<ID, Decimal> conteoPorInfID = new Map<ID, Decimal>();

        Map<ID, Informe_de_Negociaci_n__c> infNegMap = new Map<ID, Informe_de_Negociaci_n__c>([
            SELECT Reservar__c, Cantidad_de_Accesorios__c, InformeSincronizado__c
            FROM Informe_de_Negociaci_n__c
            WHERE ID IN :infNegIDList
        ]);

        return infNegMap;
    }

    private static Boolean obtenerValidacion() {
        List<Profile> profList = [
            SELECT Name
            FROM Profile
            WHERE ID =: UserInfo.getProfileId()
        ];

        List<Omitir_validaci_n_despachado__mdt> validacion = [
            SELECT ID
            FROM Omitir_validaci_n_despachado__mdt
            WHERE MasterLabel = 'OMITIR VALIDACION' AND Activo__c = true
        ];

        Boolean omitirValidacion = false;
        
        if (!validacion.isEmpty() && (profList[0].Name == 'System Administrator' || profList[0].Name == 'Administrador del sistema')) {
            omitirValidacion = true;
        }

        return omitirValidacion;
    }
}