force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Codigo_de_parte__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_parte__c</fullName>
    <formula>Accesorio__r.CodigoParte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de parte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Codigo_equivalente__c.field-meta.xml
<CustomField>
    <fullName>Codigo_equivalente__c</fullName>
    <formula>Accesorio__r.CodParteEquivalente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código equivalente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Solicitar_Accesorio_Equivalente__c.field-meta.xml
<CustomField>
    <fullName>Solicitar_Accesorio_Equivalente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitar accesorio equivalente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Consecutivo_del_Informe__c.field-meta.xml
<CustomField>
    <fullName>Consecutivo_del_Informe__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Consecutivo del Informe</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActualizarAccesoriosSolicitados.cls
public without sharing class ActualizarAccesoriosSolicitados {
    @future(callout=true)
    public static void ActualizarAccesoriosSolicitados(String idInforme) {
        List<Accesorios_del_informe__c> accInfList = new List<Accesorios_del_informe__c>();
        List<Accesorios_del_informe__c> accesoriosToUpdate = new List<Accesorios_del_informe__c>();
        Map<String, ProcesaGetAccesoriosSolicitados.wAccesoriosSolicitados> wrapperPorCodigo = new Map<String, ProcesaGetAccesoriosSolicitados.wAccesoriosSolicitados>(); 

        if (idInforme == 'Todos') {
            accInfList = 
                [SELECT Id, Codigo_de_parte__c, InformeNegociacion__r.Consecutivo_del_Informe__c, Estado__c, Codigo_equivalente__c, Solicitar_Accesorio_Equivalente__c 
                FROM Accesorios_del_informe__c 
                WHERE Estado__c != 'Solicitado' AND InformeNegociacion__r.Oportunidad__r.Stagename != 'Cerrada perdida' AND InformeNegociacion__r.Oportunidad__r.Stagename != 'Cerrada ganada'
                ];
        } else if (String.isNotBlank(idInforme)) {
            accInfList = 
                [SELECT Id, Codigo_de_parte__c, InformeNegociacion__r.Consecutivo_del_Informe__c, Estado__c, Codigo_equivalente__c, Solicitar_Accesorio_Equivalente__c 
                FROM Accesorios_del_informe__c 
                WHERE Estado__c != 'Solicitado' AND InformeNegociacion__c =: idInforme AND InformeNegociacion__r.Oportunidad__r.Stagename != 'Cerrada perdida' 
                        AND InformeNegociacion__r.Oportunidad__r.Stagename != 'Cerrada ganada'
                ];
        }
        
        if (!accInfList.isEmpty()) {
            List<ProcesaGetAccesoriosSolicitados.wAccesoriosSolicitados> wAccSoliList = ProcesaGetAccesoriosSolicitados.getAccesoriosSolicitados();  
            
            for (ProcesaGetAccesoriosSolicitados.wAccesoriosSolicitados wrapp : wAccSoliList) {
                wrapperPorCodigo.put(wrapp.codigoParte.trim() + '_' + wrapp.consecutivoInforme.trim(), wrapp);
            }
            
            for (Accesorios_del_informe__c acc : accInfList) {
                String nameINFNeg = '';
                String accBusqueda = '';

                if (acc.InformeNegociacion__r.Consecutivo_del_Informe__c.isNumeric()) {
                    nameINFNeg = '' + Decimal.valueOf(acc.InformeNegociacion__r.Consecutivo_del_Informe__c);
                }

                if (acc.Solicitar_Accesorio_Equivalente__c) {
                    accBusqueda = acc.Codigo_equivalente__c;
                } else {
                    accBusqueda = acc.Codigo_de_parte__c;
                }

                System.debug(accBusqueda + '_' + nameINFNeg);

                if (wrapperPorCodigo.containsKey(accBusqueda + '_' + nameINFNeg)) {
                    acc.Estado__c = 'Solicitado';
                    accesoriosToUpdate.add(acc);
                }
            }

            if (!accesoriosToUpdate.isEmpty()) {
                update accesoriosToUpdate;
            }
        }
    }
}