force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/InformeSincronizado__c.field-meta.xml
<CustomField>
    <fullName>InformeSincronizado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Informe sincronizado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/XML__c.field-meta.xml
<CustomField>
    <fullName>XML__c</fullName>
    <label>XML</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProcesaWSInsertaObjetoInformeNegociacion.cls
public class ProcesaWSInsertaObjetoInformeNegociacion {
    
    public static void insertaObjeto (String xmlRequest, String IdInfNeg){

        Boolean solicitudOK = true;

        WS_InformeNegociaciones.wsInformeNegociacionPort port = new WS_InformeNegociaciones.wsInformeNegociacionPort();
        port.timeout_x = 120000;

        String resp = port.InsertarObjeto(Label.strKey, Label.strApp, Label.strModulo,xmlRequest, 0, 0, 0, '');
        System.debug('res ProcesaWSInsertaObjetoInformeNegociacion: ' + resp);
        
        List<Informe_de_Negociaci_n__c> informe = 
            [SELECT ID, InformeSincronizado__c, XML__c 
            FROM Informe_de_Negociaci_n__c 
            WHERE Id =: IdInfNeg
            ];

        List<Accesorios_del_informe__c> accesoriosList = 
            [SELECT ID, Estado__c 
            FROM Accesorios_del_informe__c 
            WHERE InformeNegociacion__c =: IdInfNeg
            AND Estado__c != 'Despachado'
            ];    
        
        
        if (resp == 'Bien') {
            if (!accesoriosList.isEmpty()) {
                for (Accesorios_del_informe__c acc : accesoriosList) {
                    if(acc.Estado__c == 'No solicitado' || String.isBlank(acc.Estado__c)) {
                        acc.Estado__c = 'Solicitado';
                    }
                }

                informe[0].InformeSincronizado__c = true;
                informe[0].XML__c = xmlRequest + '\n\n RESPUESTA WS: ' + resp ;

                update informe;
                update accesoriosList;
            }
        } else {
            if(!informe.isEmpty()) {
            	informe[0].XML__c = xmlRequest + '\n\n RESPUESTA WS: ' + resp ;
                update informe;    
            }
        }
	}
}