force-app/main/default/objects/Accesorios_del_informe__c/Accesorios_del_informe__c.object-meta.xml
<CustomObject>
    <label>Accesorios del informe</label>
    <nameField>
        <displayFormat>AccInf-{00000000}</displayFormat>
        <label>Nombre de Accesorios del informe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Combo</label>
    <referenceTo>CombosDeInformeDeNegociacion__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No solicitado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Despachado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accesorios_del_informe__c/fields/InformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>InformeNegociacion__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Accesorios del informe</relationshipLabel>
    <relationshipName>Accesorios_del_informe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccesoriosComboParaNegociacion__c/AccesoriosComboParaNegociacion__c.object-meta.xml
<CustomObject>
    <label>Accesorio del combo para negociación</label>
    <nameField>
        <displayFormat>ACN-{000000000}</displayFormat>
        <label>Nombre de Aceesorios del combo para nego</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del combo para negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccesoriosComboParaNegociacion__c/fields/Accesorio__c.field-meta.xml
<CustomField>
    <fullName>Accesorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accesorio</label>
    <referenceTo>Accesorios__c</referenceTo>
    <relationshipName>Accesorios_del_combo_para_negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccesoriosComboParaNegociacion__c/fields/Combo_del_informe__c.field-meta.xml
<CustomField>
    <fullName>Combo_del_informe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Combo del informe</label>
    <referenceTo>CombosDeInformeDeNegociacion__c</referenceTo>
    <relationshipName>Accesorios_del_combo_para_negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Combo__c/Combo__c.object-meta.xml
<CustomObject>
    <label>Combo</label>
    <nameField>
        <label>Nombre de Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/CombosDeInformeDeNegociacion__c.object-meta.xml
<CustomObject>
    <label>Combos del informe</label>
    <nameField>
        <label>Nombre de Informe / Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <label>Combo</label>
    <referenceTo>Combo__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccesoriosComboParaNegociacionHelper.cls
public with sharing class AccesoriosComboParaNegociacionHelper {

    public static void crearAccesoriosDelInforme(
        List<AccesoriosComboParaNegociacion__c> combosDeAccesorioNuevo
    ) {

        List<ID> combosID = new List<ID>();

        for (AccesoriosComboParaNegociacion__c accesoriosCombo : combosDeAccesorioNuevo) {
            if (!combosID.contains(accesoriosCombo.Combo_del_informe__c)) {
                combosID.add(accesoriosCombo.Combo_del_informe__c);
            }
        }
        
        Map<ID, CombosDeInformeDeNegociacion__c> combosByID = 
                                new Map<ID, CombosDeInformeDeNegociacion__c>(
                                        [SELECT Informe_de_Negociaci_n__c 
                                        FROM CombosDeInformeDeNegociacion__c 
                                        WHERE ID IN :combosID]                          
                                );
        
        List<Accesorios_del_informe__c> accesoriosInfList = new List<Accesorios_del_informe__c> ();

        for (AccesoriosComboParaNegociacion__c accCN : combosDeAccesorioNuevo) {
                Accesorios_del_informe__c accInf = new Accesorios_del_informe__c();
                accInf.Accesorio__c = accCN.Accesorio__c;
                accInf.Cantidad__c = accCN.Cantidad__c;
                accInf.Combo__c = accCN.Combo_del_informe__c;
                accInf.InformeNegociacion__c = combosByID.get(accCN.Combo_del_informe__c).Informe_de_Negociaci_n__c;
                accInf.Descripcion__c = accCN.Descripcion__c;
                accInf.Estado__c = 'No solicitado';
                accesoriosInfList.add(accInf);
        }
        
        insert accesoriosInfList;

        for(Accesorios_del_informe__c accInforme : accesoriosInfList){
            try {
                CtrlConsultaDisponibilidadAccesorios.validaDisponibilidadFROMAccesoriosDelComboParaInforme(
                                                                ''+accInforme.InformeNegociacion__c
                );
            } catch (Exception e) {
                if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION,' 
                                            + ' El informe se encuentra en el estado')) {
                    accInforme.addError('Los accesorios no pudieron ser agregados al informe de negociación,' 
                            + ' ya que este se encuentra en un estado donde ya no es posible agregar esta acción'
                    );
                }
            }
        }
    }
}