force-app/main/default/objects/Estructura_Organizacional__c/Estructura_Organizacional__c.object-meta.xml
<CustomObject>
    <label>Estructura Organizacional</label>
    <nameField>
        <displayFormat>EstOrg-{000000000}</displayFormat>
        <label>Nombre de Estructura Organizacional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estructura Organizacional</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estructura_Organizacional__c/fields/CodCompania__c.field-meta.xml
<CustomField>
    <fullName>CodCompania__c</fullName>
    <label>Código de la compañía</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estructura_Organizacional__c/fields/CodSucursal__c.field-meta.xml
<CustomField>
    <fullName>CodSucursal__c</fullName>
    <label>Código de la sucursal</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estructura_Organizacional__c/fields/CodUnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>CodUnidadNegocio__c</fullName>
    <label>Código de la unidad de negocio</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estructura_Organizacional__c/fields/Compania__c.field-meta.xml
<CustomField>
    <fullName>Compania__c</fullName>
    <label>Nombre de la compañia</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estructura_Organizacional__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Nombre de la sucursal</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estructura_Organizacional__c/fields/UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadNegocio__c</fullName>
    <label>Nombre de la unidad de negocio</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcesaWS_EstructuraOrganizacional.cls
public class ProcesaWS_EstructuraOrganizacional {
    
    public static void getEstructuras (){
        
        List<String> errorsList = new List<String>();
        List <Estructura_Organizacional__c> estListInsert = new List<Estructura_Organizacional__c>();
        
        HttpResponse response;
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        //QA
        //request.setEndpoint('http://ap1.casapellas.com.ni:9089/GCPWSREST/gcpwsrest/EOrganizacionalRest/GetEOrganizacional');  
        request.setEndpoint(Label.URL_WS_EstructuraOrganizacional);  
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('key', Label.strKey);
        request.setHeader('app', Label.strApp);
        request.setHeader('mod', Label.strModulo);
        
        try{
        	response = http.send(request);
            
            if (response.getStatusCode() != 201) {
                System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
            } else {
               	System.debug('RESPUESTA: ' + response.getBody());
                List<ObjResponseEstructuraOrg> estList = ObjResponseEstructuraOrg.parse(response.getBody());
                
                if(estList.size()>0){
                    for(ObjResponseEstructuraOrg est: estList){
                        estListInsert.add(new Estructura_Organizacional__c(CodCompania__c = est.codcompania, Compania__c= est.compania, CodUnidadNegocio__c = est.codunidadnegocio, UnidadNegocio__c = est.unidadnegocio, CodSucursal__c = est.codsucursal, Sucursal__c = est.sucursal));
                    }
                    
                    if(estListInsert.size()>0){
                        Database.SaveResult[] srList  = Database.insert(estListInsert, false);
                
                        for (Database.SaveResult sr : srList) {
                            if (sr.isSuccess()){
                                
                            }else {
                                for(Database.Error err : sr.getErrors()) {
                                    System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                                    System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                                    
                                    errorsList.add('Ha ocurrido un error en la UDC:' + err.getStatusCode() + ': ' + err.getMessage() + '\n' + 'Los campos que interfieren en el error son: ' + err.getFields()+ '\n\n');
                                    
                                }
                            }
                       } 
                    
                        if(errorsList.size()>0){
                            //ProcesaWSClientes.notificaLlamadoWS(errorsList);
                        }
                    }
                }
                //ObjResponsePromedioKg_M3 ObjRAE = ObjResponsePromedioKg_M3.parse(response.getBody());
            }
            
            //generaSolicitudEmail(generaJSONBody(dateoutput));
            //generaSolicitudEmail(response.getBody());
            //generaSolicitudEmail(generaJSONBody(dateoutput));
            
        }catch (CallOutException ex){/*generaSolicitudEmail('Hubo una excepcion: ' + ex.getMessage() +', '+ ex.getStackTraceString());*/}
    }

}