force-app/main/default/objects/Grupo_Agentes__c/Grupo_Agentes__c.object-meta.xml
<CustomObject>
    <description>Se utilizan para agregar los usuarios a las asignaciones de oportunidades</description>
    <label>Grupos Agentes</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Nombre de Grupos Agentes</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos Agentes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grupo_Agentes__c/fields/Activo_para_Oportunidades__c.field-meta.xml
<CustomField>
    <fullName>Activo_para_Oportunidades__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo para Oportunidades</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grupo_Agentes__c/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Grupo</label>
    <referenceTo>Grupo_Oportunidades__c</referenceTo>
    <relationshipLabel>Grupos Agentes</relationshipLabel>
    <relationshipName>Grupos_Agentes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grupo_Oportunidades__c/Grupo_Oportunidades__c.object-meta.xml
<CustomObject>
    <label>Grupo Oportunidades</label>
    <nameField>
        <label>Nombre de Grupos Oportunidades</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos Oportunidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoundRobin__c/RoundRobin__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Utilizado para asignar agentes por Round Robin a las oportunidades</description>
    <label>RoundRobin</label>
</CustomObject>

force-app/main/default/objects/RoundRobin__c/fields/IndexOfLastUsed__c.field-meta.xml
<CustomField>
    <fullName>IndexOfLastUsed__c</fullName>
    <label>IndexOfLastUsed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RoundRobin__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>ObjectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/asignarGestor_Test.cls
@Istest (seealldata= true)
public class asignarGestor_Test {
    
    @istest
    public static void Test(){
        List<asignarGestor.RoundRobinAssignment> ra = new List<asignarGestor.RoundRobinAssignment>();
        
        RoundRobin__c rr = [SELECT id, GroupName__c, FieldName__c, Object__c, IndexOfLastUsed__c FROM RoundRobin__c WHERE  GroupName__c = 'Bancario'];
        
        asignarGestor.RoundRobinAssignment ra2 = new asignarGestor.RoundRobinAssignment();
        ra2.groupName = 'Bancario';
        ra2.recordId = rr.Id;
            
        ra.add(ra2);
            
        asignarGestor.assign(ra);
                
    }
    
    @istest
    public static void assignTest(){
        List<asignarGestor.RoundRobinAssignment> ra = new List<asignarGestor.RoundRobinAssignment>();
        
        RoundRobin__c rr = 
            [SELECT id, GroupName__c, FieldName__c, Object__c, IndexOfLastUsed__c 
             FROM RoundRobin__c 
             WHERE GroupName__c = 'Bancario'
            ];
        
        Grupo_Oportunidades__c go = new Grupo_Oportunidades__c();
        go.Name = 'Bancario';
        insert go;
        
        Grupo_Agentes__c ga = new Grupo_Agentes__c();
        ga.Activo_para_Oportunidades__c = true;
        ga.grupo__c = go.ID;
        insert ga;
        
        asignarGestor.RoundRobinAssignment ra2 = new asignarGestor.RoundRobinAssignment();
        ra2.groupName = 'Bancario';
        ra2.recordId = rr.Id;
        ra.add(ra2);
            
        asignarGestor.assign(ra);
                
    }

}