force-app/main/default/objects/Opportunity/recordTypes/Principal_Autolote.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autolote</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal Autolote</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VehiculoDeLaOportunidadHelper.cls
public without sharing class VehiculoDeLaOportunidadHelper {
    public static void crearCotizacion(List<Vehiculo_de_la_Oportunidad__c> vehiculoList) {
        ID principalAutoloteId = Schema.SObjectType.Opportunity
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Principal_Autolote')
                                    .getRecordTypeId();
        
        List<Quote> quotesList = new List<Quote>();
        Set<Id> oppIdLista = new Set<Id>();

        for (Vehiculo_de_la_Oportunidad__c vehiculo : vehiculoList) {
            oppIdLista.add(vehiculo.Oportunidad__c);
        }

        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([
            SELECT RecordTypeId, Name, Id
            FROM Opportunity
            WHERE Id IN :oppIdLista
        ]);

        for (Vehiculo_de_la_Oportunidad__c vehiculo : vehiculoList) {
            if (oppMap.containsKey(vehiculo.Oportunidad__c)) {
                Opportunity oppPadre = oppMap.get(vehiculo.Oportunidad__c);
                if (oppPadre.RecordTypeId == principalAutoloteId) {
    
                    Quote q = new Quote();
                    q.Name = oppPadre.Name;
                    q.Vehiculo__c = vehiculo.Vehiculo__c;
                    q.OpportunityId = oppPadre.Id;
                    q.ExpirationDate = Date.today().addDays(10);
                    quotesList.add(q);
                }
            }
        }

        if (!quotesList.isEmpty()) {
            insert quotesList;
        }
    }

    public static void liberarVehiculos(List<Vehiculo_de_la_Oportunidad__c> vehiculoList) {
        List<Id> vehiculoIdList = new List<Id>();

        for (Vehiculo_de_la_Oportunidad__c vehOpp : vehiculoList) {
            vehiculoIdList.add(vehOpp.Vehiculo__c);
        }

        List<Vehiculo__c> vehList = [
            SELECT Estado__c 
            FROM Vehiculo__c 
            WHERE Id IN :vehiculoIdList
        ];

        for (Vehiculo__c v : vehList) {
            v.Estado__c = 'Libre';
        }

        if (!vehList.isEmpty()) {
            update vehList;
        }
    }
}