force-app/main/default/objects/Lead/fields/Cedula_Nro__c.field-meta.xml
<CustomField>
    <fullName>Cedula_Nro__c</fullName>
    <label>Cedula Nro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_a_cotizar__c.field-meta.xml
<CustomField>
    <fullName>Marca_a_cotizar__c</fullName>
    <label>Marca a cotizar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Autolote</fullName>
            </value>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BYD</fullName>
            </value>
            <value>
                <fullName>Mercedes Benz</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Modelo_a_cotizar__c.field-meta.xml
<CustomField>
    <fullName>Modelo_a_cotizar__c</fullName>
    <label>Modelo a cotizar</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Marca_a_cotizar__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agya</fullName>
            </value>
            <value>
                <fullName>Yaris</fullName>
            </value>
            <value>
                <fullName>Yaris Hatchback</fullName>
            </value>
            <value>
                <fullName>Corolla</fullName>
            </value>
            <value>
                <fullName>Prius</fullName>
            </value>
            <value>
                <fullName>Camry</fullName>
            </value>
            <value>
                <fullName>Rush</fullName>
            </value>
            <value>
                <fullName>Fortuner</fullName>
            </value>
            <value>
                <fullName>Rav4</fullName>
            </value>
            <value>
                <fullName>Prado</fullName>
            </value>
            <value>
                <fullName>Landcruiser SW</fullName>
            </value>
            <value>
                <fullName>Hilux 2.4 4x2</fullName>
            </value>
            <value>
                <fullName>Hilux 2.4 4x4</fullName>
            </value>
            <value>
                <fullName>Hilux 2.8 4x4</fullName>
            </value>
            <value>
                <fullName>Tacoma</fullName>
            </value>
            <value>
                <fullName>Tundra</fullName>
            </value>
            <value>
                <fullName>Land Cruiser Pickup cabina sencilla</fullName>
            </value>
            <value>
                <fullName>Land Cruiser Pickup cabina doble</fullName>
            </value>
            <value>
                <fullName>Hiace bus</fullName>
            </value>
            <value>
                <fullName>Hiace</fullName>
            </value>
            <value>
                <fullName>Coaster</fullName>
            </value>
            <value>
                <fullName>Dyna</fullName>
            </value>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Celerio</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Dzire</fullName>
            </value>
            <value>
                <fullName>S-presso</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Vitara</fullName>
            </value>
            <value>
                <fullName>XL7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Anfitrion.recordType-meta.xml
<RecordType>
    <fullName>Anfitrion</fullName>
    <active>true</active>
    <businessProcess>Proceso de leads para Anfitrión</businessProcess>
    <label>Anfitrión</label>
</RecordType>

force-app/main/default/classes/notificarLeadsAnfitrionTest.cls
@IsTest
public class notificarLeadsAnfitrionTest {
    @IsTest
    public static void ejecutaWSProductosDia(){
        ID anfitrionId = Schema.SObjectType.Lead
                            .getRecordTypeInfosByDeveloperName()
                            .get('Anfitrion')
                            .getRecordTypeId();

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Vendedor'];
        
        User u = new User();
        u.Alias = 'TestUser';
        u.Email = 'test@email.com';
        u.EmailEncodingKey = 'UTF-8';
        u.LastName = 'Testing'; 
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US'; 
        u.ProfileId = p.Id;
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.UserName = 'test@email.com.casapellas';
        
        insert u;
        
        Lead ld = new Lead();
        ld.FirstName = 'FirstName';
        ld.MiddleName = 'MiddleName';
        ld.LastName = 'LastName';
        ld.Email = 'email@email.com';
        ld.Phone = '+505512345678';
        ld.Cedula_Nro__c = 'cedula123';
        ld.LeadSource = 'Presencial';
        ld.Status = 'Contacto exitoso';
        ld.Marca_a_cotizar__c = 'Toyota';
        ld.Modelo_a_cotizar__c = 'Corolla';
        ld.RecordTypeId = anfitrionId;
        ld.OwnerId = u.Id;
        insert ld;
        
        Test.setCreatedDate(ld.Id, Date.today().addDays(-1));

        SchedulableContext sc = null;
        notificarLeadsAnfitrion x = new notificarLeadsAnfitrion();

        Test.startTest();
        x.execute(sc);
        Test.stopTest();
    }
}