force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Avaluo.recordType-meta.xml
<RecordType>
    <fullName>Avaluo</fullName>
    <active>true</active>
    <businessProcess>Avaluo</businessProcess>
    <label>Avalúo</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Autolote.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autolote</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal Autolote</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Anio_opcion__c.field-meta.xml
<CustomField>
    <fullName>Anio_opcion__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>1984</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VehiculoDeLaOportunidadTriggerTest.cls
@isTest
public without sharing class VehiculoDeLaOportunidadTriggerTest {
    @TestSetup
    public static void crearOportunidad() {
        ID principalAutoloteId = Schema.SObjectType.Opportunity
                .getRecordTypeInfosByDeveloperName()
                .get('Principal_Autolote')
                .getRecordTypeId();

        ID avaluoId = Schema.SObjectType.Opportunity
                .getRecordTypeInfosByDeveloperName()
                .get('Avaluo')
                .getRecordTypeId();
        

        Opportunity oppAutolote = new Opportunity();
        oppAutolote.CloseDate = Date.today().addDays(7);
        oppAutolote.StageName = 'Contacto exitoso';
        oppAutolote.RecordTypeId = principalAutoloteId;
        oppAutolote.Name = 'TEST';
        insert oppAutolote;

        Opportunity avaluoOpp = new Opportunity();
        avaluoOpp.CloseDate = Date.today().addDays(7);
        avaluoOpp.StageName = 'Esperando contacto';
        avaluoOpp.RecordTypeId = avaluoId;
        avaluoOpp.Name = 'AVALUO/';
        insert avaluoOpp;
    }

    @isTest
    public static void crearPresupuestoAutolote(){
        Opportunity opp = [
            SELECT Id, Name
            FROM Opportunity
            WHERE RecordType.DeveloperName = 'Principal_Autolote'
        ];

        Vehiculo__c vehiculo = new Vehiculo__c();
        vehiculo.Anio_opcion__c = '2021';
        vehiculo.Chasis__c = '123456789abcdefgh';
        vehiculo.Estado__c = 'Libre';
        insert vehiculo;

        Vehiculo_de_la_Oportunidad__c vehiculoOpp = new Vehiculo_de_la_Oportunidad__c();
        vehiculoOpp.Oportunidad__c = opp.Id;
        vehiculoOpp.Vehiculo__c = vehiculo.Id;

        Test.startTest();
        Database.SaveResult sr = Database.insert(vehiculoOpp, false);
        Test.stopTest();

        Vehiculo__c vehiculoSeteado = [
            SELECT Name
            FROM Vehiculo__c
            WHERE Id =: vehiculo.Id
            LIMIT 1
        ];

        List<Quote> qList = [
            SELECT Id, Name, OpportunityId, ExpirationDate 
            FROM Quote
            WHERE Vehiculo__c =: vehiculo.Id
        ];

        System.assertEquals(true, sr.isSuccess(), 'La insercion del objeto junction esta fallando cuando no deberia');
        System.assertEquals(false, qList.isEmpty(), 'No se esta creando una cotizacion cuando deberia');
        System.assertEquals(opp.Name, qList[0].Name, 'El nombre no se setea correctamente');
        System.assertEquals(opp.Id, qList[0].OpportunityId, 'La oportunidad no se esta seteando correctamente');
        System.assertEquals(Date.today().addDays(7), qList[0].ExpirationDate, 'La fecha de expiracion no se esta seteando como deberia');
    }

    @isTest
    public static void noCrearPresupuestoUsado(){
        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            WHERE RecordType.DeveloperName = 'Avaluo'
        ];

        Vehiculo__c vehiculo = new Vehiculo__c();
        vehiculo.Anio_opcion__c = '2021';
        vehiculo.Chasis__c = '123456789abcdefgh';
        vehiculo.Estado__c = 'Libre';
        insert vehiculo;

        Vehiculo_de_la_Oportunidad__c vehiculoOpp = new Vehiculo_de_la_Oportunidad__c();
        vehiculoOpp.Oportunidad__c = opp.Id;
        vehiculoOpp.Vehiculo__c = vehiculo.Id;

        Test.startTest();
        Database.SaveResult sr = Database.insert(vehiculoOpp, false);
        Test.stopTest();

        List<Quote> qList = [
            SELECT Id 
            FROM Quote
            WHERE Vehiculo__c =: vehiculo.Id
        ];

        System.assertEquals(true, sr.isSuccess(), 'La insercion del objeto junction esta fallando cuando no deberia');
        System.assertEquals(true, qList.isEmpty(), 'Se esta creando una cotizacion cuando no deberia');
    }

    @isTest
    public static void eliminarVehiculoDeLaOportunidad() {

        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            WHERE RecordType.DeveloperName = 'Principal_Autolote'
        ];

        Vehiculo__c vehiculo = new Vehiculo__c();
        vehiculo.Anio_opcion__c = '2021';
        vehiculo.Chasis__c = '123456789abcdefgh';
        vehiculo.Estado__c = 'Libre';
        insert vehiculo;

        Vehiculo_de_la_Oportunidad__c vehiculoOpp = new Vehiculo_de_la_Oportunidad__c();
        vehiculoOpp.Oportunidad__c = opp.Id;
        vehiculoOpp.Vehiculo__c = vehiculo.Id;
        insert vehiculoOpp;

        Test.startTest();
        Database.DeleteResult dr = Database.delete(vehiculoOpp, false);
        Test.stopTest();

        Vehiculo__c vehiculoActualizado = [
            SELECT Estado__c
            FROM Vehiculo__c 
            WHERE Id =: vehiculo.Id 
        ];

        System.assertEquals(true, dr.isSuccess(), 'La eliminacion esta fallando cuando no deberia');
        System.assertEquals('Libre', vehiculoActualizado.Estado__c, 'El estado del vehiculo no se esta seteando correctamente');
    }
}