force-app/main/default/objects/Opportunity/fields/Detalle_de_perdida__c.field-meta.xml
<CustomField>
    <fullName>Detalle_de_perdida__c</fullName>
    <label>Detalle de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razon_perdida__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Situacion politica/economica</fullName>
                <label>Situación política/económica</label>
            </value>
            <value>
                <fullName>Problemas personales</fullName>
            </value>
            <value>
                <fullName>Compro otra marca (Ext)</fullName>
                <label>Compró otra marca (Ext)</label>
            </value>
            <value>
                <fullName>Compro usado</fullName>
                <label>Compró usado</label>
            </value>
            <value>
                <fullName>No compro</fullName>
                <label>No compró</label>
            </value>
            <value>
                <fullName>Credex</fullName>
            </value>
            <value>
                <fullName>CrediQ</fullName>
            </value>
            <value>
                <fullName>Leasing AN</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Compró nuevo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_detalle_de_perdida__c.field-meta.xml
<CustomField>
    <fullName>Marca_detalle_de_perdida__c</fullName>
    <label>Marca detalle de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Detalle_de_perdida__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Hyundai - Deshon</fullName>
            </value>
            <value>
                <fullName>Hyundai - Excel</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mitsubichi</fullName>
            </value>
            <value>
                <fullName>Isuzu</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Toyota - CP</fullName>
            </value>
            <value>
                <fullName>Toyota -AN</fullName>
            </value>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Razon_perdida__c.field-meta.xml
<CustomField>
    <fullName>Razon_perdida__c</fullName>
    <label>Razón principal de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cliente no contesta</fullName>
            </value>
            <value>
                <fullName>Cliente sólo quería saber información</fullName>
            </value>
            <value>
                <fullName>No aplica a financiamiento</fullName>
            </value>
            <value>
                <fullName>Cliente Pospone Compra</fullName>
            </value>
            <value>
                <fullName>Ya atendido por otro vendedor</fullName>
            </value>
            <value>
                <fullName>Precio/Extras</fullName>
            </value>
            <value>
                <fullName>Inventario/Tiempo de entrega</fullName>
            </value>
            <value>
                <fullName>Disenio/Atributos</fullName>
                <label>Diseño/Atributos</label>
            </value>
            <value>
                <fullName>Facilidad credito competencia</fullName>
                <label>Facilidad crédito competencia</label>
            </value>
            <value>
                <fullName>Cliente no brinda datos UAF</fullName>
            </value>
            <value>
                <fullName>Oportunidad Duplicada</fullName>
            </value>
            <value>
                <fullName>Cliente en Lista Negra</fullName>
            </value>
            <value>
                <fullName>Cambio de Nombre/Razon social</fullName>
                <label>Cambio de Nombre/Razón social</label>
            </value>
            <value>
                <fullName>Se sintio mejor atendido en otra empresa</fullName>
                <label>Se sintió mejor atendido en otra empresa</label>
            </value>
            <value>
                <fullName>Falta de seguimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OportunidadCerradaController.cls
public class OportunidadCerradaController {

    @AuraEnabled
    public static List<String> obtenerPickList() {
        List<String> picklistOptions = new List<String>();

        Schema.DescribeFieldResult field = Opportunity.Razon_perdida__c.getDescribe();

        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            if (f.getLabel() != 'Oportunidad Duplicada' && f.getLabel() != 'Cliente en Lista Negra') {
                picklistOptions.add(f.getLabel());
            }
        }


        return picklistOptions;
    }

    @AuraEnabled
    public static List<String> obtenerDetalle(String razon) {
        List<String> picklistOptions = new List<String>();

        Schema.DescribeFieldResult F = Opportunity.Detalle_de_perdida__c.getDescribe();
        Schema.sObjectField T = F.getSObjectField();

        Map<String, List<String>> mapaDependencias = getDependentPicklistValues(T);

        for (String key : mapaDependencias.keySet()) {
            if (key == razon) {
                picklistOptions = mapaDependencias.get(key);
            }
        }

        return picklistOptions;
    }

    @AuraEnabled
    public static List<String> obtenerMarcas(String detalle) {
        List<String> picklistOptions = new List<String>();

        Schema.DescribeFieldResult F = Opportunity.Marca_detalle_de_perdida__c.getDescribe();
        Schema.sObjectField T = F.getSObjectField();

        Map<String, List<String>> mapaDependencias = getDependentPicklistValues(T);

        for (String key : mapaDependencias.keySet()) {
            if (key == detalle) {
                picklistOptions = mapaDependencias.get(key);
            }
        }

        return picklistOptions;
    }

    @AuraEnabled
    public static String setearRazonPerdida(String idOpp, String razon, String detalle, String marca){
        List<Opportunity> oppList = 
            [SELECT ID, Razon_perdida__c, Detalle_de_perdida__c, Marca_detalle_de_perdida__c
            FROM Opportunity
            WHERE ID =: idOpp
            LIMIT 1
            ];

        System.debug(razon);

        if (!oppList.isEmpty()) {
            oppList[0].Razon_perdida__c = razon;
            
            if (String.isNotBlank(detalle)) {
                oppList[0].Detalle_de_perdida__c = detalle;
            }
            
            if (String.isNotBlank(marca)) {
                oppList[0].Marca_detalle_de_perdida__c = marca;
            }

            List<Database.SaveResult> srList = Database.update(oppList, false);

            if (!srList[0].isSuccess()) {
                return 'Error: ' + srList[0].getErrors()[0].getMessage();
            } else {
                return 'Bien';
            }
        } else {
            return 'Error: No se han encontrado oportunidades';
        }
    }

    public static Map<String, List<String>> getDependentPicklistValues(Schema.sObjectField dependToken) {
        Schema.DescribeFieldResult depend = dependToken.getDescribe();
        Schema.sObjectField controlToken = depend.getController();
        if (controlToken == null) {
            return new Map<String, List<String>>();
        }
     
        Schema.DescribeFieldResult control = controlToken.getDescribe();
        List<Schema.PicklistEntry> controlEntries;
        if(control.getType() != Schema.DisplayType.Boolean) {
            controlEntries = control.getPicklistValues();
        }
     
        String base64map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        Map<String,List<String>> dependentPicklistValues = new Map<String,List<String>>();
        for (Schema.PicklistEntry entry : depend.getPicklistValues()) {
            if (entry.isActive() && String.isNotEmpty(String.valueOf(((Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(entry))).get('validFor')))) {
                List<String> base64chars =
                        String.valueOf(((Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(entry))).get('validFor')).split('');
                for (Integer index = 0; index < (controlEntries != null ? controlEntries.size() : 2); index++) {
                    Object controlValue =
                            (controlEntries == null
                                    ?   (Object) (index == 1)
                                    :   (Object) (controlEntries[index].isActive() ? controlEntries[index].getLabel() : null)
                            );
                    Integer bitIndex = index / 6;
                    if (bitIndex > base64chars.size() - 1) {
                        break;
                    }
                    Integer bitShift = 5 - Math.mod(index, 6);
                    if  (controlValue == null || (base64map.indexOf( base64chars[ bitIndex ] ) & (1 << bitShift)) == 0)
                        continue;
                    if (!dependentPicklistValues.containsKey((String) controlValue)) {
                        dependentPicklistValues.put((String) controlValue, new List<String>());
                    }
                    dependentPicklistValues.get((String) controlValue).add(entry.getLabel());
                }
            }
        }
        return dependentPicklistValues;
    }
}