force-app/main/default/objects/Opportunity/fields/Detalle_de_perdida__c.field-meta.xml
<CustomField>
    <fullName>Detalle_de_perdida__c</fullName>
    <label>Detalle de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razon_perdida__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Situacion politica/economica</fullName>
                <label>Situación política/económica</label>
            </value>
            <value>
                <fullName>Problemas personales</fullName>
            </value>
            <value>
                <fullName>Compro otra marca (Ext)</fullName>
                <label>Compró otra marca (Ext)</label>
            </value>
            <value>
                <fullName>Compro usado</fullName>
                <label>Compró usado</label>
            </value>
            <value>
                <fullName>No compro</fullName>
                <label>No compró</label>
            </value>
            <value>
                <fullName>Credex</fullName>
            </value>
            <value>
                <fullName>CrediQ</fullName>
            </value>
            <value>
                <fullName>Leasing AN</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Compró nuevo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_detalle_de_perdida__c.field-meta.xml
<CustomField>
    <fullName>Marca_detalle_de_perdida__c</fullName>
    <label>Marca detalle de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Detalle_de_perdida__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Hyundai - Deshon</fullName>
            </value>
            <value>
                <fullName>Hyundai - Excel</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mitsubichi</fullName>
            </value>
            <value>
                <fullName>Isuzu</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Toyota - CP</fullName>
            </value>
            <value>
                <fullName>Toyota -AN</fullName>
            </value>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Razon_perdida__c.field-meta.xml
<CustomField>
    <fullName>Razon_perdida__c</fullName>
    <label>Razón principal de perdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cliente no contesta</fullName>
            </value>
            <value>
                <fullName>Cliente sólo quería saber información</fullName>
            </value>
            <value>
                <fullName>No aplica a financiamiento</fullName>
            </value>
            <value>
                <fullName>Cliente Pospone Compra</fullName>
            </value>
            <value>
                <fullName>Ya atendido por otro vendedor</fullName>
            </value>
            <value>
                <fullName>Precio/Extras</fullName>
            </value>
            <value>
                <fullName>Inventario/Tiempo de entrega</fullName>
            </value>
            <value>
                <fullName>Disenio/Atributos</fullName>
                <label>Diseño/Atributos</label>
            </value>
            <value>
                <fullName>Facilidad credito competencia</fullName>
                <label>Facilidad crédito competencia</label>
            </value>
            <value>
                <fullName>Cliente no brinda datos UAF</fullName>
            </value>
            <value>
                <fullName>Oportunidad Duplicada</fullName>
            </value>
            <value>
                <fullName>Cliente en Lista Negra</fullName>
            </value>
            <value>
                <fullName>Cambio de Nombre/Razon social</fullName>
                <label>Cambio de Nombre/Razón social</label>
            </value>
            <value>
                <fullName>Se sintio mejor atendido en otra empresa</fullName>
                <label>Se sintió mejor atendido en otra empresa</label>
            </value>
            <value>
                <fullName>Falta de seguimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OportunidadCerradaControllerTest.cls
@isTest
public class OportunidadCerradaControllerTest {
    @TestSetup
    public static void crearOpp(){
        Opportunity opp = new Opportunity();
        opp.CloseDate = Date.today();
        opp.StageName = 'Contacto Exitoso';

        insert opp;
    }

    @IsTest
    public static void obtenerPickListTest(){
        Schema.DescribeFieldResult field = Opportunity.Razon_perdida__c.getDescribe();
        
        Test.startTest();
        List<String> razonesList = OportunidadCerradaController.obtenerPickList();
        Test.stopTest();
        
        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            if (f.getLabel() == 'Oportunidad Duplicada' || f.getLabel() == 'Cliente en Lista Negra') {
                System.AssertEquals(false, razonesList.contains(f.getLabel()), f.getLabel() + ' está incluido en la lista cuando no deberia estarlo');
            } else {
                System.AssertEquals(true, razonesList.contains(f.getLabel()), f.getLabel() + ' no está incluido en la lista cuando deberia estarlo');
            }
        }
    }
    
    @IsTest
    public static void obtenerDetalleTest(){
        List<String> picklistOptions = new List<String>();

        Schema.DescribeFieldResult F = Opportunity.Detalle_de_perdida__c.getDescribe();
        Schema.sObjectField T = F.getSObjectField();

        Map<String, List<String>> mapaDependencias = OportunidadCerradaController.getDependentPicklistValues(T);

        for (String key : mapaDependencias.keySet()) {
            if (key == 'Precio/Extras') {
                picklistOptions = mapaDependencias.get(key);
            }
        }
        
        Test.startTest();
        List<String> razonesList = OportunidadCerradaController.obtenerDetalle('Precio/Extras');
        Test.stopTest();
        
        for (String str : razonesList) {
            System.AssertEquals(true, picklistOptions.contains(str), str + ' no está incluido en la lista de detalles cuando deberia estarlo');
        }
    }
    
    @IsTest
    public static void obtenerMarcasTest(){
        List<String> picklistOptions = new List<String>();

        Schema.DescribeFieldResult F = Opportunity.Marca_detalle_de_perdida__c.getDescribe();
        Schema.sObjectField T = F.getSObjectField();

        Map<String, List<String>> mapaDependencias = OportunidadCerradaController.getDependentPicklistValues(T);

        for (String key : mapaDependencias.keySet()) {
            if (key == 'Compró otra marca (Ext)') {
                picklistOptions = mapaDependencias.get(key);
            }
        }
        
        Test.startTest();
        List<String> razonesList = OportunidadCerradaController.obtenerMarcas('Compró otra marca (Ext)');
        Test.stopTest();
        
        for (String str : razonesList) {
            System.AssertEquals(true, picklistOptions.contains(str), str + ' no está incluido en la lista de detalles cuando deberia estarlo');
        }
    }

    @IsTest
    public static void setearRazonPerdidaTest(){
        List<Opportunity> oppList = 
            [SELECT ID
            FROM Opportunity
            ];

        Test.startTest();
        OportunidadCerradaController.setearRazonPerdida(oppList[0].ID, 'Precio/Extras', 'Compró otra marca (Ext)', 'Nissan');
        Test.stopTest();

        Opportunity oppActualizada = 
            [SELECT Razon_perdida__c, Detalle_de_perdida__c, Marca_detalle_de_perdida__c 
            FROM Opportunity
            WHERE ID =: oppList[0].ID 
            LIMIT 1
            ];

        System.assertEquals('Precio/Extras', oppActualizada.Razon_perdida__c, 'La razón de perdida no se ha actualizado correctamente');
        System.assertEquals('Compró otra marca (Ext)', oppActualizada.Detalle_de_perdida__c, 'El detalle de perdida no se ha actualizado correctamente');
        System.assertEquals('Nissan', oppActualizada.Marca_detalle_de_perdida__c, 'La marca de detalle de perdida no se ha actualizado correctamente');
    }
}