force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTOLOTE</fullName>
            </value>
            <value>
                <fullName>GENESIS</fullName>
            </value>
            <value>
                <fullName>HAOJUE</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>YAMAHA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OportunidadesPorMarcaController.cls
public without sharing class OportunidadesPorMarcaController {
    @AuraEnabled
    public static List<Opportunity> obtenerOportunidades(String cuentaID) {
        ID usuario = UserInfo.getUserId();

        List<String> marcasHabilitadas = new List<String>();

        List<User> usuarioList = 
            [SELECT Marca__c
            FROM User
            WHERE ID =: usuario 
            ];

        if (usuarioList.isEmpty()) {
            return null;
        } else {
            if (String.isNotBlank(usuarioList[0].Marca__c)) {
                marcasHabilitadas = usuarioList[0].Marca__c.split(';');
            }
        }

        List<Opportunity> oppList = 
            [SELECT Name, OwnerID, StageName, Owner.Name
            FROM Opportunity
            WHERE AccountID =: cuentaID
                  AND Marca_UDC__r.Name IN :marcasHabilitadas
                  AND Stagename != 'Cerrada perdida' 
                  AND Stagename != 'Cerrada ganada'
            ];

        System.debug(oppList);

        if (!oppList.isEmpty()) {
            return oppList;
        } else {
            return null;
        }
    }
}