force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/Permitido_para_autolote__c.field-meta.xml
<CustomField>
    <fullName>Permitido_para_autolote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permitido para autolote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/UDC_Padre__c.field-meta.xml
<CustomField>
    <fullName>UDC_Padre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UDC Padre</label>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Catalogos UDC</relationshipLabel>
    <relationshipName>Catalogos_UDC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Submodelo.recordType-meta.xml
<RecordType>
    <fullName>Submodelo</fullName>
    <active>true</active>
    <label>Submodelo</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Oportunidad_original__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad_original__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad original</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Avaluo.recordType-meta.xml
<RecordType>
    <fullName>Avaluo</fullName>
    <active>true</active>
    <businessProcess>Avaluo</businessProcess>
    <label>Avalúo</label>
</RecordType>

force-app/main/default/objects/Orden_de_etapas_por_recordType__mdt/Orden_de_etapas_por_recordType__mdt.object-meta.xml
<CustomObject>
    <label>Orden de etapas por recordType</label>
    <pluralLabel>Ordenes de etapas por recordType</pluralLabel>
</CustomObject>

force-app/main/default/objects/Orden_de_etapas_por_recordType__mdt/fields/Codigo_de_color__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_color__c</fullName>
    <label>Codigo de color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Anio_opcion__c.field-meta.xml
<CustomField>
    <fullName>Anio_opcion__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>1984</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Veh_culos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Kilometraje__c.field-meta.xml
<CustomField>
    <fullName>Kilometraje__c</fullName>
    <label>Kilometraje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Vehiculos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos (Modelo)</relationshipLabel>
    <relationshipName>Vehiculos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Submodelo__c.field-meta.xml
<CustomField>
    <fullName>Submodelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submodelo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Submodelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos (Submodelo)</relationshipLabel>
    <relationshipName>Vehiculos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esteli</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Leon</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/mostrarOportunidadHijo.cls
public without sharing class mostrarOportunidadHijo {
    public static final String etapaInicialAvaluo = 'Esperando Contacto';

    @AuraEnabled
    public static List<Vehiculo_de_la_Oportunidad__c> obtenerHijoAvaluo(String opportunityId) {
        List<Id> oppAvaluosId = new List<Id>();

        for (Opportunity oppAvaluos : [SELECT Id
                                        FROM Opportunity
                                        WHERE Oportunidad_original__c =: opportunityId
                                            AND StageName != 'Cerrada perdida'
                                            AND RecordType.DeveloperName = 'Avaluo'
                                        ]) {
            oppAvaluosId.add(oppAvaluos.Id);
        }

        List<Vehiculo_de_la_Oportunidad__c> vehiculoList = new List<Vehiculo_de_la_Oportunidad__c>();

        if (!oppAvaluosId.isEmpty()) {
            vehiculoList = [
                SELECT Vehiculo__c, Vehiculo__r.Marca__c, Vehiculo__r.Marca__r.Name,
                    Vehiculo__r.Modelo__c, Vehiculo__r.Modelo__r.Name,
                    Vehiculo__r.Placa__c, Oportunidad__c, Oportunidad__r.OwnerId,
                    Oportunidad__r.Owner.Name, Oportunidad__r.StageName
                FROM Vehiculo_de_la_Oportunidad__c
                WHERE Oportunidad__c IN :oppAvaluosId
            ];
        }

        return vehiculoList;
    }

    @AuraEnabled
    public static Map<String, String> obtenerMapaEtapas(){
        Map<String, String> colorPorEtapa = new Map<String, String>();
        
        for (Orden_de_etapas_por_recordType__mdt orden : [SELECT Label, Codigo_de_color__c 
                                                        FROM Orden_de_etapas_por_recordType__mdt
                                                        WHERE RecordType__c = 'Avaluo']) {
            colorPorEtapa.put(orden.Label, orden.Codigo_de_color__c);
        }

        return colorPorEtapa;
    }

    @AuraEnabled
    public static List<Map<String, List<String>>> obtenerUdcs(){
        List<Catalogo_UDC__c> marcasList = [
            SELECT Name
            FROM Catalogo_UDC__c
            WHERE RecordType.DeveloperName = 'Marcas' 
                AND Permitido_para_autolote__c = true
        ];

        List<Map<String, List<String>>> listaMapaUdc = new List<Map<String, List<String>>>();
        Map<String, List<String>> modelosPorMarcaMap = new Map<String, List<String>>();
        Map<String, List<String>> submodeloPorModeloMap = new Map<String, List<String>>();

        List<Id> marcasIdList = new List<Id>();

        for (Catalogo_UDC__c marca : marcasList) {
            marcasIdList.add(marca.Id);
        }

        if (!marcasIdList.isEmpty()) {
            List<Catalogo_UDC__c> modelosList = [
                SELECT Name, udc_padre__r.Name 
                FROM Catalogo_UDC__c
                WHERE RecordType.DeveloperName = 'Modelo' 
                    AND udc_padre__c IN :marcasIdList
                    AND Permitido_para_autolote__c = true
            ];

            List<Id> modelosIdList = new List<Id>();

            for (Catalogo_UDC__c modelo : modelosList) {
                modelosIdList.add(modelo.Id);
            }

            if (!modelosIdList.isEmpty()) {
                List<Catalogo_UDC__c> submodelosList = [
                    SELECT Name, udc_padre__r.Name 
                    FROM Catalogo_UDC__c
                    WHERE RecordType.DeveloperName = 'Submodelo' 
                        AND udc_padre__c IN :modelosIdList
                        AND Permitido_para_autolote__c = true
                ];

                for (Catalogo_UDC__c modelo : modelosList) {
                    List<String> modelosPorMarca;

                    if (modelosPorMarcaMap.containsKey(modelo.udc_padre__r.Name)) {
                        modelosPorMarca = modelosPorMarcaMap.get(modelo.udc_padre__r.Name);
                    } else {
                        modelosPorMarca = new List<String>();
                    }

                    modelosPorMarca.add(modelo.Name);

                    modelosPorMarcaMap.put(modelo.udc_padre__r.Name, modelosPorMarca);
                }

                for (Catalogo_UDC__c submodelo : submodelosList) {
                    List<String> submodelosPorModelo;

                    if (submodeloPorModeloMap.containsKey(submodelo.udc_padre__r.Name)) {
                        submodelosPorModelo = submodeloPorModeloMap.get(submodelo.udc_padre__r.Name);
                    } else {
                        submodelosPorModelo = new List<String>();
                    }

                    submodelosPorModelo.add(submodelo.Name);

                    submodeloPorModeloMap.put(submodelo.udc_padre__r.Name, submodelosPorModelo);
                }

                listaMapaUdc.add(modelosPorMarcaMap);   
                listaMapaUdc.add(submodeloPorModeloMap);
            }
        }

        return listaMapaUdc;
    }

    @AuraEnabled
    public static List<String> obtenerListaAnios(){
        List<String> anios = new List<String>();

        Schema.DescribeFieldResult f = Vehiculo__c.Anio_opcion__c.getDescribe();
		List<Schema.PicklistEntry> pickL = f.getPicklistValues();
        
		for (Schema.PicklistEntry pickV : pickL) {
            anios.add(pickV.getLabel());
		}     

        return anios;
    }

    @AuraEnabled
    public static String crearAvaluo(String opportunityId, String placa, String marca, String modelo, String submodelo, String anio, String kilometraje) {
        List<Vehiculo__c> vehiculoExistente = [
            SELECT Id
            FROM Vehiculo__c
            WHERE Placa__c =: placa
        ];

        if (vehiculoExistente.isEmpty()) {
            ID avaluoId = Schema.SObjectType.Opportunity
                    .getRecordTypeInfosByDeveloperName()
                    .get('Avaluo')
                    .getRecordTypeId();

            List<Catalogo_UDC__c> marcaList = [
                SELECT Id 
                FROM Catalogo_UDC__c 
                WHERE Name =: marca AND RecordType.DeveloperName = 'Marcas'
            ];
    
            List<Catalogo_UDC__c> modeloList = [
                SELECT Id 
                FROM Catalogo_UDC__c 
                WHERE Name =: modelo AND RecordType.DeveloperName = 'Modelo'
            ];
    
            List<Catalogo_UDC__c> subModeloList = [
                SELECT Id 
                FROM Catalogo_UDC__c 
                WHERE Name =: submodelo AND RecordType.DeveloperName = 'Submodelo'
            ];

            Opportunity opportunity = [
                SELECT Id, CloseDate, AccountId, Name, Sucursal__c
                FROM Opportunity
                WHERE Id =: opportunityId
                LIMIT 1
            ];

            Vehiculo__c veh = new Vehiculo__c();
            veh.Marca__c = marcaList[0].Id;
            veh.Modelo__c = modeloList[0].Id;
            veh.Submodelo__c = subModeloList[0].Id;
            veh.Placa__c = placa;
            veh.Cliente__c = opportunity.AccountId;
            veh.Anio_opcion__c = anio;
            veh.Kilometraje__c = kilometraje;
            veh.Estado__c = 'Pendiente';

            Database.SaveResult vehSr = Database.insert(veh, false);
            if (!vehSr.isSuccess()) {
                return vehSr.getErrors()[0].getMessage();
            }

            Opportunity oppHijo = new Opportunity();
            oppHijo.CloseDate = opportunity.CloseDate;
            oppHijo.Sucursal__c = opportunity.Sucursal__c;
            oppHijo.RecordTypeId = avaluoId;
            oppHijo.StageName = mostrarOportunidadHijo.etapaInicialAvaluo;
            oppHijo.AccountId = opportunity.AccountId;
            oppHijo.Name = 'AVALUO/' + opportunity.Name.split('/')[0];
            oppHijo.Oportunidad_original__c = opportunity.Id;

            Database.SaveResult oppHijoSr = Database.insert(oppHijo, false);
            if (!oppHijoSr.isSuccess()) {
                return oppHijoSr.getErrors()[0].getMessage();
            }

            Vehiculo_de_la_Oportunidad__c vehOpp = new Vehiculo_de_la_Oportunidad__c();
            vehOpp.Vehiculo__c = veh.Id;
            vehOpp.Oportunidad__c = oppHijo.Id;

            Database.SaveResult vehOppSr = Database.insert(vehOpp, false);
            if (!vehOppSr.isSuccess()) {
                return vehOppSr.getErrors()[0].getMessage();
            }
            
            return 'Ok';

        } else {
            return 'Ya existe un vehiculo con esa placa';
        }
    }

    @AuraEnabled
    public static String asociarVehiculoExistente(String opportunityId, String placa){
        ID avaluoId = Schema.SObjectType.Opportunity
                    .getRecordTypeInfosByDeveloperName()
                    .get('Avaluo')
                    .getRecordTypeId();

        Opportunity opportunity = [
            SELECT Id, CloseDate, AccountId, Name, Sucursal__c
            FROM Opportunity
            WHERE Id =: opportunityId
        ];

        List<Vehiculo__c> vehList = [
            SELECT Id
            FROM Vehiculo__c
            WHERE Placa__c =: placa
                AND (Estado__c = 'Pendiente' OR Estado__c = 'Vendido')
        ];

        if (vehList.isEmpty()) {
            return 'No existe vehiculo disponible con la placa indicada';
        }

        List<Vehiculo_de_la_Oportunidad__c> avaluosAbiertos = [
            SELECT Id, Oportunidad__r.Owner.Name
            FROM Vehiculo_de_la_Oportunidad__c
            WHERE Vehiculo__c =: vehList[0].Id
                AND Oportunidad__r.RecordType.DeveloperName = 'Avaluo'
                AND Oportunidad__r.StageName != 'Cerrada ganada'
                AND Oportunidad__r.StageName != 'Cerrada perdida'
        ];

        if (!avaluosAbiertos.isEmpty()) {
            return 'Este vehiculo es parte de un proceso llevado por ' + avaluosAbiertos[0].Oportunidad__r.Owner.Name + ', con lo cual no puede ser asociado.';
        }

        Opportunity oppHijo = new Opportunity();
        oppHijo.CloseDate = opportunity.CloseDate;
        oppHijo.RecordTypeId = avaluoId;
        oppHijo.Sucursal__c = opportunity.Sucursal__c;
        oppHijo.StageName = mostrarOportunidadHijo.etapaInicialAvaluo;
        oppHijo.AccountId = opportunity.AccountId;
        oppHijo.Name = 'AVALUO/' + opportunity.Name.split('/')[0];
        oppHijo.Oportunidad_original__c = opportunity.Id;

        Database.SaveResult oppHijoSr = Database.insert(oppHijo, false);
        if (!oppHijoSr.isSuccess()) {
            return oppHijoSr.getErrors()[0].getMessage();
        }

        Vehiculo_de_la_Oportunidad__c vehOpp = new Vehiculo_de_la_Oportunidad__c();
        vehOpp.Vehiculo__c = vehList[0].Id;
        vehOpp.Oportunidad__c = oppHijo.Id;

        Database.SaveResult vehOppSr = Database.insert(vehOpp, false);
        if (!vehOppSr.isSuccess()) {
            return vehOppSr.getErrors()[0].getMessage();
        }
        
        return 'Ok';
    }
}