force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Codigo_WS_de_UDC__mdt/Codigo_WS_de_UDC__mdt.object-meta.xml
<CustomObject>
    <description>Los UDC son designados en WS con un par de códigos que los identifican</description>
    <label>Codigo WS de Catalogo UDC</label>
    <pluralLabel>Codigos WS de Catalogo UDC</pluralLabel>
</CustomObject>

force-app/main/default/objects/Codigo_WS_de_UDC__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Codigo_WS_de_UDC__mdt/fields/User_Defined_Code__c.field-meta.xml
<CustomField>
    <fullName>User_Defined_Code__c</fullName>
    <label>User Defined Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcesaWS_UDCsJSON.cls
public class ProcesaWS_UDCsJSON {
	public static void getUDCJSON() {
        List<Catalogo_UDC__c> udcListInsert = new List<Catalogo_UDC__c>();
        List<String> errorsList = new List<String>();
        Map<String, ID> recordIDByDeveloperName = new Map<String, ID>();
        Map<String, String> codeByDeveloperName = new Map<String, String>();

        for (RecordType rt : [SELECT ID, DeveloperName
                                FROM Recordtype
                                WHERE SobjectType = 'Catalogo_UDC__c']) {
            recordIDByDeveloperName.put(rt.DeveloperName, rt.ID);
        }

        for(Codigo_WS_de_UDC__mdt udcCode : [SELECT DeveloperName, Product_Code__c, User_Defined_Code__c
                                            FROM Codigo_WS_de_UDC__mdt]) {
            codeByDeveloperName.put(udcCode.DeveloperName, udcCode.Product_Code__c + '_' + 
                                                                udcCode.User_Defined_Code__c );
        }

        HttpResponse response;
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(Label.URL_WS_UDC);   
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('key', Label.strKey);
        request.setHeader('app', Label.strApp);
        request.setHeader('mod', Label.strModulo);

        try{
        	response = http.send(request);
            if (response.getStatusCode() != 201) {
                System.debug('Ha ocurrido un error ' + response.getStatus() + ', codigo: ' + response.getStatusCode());
            } else {
                System.debug('Todo ha salido bien!');
				List<ObjResponseUDCs> udcList = ObjResponseUDCs.parse(response.getBody());
                if (!udcList.isEmpty()) {
                    for(ObjResponseUDCs udc: udcList){
                        String udcName = udc.nombreudc.replaceAll(' ', '_');
                        if(recordIDByDeveloperName.get(udcName) != null && udc.descripction1 != '.') {
                            Catalogo_UDC__c d = new Catalogo_UDC__c();
                            d.RecordTypeId = recordIDByDeveloperName.get(udcName);
                            d.description1__c = udc.descripction1;
                            d.Name = d.description1__c;
                            d.description2__c = udc.descripction2;
                            d.productCode__c = udc.codigo.trim();
                            d.ExternalId__c = codeByDeveloperName.get(udcName) + '_' + d.productCode__c;
                            udcListInsert.add(d);
                        } else if (recordIDByDeveloperName.get(udcName) == null) {
                            System.debug(udc.nombreudc);
                        }
                    }
                }

                if (!udcListInsert.isEmpty()) {
                    Database.UpsertResult[] srList  = Database.upsert(udcListInsert, Catalogo_UDC__c.ExternalId__c, false);                
                    Integer success = 0;
                    for (Database.UpsertResult sr : srList) {
                        if (!sr.isSuccess()) {
                            for (Database.Error err : sr.getErrors()) {
                                errorsList.add('Ha ocurrido un error en la UDC:' + err.getStatusCode() + ': ' + err.getMessage() + 
                                    '\n' + 'Los campos que interfieren en el error son: ' + err.getFields()+ '\n\n');
                            }
                        } else {
                            success++;
                        }
                    }
        
                    System.debug(success);
                }
        
                if (!errorsList.isEmpty()) {
                    System.debug(errorsList.size());
                }
            }
        } catch (CallOutException ex) {
            errorsList.add('Hubo una excepcion: ' + ex.getMessage() +', '+ ex.getStackTraceString());
        }                
    }
}