force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Lineas_de_negocio.recordType-meta.xml
<RecordType>
    <fullName>Lineas_de_negocio</fullName>
    <active>true</active>
    <label>Lineas de negocio</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Permite_Ganar_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Permite_Ganar_Oportunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permite Ganar Oportunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConsultarInventarioController.cls
public without sharing class ConsultarInventarioController {
    
    @AuraEnabled
    public static String consultarInventario(Id oppId) {
        List<Id> vehIdList = new List<Id>();
        List<String> chasisVehList = new List<String>();
        List<String> chasisList = new List<String>();

        String casaPellas = [
            SELECT productCode__c
            FROM Catalogo_UDC__c
            WHERE RecordType.DeveloperName = 'Companias'
                AND Name = 'CASA PELLAS, S.A'
        ].productCode__c;

        String autolote = [
            SELECT productCode__c
            FROM Catalogo_UDC__c
            WHERE RecordType.DeveloperName = 'Lineas_de_negocio'
                AND Name = 'Autos Usados'
        ].productCode__c;

        for (Vehiculo_de_la_Oportunidad__c vehOpp : [SELECT Oportunidad__c, Vehiculo__r.Chasis__c
                                                    FROM Vehiculo_de_la_Oportunidad__c 
                                                    WHERE Oportunidad__c =: oppId]) {
            chasisVehList.add(vehOpp.Vehiculo__r.Chasis__c);
        }

        for (WS_InventorySearchList.Inventory inventory : WS_InventorySearchList.getInventario(casaPellas, autolote, '', '', 'true')) {
            chasisList.add(inventory.chasis.toUpperCase());
        }

        if (chasisVehList.isEmpty()) {
            return 'La oportunidad debe tener vehiculos asociados para hacer la consulta.';
        }

        String chasisNoIncluidos = '';
        for (String chasis : chasisVehList) {
            if (!chasisList.contains(chasis.toUpperCase())) {
                chasisNoIncluidos =+ chasis + ', ';
            }
        }

        if (String.isNotBlank(chasisNoIncluidos)) {
            chasisNoIncluidos = chasisNoIncluidos.removeEnd(', ');
            return 'Los siguientes chasis no estan ingresados en el inventario: ' + chasisNoIncluidos;
        }

        Opportunity opp = [
            SELECT Permite_ganar_oportunidad__c
            FROM Opportunity
            WHERE Id =: oppId
        ];

        opp.Permite_ganar_oportunidad__c = true;
        Database.SaveResult sr = Database.update(opp, false);

        if (!sr.isSuccess()) {
            return sr.getErrors()[0].getMessage();
        }

        return 'Ok. Todos los vehiculos se encuentran ingresados correctamente en el inventario, puede cerrar la oportunidad.';
    }
}