force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Lineas_de_negocio.recordType-meta.xml
<RecordType>
    <fullName>Lineas_de_negocio</fullName>
    <active>true</active>
    <label>Lineas de negocio</label>
</RecordType>

force-app/main/default/classes/BatchCallWSGetFacturasDetalleDiaList.cls
global class BatchCallWSGetFacturasDetalleDiaList implements Database.Batchable<sObject>,  Database.AllowsCallouts, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext Bc){
        if(test.isRunningTest()){
            return Database.getQueryLocator(
                			[SELECT Name, productCode__c 
                             FROM Catalogo_UDC__c 
                             WHERE RecordTypeId in (SELECT Id 
                                                    FROM RecordType 
                                                    WHERE DeveloperName = 'Lineas_de_negocio') 
                             		AND productCode__c = '01' 
                             LIMIT 1 
                            ]);
        } else {
            return Database.getQueryLocator(
                			[SELECT Name, productCode__c 
                             FROM Catalogo_UDC__c 
                             WHERE RecordTypeId in (SELECT Id 
                                                    FROM RecordType 
                                                    WHERE DeveloperName = 'Lineas_de_negocio') 
                             		AND productCode__c != '' 
                             		AND productCode__c != null
                            ]);
        }
    }

    global void execute(Database.BatchableContext Bc, List<Catalogo_UDC__c> UDCList){
        System.debug('INICIA BATCH CON LINEA : ' + UDCList[0].productCode__c);
        ProcesaWSGetFacturasDetalleDiaList.GetFacturasDetalleDiaList(UDCList[0].productCode__c);
    }
    
    global void finish(Database.BatchableContext Bc){}
    
}