force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Codigomodelogenerico__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelogenerico__c</fullName>
    <description>Descripcion del modelo generico del producto</description>
    <label>Codigo modelo generico</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/modelogenerico__c.field-meta.xml
<CustomField>
    <fullName>modelogenerico__c</fullName>
    <label>Modelo generico</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/classes/Test_CallActualizaModelosUDC.cls
@IsTest
public class Test_CallActualizaModelosUDC {

    @IsTest
    public static void ejecutaWSProductosDia(){
        ID RTId = Schema.SObjectType.Catalogo_UDC__c
                .getRecordTypeInfosByDeveloperName()
                .get('Modelo')
                .getRecordTypeId();

        Product2 p = new Product2();
        p.Name = 'AUTO KIA';
        p.Codigomodelogenerico__c = 'K09';
        p.ProductCode__c = 'K09';
        p.modelogenerico__c = 'RIO';
        p.Marca_P__c = 'Kia';
        insert p;
        
        SchedulableContext sc = null;
        Call_ActualizaModelosUDC x = new Call_ActualizaModelosUDC();

        Test.startTest();
        x.execute(sc);
        Test.stopTest();

        List<Catalogo_UDC__c> modelosUDC =
            [SELECT Name, productCode__c, description1__c, description2__c,
                    ExternalId__c
            FROM Catalogo_UDC__c
            WHERE RecordTypeId =: RTId
            ];

        System.assertEquals(false, modelosUDC.isEmpty(), 'La lista de catalogos esta vacia cuando no deberia estarlo.');
        System.assertEquals('RIO', modelosUDC[0].Name, 'El nombre no se ha seteado correctamente.');
        System.assertEquals('RIO', modelosUDC[0].description1__c, 'La descripcion no se ha seteado correctamente.');
        System.assertEquals('K09', modelosUDC[0].productCode__c, 'El codigo de producto no se ha seteado correctamente.');
        System.assertEquals('Kia', modelosUDC[0].description2__c, 'La segunda descripcion no se ha seteado correctamente.');
        System.assertEquals('Modelo_K09', modelosUDC[0].ExternalId__c, 'El id externo no se ha seteado correctamente.');
    }
}