force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/Marca_relacionada__c.field-meta.xml
<CustomField>
    <fullName>Marca_relacionada__c</fullName>
    <label>Marca relacionada</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTOLOTE</fullName>
            </value>
            <value>
                <fullName>GENESIS</fullName>
            </value>
            <value>
                <fullName>HAOJUE</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>YAMAHA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Companias.recordType-meta.xml
<RecordType>
    <fullName>Companias</fullName>
    <active>true</active>
    <label>Companias</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Codigomodelofabrica__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelofabrica__c</fullName>
    <description>Codigo del modelo de fabrica de producto</description>
    <label>Codigo modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/modelofabrica__c.field-meta.xml
<CustomField>
    <fullName>modelofabrica__c</fullName>
    <description>Nombre del modelo de fabrica del producto</description>
    <label>Modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/modelogenerico__c.field-meta.xml
<CustomField>
    <fullName>modelogenerico__c</fullName>
    <label>Modelo generico</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTOLOTE</fullName>
            </value>
            <value>
                <fullName>GENESIS</fullName>
            </value>
            <value>
                <fullName>HAOJUE</fullName>
            </value>
            <value>
                <fullName>HERO</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>YAMAHA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WS_InventorySearchList.cls
public class WS_InventorySearchList {
    @AuraEnabled
    public static List<Inventory> getInventario(String compania, String linea, String marca, String modelo, String inbond) {
        List<Inventory> inventoryList = new List<Inventory>();
        List<String> modeloList = new List<String>();

        if (String.isNotBlank(modelo) && modelo.contains(',')) {
            modeloList.addAll(modelo.split(','));
        } else {
            modeloList.add(modelo);
        }

        for (String str : modeloList) {
            HttpRequest request = new HttpRequest();
            request.setEndpoint(Label.URL_WS_ConsultaDisponibilidad);
            request.setMethod('GET');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('key', Label.strKey);
            request.setHeader('app', Label.strApp);
            request.setHeader('mod', Label.strModulo);
            request.setHeader('compania',compania);
            request.setHeader('linea', linea);
            request.setHeader('marca', marca);
            request.setHeader('modelo', str);
            request.setHeader('isInbond', inbond);
            request.setTimeout(120000);

            inventoryList.addAll((List<Inventory>)JSON.deserialize(new Http().send(request).getBody(), List<Inventory>.class));
        }
        
        return inventoryList;
    }
    
    @AuraEnabled
    public static List<Inventory> getInventarioByString(String searchKey, List<Inventory> inventoryList) {
        
       List<Inventory> ReturnInventarioByString = new List<Inventory>();
        
        if (searchKey == ''){
            return inventoryList;
        }
        
        for(Inventory a : inventoryList ) {
            
            if(a.chasis !=null && a.chasis.containsIgnoreCase(searchKey)){
                ReturnInventarioByString.add(a);
                continue;
            }
            if(a.descripcion !=null && a.descripcion.containsIgnoreCase(searchKey)){
                ReturnInventarioByString.add(a);
                continue;   
            }
            if(a.codigomotor !=null && a.codigomotor.containsIgnoreCase(searchKey)){
                ReturnInventarioByString.add(a);
                continue;
            }
            if(string.valueOf(a.numerocorto).containsIgnoreCase(searchKey)){
                ReturnInventarioByString.add(a);
                continue;
            }
            
        }
                
        return ReturnInventarioByString;

    }
    
    /** Carga los combos */
    @AuraEnabled
    public static List<List<Catalogo_UDC__c>> cargaPickList() {
        
        Id userId = UserInfo.getUserId();

        User u = [
            SELECT Marca__c
            FROM User 
            WHERE Id =: userId
        ];

        List<String> marcas = String.isNotBlank(u.Marca__c)? u.Marca__c.split(';') : new List<String>();

        List<Catalogo_UDC__c> companias = new List<Catalogo_UDC__c>();
        List<Catalogo_UDC__c> lineaNegocio = new List<Catalogo_UDC__c>();
        
        List<List<Catalogo_UDC__c>> catalogoUDC = new List<List<Catalogo_UDC__c>>();

        for (Catalogo_UDC__c pLineaNegocio : [SELECT Id, Name, description1__c, description2__c, productCode__c, Marca_relacionada__c  
                                        FROM Catalogo_UDC__c 
                                        WHERE RecordType.Name = 'Lineas de negocio' 
                                        ORDER BY description1__c]) {
            if (String.isNotBlank(pLineaNegocio.Marca_relacionada__c)) {
                for (String marca : pLineaNegocio.Marca_relacionada__c.split(';')) {
                    if (marcas.contains(marca) && !lineaNegocio.contains(pLineaNegocio)) {
                        lineaNegocio.add(pLineaNegocio);
                    }
                }
            }
        }

        catalogoUDC.add(lineaNegocio);

        for (Catalogo_UDC__c pCompania : [SELECT Id, Name, description1__c, description2__c, productCode__c, Marca_relacionada__c  
                                        FROM Catalogo_UDC__c 
                                        WHERE RecordType.Name = 'Companias' 
                                        AND productCode__c LIKE 'E%' 
                                        ORDER BY description1__c]) {
            if (String.isNotBlank(pCompania.Marca_relacionada__c)) {
                for (String marca : pCompania.Marca_relacionada__c.split(';')) {
                    if (marcas.contains(marca) &&  !companias.contains(pCompania)) {
                        companias.add(pCompania);
                    }
                }
            }
        }

        catalogoUDC.add(companias);

      	List<Catalogo_UDC__c> pMarca = 
            [SELECT Id,Name, description1__c, description2__c, productCode__c 
            FROM Catalogo_UDC__c 
            WHERE RecordType.Name = 'Marcas' 
            ORDER BY description1__c
            ];

        catalogoUDC.add(pMarca);

        return catalogoUDC;
    }

    @AuraEnabled
    public static List<modeloData> modelosPorMarca(String marca){
        List<Product2> prodList =
            [SELECT Codigomodelofabrica__c, modelofabrica__c, modelogenerico__c
            FROM Product2 
            WHERE Marca_P__c =: marca
             	  AND (NOT modelogenerico__c LIKE 'MOTORES MARINOS%')
            ];

        List<modeloData> modList = new List<modeloData>();
        List<String> modPresentes = new List<String>();

        for (Product2 p : prodList) {
            if(!modPresentes.contains(p.modelofabrica__c)) {
                modeloData m = new modeloData();
                m.nombre = p.modelofabrica__c;
                m.codigo = p.Codigomodelofabrica__c;
    
                modList.add(m);
            }
        }

        return modList;
    }

    @AuraEnabled
    public static Boolean getCurrentPermission(){
        List<PermissionSetAssignment> permissionAssignment = [
            SELECT Id 
            FROM PermissionSetAssignment 
            WHERE AssigneeId =: UserInfo.getUserId()
                AND PermissionSet.Name = 'Deshabilitar_busqueda_de_vehiculos_inbound'
        ];

        return permissionAssignment.isEmpty();
    }
    
    ///////////////////////
   
    public class modeloData{
        @AuraEnabled public String nombre {get;set;}
        @AuraEnabled public String codigo {get;set;}
    }

    public class Inventory{
        // ============== Campos ============== //
        @AuraEnabled public Integer numerocorto {get;set;}
        @AuraEnabled public String chasis {get;set;}
        @AuraEnabled public String codigomotor  {get;set;}
        @AuraEnabled public String descripcion {get;set;}
        @AuraEnabled public String codigovehiculo{get;set;}
        @AuraEnabled public String codigocolorexterno {get;set;}
        @AuraEnabled public String colorexterno {get;set;}
        @AuraEnabled public String codigocolorinterno {get;set;}
        @AuraEnabled public String colorinterno {get;set;}
        @AuraEnabled public String anovehiculo {get;set;}
        @AuraEnabled public String codigomodelogenerico {get;set;}
        @AuraEnabled public String modelogenerico {get;set;}
        @AuraEnabled public String codigomarca {get;set;}
        @AuraEnabled public String marca {get;set;}
        @AuraEnabled public String codigomodelofabrica {get;set;}
        @AuraEnabled public String modelofabrica {get;set;}
        @AuraEnabled public String codigounidadnegocio {get;set;}
        @AuraEnabled public String unidadnegocio {get;set;}
        @AuraEnabled public String codigobodega {get;set;}
        @AuraEnabled public String nacionalizado {get;set;}
        @AuraEnabled public String produccion {get;set;}
        @AuraEnabled public Integer cantidadexistencia {get;set;}
        @AuraEnabled public Integer cantidadtransito {get;set;}
        @AuraEnabled public Integer cantidadreservadaubicacion {get;set;}
        @AuraEnabled public Integer cantidadreservadaflexible {get;set;}
        @AuraEnabled public String estado {get;set;}
        @AuraEnabled public String codigolinea {get;set;}
        @AuraEnabled public String linea {get;set;}
        @AuraEnabled public String codigocompania {get;set;}
        @AuraEnabled public String compania {get;set;}
        @AuraEnabled public String codigosucursal {get;set;}
        @AuraEnabled public String sucursal {get;set;}
        @AuraEnabled public Integer numeroorden {get;set;}
        @AuraEnabled public Integer codigocliente {get;set;}
        @AuraEnabled public String notasordenventa {get;set;}
        @AuraEnabled public String nombrecliente {get;set;}
        @AuraEnabled public Integer codigovendedor {get;set;}
        @AuraEnabled public String nombrevendedor {get;set;}
        @AuraEnabled public Integer pedido {get;set;}
        @AuraEnabled public Integer cantidad {get;set;}
        @AuraEnabled public String tipo {get;set;}
        @AuraEnabled public String fechaEntrega {get;set;}
        @AuraEnabled public String promesaEntrega {get;set;}
        @AuraEnabled public String fechaarribo {get;set;}
        @AuraEnabled public String ubicacion {get;set;}
        @AuraEnabled public String transmision {get;set;}
        @AuraEnabled public Decimal precio {get;set;}
        @AuraEnabled public String placa {get;set;}
        @AuraEnabled public String comentarioschasis {get;set;}
        @AuraEnabled public String codigoubicacion {get;set;}  
        @AuraEnabled public String bl {get;set;}  
    }
}