force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Codigomodelofabrica__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelofabrica__c</fullName>
    <description>Codigo del modelo de fabrica de producto</description>
    <label>Codigo modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigomodelogenerico__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelogenerico__c</fullName>
    <description>Descripcion del modelo generico del producto</description>
    <label>Codigo modelo generico</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/modelofabrica__c.field-meta.xml
<CustomField>
    <fullName>modelofabrica__c</fullName>
    <description>Nombre del modelo de fabrica del producto</description>
    <label>Modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/modelogenerico__c.field-meta.xml
<CustomField>
    <fullName>modelogenerico__c</fullName>
    <label>Modelo generico</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Genesis.recordType-meta.xml
<RecordType>
    <fullName>Genesis</fullName>
    <active>true</active>
    <label>Genesis</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <label>Hero</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Yamaha.recordType-meta.xml
<RecordType>
    <fullName>Yamaha</fullName>
    <active>true</active>
    <label>Yamaha</label>
</RecordType>

force-app/main/default/classes/ActualizaModelosUDC.cls
public class ActualizaModelosUDC {
    public static void actualizaModelos () {
        Map<String, String> modeloCodeByName = new Map<String, String>();
        Map<String, String> marcaByModeloName = new Map<String, String>();
        List<Catalogo_UDC__c> modelosToUpsert = new List<Catalogo_UDC__c>();
        ID RTId = Schema.SObjectType.Catalogo_UDC__c
                .getRecordTypeInfosByDeveloperName()
                .get('Modelo')
                .getRecordTypeId();
        
        List<Product2> productList = 
            [SELECT Id, Codigomodelogenerico__c, modelogenerico__c, Marca_P__c, 
                    modelofabrica__c, Codigomodelofabrica__c 
            FROM Product2 
            WHERE (Codigomodelogenerico__c != '' 
                    AND Codigomodelogenerico__c != null)
                  OR (Codigomodelofabrica__c != '' 
                    AND Codigomodelofabrica__c != null)
            ];

        for (Product2 p : productList) {
            if (p.Marca_P__c == 'Yamaha' || p.Marca_P__c == 'Hero' || p.Marca_P__c == 'Genesis') {
                if (!modeloCodeByName.containsKey(p.modelofabrica__c)) {
                    modeloCodeByName.put(p.modelofabrica__c, p.Codigomodelofabrica__c);
                }
    
                if (!marcaByModeloName.containsKey(p.modelofabrica__c)) {
                    marcaByModeloName.put(p.modelofabrica__c, p.Marca_P__c);
                }
            } else {
                if (!modeloCodeByName.containsKey(p.modelogenerico__c)) {
                    modeloCodeByName.put(p.modelogenerico__c, p.codigomodelogenerico__c);
                }
    
                if (!marcaByModeloName.containsKey(p.modelogenerico__c)) {
                    marcaByModeloName.put(p.modelogenerico__c, p.Marca_P__c);
                }
            }
        }
        
        for (String name : modeloCodeByName.KeySet()) {
            Catalogo_UDC__c modelo = new Catalogo_UDC__c();
            modelo.RecordTypeId = RTId;
            modelo.productCode__c = modeloCodeByName.get(name);
            modelo.name = name.toUpperCase();
            modelo.description1__c = name.toUpperCase();
            modelo.description2__c = marcaByModeloName.get(name);
            modelo.ExternalId__c = 'Modelo_' + modelo.productCode__c;

            modelosToUpsert.add(modelo);
        }
            
        if (!modelosToUpsert.isEmpty()) {
            Database.UpsertResult[] srList  = Database.upsert(modelosToUpsert, Catalogo_UDC__c.ExternalId__c, false);
            
            for (Database.UpsertResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                        System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                    }
                }
            } 
        }
    }
}