force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Actividad_Economica.recordType-meta.xml
<RecordType>
    <fullName>Actividad_Economica</fullName>
    <active>true</active>
    <label>Actividad económica</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/classes/ProcesaWSUDCTest.cls
@Istest
public class ProcesaWSUDCTest {
	@IsTest
    public static void getUDCTest(){
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_UDC_Mock());
        
        Test.startTest();
        ProcesaWS_UDCs.getUDCs();
        Test.stopTest();

        List<Catalogo_UDC__c> catList = 
           [SELECT RecordType.DeveloperName, productCode__c, description2__c
            FROM Catalogo_UDC__c
            WHERE Name = 'TESTACTECONOMICA'
            ];
        
        System.assertEquals(true, !catList.isEmpty(), 'La lista esta vacia cuando no deberia');
        System.assertEquals('Actividad_Economica', catList[0].RecordType.DeveloperName, 'El record type no es el correcto.');
        System.assertEquals('Mayorista', catList[0].description2__c, 'La descripcion no es la correcta.');
        System.assertEquals('COM', catList[0].productCode__c, 'El codigo de producto no es el correcto.');
    }
    
    @IsTest
    public static void getUDCJSONTest(){
        Test.setMock(HttpCalloutMock.class, new Test_HTTP_UDC_Mock());
        
        Test.startTest();
        ProcesaWS_UDCsJSON.getUDCJSON();
        Test.stopTest();
        
        List<Catalogo_UDC__c> catList = 
            [SELECT RecordType.DeveloperName, productCode__c, description2__c
            FROM Catalogo_UDC__c
            WHERE Name = 'TESTDESCRIPCION'
            ];
        
        System.assertEquals(true, !catList.isEmpty(), 'La lista esta vacia cuando no deberia');
        System.assertEquals('Marcas', catList[0].RecordType.DeveloperName, 'El record type no es el correcto.');
        System.assertEquals('TESTDESCRIPCION', catList[0].description2__c, 'La descripcion no es la correcta.');
        System.assertEquals('8979878789', catList[0].productCode__c, 'El codigo de producto no es el correcto.');            
    }
}