force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Color_Externo__c.field-meta.xml
<CustomField>
    <fullName>Color_Externo__c</fullName>
    <label>Color Externo</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación (Cuenta)</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Facturar_a_nombre_de__c.field-meta.xml
<CustomField>
    <fullName>Facturar_a_nombre_de__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturar a nombre de</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Forma_de_Pago_Informe__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_Informe__c</fullName>
    <label>Forma de Adquisición</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Financiamiento Bancario</fullName>
            </value>
            <value>
                <fullName>Ciclo Casa Pellas</fullName>
            </value>
            <value>
                <fullName>Go Leasing</fullName>
            </value>
            <value>
                <fullName>Tasa 0</fullName>
            </value>
            <value>
                <fullName>Financiamiento</fullName>
            </value>
            <value>
                <fullName>Aún no desea realizar su compra</fullName>
                <isActive>false</isActive>
                <label>Aún no desea realizar su compra</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Precio_de_Lista_sin_IMP__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Lista_sin_IMP__c</fullName>
    <label>Precio de Lista sin IMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Precio_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta__c</fullName>
    <label>Precio de Venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_Multiple__c</fullName>
    <label>Forma de Adquisición</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Financiamiento Bancario</fullName>
            </value>
            <value>
                <fullName>Ciclo Casa Pellas</fullName>
            </value>
            <value>
                <fullName>Go Leasing</fullName>
            </value>
            <value>
                <fullName>Financiamiento</fullName>
            </value>
            <value>
                <fullName>Tasa 0</fullName>
            </value>
            <value>
                <fullName>Aun no desea realizar su compra</fullName>
                <label>Aún no desea realizar su compra</label>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bueno</fullName>
            </value>
            <value>
                <fullName>Malo</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <description>Vehículos de autolote. Utilizados en el proceso de compra y/o venta de autos usados</description>
    <label>Vehículo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos</relationshipLabel>
    <relationshipName>Vehiculos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Vehículos (Modelo)</relationshipLabel>
    <relationshipName>Vehiculos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/Vehiculo_de_la_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Vehículo de la Oportunidad</label>
    <nameField>
        <label>Nombre de Vehiculo de la Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehículos de la Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Informe_de_negociacion__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_negociacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informe de negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Precio_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_venta__c</fullName>
    <inlineHelpText>Únicamente rellenar durante una venta</inlineHelpText>
    <label>Precio de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_la_Oportunidad__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <label>Vehículo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Vehículos de la Oportunidad</relationshipLabel>
    <relationshipName>Vehiculos_de_la_Oportunidad</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CrearInformeDeNeg.cls
public without sharing class CrearInformeDeNeg {
    @AuraEnabled
    public static List<Vehiculo__c> obtenerVehiculos(String oppId) {

        List<Id> vehiculosId = new List<Id>();

        for (Vehiculo_de_la_oportunidad__c vehOpp : [
            SELECT Id, Vehiculo__c
            FROM Vehiculo_de_la_oportunidad__c 
            WHERE Oportunidad__c =: oppId
            ]){
                vehiculosId.add(vehOpp.Vehiculo__c);
        }

        if (!vehiculosId.isEmpty()) {
            List<Vehiculo__c> vehList = [
                SELECT Marca__c, Modelo__c, Marca__r.Name, Modelo__r.Name, Chasis__c
                FROM Vehiculo__c
                WHERE Id IN :vehiculosId
            ];

            return vehList;

        } else {
            return null;
        }
    }

    @AuraEnabled
    public static String CrearInformeNegociacion(String vehId, String oppId) {
        Vehiculo_de_la_oportunidad__c vehOpp = [
            SELECT Oportunidad__c, Vehiculo__c, Informe_de_negociacion__c, Precio_de_venta__c
            FROM Vehiculo_de_la_Oportunidad__c 
            WHERE Vehiculo__c =: vehId AND Oportunidad__c =: oppId
            LIMIT 1
        ];
        
        Opportunity opp = [
            SELECT Forma_de_Pago_Multiple__c, AccountId,Account.Name
            FROM Opportunity
            WHERE ID =: oppId
            LIMIT 1
        ];

        Vehiculo__c veh = [
            SELECT Chasis__c, Color__c, Motor__c
            FROM Vehiculo__c
            WHERE Id =: vehId
            LIMIT 1
        ];

        if (String.isNotBlank(vehOpp.Informe_de_negociacion__c)) {
            List<Informe_de_Negociaci_n__c> inf = [
                SELECT ID 
                FROM Informe_de_Negociaci_n__c 
                WHERE ID =: vehOpp.Informe_de_negociacion__c
            ];
            
            if (!inf.isEmpty()) {
            	return 'Ya se ha creado un informe para este vehículo.';    
            }
        }
        
        Informe_de_Negociaci_n__c infNeg = new Informe_de_Negociaci_n__c();
        infNeg.Vehiculo__c = vehOpp.Vehiculo__c;
        infNeg.Oportunidad__c = vehOpp.Oportunidad__c;
        infNeg.Chasis__c = veh.Chasis__c;
        infNeg.Motor__c = veh.Motor__c;
        infNeg.Color_Externo__c = veh.Color__c;
        infNeg.Precio_de_Lista_sin_IMP__c = vehOpp.Precio_de_venta__c;
        infNeg.Forma_de_Pago_Informe__c = opp.Forma_de_Pago_Multiple__c;
        infNeg.Cuenta__c = opp.AccountId;
        infNeg.Facturar_a_nombre_de__c = opp.AccountId;

        Database.SaveResult sr = Database.insert(infNeg, false);

        if (!sr.isSuccess()) {
            System.debug(sr.getErrors());
            return sr.getErrors()[0].getMessage();
        }

        vehOpp.Informe_de_negociacion__c = infNeg.Id;
        
        Database.SaveResult ur = Database.update(vehOpp, false);

        if (!ur.isSuccess()) {
            System.debug(ur.getErrors());
            return ur.getErrors()[0].getMessage();
        }
        
        return 'Bien';
    }

    public class Vehiculo{
        public String marca;
        public String modelo;
        public String chasis;
    }
}