force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_para_enviar_reporte_de_chasis__mdt/Email_para_enviar_reporte_de_chasis__mdt.object-meta.xml
<CustomObject>
    <description>Listado de emails para enviar reportes de asignación de chasis según Marca</description>
    <label>Email para enviar reporte de chasis</label>
    <pluralLabel>Emails para enviar reporte de chasis</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_para_enviar_reporte_de_chasis__mdt/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIA</fullName>
                <default>true</default>
                <label>KIA</label>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Prima__c.field-meta.xml
<CustomField>
    <fullName>Prima__c</fullName>
    <formula>All_Recibidos__r.MontoAplicado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prima USD$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/X15_I_V__c.field-meta.xml
<CustomField>
    <fullName>X15_I_V__c</fullName>
    <defaultValue>false</defaultValue>
    <label>El cliente paga IVA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compa_a__c.field-meta.xml
<CustomField>
    <fullName>Compa_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Companias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Compañía)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_Multiple__c</fullName>
    <label>Forma de Adquisición</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Financiamiento Bancario</fullName>
            </value>
            <value>
                <fullName>Ciclo Casa Pellas</fullName>
            </value>
            <value>
                <fullName>Go Leasing</fullName>
            </value>
            <value>
                <fullName>Financiamiento</fullName>
            </value>
            <value>
                <fullName>Tasa 0</fullName>
            </value>
            <value>
                <fullName>Aun no desea realizar su compra</fullName>
                <label>Aún no desea realizar su compra</label>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/L_neas_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>L_neas_de_Negocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Líneas de Negocio</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor no existe o no coinciden los criterios de filtro. Insertar un valor valido para la línea de negocio</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Lineas de negocio</value>
        </filterItems>
        <infoMessage>Insertar un valor de línea de negocio</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Marca del producto de interés</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HINO</fullName>
            </value>
            <value>
                <fullName>JMC</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>SUZUKI</fullName>
            </value>
            <value>
                <fullName>TOYOTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bueno</fullName>
            </value>
            <value>
                <fullName>Malo</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prima__c.field-meta.xml
<CustomField>
    <fullName>Prima__c</fullName>
    <label>Prima %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IdInformeNegociacion__c.field-meta.xml
<CustomField>
    <fullName>IdInformeNegociacion__c</fullName>
    <label>IdInformeNegociacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Motor__c.field-meta.xml
<CustomField>
    <fullName>Motor__c</fullName>
    <label>Motor</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prima__c.field-meta.xml
<CustomField>
    <fullName>Prima__c</fullName>
    <label>Prima</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>ListPrice/1.15</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tipo_de_reserva__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_reserva__c</fullName>
    <label>Tipo de reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>Devolucion</fullName>
            </value>
            <value>
                <fullName>Cambio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X15_I_V_A__c.field-meta.xml
<CustomField>
    <fullName>X15_I_V_A__c</fullName>
    <defaultValue>true</defaultValue>
    <label>El cliente paga IVA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/codigomarca__c.field-meta.xml
<CustomField>
    <fullName>codigomarca__c</fullName>
    <label>Codigo marca</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigomodelofabrica__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelofabrica__c</fullName>
    <description>Codigo del modelo de fabrica de producto</description>
    <label>Codigo modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityProduct_Edit_Controller.cls
public without sharing class OpportunityProduct_Edit_Controller {

    @AuraEnabled
    public static List<OpportunityLineItem> getProductos(String idOpp) {

        List<OpportunityLineItem> lprodOpp = 
            [SELECT Id, Name, Product2.Name, Motor__c, Chasis__c, 
                    Opportunity.Compa_a__r.productCode__c,
                    Opportunity.Marca_UDC__r.productCode__c, 
                    Opportunity.L_neas_de_Negocio__r.productCode__c,
                    Product2.codigomarca__c, product2.Codigomodelofabrica__c 
            FROM OpportunityLineItem 
            WHERE OpportunityId = :idOpp
            ORDER BY CreatedDate
            ];
        
        return lprodOpp;
    }
    
    @AuraEnabled
    public static String AsignarMotorChasis(String idOppProd, 
                                            String Motor, 
                                            String Chasis, 
                                            String Color
    ) { 
        List<OpportunityLineItem> oppProd = [
            SELECT ID, Motor__c, Chasis__c, IdInformeNegociacion__c, Quantity, Tipo_de_reserva__c
            FROM OpportunityLineItem 
            WHERE Id = :idOppProd
            ];

        if (oppProd[0].Quantity > 1) {
            return 'Para asignar chasis debe haber 1 solo producto asignado.';   
        }

        if (String.isNotBlank(oppProd[0].IdInformeNegociacion__c)) {
            List<Informe_de_Negociaci_n__c> InfNeg = [
                SELECT ID 
                FROM Informe_de_Negociaci_n__c 
                WHERE ID = :oppProd[0].IdInformeNegociacion__c
                ];
            
            if (!InfNeg.isEmpty()) {
                return 'Para modificar el chasis no debe haber informe de negociación asignado.';    
            }
        }

        if (String.isNotBlank(Chasis)) {
            List<OpportunityLineItem> oppProdList = new List<OpportunityLineItem>();

            if (chasis != 'SIN CHASIS') {
                oppProdList = [
                    SELECT ID, Opportunity.Name, Chasis__c, Opportunity.Owner.Name
                    FROM OpportunityLineItem
                    WHERE Chasis__c =: Chasis
                        AND Opportunity.StageName != 'Cerrada perdida' 
                    ];
            }
    
            if (oppProdList.isEmpty()) {
                if (String.isBlank(oppProd[0].Chasis__c)) {
                    oppProd[0].Motor__c = Motor;
                    oppProd[0].Chasis__c = Chasis;
                    oppProd[0].Color__c = Color;
                    oppProd[0].IdInformeNegociacion__c = '';

                    if (String.isBlank(oppProd[0].Tipo_de_reserva__c)) {
                        oppProd[0].Tipo_de_reserva__c = 'Nueva';
                    } else {
                        oppProd[0].Tipo_de_reserva__c = 'Cambio';
                    }
            
                    update oppProd;
            
                    return 'ok';    
                } else {
                    return 'Para asignar un chasis debe deasignar primero';
                }
            } else {
                return 'Ese chasis ya ha sido asignado por el vendedor ' + 
                        oppProdList[0].Opportunity.Owner.Name +
                        ', en la oportunidad ' +
                        oppProdList[0].Opportunity.Name + '.';
            }
        }
        
        return 'nada';
    }
    
    @AuraEnabled
    public static String Desasignar(String idOppProd, String motivo, String tipoDeasignacion) {
        OpportunityLineItem oppProd = 
            [SELECT ID, Motor__c, Chasis__c, IdInformeNegociacion__c, Product2.Marca_P__c,
                    Opportunity.Owner.Email, Opportunity.Account.Name, Opportunity.Owner.Name,
                    Opportunity.Name, Tipo_de_reserva__c
            FROM OpportunityLineItem 
            WHERE ID = :idOppProd
			];
        
        if (String.isBlank(oppProd.Chasis__c)) {
        	return 'ChasisNoAsignado';    
        } else if (String.isNotBlank(oppProd.IdInformeNegociacion__c)) {
            List<Informe_de_Negociaci_n__c> InfNeg = 
                [SELECT ID 
                FROM Informe_de_Negociaci_n__c 
                WHERE ID = :oppProd.IdInformeNegociacion__c
                ];
            
            if (!InfNeg.isEmpty()) {
                return 'InformeExistente';    
            }
        }
        
        List<EmailTemplate> etList = 
            [SELECT Id, HtmlValue 
            FROM EmailTemplate  
            WHERE Name LIKE 'Deasignacion Chasis' 
            ];

        List<Messaging.Email> emailList = new List<Messaging.Email>();
        Map<String, List<String>> emailPorMarca = new Map<String, List<String>>();
        Map<String, String> aprobadorPorEmail = new Map<String, String>();

        for (Email_para_enviar_reporte_de_chasis__mdt email :  
                [SELECT Marca__c, Email__c, Nombre__c
                    FROM Email_para_enviar_reporte_de_chasis__mdt
        ]) {

            List<String> listadoMails;

            if (emailPorMarca.containsKey(email.Marca__c)) {
                listadoMails = emailPorMarca.get(email.Marca__c);
            } else {
                listadoMails = new List<String>();
            }

            listadoMails.add(email.Email__c);
            emailPorMarca.put(email.Marca__c, listadoMails);
            aprobadorPorEmail.put(email.Email__c, email.Nombre__c);
        }
        
        if(emailPorMarca.containsKey(oppProd.Product2.Marca_P__c.toUpperCase())) {
            for (String destinatario : emailPorMarca.get(oppProd.Product2.Marca_P__c.toUpperCase())) {
                String nombreReceptor = aprobadorPorEmail.get(destinatario);
                String bodyHtml;
                if (!Test.isRunningTest()) {
                    bodyHtml =  etList[0].HtmlValue.replace('$aprobador', nombreReceptor)
                                        .replace('$vendedor', oppProd.Opportunity.Owner.Name)
                                        .replace('$nombreCliente', oppProd.Opportunity.Account.Name)
                                        .replace('$nombreOportunidad', oppProd.Opportunity.Name)
                                        .replace('$numeroChasis', oppProd.Chasis__c)
                                        .replace('$motivo', motivo);
                
                } else {
                    bodyHtml =  'Test HTML';
                }

                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>{destinatario});
                mail.setReplyTo(oppProd.Opportunity.Owner.Email);
                mail.setSenderDisplayName(oppProd.Opportunity.Owner.Name);
                mail.setSubject('Se ha deasignado un chasis');
                mail.setBccSender(false);
                mail.setUseSignature(false);
                mail.setHtmlBody(bodyHtml);
                emailList.add(mail);
            } 
        }

        if(!emailList.isEmpty()) {
            Messaging.sendEmail(emailList);    
        }

        oppProd.Motor__c = '';
        oppProd.Chasis__c = '';
        oppProd.Color__c = '';
        oppProd.IdInformeNegociacion__c = null;

        if (tipoDeasignacion == 'Devolucion') {
            oppProd.Tipo_de_reserva__c = 'Devolucion';
        }
        
        update oppProd;               

        return 'ok';
    }

    @AuraEnabled
    public static String obtenerRecordTypeOpp(String recordID){  
        List<Opportunity> oppList = 
            [SELECT RecordType.DeveloperName
            FROM Opportunity
            WHERE ID =: recordID 
            ];

        if (oppList.isEmpty()) {
            return null;
        } else {
            return oppList[0].RecordType.DeveloperName;
        }
    }
    
    @AuraEnabled
    public static String CrearInformeNegociacion(String idOppProd) {
        OpportunityLineItem oppProd = 
            [SELECT ID, Motor__c, Chasis__c, Color__c, Subtotal__c,
                    OpportunityId, Product2Id, IdInformeNegociacion__c,
             		X15_I_V_A__c, Prima__c, Opportunity.AccountId
            FROM OpportunityLineItem 
            WHERE Id = :idOppProd
            ];
        
        List<Opportunity> opp = 
            [SELECT Forma_de_Pago_Multiple__c
            FROM Opportunity
            WHERE ID =: oppProd.OpportunityId
            ];

        if (oppProd.IdInformeNegociacion__c != null) {
            List<Informe_de_Negociaci_n__c> inf = 
                [SELECT ID FROM Informe_de_Negociaci_n__c WHERE ID =: oppProd.IdInformeNegociacion__c];
            
            if (!inf.isEmpty()) {
            	return 'InformeYaCreado';    
            }
        }
        
        if (oppProd.Motor__c == null) {
            return 'MotorChasisNoAsignado';
        }
        
        Informe_de_Negociaci_n__c infoNeg = new Informe_de_Negociaci_n__c();
        infoNeg.Producto__c = oppProd.Product2Id;
        infoNeg.Oportunidad__c = oppProd.OpportunityId;
        infoNeg.X15_I_V__c = oppProd.X15_I_V_A__c;
        infoNeg.Motor__c = oppProd.Motor__c;
        infoNeg.Prima_USD__c = oppProd.Prima__c;
        infoNeg.Chasis__c = oppProd.Chasis__c;
        infoNeg.Color_Externo__c = oppProd.Color__c;
        infoNeg.Precio_de_Lista_sin_IMP__c = oppProd.Subtotal__c;
        infoNeg.Forma_de_Pago_Informe__c = opp[0].Forma_de_Pago_Multiple__c;
        infoNeg.Cuenta__c = oppProd.Opportunity.AccountId;
        infoNeg.Facturar_a_nombre_de__c = oppProd.Opportunity.AccountId;
        infoNeg.OrdenAbierta__c='1';    
        
        insert infoNeg;

        oppProd.IdInformeNegociacion__c = infoNeg.id;
        
        update oppProd;
        
        return 'ok';
    }
}