force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/description2__c.field-meta.xml
<CustomField>
    <fullName>description2__c</fullName>
    <description>Descriocion 2</description>
    <label>description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/ImagenProducto__c/ImagenProducto__c.object-meta.xml
<CustomObject>
    <label>Imagen Producto</label>
    <nameField>
        <label>Nombre de ImagenProducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Imagenes Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImagenProducto__c/fields/IdExt__c.field-meta.xml
<CustomField>
    <fullName>IdExt__c</fullName>
    <externalId>true</externalId>
    <label>IdExt Imagen producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImagenProducto__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductCode</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Imagenes Productos</relationshipLabel>
    <relationshipName>Imagenes_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImagenProducto__c/fields/urlimagen__c.field-meta.xml
<CustomField>
    <fullName>urlimagen__c</fullName>
    <label>Url imagen</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AnioModelo__c.field-meta.xml
<CustomField>
    <fullName>AnioModelo__c</fullName>
    <description>Año del modelo del producto</description>
    <label>Año Modelo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Aniovehiculo__c.field-meta.xml
<CustomField>
    <fullName>Aniovehiculo__c</fullName>
    <description>Año del modelo del vehículo</description>
    <label>Año vehículo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigocolorexterno__c.field-meta.xml
<CustomField>
    <fullName>Codigocolorexterno__c</fullName>
    <description>Codigo del color externo del producto</description>
    <label>Codigo color externo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigocolorinterno__c.field-meta.xml
<CustomField>
    <fullName>Codigocolorinterno__c</fullName>
    <description>Codigo del color interno del producto</description>
    <label>Codigo color interno</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/codigomarca__c.field-meta.xml
<CustomField>
    <fullName>codigomarca__c</fullName>
    <label>Codigo marca</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigomodelofabrica__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelofabrica__c</fullName>
    <description>Codigo del modelo de fabrica de producto</description>
    <label>Codigo modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigomodelogenerico__c.field-meta.xml
<CustomField>
    <fullName>Codigomodelogenerico__c</fullName>
    <description>Descripcion del modelo generico del producto</description>
    <label>Codigo modelo generico</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigovehiculo__c.field-meta.xml
<CustomField>
    <fullName>Codigovehiculo__c</fullName>
    <description>Codigo visible del vehiculo</description>
    <label>Codigo vehiculo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Colorexterno__c.field-meta.xml
<CustomField>
    <fullName>Colorexterno__c</fullName>
    <description>Nombre del color externo del producto</description>
    <label>Color externo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Colorinterno__c.field-meta.xml
<CustomField>
    <fullName>Colorinterno__c</fullName>
    <description>Nombre del color interno del producto</description>
    <label>Color interno</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaci_n_1__c.field-meta.xml
<CustomField>
    <fullName>Especificaci_n_1__c</fullName>
    <label>Especificación 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Especificaciones__c.field-meta.xml
<CustomField>
    <fullName>Especificaciones__c</fullName>
    <description>Especificaciones del producto</description>
    <label>Especificaciones</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca_P__c.field-meta.xml
<CustomField>
    <fullName>Marca_P__c</fullName>
    <description>Marca relacionada a objeto Productos</description>
    <label>Marca (P)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hino</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>.</fullName>
            </value>
            <value>
                <fullName>Yamaha</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Jmc</fullName>
                <label>JMC</label>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>SsangYong</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/modelofabrica__c.field-meta.xml
<CustomField>
    <fullName>modelofabrica__c</fullName>
    <description>Nombre del modelo de fabrica del producto</description>
    <label>Modelo fabrica</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/modelogenerico__c.field-meta.xml
<CustomField>
    <fullName>modelogenerico__c</fullName>
    <label>Modelo generico</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Genesis.recordType-meta.xml
<RecordType>
    <fullName>Genesis</fullName>
    <active>true</active>
    <label>Genesis</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <label>Hero</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Hino.recordType-meta.xml
<RecordType>
    <fullName>Hino</fullName>
    <active>true</active>
    <label>Hino</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Kia.recordType-meta.xml
<RecordType>
    <fullName>Kia</fullName>
    <active>true</active>
    <label>Kia</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Suzuki.recordType-meta.xml
<RecordType>
    <fullName>Suzuki</fullName>
    <active>true</active>
    <label>Suzuki</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Toyota.recordType-meta.xml
<RecordType>
    <fullName>Toyota</fullName>
    <active>true</active>
    <label>Toyota</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Yamaha.recordType-meta.xml
<RecordType>
    <fullName>Yamaha</fullName>
    <active>true</active>
    <label>Yamaha</label>
</RecordType>

force-app/main/default/classes/ws_CatalogoProductos_ProcessData.cls
public class ws_CatalogoProductos_ProcessData {
    @future(callout=true)
    public static void procesaProductosDia(string ano, string mes, string dia) {
        ws_CatalogoProductos.wsProductosPort port = new ws_CatalogoProductos.wsProductosPort();
        String resp = port.GetProductosDia(Label.strKey,Label.strApp,Label.strModulo, ano, mes, dia);
        ID RTId = Schema.SObjectType.Catalogo_UDC__c
                .getRecordTypeInfosByDeveloperName()
                .get('Modelo')
                .getRecordTypeId();
        List<Catalogo_UDC__c> modelosToUpsert = new List<Catalogo_UDC__c>();
        Set<String> modelosList = new Set<String>();

        for (Catalogo_UDC__c mod : [SELECT ID, Name
                                    FROM Catalogo_UDC__c
                                    WHERE RecordType.DeveloperName = 'Modelo' 
                                    ]) {

            modelosList.add(mod.Name);
        }
        
        ID kiaProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Kia')
                                    .getRecordTypeId();
        
        ID hinoProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Hino')
                                    .getRecordTypeId();
        
        ID toyotaProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Toyota')
                                    .getRecordTypeId();
        
        ID suzukiProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Suzuki')
                                    .getRecordTypeId();
        
        ID heroProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Hero')
                                    .getRecordTypeId();
        
        ID genesisProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Genesis')
                                    .getRecordTypeId();
        
        ID yamahaProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Yamaha')
                                    .getRecordTypeId();
        
        ID generalProdID = Schema.SObjectType.Product2
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('General')
                                    .getRecordTypeId();
        
        Dom.Document doc = new Dom.Document();  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  

        System.debug('rootElement.getChildElements(): ' + rootElement.getChildElements().size());
        List<Product2> productLst = new List<Product2>();
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
            	Product2 p = new Product2();             
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){ 
                switch on detailElement.getName() {
                    when 'descripcion' { 
                        p.Description = detailElement.getText() != null ? detailElement.getText() : null;  
                    }
                    when 'idproducto' { 
                        p.ProductCode = detailElement.getText() != null ? detailElement.getText() : null; 
                        p.ProductCode__c = p.ProductCode; 
                    }
                    when 'codigocolorinterno' { 
                        p.Colorinterno__c = detailElement.getText() != null ? detailElement.getText() : null; 
                        p.Codigocolorinterno__c = p.Colorinterno__c;
                    }
                    when 'colorexterno' { 
                        p.Colorexterno__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'codigovehiculo'				{ 
                        p.Codigovehiculo__c	= detailElement.getText() != null ? detailElement.getText() : null;
                        p.Name = p.Codigovehiculo__c != null? p.Codigovehiculo__c : 'Generico';
                    }
                    when 'aniomodelo'				{ 
                        p.AnioModelo__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'aniovehiculo' { 
                        p.Aniovehiculo__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'codigocolorexterno' { 
                        p.Codigocolorexterno__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'codigomarca' { 
                        p.codigomarca__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'marca' { 
                        p.Marca_P__c = detailElement.getText() != null ? detailElement.getText().toLowerCase().capitalize() : null;
                        
                        switch on p.Marca_P__c {
                            when 'Kia' {
                                p.RecordTypeId = kiaProdID;
                            }	
                            when 'Toyota' {
                                p.RecordTypeId = toyotaProdID;
                            }
                            when 'Hino' {
                                p.RecordTypeId = hinoProdID;
                            }
                            when 'Suzuki' {
                                p.RecordTypeId = suzukiProdID;
                            }
                            when 'Yamaha' {
                                p.RecordTypeId = yamahaProdID;
                            }
                            when 'Hero' {
                                p.RecordTypeId = heroProdID;
                            }
                            when 'Genesis' {
                                p.RecordTypeId = genesisProdID;
                            }
                            when else {
                                p.RecordTypeId = generalProdID;
                            }
                        }
                    }
                    when 'codigomodelofabrica' { 
                        p.Codigomodelofabrica__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'codigomodelogenerico' { 
                        p.Codigomodelogenerico__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'especificaciones' { 
                        p.Especificaciones__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'modelofabrica' { 
                        p.modelofabrica__c = detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when 'modelogenerico' { 
                        p.modelogenerico__c	= detailElement.getText() != null ? detailElement.getText() : null; 
                    }
                    when else {}
                }
            }
        	
            if (p.ProductCode__c != null) {
                productLst.add(p);    
            }
    	}
        
        if (!productLst.isEmpty()) {
            Schema.SObjectField c = Product2.Fields.ProductCode__c;
			Database.UpsertResult [] srList = Database.upsert(productLst, c, false);
            for (Database.UpsertResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                        System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                    }
                }
           } 
        }
        
        if (!productLst.isEmpty()) {
        	for (Product2 prod : productLst) {
                String modelo = '';
                String codigo = '';
                String tipoProducto = '';

                if (prod.Marca_P__c == 'Yamaha' ||
                    prod.Marca_P__c == 'Genesis' ||
                    prod.Marca_P__c == 'Hero') {

                    modelo = prod.modelofabrica__c;
                    codigo = prod.Codigomodelofabrica__c;
                    tipoProducto = prod.modelogenerico__c;
                } else {
                    modelo = prod.modelogenerico__c;
                    codigo = prod.codigomodelogenerico__c;
                }

                if (!modelosList.contains(modelo)) {
                    Catalogo_UDC__c modeloUDC = new Catalogo_UDC__c();
                    modeloUDC.RecordTypeId = RTId;
                    modeloUDC.productCode__c = codigo;
                    modeloUDC.name = modelo.toUpperCase();
                    if (String.isNotBlank(tipoProducto)) {
                        modeloUDC.description1__c = tipoProducto;
                    } else {
                        modeloUDC.description1__c = modelo.toUpperCase();
                    }
                    modeloUDC.description2__c = prod.Marca_P__c;
                    modeloUDC.ExternalId__c = 'Modelo_' + modeloUDC.productCode__c;

                    modelosToUpsert.add(modeloUDC);
                }
            }
        }

        if (!modelosToUpsert.isEmpty()) {
            Database.UpsertResult[] srList  = Database.upsert(modelosToUpsert, Catalogo_UDC__c.ExternalId__c, false);
            
            for (Database.UpsertResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                        System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                    }
                }
            } 
        }
	}

    public static void getImagenesProductosDia(string ano, string mes, string dia) {
        String errors = 'Errores: \n\n';
        List<String> errorsList = new List<String>();
        List<ImagenProducto__c> imgproductLst = new List<ImagenProducto__c>();
        ws_CatalogoProductos.wsProductosPort port = new ws_CatalogoProductos.wsProductosPort();
        String resp = port.GetProductosImagenesDia(Label.strKey,Label.strApp,Label.strModulo,ano, mes, dia);
        
        Dom.Document doc = new Dom.Document();  
        doc.load(resp);  
        Dom.XMLNode rootElement = doc.getRootElement();  
        
        for ( Dom.XMLNode childElement : rootElement.getChildElements() ) {  
            	ImagenProducto__c imgProd = new ImagenProducto__c ();             
            for ( Dom.XMLNode detailElement : childElement.getChildElements() ){ 
                switch on detailElement.getName() {
                    when 'idproducto' { 
                        if (detailElement.getText() != null) {
                            imgProd.ProductCode__r = new Product2(ProductCode__c = detailElement.getText());
                        }
                    }
                    when 'codigovehiculo' 			{ 
                        imgProd.Name = detailElement.getText() != null ? detailElement.getText() : ''; 
                    }
                    when 'urlimagen' 		{ 
                        imgProd.urlimagen__c 	= detailElement.getText().trim() != '' ? detailElement.getText() : null; 
                    }
                    when else {}
                }
            }
        	
            if(imgProd.urlimagen__c != null){
                imgProd.IdExt__c = imgProd.Name + '_' + imgProd.urlimagen__c;
                imgproductLst.add(imgProd);    
            }
    	}
        
        if (!imgproductLst.isEmpty()) {
            Schema.SObjectField c = ImagenProducto__c.Fields.IdExt__c;
			Database.UpsertResult [] srList = Database.upsert(imgproductLst, c, false);
                for (Database.UpsertResult sr : srList) {
                    if (!sr.isSuccess()) {
                        for (Database.Error err : sr.getErrors()) {
                            System.debug('Ha ocurrido un error:' + err.getStatusCode() + ': ' + err.getMessage());                    
                            System.debug('Los campos que interfieren en el error son: ' + err.getFields());
                            errorsList.add('Ha ocurrido un error en el vehiculo:' + err.getStatusCode() + ': ' + 
                                            err.getMessage() + '\n' + 'Los campos que interfieren en el error son: ' + 
                                            err.getFields()+ '\n\n');
                        }
                    }
               } 
        }
    }
    
    public static void FormatearEspecificaciones() {
        List<Product2> lprod = 
            [SELECT ID, Especificaciones__c 
            FROM Product2 
            WHERE ProductCode = '306137'
            ];

        for (product2 p : lprod) {
            Blob blobValue = EncodingUtil.convertFromHex(p.Especificaciones__c);
            string espec = blobValue.toString();
            p.Especificaci_n_1__c = espec;
            update p;
        }
    }
}