force-app/main/default/objects/Catalogo_UDC__c/Catalogo_UDC__c.object-meta.xml
<CustomObject>
    <label>Catalogo UDC</label>
    <nameField>
        <label>Nombre de Catalogo UDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos UDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Catalogo_UDC__c/fields/description1__c.field-meta.xml
<CustomField>
    <fullName>description1__c</fullName>
    <description>description1</description>
    <label>description</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/fields/productCode__c.field-meta.xml
<CustomField>
    <fullName>productCode__c</fullName>
    <description>Product Code</description>
    <label>productCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Marcas.recordType-meta.xml
<RecordType>
    <fullName>Marcas</fullName>
    <active>true</active>
    <label>Marcas</label>
</RecordType>

force-app/main/default/objects/Catalogo_UDC__c/recordTypes/Modelo.recordType-meta.xml
<RecordType>
    <fullName>Modelo</fullName>
    <active>true</active>
    <label>Modelo</label>
</RecordType>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Esperando aprobacion&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Esperando aprobacion</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informes de Negociación</relationshipLabel>
    <relationshipName>Informes_de_Negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <formula>text(Oportunidad__r.Sucursal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sucursal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/fields/total_negociado__c.field-meta.xml
<CustomField>
    <fullName>total_negociado__c</fullName>
    <description>El monto total de la negociación, que determinara el monto de descuento especial y el IVA en el informe</description>
    <inlineHelpText>El monto total de la negociación</inlineHelpText>
    <label>Total Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_digo_de_Oportunidad_Numerico__c.field-meta.xml
<CustomField>
    <fullName>C_digo_de_Oportunidad_Numerico__c</fullName>
    <label>Código de Oportunidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Desea_realizar_intercambio__c.field-meta.xml
<CustomField>
    <fullName>Desea_realizar_intercambio__c</fullName>
    <label>Desea realizar intercambio?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_Pago_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pago_Multiple__c</fullName>
    <label>Forma de Adquisición</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Financiamiento Bancario</fullName>
            </value>
            <value>
                <fullName>Ciclo Casa Pellas</fullName>
            </value>
            <value>
                <fullName>Go Leasing</fullName>
            </value>
            <value>
                <fullName>Financiamiento</fullName>
            </value>
            <value>
                <fullName>Tasa 0</fullName>
            </value>
            <value>
                <fullName>Aun no desea realizar su compra</fullName>
                <label>Aún no desea realizar su compra</label>
            </value>
            <value>
                <fullName>Consumo Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca_UDC__c.field-meta.xml
<CustomField>
    <fullName>Marca_UDC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3) OR (1 AND 4)</booleanFilter>
        <errorMessage>No tiene permitido seleccionar esa marca. Consulte a un administrador.</errorMessage>
        <filterItems>
            <field>Catalogo_UDC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marcas</value>
        </filterItems>
        <filterItems>
            <field>$User.Marca_texto__c</field>
            <operation>contains</operation>
            <valueField>Catalogo_UDC__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Principal Autolote</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Avalúo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Marca)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ModeloVehiculo__c.field-meta.xml
<CustomField>
    <fullName>ModeloVehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo Vehiculo UDC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Catalogo_UDC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Modelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Catalogo_UDC__c</referenceTo>
    <relationshipLabel>Oportunidades (Modelo Vehiculo UDC)</relationshipLabel>
    <relationshipName>UDCMODELO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origen_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Origen_de_los_fondos__c</fullName>
    <label>Origen de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahorro</fullName>
            </value>
            <value>
                <fullName>Bienes muebles</fullName>
            </value>
            <value>
                <fullName>Donaciones (Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Donaciones (No Giro Negocio)</fullName>
            </value>
            <value>
                <fullName>Financiamiento instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Herencia</fullName>
            </value>
            <value>
                <fullName>Ingresos del negocio</fullName>
            </value>
            <value>
                <fullName>Obsequio</fullName>
            </value>
            <value>
                <fullName>Premio de casino</fullName>
            </value>
            <value>
                <fullName>Premio de lotería</fullName>
            </value>
            <value>
                <fullName>Remesa</fullName>
            </value>
            <value>
                <fullName>Rifa</fullName>
            </value>
            <value>
                <fullName>Venta de inmuebles</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Procedencia_de_los_fondos__c.field-meta.xml
<CustomField>
    <fullName>Procedencia_de_los_fondos__c</fullName>
    <label>Procedencia de los fondos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instituciones financieras</fullName>
            </value>
            <value>
                <fullName>Microfinancieras</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prueba_de_manejo__c.field-meta.xml
<CustomField>
    <fullName>Prueba_de_manejo__c</fullName>
    <label>Prueba de manejo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Altamira</fullName>
            </value>
            <value>
                <fullName>Chinandega</fullName>
            </value>
            <value>
                <fullName>Estelí</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Juigalpa</fullName>
            </value>
            <value>
                <fullName>Kia El Retiro</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Matagalpa</fullName>
            </value>
            <value>
                <fullName>Plaza España</fullName>
            </value>
            <value>
                <fullName>Puerto Cabezas</fullName>
            </value>
            <value>
                <fullName>Rivas</fullName>
            </value>
            <value>
                <fullName>Acahualinca</fullName>
            </value>
            <value>
                <fullName>Motoplaza GENESIS</fullName>
            </value>
            <value>
                <fullName>Motoplaza Masaya</fullName>
            </value>
            <value>
                <fullName>Multicentro las Américas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tour_CP__c.field-meta.xml
<CustomField>
    <fullName>Tour_CP__c</fullName>
    <label>Tour CP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Walk_Around__c.field-meta.xml
<CustomField>
    <fullName>Walk_Around__c</fullName>
    <label>Walk Around</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Autos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Autos</fullName>
    <active>true</active>
    <businessProcess>Principal</businessProcess>
    <label>Principal</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Principal_Motos.recordType-meta.xml
<RecordType>
    <fullName>Principal_Motos</fullName>
    <active>true</active>
    <businessProcess>Principal Motos</businessProcess>
    <label>Principal Motos</label>
</RecordType>

force-app/main/default/classes/EnviarInformeParaAprobacionTest.cls
@isTest
public class EnviarInformeParaAprobacionTest {
    @TestSetup
    public static void crearInforme() {
        Id motosID = Schema.SObjectType.Opportunity
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Principal_Motos')
                                    .getRecordTypeId();
        
        Id autosID = Schema.SObjectType.Opportunity
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Principal_Autos')
                                    .getRecordTypeId();
        
        Id marcasID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Marcas')
                                    .getRecordTypeId();
                
        Id modeloID = Schema.SObjectType.Catalogo_UDC__c
                                    .getRecordTypeInfosByDeveloperName()
                                    .get('Modelo')
                                    .getRecordTypeId();
        
        Catalogo_UDC__c toyota = new Catalogo_UDC__c();
        toyota.RecordTypeID = marcasID;
        toyota.Name = 'TOYOTA';
        toyota.productCode__c = 'TY';
        insert toyota;
                
        Catalogo_UDC__c xf3r = new Catalogo_UDC__c();
        xf3r.RecordTypeID = modeloID;
        xf3r.Name = 'XF3R';
        xf3r.productCode__c = 'XF3R';
        xf3r.description1__c = 'MOTOCICLETA';
        insert xf3r;
        
        Catalogo_UDC__c hero = new Catalogo_UDC__c();
        hero.RecordTypeID = marcasID;
        hero.Name = 'HERO';
        hero.productCode__c = 'HR';
        insert hero;
        
        Opportunity oppMoto = new Opportunity();
        oppMoto.Name = 'TEST OPP CTE1';
        oppMoto.StageName = 'Contacto Exitoso';
        oppMoto.CloseDate = date.today();
        oppMoto.C_digo_de_Oportunidad_Numerico__c = 1234566;
        oppMoto.Forma_de_Pago_Multiple__c = 'Contado';
        oppMoto.Sucursal__c = 'Kia El Retiro'; 
        oppMoto.Forma_de_Pago_Multiple__c = 'Contado';
        oppMoto.Prueba_de_manejo__c = 'No';
        oppMoto.Tour_CP__c = 'No';
        oppMoto.Walk_Around__c = 'No';
        oppMoto.Origen_de_los_fondos__c = 'Ahorro';
        oppMoto.Procedencia_de_los_fondos__c = 'Otros';
        oppMoto.Desea_realizar_intercambio__c = 'No';
        oppMoto.RecordTypeId = motosID;
        oppMoto.Marca_UDC__c = hero.ID;
        oppMoto.ModeloVehiculo__c = xf3r.ID;
        insert oppMoto;
        
        Opportunity oppAuto = new Opportunity();
        oppAuto.Name = 'TEST OPP CTE1';
        oppAuto.StageName = 'Contacto Exitoso';
        oppAuto.CloseDate = date.today();
        oppAuto.C_digo_de_Oportunidad_Numerico__c = 1234567;
        oppAuto.Forma_de_Pago_Multiple__c = 'Contado';
        oppAuto.Sucursal__c = 'Kia El Retiro'; 
        oppAuto.Forma_de_Pago_Multiple__c = 'Contado';
        oppAuto.Prueba_de_manejo__c = 'No';
        oppAuto.Tour_CP__c = 'No';
        oppAuto.Walk_Around__c = 'No';
        oppAuto.Origen_de_los_fondos__c = 'Ahorro';
        oppAuto.Procedencia_de_los_fondos__c = 'Otros';
        oppAuto.Desea_realizar_intercambio__c = 'No';
        oppAuto.RecordTypeId = autosID;
        oppAuto.Marca_UDC__c = toyota.ID;
        insert oppAuto;
        
       	Informe_de_Negociaci_n__c infMoto = new Informe_de_Negociaci_n__c();
        infMoto.Estado__c = 'Esperando aprobacion';
        infMoto.Oportunidad__c = oppMoto.ID;
        infMoto.total_negociado__c = 0;
    	insert infMoto; 
        
        Informe_de_Negociaci_n__c infAuto = new Informe_de_Negociaci_n__c();
        infAuto.Estado__c = 'Rechazado';
        infAuto.total_negociado__c = 0;
        infAuto.Oportunidad__c = oppAuto.ID;
    	insert infAuto; 
    }
    
	@isTest
    public static void enviarReporteTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            WHERE Estado__c = 'Rechazado'
            ];
        
        Test.startTest();
        String respuesta = EnviarInformeParaAprobacion.enviarReporte(infList[0].ID);
        Test.stopTest();
        
        //System.assertEquals('Ok', respuesta, 'El envio esta fallando cuando no deberia.');
    }
    
    @isTest
    public static void enviarReporteMotosTest() {
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID
            FROM Informe_de_Negociaci_n__c
            WHERE Estado__c = 'Esperando aprobacion'
            ];
        
        Test.startTest();
        String respuesta = EnviarInformeParaAprobacion.enviarReporte(infList[0].ID);
        Test.stopTest();
        
        System.assertEquals('Ok', respuesta, 'El envio esta fallando cuando no deberia.');
    }
    
    @isTest
    public static void informeConMontoMenor() {
		List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID, total_negociado__c 
            FROM Informe_de_Negociaci_n__c
            WHERE Estado__c = 'Rechazado'
            ];
        
        infList[0].total_negociado__c  = 1;
        update infList;
        
        Test.startTest();
        String respuesta = EnviarInformeParaAprobacion.enviarReporte(infList[0].ID);
        Test.stopTest();
        
        System.assertEquals('Pendiente', respuesta, 'El envio no falla a pesar de tener un monto pendiente.');
    }
    
    @isTest
    public static void informeYaAprobado() {
		List<Informe_de_Negociaci_n__c> infList = 
            [SELECT ID, Estado__c
            FROM Informe_de_Negociaci_n__c
            WHERE Estado__c = 'Rechazado'
            ];
        
        infList[0].Estado__c  = 'Aprobado';
        update infList;
        
        Test.startTest();
        String respuesta = EnviarInformeParaAprobacion.enviarReporte(infList[0].ID);
        Test.stopTest();
        
        System.assertEquals('Aprobado', respuesta, 'El envio no falla a pesar de tener ya estar aprobado.');
    }
}