force-app/main/default/objects/AccesoriosComboParaNegociacion__c/AccesoriosComboParaNegociacion__c.object-meta.xml
<CustomObject>
    <label>Accesorio del combo para negociación</label>
    <nameField>
        <displayFormat>ACN-{000000000}</displayFormat>
        <label>Nombre de Aceesorios del combo para nego</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accesorios del combo para negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccesoriosComboParaNegociacion__c/fields/Asociar_al_informe_Negociacion__c.field-meta.xml
<CustomField>
    <fullName>Asociar_al_informe_Negociacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Asociar al informe de negociación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccesoriosComboParaNegociacion__c/fields/Combo_del_informe__c.field-meta.xml
<CustomField>
    <fullName>Combo_del_informe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Combo del informe</label>
    <referenceTo>CombosDeInformeDeNegociacion__c</referenceTo>
    <relationshipName>Accesorios_del_combo_para_negociaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Combo__c/Combo__c.object-meta.xml
<CustomObject>
    <label>Combo</label>
    <nameField>
        <label>Nombre de Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/CombosDeInformeDeNegociacion__c.object-meta.xml
<CustomObject>
    <label>Combos del informe</label>
    <nameField>
        <label>Nombre de Informe / Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combos del informe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Combo__c.field-meta.xml
<CustomField>
    <fullName>Combo__c</fullName>
    <label>Combo</label>
    <referenceTo>Combo__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CombosDeInformeDeNegociacion__c/fields/Informe_de_Negociaci_n__c.field-meta.xml
<CustomField>
    <fullName>Informe_de_Negociaci_n__c</fullName>
    <label>Informe de Negociación</label>
    <referenceTo>Informe_de_Negociaci_n__c</referenceTo>
    <relationshipName>Informes_Combos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Informe_de_Negociaci_n__c/Informe_de_Negociaci_n__c.object-meta.xml
<CustomObject>
    <label>Informe de Negociación</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informe de Negociación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes de Negociación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccesorioComboParaNegociacionTest.cls
@isTest
public class AccesorioComboParaNegociacionTest {
	@TestSetup
    public static void setup(){
        Informe_de_Negociaci_n__c inf = new Informe_de_Negociaci_n__c();
        insert inf;
        
        Combo__c c = new Combo__c();
        insert c;
        
        CombosDeInformeDeNegociacion__c com = new CombosDeInformeDeNegociacion__c();
        com.Informe_de_Negociaci_n__c = inf.ID;
        com.Combo__c = c.ID;
        insert com;
    }
    
    @isTest
    public static void crearAccesoriosDelInformeTest() {
        List<CombosDeInformeDeNegociacion__c> comList = 
            [SELECT ID
            FROM CombosDeInformeDeNegociacion__c
            ];
        
        Test.setMock(WebServiceMock.class, new Test_MockWSAccesorios());
        
        AccesoriosComboParaNegociacion__c acc = new AccesoriosComboParaNegociacion__c();
        acc.Asociar_al_informe_Negociacion__c = false;
        acc.Combo_del_informe__c = comList[0].ID;
        acc.Descripcion__c = 'TEST';
        acc.Cantidad__c = 1;
        insert acc;
        
        acc.Asociar_al_informe_Negociacion__c = true;
        
        Test.startTest();
		update acc;        
        Test.stopTest();
    }
}