force-app/main/default/objects/Debug_log__c/Debug_log__c.object-meta.xml
<CustomObject>
    <label>Debug log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Debug log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debugs logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error ocurrido</description>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/fields/ID_Objeto__c.field-meta.xml
<CustomField>
    <fullName>ID_Objeto__c</fullName>
    <description>ID del objeto sobre el que ocurrió el error</description>
    <label>ID Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/fields/XML__c.field-meta.xml
<CustomField>
    <fullName>XML__c</fullName>
    <description>En caso de errores se almacena el XML del envio que falló.
En caso de reservas se almacena el detalle del cambio en la reserva.</description>
    <label>Detalle</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CallWsGuardarClienteCreditoTest.cls
@isTest
public class CallWsGuardarClienteCreditoTest {
    
	@isTest
    public static void ConsultarClienteCreditoError(){
        
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(false));
        Test.startTest();
        CallWsGuardarClienteCredito.guardarClienteCredito('1128701');
        Test.stopTest();

		List<Debug_log__c> log = [SELECT Error__c, XML__c, ID_Objeto__c FROM Debug_log__c];  
        
        System.assertEquals(false, log.isEmpty(), 'No se registraron los debugs');
        
        System.assertEquals('Cliente credito', log[0].Error__c, 'El campo errror no esta correcto');
        System.assertEquals('Incorrecto', log[0].XML__c, 'El campo XML no esta correcto');
        System.assertEquals('1128701', log[0].ID_Objeto__c, 'El campo Objeto no esta correcto');
    }
    
    @isTest
    public static void ConsultarClienteCreditoBien(){
        
        Test.setMock(WebServiceMock.class, new Test_MockWSGuardarClienteCredito(true));
        Test.startTest();
        CallWsGuardarClienteCredito.guardarClienteCredito('1128701');
        Test.stopTest();

		List<Debug_log__c> log = [SELECT Error__c, XML__c, ID_Objeto__c FROM Debug_log__c];  
        
        System.assertEquals(true, log.isEmpty(), 'No se registraron los debugs');

    }
}