force-app/main/default/objects/Debug_log__c/Debug_log__c.object-meta.xml
<CustomObject>
    <label>Debug log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Debug log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debugs logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error ocurrido</description>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/fields/ID_Objeto__c.field-meta.xml
<CustomField>
    <fullName>ID_Objeto__c</fullName>
    <description>ID del objeto sobre el que ocurrió el error</description>
    <label>ID Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_log__c/fields/XML__c.field-meta.xml
<CustomField>
    <fullName>XML__c</fullName>
    <description>En caso de errores se almacena el XML del envio que falló.
En caso de reservas se almacena el detalle del cambio en la reserva.</description>
    <label>Detalle</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CallWSGuardarClienteCredito.cls
public class CallWSGuardarClienteCredito {
 public static void guardarClienteCredito (String numCliente){
     
      //Para debug de clientes en la tabla de credito
        List<Debug_log__c> debugToCredito = new List<Debug_log__c>();
          
            ClientesWS.wsClientesPort portObj = new ClientesWS.wsClientesPort(); 
            portObj.timeout_x = 120000; 
            String resp = portObj.InsertarClientesCredito(Label.strKey, 
                                                        Label.strApp, 
                                                        Label.strModulo, 
                                                        numCliente
                                                        );
     System.debug('respuesta:'+ resp);
     if (resp != 'Bien')
     {      
        Debug_log__c dlerror = new Debug_log__c();
        dlerror.Error__c = 'Cliente credito';
        dlerror.XML__c =resp;   
        dlerror.ID_Objeto__c=numCliente;
        insert dlerror;
         
         
     }
            
     
    }
}